class AdanaSchoolList {
  List<String> rawData = [
    'ADANA - ALADAĞ - Akören İlkokulu'
        'ADANA - ALADAĞ - Atatürk İlkokulu',
    'ADANA - ALADAĞ - Akören Ortaokulu',
    'ADANA - ALADAĞ - Boztahta Şehit Serdar Yıldırım İlkokulu',
    'ADANA - ALADAĞ - Büyüksofulu Şehit Ziya Şahin İlkokulu',
    'ADANA - ALADAĞ - Ceritler Necati Özsırkıntı İlkokulu',
    'ADANA - ALADAĞ - Gerdibi Ortaokulu',
    'ADANA - ALADAĞ - Gerdibi Sivişli İlkokulu',
    'ADANA - ALADAĞ - Başpınar Halil Yüksek İlkokulu',
    'ADANA - ALADAĞ - Aladağ Halk Eğitimi Merkezi',
    'ADANA - ALADAĞ - Kışlak İlkokulu',
    'ADANA - ALADAĞ - Kızıldam İlkokulu',
    'ADANA - ALADAĞ - Boztahta Şehit Serdar Yıldırım Ortaokulu',
    'ADANA - ALADAĞ - Atatürk Ortaokulu',
    'ADANA - ALADAĞ - Aladağ Öğretmenevi ve Akşam Sanat Okulu',
    'ADANA - ALADAĞ - Sinanpaşa İlkokulu',
    'ADANA - ALADAĞ - Akören Çok Programlı Anadolu Lisesi',
    'ADANA - ALADAĞ - Köprücük İlkokulu',
    'ADANA - ALADAĞ - Aladağ İmam Hatip Ortaokulu',
    'ADANA - ALADAĞ - Kökez İlkokulu',
    'ADANA - ALADAĞ - Kökez Ortaokulu',
    'ADANA - ALADAĞ - Dölekli İlkokulu',
    'ADANA - ALADAĞ - Dölekli Ortaokulu',
    'ADANA - ALADAĞ - Kıcak Şehit Arif Mamış İlkokulu',
    'ADANA - ALADAĞ - Kıcak Şehit Arif Mamış Ortaokulu',
    'ADANA - ALADAĞ - Gerdibi İlkokulu',
    'ADANA - ALADAĞ - Aladağ Sinanpaşa Anadolu İmam Hatip Lisesi',
    'ADANA - ALADAĞ - YETİMLİ İLKOKULU',
    'ADANA - ALADAĞ - Büyüksofulu İmam Hatip Ortaokulu',
    'ADANA - ALADAĞ - Kökez Cumhuriyet İlkokulu',
    'ADANA - ALADAĞ - Sanko Aladağ Anadolu Lisesi',
    'ADANA - ALADAĞ - Şehit Adem Oğuz Yatılı Bölge Ortaokulu',
    'ADANA - ALADAĞ - Karatepe İlkokulu',
    'ADANA - ALADAĞ - Kabasakal İlkokulu',
    'ADANA - ALADAĞ - Darılık İlkokulu',
    'ADANA - ALADAĞ - Gökçeköy İlkokulu',
    'ADANA - CEYHAN - 60.Yıl Manas İlkokulu',
    'ADANA - CEYHAN - 75.Yıl Cumhuriyet Anaokulu',
    'ADANA - CEYHAN - Arif-Hasan Bilici İmam Hatip Ortaokulu',
    'ADANA - CEYHAN - Atatürk İlkokulu',
    'ADANA - CEYHAN - Ayşe Malaz İlkokulu',
    'ADANA - CEYHAN - Birkent Ortaokulu',
    'ADANA - CEYHAN - Anadolu İmam Hatip Lisesi',
    'ADANA - CEYHAN - Ceyhan Biliciler Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - CEYHAN - Ceyhan Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - CEYHAN - Ceyhan Ticaret Borsası Sosyal Bilimler Lisesi',
    'ADANA - CEYHAN - Altı Ocak Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - CEYHAN - Çataklı Tatarlı Bakırlı İlkokulu',
    'ADANA - CEYHAN - Dokuztekne Şehit Adem Çoban İlkokulu',
    'ADANA - CEYHAN - Dokuztekne Şehit Adem Çoban Ortaokulu',
    'ADANA - CEYHAN - Eczacı Bahattin-Sevinç Erdinç Fen Lisesi',
    'ADANA - CEYHAN - Halil Çiftçi Anadolu Lisesi',
    'ADANA - CEYHAN - Ceyhan Halk Eğitimi Merkezi',
    'ADANA - CEYHAN - Hamidiye Anaokulu',
    'ADANA - CEYHAN - Yaltır Kardeşler Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - CEYHAN - Toros Tarım İlkokulu',
    'ADANA - CEYHAN - Mehmetçik İlkokulu',
    'ADANA - CEYHAN - Ceyhan Mesleki Eğitim Merkezi',
    'ADANA - CEYHAN - Sağkaya Ortaokulu',
    'ADANA - CEYHAN - Şaban Üçgül ve Kardeşleri Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - CEYHAN - Sarısakal İlkokulu',
    'ADANA - CEYHAN - Toros Tarım Anadolu Lisesi',
    'ADANA - CEYHAN - Yeşildam İlkokulu',
    'ADANA - CEYHAN - Kösreli İlkokulu',
    'ADANA - CEYHAN - Cumhuriyet İlkokulu',
    'ADANA - CEYHAN - Mehmet Akif Ersoy İlkokulu',
    'ADANA - CEYHAN - Necati Akçağlılar İlkokulu',
    'ADANA - CEYHAN - İsmail-Ayşe Önük Ortaokulu',
    'ADANA - CEYHAN - Şehit Adnan Sürücü Ortaokulu',
    'ADANA - CEYHAN - Kasım Garipoğlu Anadolu Lisesi',
    'ADANA - CEYHAN - Mercimek Tevhide Atçı İlkokulu',
    'ADANA - CEYHAN - Kurtkulağı Orhan Ekinci Ortaokulu',
    'ADANA - CEYHAN - Borsa İstanbul Ceyhan Anadolu Lisesi',
    'ADANA - CEYHAN - Gümürdülü İlkokulu',
    'ADANA - CEYHAN - Sarısakal Ortaokulu',
    'ADANA - CEYHAN - Gümürdülü Ortaokulu',
    'ADANA - CEYHAN - Kurtkulağı Orhan Ekinci İlkokulu',
    'ADANA - CEYHAN - Mithatpaşa Şehit Battal Özaslan İlkokulu',
    'ADANA - CEYHAN - Mustafabeyli Ortaokulu',
    'ADANA - CEYHAN - Hamdilli Ortaokulu',
    'ADANA - CEYHAN - Şehit Fehmi Koç İlkokulu',
    'ADANA - CEYHAN - Namık Kemal İlkokulu',
    'ADANA - CEYHAN - Yeşildam Ortaokulu',
    'ADANA - CEYHAN - Heydar Aliyev Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - CEYHAN - Botaş Ortaokulu',
    'ADANA - CEYHAN - Mehmet Orhun Yaylacı Anadolu Lisesi',
    'ADANA - CEYHAN - Kösreli Ortaokulu',
    'ADANA - CEYHAN - Ali Fevziye Özçelik İlkokulu',
    'ADANA - CEYHAN - Büyük Mangıt Şehit Cüneyt Muhacir Ortaokulu',
    'ADANA - CEYHAN - Dumlupınar İlkokulu',
    'ADANA - CEYHAN - İlbeyli - Beyteks Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - CEYHAN - Botaş İlkokulu',
    'ADANA - CEYHAN - Sakine Garipoğlu İlkokulu',
    'ADANA - CEYHAN - Fatih Sultan Mehmet İlkokulu',
    'ADANA - CEYHAN - Şehit İsa Çiçek İlkokulu',
    'ADANA - CEYHAN - Cennet Çetin Anaokulu',
    'ADANA - CEYHAN - Gaziosmanpaşa İlkokulu',
    'ADANA - CEYHAN - Arif Nihat Asya Ortaokulu',
    'ADANA - CEYHAN - Mercimek Tevhide Atçı Ortaokulu',
    'ADANA - CEYHAN - Toros Tarım Ortaokulu',
    'ADANA - CEYHAN - İhsan Demirtaş İlkokulu',
    'ADANA - CEYHAN - Ceyhan Şehit Tuncay Ateş İmam Hatip Ortaokulu',
    'ADANA - CEYHAN - Cengiz Topel İlkokulu',
    'ADANA - CEYHAN - Şehit Süleyman Çakır Anaokulu',
    'ADANA - CEYHAN - Şerife Topal Anaokulu',
    'ADANA - CEYHAN - Yaltır Kardeşler Ortaokulu',
    'ADANA - CEYHAN - 23 Nisan İlkokulu',
    'ADANA - CEYHAN - Gazi Ortaokulu',
    'ADANA - CEYHAN - Beşocak İlkokulu',
    'ADANA - CEYHAN - Kuzucak İlkokulu',
    'ADANA - CEYHAN - Remzi Oğuz Arık İlkokulu',
    'ADANA - CEYHAN - Sakarya Ortaokulu',
    'ADANA - CEYHAN - Pamukeli Ortaokulu',
    'ADANA - CEYHAN - Fevzi Çakmak Ortaokulu',
    'ADANA - CEYHAN - Sakarya İlkokulu',
    'ADANA - CEYHAN - Çataklı Tatarlı Bakırlı Ortaokulu',
    'ADANA - CEYHAN - Mürüvvet - Mahmut Kayhan Anaokulu',
    'ADANA - CEYHAN - Ceyhan Polis Amca Anaokulu',
    'ADANA - CEYHAN - Mercimek Anaokulu',
    'ADANA - CEYHAN - Başören İlkokulu',
    'ADANA - CEYHAN - Başören Ortaokulu',
    'ADANA - CEYHAN - Ceyhan Öğretmenevi ve Akşam Sanat Okulu',
    'ADANA - CEYHAN - Ceyhan Anadolu Lisesi',
    'ADANA - CEYHAN - Mustafabeyli İlkokulu',
    'ADANA - CEYHAN - Hamdilli İlkokulu',
    'ADANA - CEYHAN - Kaymakam Gürbüz Karakuş Ortaokulu',
    'ADANA - CEYHAN - Kadir Sevil Aydar Anaokulu',
    'ADANA - CEYHAN - Tekfen Vakfı Özel Eğitim Uygulama Merkezi I. Kademe',
    'ADANA - CEYHAN - 100. Yıl Sarısakal İlkokulu',
    'ADANA - CEYHAN - Sağkaya Çok Programlı Anadolu Lisesi',
    'ADANA - CEYHAN - Güler Aral Anaokulu',
    'ADANA - CEYHAN - Kıvrıklı İlkokulu',
    'ADANA - CEYHAN - Şehit Hüseyin Birimen Ortaokulu',
    'ADANA - CEYHAN - Hafsa Sultan Anaokulu',
    'ADANA - CEYHAN - Büyükmangıt Atakuş Kardeşler Anaokulu',
    'ADANA - CEYHAN - Sağkaya İlkokulu',
    'ADANA - CEYHAN - Şehit Ertan Sevim Ortaokulu',
    'ADANA - CEYHAN - Doruk Merkez İlkokulu',
    'ADANA - CEYHAN - Toktamış İlkokulu',
    'ADANA - CEYHAN - Ülkü Halim Gökçedağ İlkokulu',
    'ADANA - CEYHAN - Şadiye Mustafa Caf Ortaokulu',
    'ADANA - CEYHAN - Soysallı Şehit Eren Çelik İlkokulu',
    'ADANA - CEYHAN - Çakabey Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - CEYHAN - Birkent İlkokulu',
    'ADANA - CEYHAN - Doruk Şehit Necip Un Ortaokulu',
    'ADANA - CEYHAN - Şehit Zeynep Sağır Anadolu Lisesi',
    'ADANA - CEYHAN - Doruk Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - CEYHAN - Ceyhan Kız Anadolu İmam Hatip Lisesi',
    'ADANA - CEYHAN - Kuzucak Ortaokulu',
    'ADANA - CEYHAN - Ceyhan Özel Eğitim Uygulama Okulu III. Kademe',
    'ADANA - CEYHAN - TEKFEN VAKFI ÖZEL EĞİTİM UYGULAMA OKULU II. KADEME',
    'ADANA - CEYHAN - KÜÇÜKMANGIT İLKOKULU',
    'ADANA - CEYHAN - YÜKSEL DAL ANAOKULU',
    'ADANA - CEYHAN - KÖRKUYU İLKOKULU',
    'ADANA - CEYHAN - Zerrin Ziya Çetin Anaokulu',
    'ADANA - CEYHAN - Nurhan Demirtaş Ortaokulu',
    'ADANA - CEYHAN - Zahit Çetin İlkokulu',
    'ADANA - CEYHAN - Ceyhan Rehberlik ve Araştırma Merkezi',
    'ADANA - CEYHAN - Polis Amca Özel Eğitim Anaokulu',
    'ADANA - CEYHAN - Ceyhan Bilim ve Sanat Merkezi',
    'ADANA - CEYHAN - Ceyhan Devlet Hastanesi Bekir Özer Anaokulu',
    'ADANA - CEYHAN - Mehmetçik Anaokulu',
    'ADANA - CEYHAN - Mithatpaşa Şehit Battal Özaslan Anaokulu',
    'ADANA - CEYHAN - Sarıbahçe İlkokulu',
    'ADANA - CEYHAN - Remzi Oğuz Arık Anaokulu',
    'ADANA - CEYHAN - Gümüşdere İlkokulu',
    'ADANA - CEYHAN - Çakaldere İlkokulu',
    'ADANA - CEYHAN - Cumhuriyet Anaokulu',
    'ADANA - ÇUKUROVA - Abbas-Sıdıka Çalık Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Abdullah Cem Turhan Anaokulu',
    'ADANA - ÇUKUROVA - Adana Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Adana Ticaret Borsası Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Akşemsettin Ortaokulu',
    'ADANA - ÇUKUROVA - Buhara Ortaokulu',
    'ADANA - ÇUKUROVA - ÇEAS Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Hacı Ahmet Atıl Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Çukurova Halk Eğitimi Merkezi',
    'ADANA - ÇUKUROVA - DSİ Baraj Ortaokulu',
    'ADANA - ÇUKUROVA - Şehit Yalçın Palıt Anaokulu',
    'ADANA - ÇUKUROVA - Hasan Adalı Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Hoca Ahmet Yesevi İlkokulu',
    'ADANA - ÇUKUROVA - Şehit Serhat Sığnak Anaokulu',
    'ADANA - ÇUKUROVA - İbn-i Sina Ortaokulu',
    'ADANA - ÇUKUROVA - İsmail Kulak Anadolu Lisesi',
    'ADANA - ÇUKUROVA - İsmail Safa Özler Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Kabasakal Şehit Selçuk Beki İlkokulu',
    'ADANA - ÇUKUROVA - Şehit Tolga Özdinç İlkokulu',
    'ADANA - ÇUKUROVA - Yaşar Rukiye Kısacık Anadolu İmam Hatip Lisesi',
    'ADANA - ÇUKUROVA - Kurttepe Şehit Ali Öztaş Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Lütfiye Bağcivan Anaokulu',
    'ADANA - ÇUKUROVA - Mehmet Özöncel Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Meryem-Mehmet Kayhan Ortaokulu',
    'ADANA - ÇUKUROVA - Çukurova Mesleki Eğitim Merkezi',
    'ADANA - ÇUKUROVA - Nigahi Soykan İlkokulu',
    'ADANA - ÇUKUROVA - Niyazi Ekerbiçer Özel Eğitim Meslek Okulu',
    'ADANA - ÇUKUROVA - Oğuz Kağan Köksal Görme Engelliler Ortaokulu',
    'ADANA - ÇUKUROVA - Piri Reis Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Recep Birsin Özen Ortaokulu',
    'ADANA - ÇUKUROVA - Sabancı İlkokulu',
    'ADANA - ÇUKUROVA - Salbaş İlkokulu',
    'ADANA - ÇUKUROVA - Salbaş Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Salbaş Şehit Zeki Kütük Ortaokulu',
    'ADANA - ÇUKUROVA - Çukurova Anaokulu',
    'ADANA - ÇUKUROVA - 15 Temmuz Şehitleri Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Sıtkı Kulak Ortaokulu',
    'ADANA - ÇUKUROVA - Sungurbey Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Şambayadı Şehit İsmet Fatih Alagöz İlkokulu',
    'ADANA - ÇUKUROVA - Şehit Temel Cingöz Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Şoför ve Otomobilciler Odası Anaokulu',
    'ADANA - ÇUKUROVA - Şehit Zeki Akgünseven Anaokulu',
    'ADANA - ÇUKUROVA - Vehbi Güzel Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Yunus Emre İlkokulu',
    'ADANA - ÇUKUROVA - Çukurova Bilim ve Sanat Merkezi',
    'ADANA - ÇUKUROVA - Semiha Yücel Akdeğirmen İlkokulu',
    'ADANA - ÇUKUROVA - Çağrıbey Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Vakıfbank Ortaokulu',
    'ADANA - ÇUKUROVA - Edebali İlkokulu',
    'ADANA - ÇUKUROVA - Çukurova Toroslar Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Alparslan İlkokulu',
    'ADANA - ÇUKUROVA - Oğuzhan Ortaokulu',
    'ADANA - ÇUKUROVA - Attila İlkokulu',
    'ADANA - ÇUKUROVA - Ahmet Kurttepeli Anadolu Lisesi',
    'ADANA - ÇUKUROVA - İbn-i Sina İlkokulu',
    'ADANA - ÇUKUROVA - Emine Nabi Menemencioğlu İlkokulu',
    'ADANA - ÇUKUROVA - Adana Genç İş İnsanları Derneği Ortaokulu',
    'ADANA - ÇUKUROVA - Ahmet Sabancı Anaokulu',
    'ADANA - ÇUKUROVA - Gönül-Ferhat Baykara İlkokulu',
    'ADANA - ÇUKUROVA - Şehit Muhammet Ali Demir Ortaokulu',
    'ADANA - ÇUKUROVA - Şehit Yılmaz Bozkurt Ortaokulu',
    'ADANA - ÇUKUROVA - Çukurova Borsa İstanbul İlkokulu',
    'ADANA - ÇUKUROVA - Ayşe Atıl İlkokulu',
    'ADANA - ÇUKUROVA - Adana Tabipler Odası İlkokulu',
    'ADANA - ÇUKUROVA - Ramazan Atıl Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Şehit Ebubekir Durmuş Ortaokulu',
    'ADANA - ÇUKUROVA - Emine Sapmaz İlkokulu',
    'ADANA - ÇUKUROVA - Adana Kız Lisesi',
    'ADANA - ÇUKUROVA - Öğretmen Zeynep Erdoğdu Ortaokulu',
    'ADANA - ÇUKUROVA - Çukurova Elektrik Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Adana Çukurova Güzel Sanatlar Lisesi',
    'ADANA - ÇUKUROVA - Ertuğrul Gazi İlkokulu',
    'ADANA - ÇUKUROVA - Kurttepe Borsa İstanbul İlkokulu',
    'ADANA - ÇUKUROVA - Emine Nabi Menemencioğlu Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Kenan Çetinel İlkokulu',
    'ADANA - ÇUKUROVA - Şambayadı Şehit İsmet Fatih Alagöz Ortaokulu',
    'ADANA - ÇUKUROVA - Selcen Hatun Anaokulu',
    'ADANA - ÇUKUROVA - Şehit Enver Buğur Ortaokulu',
    'ADANA - ÇUKUROVA - İbrahim Atalı Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Kenan Çetinel Ortaokulu',
    'ADANA - ÇUKUROVA - TOKİ Şehit Bahattin Kalaycı İlkokulu',
    'ADANA - ÇUKUROVA - Necip Fazıl Kısakürek İlkokulu',
    'ADANA - ÇUKUROVA - Hacı Nazım Turgut İlkokulu',
    'ADANA - ÇUKUROVA - Seyhan Hacı Hatice Turgut Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Mehmet-Bedia Kipri İlkokulu',
    'ADANA - ÇUKUROVA - Oğuz Kağan Köksal Görme Engelliler İlkokulu',
    'ADANA - ÇUKUROVA - Kabasakal Şehit Selçuk Beki Ortaokulu',
    'ADANA - ÇUKUROVA - Dörtler Topalak İlkokulu',
    'ADANA - ÇUKUROVA - Çukurova İmam Hatip Ortaokulu',
    'ADANA - ÇUKUROVA - Çukurova Rehberlik ve Araştırma Merkezi',
    'ADANA - ÇUKUROVA - Semiha Yücel Akdeğirmen Ortaokulu',
    'ADANA - ÇUKUROVA - Emine Nabi Menemencioğlu Anaokulu',
    'ADANA - ÇUKUROVA - SELAHADDİN EYYUBİ İMAM HATİP ORTAOKULU',
    'ADANA - ÇUKUROVA - HÜMEYRA ÖKTEN KIZ ANADOLU İMAM HATİP LİSESİ',
    'ADANA - ÇUKUROVA - Şehit Kadir Demiryürek Özel Eğitim Uygulama Okulu III. Kademe',
    'ADANA - ÇUKUROVA - ŞEHİT MUSTAFA GÖRENOĞLU ANADOLU LİSESİ',
    'ADANA - ÇUKUROVA - ŞEHİT ADEM ALGIN ANAOKULU',
    'ADANA - ÇUKUROVA - Alparslan Türkeş Ortaokulu',
    'ADANA - ÇUKUROVA - ADANA TİCARET ODASI 125. YIL İLKOKULU',
    'ADANA - ÇUKUROVA - TOKİ Şehit Bahattin Kalaycı Ortaokulu',
    'ADANA - ÇUKUROVA - Gülbeyaz Güzel Anaokulu',
    'ADANA - ÇUKUROVA - Gazi Mustafa Kemal Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Şehit Cafer Kaşan Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Mithat Topal Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Şehit Murat Erdem Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Vehbi Güzel Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Mehmet Tal İmam Hatip Ortaokulu',
    'ADANA - ÇUKUROVA - Çukurova Şehit Aytekin Kuru Halk Eğitimi Merkezi',
    'ADANA - ÇUKUROVA - Kurttepe Ortaokulu',
    'ADANA - ÇUKUROVA - Çukurova İlkokulu',
    'ADANA - ÇUKUROVA - Öğretmen Hıdır Ünverdi Ortaokulu',
    'ADANA - ÇUKUROVA - Fazilet Kibritoğlu Özel Eğitim Uygulama Okulu I. Kademe',
    'ADANA - ÇUKUROVA - Fazilet Kibritoğlu Özel Eğitim Uygulama Okulu II. Kademe',
    'ADANA - ÇUKUROVA - Nezihe Yalvaç Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - ÇUKUROVA - Oğuz Kağan Köksal Özel Eğitim Anaokulu',
    'ADANA - ÇUKUROVA - Çukurova Özel Eğitim Anaokulu',
    'ADANA - ÇUKUROVA - Çukurova Bilim ve Sanat Merkezi Anaokulu',
    'ADANA - ÇUKUROVA - Necip Fazıl Kısakürek Anaokulu',
    'ADANA - ÇUKUROVA - Adana Ticaret Odası 125. Yıl Anaokulu',
    'ADANA - ÇUKUROVA - Edebali Anaokulu',
    'ADANA - ÇUKUROVA - Nigahi Soykan Anaokulu',
    'ADANA - ÇUKUROVA - TOKİ Şehit Bahattin Kalaycı Anaokulu',
    'ADANA - FEKE - Feke Şehit Yeter Şener Anadolu İmam Hatip Lisesi',
    'ADANA - FEKE - Şehit Koray Özel Anadolu Lisesi',
    'ADANA - FEKE - Feke Halk Eğitimi Merkezi',
    'ADANA - FEKE - Lütfiye Ayşe Baytok Yatılı Bölge Ortaokulu',
    'ADANA - FEKE - Oruçlu İlkokulu',
    'ADANA - FEKE - Ormancık İlkokulu',
    'ADANA - FEKE - Çandırlar İlkokulu',
    'ADANA - FEKE - Oruçlu Ortaokulu',
    'ADANA - FEKE - Tokmanaklı İlkokulu',
    'ADANA - FEKE - Kovukçınar İlkokulu',
    'ADANA - FEKE - Kırıkuşağı İlkokulu',
    'ADANA - FEKE - Süphandere İlkokulu',
    'ADANA - FEKE - Kaleyüzü İlkokulu',
    'ADANA - FEKE - Feke İmam Hatip Ortaokulu',
    'ADANA - FEKE - Ormancık Ortaokulu',
    'ADANA - FEKE - Karacaoğlan Ortaokulu',
    'ADANA - FEKE - Şahmuratlı İlkokulu',
    'ADANA - FEKE - Süphandere Ortaokulu',
    'ADANA - FEKE - Musalar İlkokulu',
    'ADANA - FEKE - Bahçecik İlkokulu',
    'ADANA - FEKE - Gürümze İlkokulu',
    'ADANA - FEKE - Karacaoğlan İlkokulu',
    'ADANA - FEKE - Paşalı Ortaokulu',
    'ADANA - FEKE - Ali Kuşçu İlkokulu',
    'ADANA - FEKE - FEKE Öğretmen Evi ve Akşam Sanat Okulu',
    'ADANA - FEKE - Gedikli İlkokulu',
    'ADANA - FEKE - Gaffaruşağı İlkokulu',
    'ADANA - FEKE - Hıdıruşağı İlkokulu',
    'ADANA - FEKE - Çandırlar Bekirhacılı İlkokulu',
    'ADANA - İMAMOĞLU - 23 Nisan Ortaokulu',
    'ADANA - İMAMOĞLU - Atatürk İlkokulu',
    'ADANA - İMAMOĞLU - Cumhuriyet İlkokulu',
    'ADANA - İMAMOĞLU - Cumhuriyet Ortaokulu',
    'ADANA - İMAMOĞLU - İmamoğlu Halk Eğitimi Merkezi',
    'ADANA - İMAMOĞLU - Şehit Halis Koca Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - İMAMOĞLU - Yavuz Sultan Selim Ortaokulu',
    'ADANA - İMAMOĞLU - Zübeyde Hanım Anaokulu',
    'ADANA - İMAMOĞLU - Koyunevi İlkokulu',
    'ADANA - İMAMOĞLU - Hürriyet İlkokulu',
    'ADANA - İMAMOĞLU - İstiklal Ortaokulu',
    'ADANA - İMAMOĞLU - Üçtepe Ortaokulu',
    'ADANA - İMAMOĞLU - Üçtepe İlkokulu',
    'ADANA - İMAMOĞLU - Fatih Yatılı Bölge Ortaokulu',
    'ADANA - İMAMOĞLU - Koyunevi Ortaokulu',
    'ADANA - İMAMOĞLU - Şehit Mehmet Atıcı Anadolu Lisesi',
    'ADANA - İMAMOĞLU - Malıhıdırlı İlkokulu',
    'ADANA - İMAMOĞLU - Malıhıdırlı Ortaokulu',
    'ADANA - İMAMOĞLU - Sevinçli Şehit Mehmet Erdoğan Ortaokulu',
    'ADANA - İMAMOĞLU - Ayvalı İlkokulu',
    'ADANA - İMAMOĞLU - Sevinçli Şehit Mehmet Erdoğan İlkokulu',
    'ADANA - İMAMOĞLU - Yunus Emre Anaokulu',
    'ADANA - İMAMOĞLU - Pekmezci İlkokulu',
    'ADANA - İMAMOĞLU - İmamoğlu Anadolu İmam Hatip Lisesi',
    'ADANA - İMAMOĞLU - Lokman Hekim Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - İMAMOĞLU - Çörten İlkokulu',
    'ADANA - İMAMOĞLU - Alaybeyi İlkokulu',
    'ADANA - İMAMOĞLU - Saygeçit İlkokulu',
    'ADANA - İMAMOĞLU - Faydalı İlkokulu',
    'ADANA - İMAMOĞLU - Camili İlkokulu',
    'ADANA - İMAMOĞLU - ŞEHİT VELİ ATAŞCI İLKOKULU',
    'ADANA - İMAMOĞLU - ŞEHİT OSMAN TATAR İLKOKULU',
    'ADANA - İMAMOĞLU - SEVGİ ANAOKULU',
    'ADANA - İMAMOĞLU - CAMİLİ ORTAOKULU',
    'ADANA - İMAMOĞLU - Şehit Selami Akça imam Hatip Ortaokulu',
    'ADANA - İMAMOĞLU - İmamoğlu Öğretmenevi ve Akşam Sanat Okulu Müdürlüğü',
    'ADANA - İMAMOĞLU - İmamoğlu Bilim ve Sanat Merkezi',
    'ADANA - İMAMOĞLU - Alaybeyi Abdiluşağı İlkokulu',
    'ADANA - KARAİSALI - 1 Nisan Yatılı Bölge Ortaokulu',
    'ADANA - KARAİSALI - Atatürk Ortaokulu',
    'ADANA - KARAİSALI - Bekirli İlkokulu',
    'ADANA - KARAİSALI - Beydemir İlkokulu',
    'ADANA - KARAİSALI - Çukur İlkokulu',
    'ADANA - KARAİSALI - Karaisalı Halk Eğitimi Merkezi',
    'ADANA - KARAİSALI - Ömer Nasuhi Bilmen Anadolu İmam Hatip Lisesi',
    'ADANA - KARAİSALI - Karaisalı Anaokulu',
    'ADANA - KARAİSALI - Karaisalı Çatalan Çok Programlı Anadolu Lisesi',
    'ADANA - KARAİSALI - Kırıklı İlkokulu',
    'ADANA - KARAİSALI - Karaisalı Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - KARAİSALI - Beydemir Ortaokulu',
    'ADANA - KARAİSALI - Eğlence Şehitler Ortaokulu',
    'ADANA - KARAİSALI - Çukur Ortaokulu',
    'ADANA - KARAİSALI - Cumhuriyet İlkokulu',
    'ADANA - KARAİSALI - Çatalan Ortaokulu',
    'ADANA - KARAİSALI - Çatalan İlkokulu',
    'ADANA - KARAİSALI - Şehit Mehmet Çalışkan İlkokulu',
    'ADANA - KARAİSALI - Karaçobanoğulları İlkokulu',
    'ADANA - KARAİSALI - Torunsolaklı Hacı Kerim Yılmaz İlkokulu',
    'ADANA - KARAİSALI - Etekli Erkeğin Şehit Fatih Yılmaz İlkokulu',
    'ADANA - KARAİSALI - Etekli Erkeğin Şehit Fatih Yılmaz Ortaokulu',
    'ADANA - KARAİSALI - Hacılı Şehit Ali Gümüştop İlkokulu',
    'ADANA - KARAİSALI - Eğlence Şehitler İlkokulu',
    'ADANA - KARAİSALI - Çakallı İlkokulu',
    'ADANA - KARAİSALI - Karaisalı Anadolu Lisesi',
    'ADANA - KARATAŞ - Adalı İlkokulu',
    'ADANA - KARATAŞ - Ataköy İlkokulu',
    'ADANA - KARATAŞ - Atatürk İlkokulu',
    'ADANA - KARATAŞ - Bahçe İlkokulu',
    'ADANA - KARATAŞ - Çimeli Benli İlkokulu',
    'ADANA - KARATAŞ - Damlapınar İlkokulu',
    'ADANA - KARATAŞ - Karataş Halk Eğitimi Merkezi',
    'ADANA - KARATAŞ - Hasırağcı İlkokulu',
    'ADANA - KARATAŞ - Kapı İlkokulu',
    'ADANA - KARATAŞ - Karataş Borsa İstanbul Çok Programlı Anadolu Lisesi',
    'ADANA - KARATAŞ - Hacı Şerafettin Işık Anadolu Lisesi',
    'ADANA - KARATAŞ - Kesik İlkokulu',
    'ADANA - KARATAŞ - Oymaklı İlkokulu',
    'ADANA - KARATAŞ - Sirkenli İlkokulu',
    'ADANA - KARATAŞ - Tabaklar İlkokulu',
    'ADANA - KARATAŞ - Karataş Anaokulu',
    'ADANA - KARATAŞ - Tuzkuyusu İlkokulu',
    'ADANA - KARATAŞ - Tuzla İlkokulu',
    'ADANA - KARATAŞ - Yemişli İlkokulu',
    'ADANA - KARATAŞ - Mehmet Akif Ortaokulu',
    'ADANA - KARATAŞ - Cumhuriyet İlkokulu',
    'ADANA - KARATAŞ - Bebeli İlkokulu',
    'ADANA - KARATAŞ - Tuzla Ortaokulu',
    'ADANA - KARATAŞ - Tuzla Çok Programlı Anadolu Lisesi',
    'ADANA - KARATAŞ - Bahçe Ortaokulu',
    'ADANA - KARATAŞ - Sirkenli Ortaokulu',
    'ADANA - KARATAŞ - Yemişli Ortaokulu',
    'ADANA - KARATAŞ - Karagöçer İlkokulu',
    'ADANA - KARATAŞ - Tevfik Ayser Canbolat Anadolu İmam Hatip Lisesi',
    'ADANA - KARATAŞ - KARATAŞ İLKOKULU',
    'ADANA - KARATAŞ - Karataş Bilim ve Sanat Merkezi',
    'ADANA - KARATAŞ - Çakırören İlkokulu',
    'ADANA - KARATAŞ - Karataş Özel Eğitim Anaokulu',
    'ADANA - KOZAN - 100. Yıl İlkokulu',
    'ADANA - KOZAN - 50. Yıl Şehit İbrahim Yüce Anadolu Lisesi',
    'ADANA - KOZAN - Akdam Ortaokulu',
    'ADANA - KOZAN - Atatürk İlkokulu',
    'ADANA - KOZAN - Cumhuriyet İlkokulu',
    'ADANA - KOZAN - Çandık İlkokulu',
    'ADANA - KOZAN - Gaziköyü İlkokulu',
    'ADANA - KOZAN - Şehit Ali Bulduk İlkokulu',
    'ADANA - KOZAN - Hacıbeyli Atatürk İlkokulu',
    'ADANA - KOZAN - Hacıbeyli Atatürk Ortaokulu',
    'ADANA - KOZAN - Halit Dağlı İlkokulu',
    'ADANA - KOZAN - Kozan Halk Eğitimi Merkezi',
    'ADANA - KOZAN - Kozan Kız Anadolu İmam Hatip Lisesi',
    'ADANA - KOZAN - Kozan Şehit Tayfur Uluçay Anaokulu',
    'ADANA - KOZAN - Kozan Fen Lisesi',
    'ADANA - KOZAN - Kozan Gaziköy Çok Programlı Anadolu Lisesi',
    'ADANA - KOZAN - Kozan Anadolu Lisesi',
    'ADANA - KOZAN - Kozan Şehit Arda Can Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - KOZAN - Ramazanoğlu Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - KOZAN - Kozan Yusuf Baysal Anadolu Lisesi',
    'ADANA - KOZAN - Lütfiye Ali Şadi Çelik Ortaokulu',
    'ADANA - KOZAN - Mareşal Fevzi Çakmak İlkokulu',
    'ADANA - KOZAN - Şehit Önder Ertaş Mesleki Eğitim Merkezi',
    'ADANA - KOZAN - Nene Hatun Anaokulu',
    'ADANA - KOZAN - Kozan Rehberlik ve Araştırma Merkezi',
    'ADANA - KOZAN - Sis Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - KOZAN - Şehit Cüneyit Kızılarslan Anaokulu',
    'ADANA - KOZAN - Şaban Ata İlkokulu',
    'ADANA - KOZAN - Şehit Kubilay İlkokulu',
    'ADANA - KOZAN - Yeniköy İlkokulu',
    'ADANA - KOZAN - Zübeyde Hanım Anaokulu',
    'ADANA - KOZAN - Fatih Anadolu Lisesi',
    'ADANA - KOZAN - Ağlıboğaz Şehit Murat Özkozanoğlu Ortaokulu',
    'ADANA - KOZAN - Gazi İlkokulu',
    'ADANA - KOZAN - Karacaoğlan Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - KOZAN - Gazi Ortaokulu',
    'ADANA - KOZAN - Tepecikören Şehit Osman Uçar İlkokulu',
    'ADANA - KOZAN - Tepecikören Ortaokulu',
    'ADANA - KOZAN - Yunus Emre Ortaokulu',
    'ADANA - KOZAN - Duran Oflaz Anaokulu',
    'ADANA - KOZAN - Acarmantaş İlkokulu',
    'ADANA - KOZAN - Ilıca İlkokulu',
    'ADANA - KOZAN - Ahmet Cevdet Çamurdan Ortaokulu',
    'ADANA - KOZAN - Kozan Kazım Karabekir Anadolu Lisesi',
    'ADANA - KOZAN - 2 Haziran Ortaokulu',
    'ADANA - KOZAN - Şehit Mehmet Oflaz Yatılı Bölge Ortaokulu',
    'ADANA - KOZAN - 60. Yıl Şehit Mustafa Akar Ortaokulu',
    'ADANA - KOZAN - Pekmezci Şehit Bircan İlhanlı Ortaokulu',
    'ADANA - KOZAN - Acarmantaş Ortaokulu',
    'ADANA - KOZAN - Pekmezci Şehit Bircan İlhanlı İlkokulu',
    'ADANA - KOZAN - Yavuz Sultan Selim İlkokulu',
    'ADANA - KOZAN - Hacımirzalı Şehit Yusuf Demiryürek İlkokulu',
    'ADANA - KOZAN - Remzi Oğuz Arık Ortaokulu',
    'ADANA - KOZAN - Kızıllar İlkokulu',
    'ADANA - KOZAN - İnkılap İlkokulu',
    'ADANA - KOZAN - İdem Şehit Abdullah Kocaer Ortaokulu',
    'ADANA - KOZAN - Turunçlu İlkokulu',
    'ADANA - KOZAN - Arslanpaşa Şehit Seyfettin Orkun Çil İlkokulu',
    'ADANA - KOZAN - Bucak İlkokulu',
    'ADANA - KOZAN - Bucak Ortaokulu',
    'ADANA - KOZAN - TOKİ Şehit Suat Ocak İlkokulu',
    'ADANA - KOZAN - Ahmet Cevdet Çamurdan İlkokulu',
    'ADANA - KOZAN - İsmet İnönü Ortaokulu',
    'ADANA - KOZAN - Dede Mehmet Akçalı İlkokulu',
    'ADANA - KOZAN - Faydalı İlkokulu',
    'ADANA - KOZAN - Bağtepe İlkokulu',
    'ADANA - KOZAN - Turgutlu İlkokulu',
    'ADANA - KOZAN - Yüksekören Şehit Ferdi Özkan Ortaokulu',
    'ADANA - KOZAN - Mehmet Akif Ersoy Anadolu Lisesi',
    'ADANA - KOZAN - Bulduklu İlkokulu',
    'ADANA - KOZAN - Şehit Ergün Karaca Anaokulu',
    'ADANA - KOZAN - ŞEHİT ÖĞRETMEN ALİ YILDIRIM ORTAOKULU',
    'ADANA - KOZAN - Osmangazi Anadolu İmam Hatip Lisesi',
    'ADANA - KOZAN - Faydalı Dede Mehmet Akçalı Vakfı Ortaokulu',
    'ADANA - KOZAN - Postkabasakal İlkokulu',
    'ADANA - KOZAN - ESKİMANTAŞ İLKOKULU',
    'ADANA - KOZAN - Kozan Bucak Çok Programlı Anadolu Lisesi',
    'ADANA - KOZAN - Bağtepe Ortaokulu',
    'ADANA - KOZAN - Faydalı Dede Mehmet Akçalı Vakfı İlkokulu',
    'ADANA - KOZAN - Görbeyaz İlkokul',
    'ADANA - KOZAN - Mevlana İlkokulu',
    'ADANA - KOZAN - AKDAM İLKOKULU',
    'ADANA - KOZAN - Ağlıboğaz Şehit Murat Özkozanoğlu İlkokulu',
    'ADANA - KOZAN - Kozan Ortaokulu',
    'ADANA - KOZAN - Şehit Ziya Özkozanoğlu Ortaokulu',
    'ADANA - KOZAN - Güneri Ortaokulu',
    'ADANA - KOZAN - Dede Mehmet Akçalı Ortaokulu',
    'ADANA - KOZAN - 23 Nisan Özel Eğitim Uygulama Okulu I. Kademe',
    'ADANA - KOZAN - DOĞANALANI İLKOKULU',
    'ADANA - KOZAN - Necip Fazıl Kısakürek İmam Hatip Ortaokulu',
    'ADANA - KOZAN - Kozan Bilim ve Sanat Merkezi',
    'ADANA - KOZAN - Kızıllar Ortaokulu',
    'ADANA - KOZAN - ŞEHİT CENGİZ EROĞLU ORTAOKULU',
    'ADANA - KOZAN - Öğretmen Evi ve Akşam Sanat Okulu',
    'ADANA - KOZAN - Aydın Çarçabuk İlkokulu',
    'ADANA - KOZAN - Marangeçili İlkokulu',
    'ADANA - KOZAN - Tepecikören Çöbük İlkokulu',
    'ADANA - KOZAN - Kahveli İlkokulu',
    'ADANA - KOZAN - Zerdali İlkokulu',
    'ADANA - KOZAN - Kuytucak Karapınar İlkokulu',
    'ADANA - KOZAN - İdem Şehit Abdullah Kocaer İlkokulu',
    'ADANA - KOZAN - Şehit Öğretmen Ali Yıldırım İlkokulu',
    'ADANA - KOZAN - Gaziköyü Ortaokulu',
    'ADANA - KOZAN - Yüksekören Şehit Ferdi Özkan İlkokulu',
    'ADANA - KOZAN - 23 Nisan Özel Eğitim Uygulama Okulu II. Kademe',
    'ADANA - KOZAN - Kapıkaya ilkokulu',
    'ADANA - KOZAN - Bağözü Taşören İlkokulu',
    'ADANA - KOZAN - Yavuz Sultan Selim Özel Eğitim Anaokulu',
    'ADANA - KOZAN - Şehit Ergün Karaca Özel Eğitim Anaokulu',
    'ADANA - KOZAN - Ahmet Tufan Kalkan Anaokulu',
    'ADANA - KOZAN - Ayşehoca İlkokulu',
    'ADANA - KOZAN - Kıbrıslar İlkokulu',
    'ADANA - KOZAN - 100. Yıl Şehit Serkan Ağca Anaokulu',
    'ADANA - KOZAN - Durmuşlu İlkokulu',
    'ADANA - KOZAN - Arslanlı Merkez İlkokulu',
    'ADANA - KOZAN - Halit Dağlı Anaokulu',
    'ADANA - KOZAN - Cumhuriyet Anaokulu',
    'ADANA - KOZAN - Atatürk Anaokulu',
    'ADANA - POZANTI - Pozantı Halk Eğitimi Merkezi',
    'ADANA - POZANTI - Hamidiye İlkokulu',
    'ADANA - POZANTI - Borsa İstanbul Şehit Erhan Konuk Anadolu İmam Hatip Lisesi',
    'ADANA - POZANTI - Karakışlakçı İlkokulu',
    'ADANA - POZANTI - Fatma Nilgün Kayar Anaokulu',
    'ADANA - POZANTI - Türkan - İrfan Akün Çok Programlı Anadolu Lisesi',
    'ADANA - POZANTI - Aşçıbekirli Ortaokulu',
    'ADANA - POZANTI - Kamışlı Fatih İlkokulu',
    'ADANA - POZANTI - Kamışlı Fatih Ortaokulu',
    'ADANA - POZANTI - Atatürk İlkokulu',
    'ADANA - POZANTI - Atatürk Ortaokulu',
    'ADANA - POZANTI - Şehit Sefa İzbudak Ortaokulu',
    'ADANA - POZANTI - Dağdibi İlkokulu',
    'ADANA - POZANTI - Şehit Zafer Sabancı Anadolu Lisesi',
    'ADANA - POZANTI - AŞÇIBEKİRLİ İLKOKULU',
    'ADANA - POZANTI - CUMHURİYET İLKOKULU',
    'ADANA - POZANTI - POZANTI İMAM HATİP ORTAOKULU',
    'ADANA - POZANTI - GÖKBEZ AHMET OĞUZ AKAL İLKOKULU',
    'ADANA - POZANTI - Pozantı Bilim ve Sanat Merkezi',
    'ADANA - SAİMBEYLİ - Atatürk İlkokulu',
    'ADANA - SAİMBEYLİ - Himmetli İlkokulu',
    'ADANA - SAİMBEYLİ - Karakuyu İlkokulu',
    'ADANA - SAİMBEYLİ - Karakuyu Ortaokulu',
    'ADANA - SAİMBEYLİ - Şehit Ali Çakar Anadolu Lisesi',
    'ADANA - SAİMBEYLİ - Saimbeyli Şehit Bayram Ali Yardımcı Yatılı Bölge Ortaokulu',
    'ADANA - SAİMBEYLİ - Saimbeyli Şehit Adil Ay Halk Eğitimi Merkezi',
    'ADANA - SAİMBEYLİ - Çeralan İlkokulu',
    'ADANA - SAİMBEYLİ - Himmetli Ortaokulu',
    'ADANA - SAİMBEYLİ - Fatih Sultan Mehmet Ortaokulu',
    'ADANA - SAİMBEYLİ - Yardibi İlkokulu',
    'ADANA - SAİMBEYLİ - Mahmutlu İlkokulu',
    'ADANA - SAİMBEYLİ - Aksaağaç İlkokulu',
    'ADANA - SAİMBEYLİ - Gökmenler İlkokulu',
    'ADANA - SAİMBEYLİ - Çatak İlkokulu',
    'ADANA - SAİMBEYLİ - Eyüplü İlkokulu',
    'ADANA - SAİMBEYLİ - Kapaklıkuyu İlkokulu',
    'ADANA - SAİMBEYLİ - Yeniköy İlkokulu',
    'ADANA - SAİMBEYLİ - Çatak Ortaokulu',
    'ADANA - SAİMBEYLİ - Çeralan Ortaokulu',
    'ADANA - SAİMBEYLİ - Aksaağaç Ortaokulu',
    'ADANA - SAİMBEYLİ - Yardibi Ortaoba İlkokulu',
    'ADANA - SAİMBEYLİ - SAİMBEYLİ ANADOLU İMAM HATİP LİSESİ',
    'ADANA - SAİMBEYLİ - Öğretmen Evi ve Akşam Sanat Okulu',
    'ADANA - SAİMBEYLİ - Beypınarı İlkokulu',
    'ADANA - SAİMBEYLİ - Kandilli Kızılyer İlkokulu',
    'ADANA - SARIÇAM - Abdullah Öngen Anaokulu',
    'ADANA - SARIÇAM - Akif Palalı Anadolu Lisesi',
    'ADANA - SARIÇAM - Ata İlkokulu',
    'ADANA - SARIÇAM - Avcılar İlkokulu',
    'ADANA - SARIÇAM - Bahtiyar Vahabzade Sosyal Bilimler Lisesi',
    'ADANA - SARIÇAM - Baklalı Emin Veyisoğulları İlkokulu',
    'ADANA - SARIÇAM - Beyceli İlkokulu',
    'ADANA - SARIÇAM - Boztepe İlkokulu',
    'ADANA - SARIÇAM - Cihadiye İlkokulu',
    'ADANA - SARIÇAM - Çatalan Baraj İlkokulu',
    'ADANA - SARIÇAM - Çatalan Baraj Ortaokulu',
    'ADANA - SARIÇAM - Eğeciuşağı İlkokulu',
    'ADANA - SARIÇAM - Şehit Mehmet Arslangiray İlkokulu',
    'ADANA - SARIÇAM - İncirlik Anadolu Lisesi',
    'ADANA - SARIÇAM - Kozanoğlu Lions Anaokulu',
    'ADANA - SARIÇAM - Kürkçüler Ortaokulu',
    'ADANA - SARIÇAM - Sarıçam Kadirin Çiftliği İlkokulu',
    'ADANA - SARIÇAM - Sarıçam Halk Eğitimi Merkezi',
    'ADANA - SARIÇAM - Sevgi Anaokulu',
    'ADANA - SARIÇAM - Sevim Tekin Anadolu Lisesi',
    'ADANA - SARIÇAM - Suluca İlkokulu',
    'ADANA - SARIÇAM - Suluca Ortaokulu',
    'ADANA - SARIÇAM - Türk Tekstil Vakfı Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SARIÇAM - Veli Yavuz İlkokulu',
    'ADANA - SARIÇAM - Sarıçam Anadolu İmam Hatip Lisesi',
    'ADANA - SARIÇAM - Arif Nihat Asya Ortaokulu',
    'ADANA - SARIÇAM - Arif Nihat Asya İlkokulu',
    'ADANA - SARIÇAM - Erdoğan Şahinoğlu İlkokulu',
    'ADANA - SARIÇAM - Hocallı Türk Kadınlar Birliği Ortaokulu',
    'ADANA - SARIÇAM - Hocallı Türk Kadınlar Birliği İlkokulu',
    'ADANA - SARIÇAM - Kılıçlı Ahmet Akyürek İlkokulu',
    'ADANA - SARIÇAM - Şehit İslam Akyüz Ortaokulu',
    'ADANA - SARIÇAM - Mustafalar Şehit Volkan Çay Ortaokulu',
    'ADANA - SARIÇAM - Mustafalar İlkokulu',
    'ADANA - SARIÇAM - Buruk İlkokulu',
    'ADANA - SARIÇAM - Çamlık İlkokulu',
    'ADANA - SARIÇAM - Uluğ Bey İlkokulu',
    'ADANA - SARIÇAM - Uluğ Bey Ortaokulu',
    'ADANA - SARIÇAM - Remzi Oğuz Arık İlkokulu',
    'ADANA - SARIÇAM - Kızılkaş Şehit Metehan Şahbaz Ortaokulu',
    'ADANA - SARIÇAM - Kızılkaş Şehit Metehan Şahbaz İlkokulu',
    'ADANA - SARIÇAM - ÇEAŞ Sofulu İlkokulu',
    'ADANA - SARIÇAM - Hacı Özcan Sinağ Ortaokulu',
    'ADANA - SARIÇAM - Bilge Kağan İlkokulu',
    'ADANA - SARIÇAM - Şehit Murat Demirçi İmam Hatip Ortaokulu',
    'ADANA - SARIÇAM - Bilge Kağan Ortaokulu',
    'ADANA - SARIÇAM - TOKİ Sarıçam Anadolu Lisesi',
    'ADANA - SARIÇAM - Kılıçlı Ahmet Akyürek Ortaokulu',
    'ADANA - SARIÇAM - Ömer Kanaatbilen İlkokulu',
    'ADANA - SARIÇAM - Ömer Kanaatbilen Ortaokulu',
    'ADANA - SARIÇAM - Buruk Ortaokulu',
    'ADANA - SARIÇAM - Şehit Mehmet Arslangiray Ortaokulu',
    'ADANA - SARIÇAM - Yağızlar Ortaokulu',
    'ADANA - SARIÇAM - Yağızlar İlkokulu',
    'ADANA - SARIÇAM - Adana Rotary Kulübü Anaokulu',
    'ADANA - SARIÇAM - Yeni Yayla İlkokulu',
    'ADANA - SARIÇAM - Şehit Soner Gökçü Ortaokulu',
    'ADANA - SARIÇAM - Umur Bey Ortaokulu',
    'ADANA - SARIÇAM - Göztepe İlkokulu',
    'ADANA - SARIÇAM - İncirlik İlkokulu',
    'ADANA - SARIÇAM - Baklalı Emin Veyisoğulları Ortaokulu',
    'ADANA - SARIÇAM - ÇEAŞ Sofulu Ortaokulu',
    'ADANA - SARIÇAM - TOKİ Osmangazi İmam Hatip Ortaokulu',
    'ADANA - SARIÇAM - Evliya Çelebi İlkokulu',
    'ADANA - SARIÇAM - Evliya Çelebi Ortaokulu',
    'ADANA - SARIÇAM - Muhammed Ali Clay İmam Hatip Ortaokulu',
    'ADANA - SARIÇAM - Sarıçam Orhangazi İmam Hatip Ortaokulu',
    'ADANA - SARIÇAM - Cihadiye Ortaokulu',
    'ADANA - SARIÇAM - Şehit Ercan Günay Ortaokulu',
    'ADANA - SARIÇAM - Akkuyu İlkokulu',
    'ADANA - SARIÇAM - Akkuyu Ortaokulu',
    'ADANA - SARIÇAM - Yarımca İlkokulu',
    'ADANA - SARIÇAM - Kepeztepe İlkokulu',
    'ADANA - SARIÇAM - Karlık İlkokulu',
    'ADANA - SARIÇAM - Karlık Ortaokulu',
    'ADANA - SARIÇAM - Adana Ticaret Odası Anadolu Lisesi',
    'ADANA - SARIÇAM - Dağcı İlkokulu',
    'ADANA - SARIÇAM - Dağcı Ortaokulu',
    'ADANA - SARIÇAM - Çamlıca İlkokulu',
    'ADANA - SARIÇAM - Adana Sarıçam Spor Lisesi',
    'ADANA - SARIÇAM - Kürkçüler İlkokulu',
    'ADANA - SARIÇAM - Cerenli İlkokulu',
    'ADANA - SARIÇAM - Sarıçam Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SARIÇAM - Şehit Mustafa Sarı İlkokulu',
    'ADANA - SARIÇAM - Aydınyurdu İlkokulu',
    'ADANA - SARIÇAM - Şehit Hüseyin Avni Bey Ortaokulu',
    'ADANA - SARIÇAM - Hüseyin Avni Coş İlkokulu',
    'ADANA - SARIÇAM - Fatıma Zehra Kız Anadolu İmam Hatip Lisesi',
    'ADANA - SARIÇAM - Cemil Meriç Ortaokulu',
    'ADANA - SARIÇAM - Evliya Çelebi Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SARIÇAM - İbn - i Sina Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SARIÇAM - Sarıçam TOKİ Osmangazi İlkokulu',
    'ADANA - SARIÇAM - Şehit Muhammet Oruç Anaokulu',
    'ADANA - SARIÇAM - Sarıçam Konaklama Merkezi İlkokulu',
    'ADANA - SARIÇAM - Sarıçam Konaklama Merkezi İmam Hatip Ortaokulu',
    'ADANA - SARIÇAM - Türkiye Odalar ve Borsalar Birliği Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SARIÇAM - Sarıçam Konaklama Merkezi Anadolu İmam Hatip Lisesi',
    'ADANA - SARIÇAM - Beyceli Anadolu Lisesi',
    'ADANA - SARIÇAM - Yıldırım Beyazıt Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SARIÇAM - Şehit Zeyyat Dağ Anaokulu',
    'ADANA - SARIÇAM - Prof. Dr. Fuat Sezgin Ortaokulu',
    'ADANA - SARIÇAM - Konaklama Merkezi Muallim Musab İmam Hatip Ortaokulu',
    'ADANA - SARIÇAM - Sarıçam Özel Eğitim Anaokulu',
    'ADANA - SARIÇAM - Sarıçam Konaklama Merkezi Göztepe İlkokulu',
    'ADANA - SARIÇAM - Çukurova Ün.Devlet Konservatuvarı Müzik ve Bale Ortaokulu',
    'ADANA - SARIÇAM - Çukurova Ün.Devlet Konservatuvarı Müzik ve Sahne Sanatları Lisesi',
    'ADANA - SARIÇAM - Şeyh Şamil Anadolu İmam Hatip Lisesi',
    'ADANA - SARIÇAM - Şehit Ercan Günay Anadolu Lisesi',
    'ADANA - SARIÇAM - Cemil Meriç Anadolu Lisesi',
    'ADANA - SARIÇAM - Sarıçam Rehberlik ve Araştırma Merkezi',
    'ADANA - SARIÇAM - Çarkıpare Şehit Ertan Tokuş İlkokulu',
    'ADANA - SARIÇAM - Çarkıpare Şehit Ertan Tokuş Ortaokulu',
    'ADANA - SARIÇAM - Kılıçlı Anadolu Lisesi',
    'ADANA - SARIÇAM - Adana Adalet Meslekî Eğitim Merkezi',
    'ADANA - SARIÇAM - Sarıçam Bilim ve Sanat Merkezi',
    'ADANA - SARIÇAM - Arif Nihat Asya Anaokulu',
    'ADANA - SARIÇAM - Ata Anaokulu',
    'ADANA - SARIÇAM - Çarkıpare Şehit Ertan Tokuş Anaokulu',
    'ADANA - SARIÇAM - Ömer Kanaatbilen Anaokulu',
    'ADANA - SARIÇAM - Buruk Anaokulu',
    'ADANA - SARIÇAM - Hüseyin Avni Coş Anaokulu',
    'ADANA - SARIÇAM - Veli Yavuz Anaokulu',
    'ADANA - SARIÇAM - Kaşobası Girne İlkokulu',
    'ADANA - SARIÇAM - Uluğ Bey Anaokulu',
    'ADANA - SARIÇAM - Sarıçam Yıldız Anaokulu',
    'ADANA - SARIÇAM - Bayrak Anaokulu',
    'ADANA - SARIÇAM - Kozanoğlu Özel Eğitim Anaokulu',
    'ADANA - SEYHAN - TOKİ Şehit Ozan Onur İlgen Anadolu Lisesi',
    'ADANA - SEYHAN - 19 Mayıs Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit Sercan Yılmaz Ortaokulu',
    'ADANA - SEYHAN - 23 Nisan İmam Hatip Ortaokulu',
    'ADANA - SEYHAN - 5 Ocak Ortaokulu',
    'ADANA - SEYHAN - Abdulkadir Paksoy Anadolu Lisesi',
    'ADANA - SEYHAN - Adana Kıvanç Anadolu İmam Hatip Lisesi',
    'ADANA - SEYHAN - Adana Fen Lisesi',
    'ADANA - SEYHAN - Seyhan Borsa İstanbul Fen Lisesi',
    'ADANA - SEYHAN - Adana Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Adasokağı Anadolu Lisesi',
    'ADANA - SEYHAN - Adasokağı İlkokulu',
    'ADANA - SEYHAN - Adnan Menderes İlkokulu',
    'ADANA - SEYHAN - Şehit Gökhan Aygül İlkokulu',
    'ADANA - SEYHAN - Ahmet Karabucak İlkokulu',
    'ADANA - SEYHAN - Akkapı Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Anafartalar Anadolu Lisesi',
    'ADANA - SEYHAN - Atatürk İlkokulu',
    'ADANA - SEYHAN - Bahçelievler İlkokulu',
    'ADANA - SEYHAN - Bahçeşehir İlkokulu',
    'ADANA - SEYHAN - Barbaros Borsa İstanbul Anadolu Lisesi',
    'ADANA - SEYHAN - Birinci İnönü İlkokulu',
    'ADANA - SEYHAN - Gazi Anadolu Lisesi',
    'ADANA - SEYHAN - Büyükdikili İlkokulu',
    'ADANA - SEYHAN - Celalettin Sayhan İlkokulu',
    'ADANA - SEYHAN - Cumhuriyet Anaokulu',
    'ADANA - SEYHAN - Cumhuriyet Ortaokulu',
    'ADANA - SEYHAN - Seyhan ÇEP Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Çobanoğlu Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit Mehmet Volkan İlkokulu',
    'ADANA - SEYHAN - Dosteller Ortaokulu',
    'ADANA - SEYHAN - Dr.M. Feyyaz Etiz Anadolu Lisesi',
    'ADANA - SEYHAN - Adana Erkek Anadolu Lisesi',
    'ADANA - SEYHAN - Fatih Terim Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit Fatih Yeniay Anadolu Lisesi',
    'ADANA - SEYHAN - Seyhan Halk Eğitimi Merkezi',
    'ADANA - SEYHAN - Hürriyet İlkokulu',
    'ADANA - SEYHAN - İhsan Sabancı Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Borsa İstanbul 24 Kasım Anadolu Lisesi',
    'ADANA - SEYHAN - İsmet İnönü Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Seyhan İsmet İnönü Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - İstiklal Ortaokulu',
    'ADANA - SEYHAN - Karayusuflu İlkokulu',
    'ADANA - SEYHAN - Kazım Karabekir Özel Eğitim Uygulama Okulu I. Kademe',
    'ADANA - SEYHAN - Demokrasi İlkokulu',
    'ADANA - SEYHAN - Fatih Sultan Mehmet Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Leman Sayıt Ortaokulu',
    'ADANA - SEYHAN - Lütfiye Kısacık İlkokulu',
    'ADANA - SEYHAN - Mehmet Selahattin Çolak İlkokulu',
    'ADANA - SEYHAN - Hüsnü M. Özyeğin Ortaokulu',
    'ADANA - SEYHAN - Mehmet Kemal Tuncel Anadolu Lisesi',
    'ADANA - SEYHAN - Seyhan Mesleki Eğitim Merkezi',
    'ADANA - SEYHAN - Mimar Kemal İlkokulu',
    'ADANA - SEYHAN - Mimar Melahat Öngen Anaokulu',
    'ADANA - SEYHAN - Saniye Özaltın Ortaokulu',
    'ADANA - SEYHAN - Mümine Hatun Anaokulu',
    'ADANA - SEYHAN - Necatibey İlkokulu',
    'ADANA - SEYHAN - Nüsret Şenay Anaokulu',
    'ADANA - SEYHAN - Orhan Çobanoğlu İlkokulu',
    'ADANA - SEYHAN - Orhan Çobanoğlu Anadolu Lisesi',
    'ADANA - SEYHAN - Osmangazi Ortaokulu',
    'ADANA - SEYHAN - Ömer Haluk Özuçak İlkokulu',
    'ADANA - SEYHAN - Plevne İlkokulu',
    'ADANA - SEYHAN - Sabancı Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Sarıhamzalı Anadolu Lisesi',
    'ADANA - SEYHAN - Seyhan Belediyesi İlkokulu',
    'ADANA - SEYHAN - Seyhan Danişment Gazi Anadolu Lisesi',
    'ADANA - SEYHAN - Seyhan İşitme Engelliler İlkokulu',
    'ADANA - SEYHAN - Seyhan İşitme Engelliler Ortaokulu',
    'ADANA - SEYHAN - Seyhan Şakirpaşa Halk Eğitimi Merkezi',
    'ADANA - SEYHAN - Şakirpaşa İlkokulu',
    'ADANA - SEYHAN - Şakirpaşa Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit İlbey Gülbey Ortaokulu',
    'ADANA - SEYHAN - Seyhan Şehit Yavuz Öztürk Halk Eğitimi Merkezi',
    'ADANA - SEYHAN - Şehit Duran İlkokulu',
    'ADANA - SEYHAN - Şehit Murat Savaş Kale İlkokulu',
    'ADANA - SEYHAN - Taşkent Ortaokulu',
    'ADANA - SEYHAN - Tepebağ Anadolu İmam Hatip Lisesi',
    'ADANA - SEYHAN - Tepebağ Anadolu Lisesi',
    'ADANA - SEYHAN - TOKİ Şehit Fikret Yükseler İlkokulu',
    'ADANA - SEYHAN - Toros İlkokulu',
    'ADANA - SEYHAN - Turgut Özal Anadolu Lisesi',
    'ADANA - SEYHAN - Yeşilevler Şehit Duran Keskin İlkokulu',
    'ADANA - SEYHAN - Yeşilyuva İlkokulu',
    'ADANA - SEYHAN - Yıldırım Bayazıt Ortaokulu',
    'ADANA - SEYHAN - Mustafa Kemal Atatürk İlkokulu',
    'ADANA - SEYHAN - Ziya Gökalp İlkokulu',
    'ADANA - SEYHAN - Ramazanoğlu Ortaokulu',
    'ADANA - SEYHAN - Küçükdikili Mekan Ortaokulu',
    'ADANA - SEYHAN - Büyük Selçuklu Anadolu Lisesi',
    'ADANA - SEYHAN - Anafartalar İlkokulu',
    'ADANA - SEYHAN - Beşocak Anadolu Lisesi',
    'ADANA - SEYHAN - Kanuni İlkokulu',
    'ADANA - SEYHAN - Orhangazi Ortaokulu',
    'ADANA - SEYHAN - Yavuz Selim Ortaokulu',
    'ADANA - SEYHAN - Dumlupınar Ortaokulu',
    'ADANA - SEYHAN - Barbaros Ortaokulu',
    'ADANA - SEYHAN - İsmail Hazar İlkokulu',
    'ADANA - SEYHAN - Petrol Ofisi İlkokulu',
    'ADANA - SEYHAN - 29 Ekim İlkokulu',
    'ADANA - SEYHAN - Malazgirt Ortaokulu',
    'ADANA - SEYHAN - Meryem-Abdurrahim Gizer Ortaokulu',
    'ADANA - SEYHAN - Şehit Metin Malkav Ortaokulu',
    'ADANA - SEYHAN - Süreyya Nihat Oral Ortaokulu',
    'ADANA - SEYHAN - Nuri ve Zekiye Has Ortaokulu',
    'ADANA - SEYHAN - 24 Kasım İlkokulu',
    'ADANA - SEYHAN - Fatih Mehmet İlkokulu',
    'ADANA - SEYHAN - Sarıhamzalı Ortaokulu',
    'ADANA - SEYHAN - Seyit Ali Onbaşı İlkokulu',
    'ADANA - SEYHAN - Ahmet Sapmaz Ortaokulu',
    'ADANA - SEYHAN - Yıldırım Bayazıt İlkokulu',
    'ADANA - SEYHAN - Adana Seyhan Şehit Bora Süelkan Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit İdris Güler Ortaokulu',
    'ADANA - SEYHAN - İkinci İnönü İlkokulu',
    'ADANA - SEYHAN - Gülbahçesi Ortaokulu',
    'ADANA - SEYHAN - Manas Ortaokulu',
    'ADANA - SEYHAN - Abdurrahim Karakoç İlkokulu',
    'ADANA - SEYHAN - Yenidam İlkokulu',
    'ADANA - SEYHAN - 80. Yıl İlkokulu',
    'ADANA - SEYHAN - Gazipaşa İlkokulu',
    'ADANA - SEYHAN - Seyhan Sakarya Ortaokulu',
    'ADANA - SEYHAN - Milli Mensucat İlkokulu',
    'ADANA - SEYHAN - Cemil Nardalı İlkokulu',
    'ADANA - SEYHAN - Mürseloğlu İlkokulu',
    'ADANA - SEYHAN - Mevlana Ortaokulu',
    'ADANA - SEYHAN - İsmet İnönü İlkokulu',
    'ADANA - SEYHAN - Hayriye Kemal Kusun İlkokulu',
    'ADANA - SEYHAN - Hüsnü-Semih Hızlan Anaokulu',
    'ADANA - SEYHAN - İlhan Atış Anadolu Lisesi',
    'ADANA - SEYHAN - Barbaros Anaokulu',
    'ADANA - SEYHAN - Şehit Ercan Sanca İlkokulu',
    'ADANA - SEYHAN - Kayışlı İlkokulu',
    'ADANA - SEYHAN - Turhan Cemal Beriker İlkokulu',
    'ADANA - SEYHAN - Aşık Veysel Özel Eğitim Uygulama Okulu I. Kademe',
    'ADANA - SEYHAN - Yeşilevler Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - Zeytinli İlkokulu',
    'ADANA - SEYHAN - Zeytinli Ortaokulu',
    'ADANA - SEYHAN - Öğretmen Ayfer Doğruol İlkokulu',
    'ADANA - SEYHAN - Gölbaşı Ortaokulu',
    'ADANA - SEYHAN - Şehit Mehmet Fatih Ongun Ortaokulu',
    'ADANA - SEYHAN - Cebesoy İlkokulu',
    'ADANA - SEYHAN - Zübeyde Hanım Anaokulu',
    'ADANA - SEYHAN - Semiha Uruninandı Ortaokulu',
    'ADANA - SEYHAN - Gazi Ortaokulu',
    'ADANA - SEYHAN - Seyhan Rehberlik ve Araştırma Merkezi',
    'ADANA - SEYHAN - Ziyapaşa Ortaokulu',
    'ADANA - SEYHAN - Öğretmen Evi ve Akşam Sanat Okulu',
    'ADANA - SEYHAN - 125. Yıl Ortaokulu',
    'ADANA - SEYHAN - Şehit İsmail Demir Ortaokulu',
    'ADANA - SEYHAN - Necatibey Anaokulu',
    'ADANA - SEYHAN - Çıldırım İlkokulu',
    'ADANA - SEYHAN - İnkılap İmam Hatip Ortaokulu',
    'ADANA - SEYHAN - Havuzlubahçe İlkokulu',
    'ADANA - SEYHAN - Akdeniz Anaokulu',
    'ADANA - SEYHAN - Gökçeler İsmail Kayhan İlkokulu',
    'ADANA - SEYHAN - Gökçeler İsmail Kayhan Ortaokulu',
    'ADANA - SEYHAN - Şehit Mahmut Yeşilçam İlkokulu',
    'ADANA - SEYHAN - Yeşiloba İlkokulu',
    'ADANA - SEYHAN - Şehit Erhan Taştimur İlkokulu',
    'ADANA - SEYHAN - Kazım Karabekir Özel Eğitim Uygulama Okulu II. Kademe',
    'ADANA - SEYHAN - Bekir Hanife Akata İlkokulu',
    'ADANA - SEYHAN - Akkapı Şehit Kemal Yüzgeç Ortaokulu',
    'ADANA - SEYHAN - Şehit Nasıf Namlu İlkokulu',
    'ADANA - SEYHAN - Talat Hacıbekiroğlu İlkokulu',
    'ADANA - SEYHAN - Yalmanlı İlkokulu',
    'ADANA - SEYHAN - Atatürk Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - İsmail Hazar Anaokulu',
    'ADANA - SEYHAN - Kasım Sacide Ener Ortaokulu',
    'ADANA - SEYHAN - Hadırlı İlkokulu',
    'ADANA - SEYHAN - Adana Olgunlaşma Enstitüsü',
    'ADANA - SEYHAN - Adasokağı Ortaokulu',
    'ADANA - SEYHAN - Hafsa Sultan Anaokulu',
    'ADANA - SEYHAN - CAMUZCU İLKOKULU',
    'ADANA - SEYHAN - Ahmet Cevdet Çamurdan Ortaokulu',
    'ADANA - SEYHAN - Portakal Çiçeği Anaokulu',
    'ADANA - SEYHAN - ŞEHİT ZAFER OLUK ORTAOKULU',
    'ADANA - SEYHAN - BÜYÜKDİKİLİ ORTAOKULU',
    'ADANA - SEYHAN - NİLÜFER HATUN ORTAOKULU',
    'ADANA - SEYHAN - CUMHURİYET İLKOKULU',
    'ADANA - SEYHAN - ŞÜKRAN ÇOBANOĞLU ORTAOKULU',
    'ADANA - SEYHAN - SARIHAMZALI İMAM HATİP LİSESİ',
    'ADANA - SEYHAN - Mithatpaşa Ecrin Meydan İlkokulu',
    'ADANA - SEYHAN - Havuzlubahçe Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - ŞENGÜL-KENAN ŞENBAYRAK İLKOKULU',
    'ADANA - SEYHAN - KUYUMCULAR İLKOKULU',
    'ADANA - SEYHAN - Hadırlı Ortaokulu',
    'ADANA - SEYHAN - Mahmud Sami Ramazanoğlu Anadolu İmam Hatip Lisesi',
    'ADANA - SEYHAN - MEHMET ZAHİD KOTKU İMAM HATİP ORTAOKULU',
    'ADANA - SEYHAN - Sadıka Sabancı Ortaokulu',
    'ADANA - SEYHAN - DERVİŞLER İLKOKULU',
    'ADANA - SEYHAN - ŞEHİT MAHMUT YEŞİLÇAM ORTAOKULU',
    'ADANA - SEYHAN - Şehit Zeki Dağ İlkokulu',
    'ADANA - SEYHAN - ALİYA İZZET BEGOVİÇ ORTAOKULU',
    'ADANA - SEYHAN - SÜREYYA NİHAT ORAL İLKOKULU',
    'ADANA - SEYHAN - KÜÇÜKDİKİLİ MEKAN İLKOKULU',
    'ADANA - SEYHAN - MANAS İLKOKULU',
    'ADANA - SEYHAN - SARIHAMZALI İLKOKULU',
    'ADANA - SEYHAN - Mehmet-Kamuran Tekin Özel Eğitim Uygulama Okulu III. Kademe',
    'ADANA - SEYHAN - Aşık Veysel Özel Eğitim Uygulama Okulu II. Kademe',
    'ADANA - SEYHAN - LALEZAR ANAOKULU',
    'ADANA - SEYHAN - Yeşiloba Ortaokulu',
    'ADANA - SEYHAN - Turgut Reis İlkokulu',
    'ADANA - SEYHAN - Küçükdikili İlkokulu',
    'ADANA - SEYHAN - AKKAPI İLKOKULU',
    'ADANA - SEYHAN - GÖLBAŞI İLKOKULU',
    'ADANA - SEYHAN - KARAYUSUFLU ORTAOKULU',
    'ADANA - SEYHAN - KÖYLÜOĞLU İLKOKULU',
    'ADANA - SEYHAN - VEYSEL KARANİ İLKOKULU',
    'ADANA - SEYHAN - Seyhan Özel Eğitim Uygulama Okulu I. Kademe',
    'ADANA - SEYHAN - Seyhan Özel Eğitim Uygulama Okulu II. Kademe',
    'ADANA - SEYHAN - AKKAPI ANAOKULU',
    'ADANA - SEYHAN - BEDİÜZZAMAN SAİD NURSİ İMAM HATİP ORTAOKULU',
    'ADANA - SEYHAN - Şehitlik Anadolu İmam Hatip Lisesi',
    'ADANA - SEYHAN - ARİF NİHAT ASYA ANADOLU LİSESİ',
    'ADANA - SEYHAN - GÜLÇOCUK ANAOKULU',
    'ADANA - SEYHAN - ŞEHİT AHMET-MEHMET ORUÇ SPOR LİSESİ',
    'ADANA - SEYHAN - ŞEHİT YUNUS UĞUR ORTAOKULU',
    'ADANA - SEYHAN - Şehit Halit Yaşar Mine Ortaokulu',
    'ADANA - SEYHAN - 15 Temmuz Şehitleri Anadolu İmam Hatip Lisesi',
    'ADANA - SEYHAN - ŞEHİT SEVDA GÜNGÖR ANAOKULU',
    'ADANA - SEYHAN - UÇAKALANI ORTAOKULU',
    'ADANA - SEYHAN - GÜLBAHÇESİ KIZ ANADOLU LİSESİ',
    'ADANA - SEYHAN - Şehit Hacı Ahmet Öztürk İmam Hatip Ortaokulu',
    'ADANA - SEYHAN - ŞAKİRPAŞA ÜMRAN ORTAOKULU',
    'ADANA - SEYHAN - Şehitlik İlkokulu',
    'ADANA - SEYHAN - AY YILDIZ ANAOKULU MÜDÜRLÜĞÜ',
    'ADANA - SEYHAN - Motorlu Araçlar Teknolojisi Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - ŞEHİT İBRAHİM DERİNDERE ANADOLU LİSESİ',
    'ADANA - SEYHAN - ÖMER FARUK KARABUCAK ANADOLU İMAM HATİP LİSESİ',
    'ADANA - SEYHAN - ŞAKİRPAŞA MESLEKİ VE TEKNİK ANADOLU LİSESİ',
    'ADANA - SEYHAN - Gülbahçesi Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - SEYHAN - ŞEHİT NİHAT ŞENER ORTAOKULU',
    'ADANA - SEYHAN - TEPEBAĞ İMAM HATİP ORTAOKULU',
    'ADANA - SEYHAN - Şehit Ufuk Fesli Ortaokulu Müdürlüğü',
    'ADANA - SEYHAN - Seyhan Borsa Anadolu Lisesi',
    'ADANA - SEYHAN - Seyhan Anadolu Lisesi',
    'ADANA - SEYHAN - Uçakalanı İlkokulu',
    'ADANA - SEYHAN - Yeşiloba Anaokulu',
    'ADANA - SEYHAN - Şehit İsa İpek İlkokulu',
    'ADANA - SEYHAN - Gülnaz Gülenoğlu İlkokulu',
    'ADANA - SEYHAN - Necdet Kahraman Anadolu İmam Hatip Lisesi',
    'ADANA - SEYHAN - Şehit Samet Özkan İlkokulu',
    'ADANA - SEYHAN - Hüsamettin Özaltın Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit Eren Yücel Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit Alper Öçay Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit Ali Bezik Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit Yusuf Aktan Kız Anadolu Lisesi',
    'ADANA - SEYHAN - Preveze Anadolu Lisesi',
    'ADANA - SEYHAN - Cafer Recai Gizer Anadolu Lisesi',
    'ADANA - SEYHAN - Güler Namlı Anadolu Lisesi',
    'ADANA - SEYHAN - Şehit Seyfi Yozcu İlkokulu',
    'ADANA - SEYHAN - Taşköprü İlkokulu',
    'ADANA - SEYHAN - Şehit Fettah Çevikoğlu Ortaokulu',
    'ADANA - SEYHAN - Büyüksaat Ortaokulu',
    'ADANA - SEYHAN - Manas Özel Eğitim Anaokulu',
    'ADANA - SEYHAN - Keloğlan Anaokulu',
    'ADANA - SEYHAN - Şehit Sezgin Sezgin Ortaokulu',
    'ADANA - SEYHAN - Kıyıboyu İlkokulu',
    'ADANA - SEYHAN - Şakirpaşa Özel Eğitim Meslek Okulu',
    'ADANA - SEYHAN - Seyhan Bilim ve Sanat Merkezi',
    'ADANA - SEYHAN - Yeşiloba Özel Eğitim Anaokulu',
    'ADANA - SEYHAN - Gülçocuk Özel Eğitim Anaokulu',
    'ADANA - SEYHAN - Barbaros Özel Eğitim Anaokulu',
    'ADANA - SEYHAN - Seyhan İstiklal Anadolu Lisesi',
    'ADANA - SEYHAN - 80. Yıl Anaokulu',
    'ADANA - SEYHAN - Seyhan İsmail Hazar Anaokulu',
    'ADANA - SEYHAN - Mimar Kemal Anaokulu',
    'ADANA - SEYHAN - Mustafa Kemal Atatürk Anaokulu',
    'ADANA - SEYHAN - Öğretmen Ayfer Doğruol Anaokulu',
    'ADANA - SEYHAN - Seyhan Belediyesi Anaokulu',
    'ADANA - SEYHAN - Şakirpaşa Anaokulu',
    'ADANA - SEYHAN - Şehit Murat Savaş Kale Anaokulu',
    'ADANA - SEYHAN - Toros Anaokulu',
    'ADANA - SEYHAN - Yeşilevler Şehit Duran Keskin Anaokulu',
    'ADANA - SEYHAN - Meydan Ortaokulu',
    'ADANA - SEYHAN - Yeşilyurt İlkokulu',
    'ADANA - SEYHAN - Abdurrahim Karakoç Anaokulu',
    'ADANA - SEYHAN - Seyhan Sakarya Anaokulu',
    'ADANA - SEYHAN - Sarıhamzalı Anaokulu',
    'ADANA - SEYHAN - Şehit Ercan Sanca Anaokulu',
    'ADANA - SEYHAN - Birinci İnönü Anaokulu',
    'ADANA - SEYHAN - Şehit Duran Anaokulu',
    'ADANA - SEYHAN - Şehit Zeki Dağ Anaokulu',
    'ADANA - SEYHAN - Fatih Mehmet Anaokulu',
    'ADANA - SEYHAN - TOKİ Şehit Fikret Yükseler Anaokulu',
    'ADANA - SEYHAN - Yeşilyuva Anaokulu',
    'ADANA - SEYHAN - İsmail Hazar Ortaokulu',
    'ADANA - SEYHAN - İsmail Batu Dağtekin Kızılay Anaokulu',
    'ADANA - SEYHAN - Gülbahçesi İlkokulu',
    'ADANA - TUFANBEYLİ - Şehit İsmail Moğol İlkokulu',
    'ADANA - TUFANBEYLİ - Cumhuriyet İlkokulu',
    'ADANA - TUFANBEYLİ - Tufanbeyli Halk Eğitimi Merkezi',
    'ADANA - TUFANBEYLİ - Tufanbeyli Anadolu İmam Hatip Lisesi',
    'ADANA - TUFANBEYLİ - Kayarcık İlkokulu',
    'ADANA - TUFANBEYLİ - Şehit Mesut Alcı Anadolu Lisesi',
    'ADANA - TUFANBEYLİ - Yamanlı İlkokulu',
    'ADANA - TUFANBEYLİ - Doğanbeyli Ortaokulu',
    'ADANA - TUFANBEYLİ - Atatürk Yatılı Bölge Ortaokulu',
    'ADANA - TUFANBEYLİ - Doğanbeyli İlkokulu',
    'ADANA - TUFANBEYLİ - Çatalçam İlkokulu',
    'ADANA - TUFANBEYLİ - Tufanbeyli Ortaokulu',
    'ADANA - TUFANBEYLİ - İstiklal İlkokulu',
    'ADANA - TUFANBEYLİ - Şehit Mehmet Ali Zorca İlkokulu',
    'ADANA - TUFANBEYLİ - Çatalçam Ortaokulu',
    'ADANA - TUFANBEYLİ - Kirazlıyurt İlkokulu',
    'ADANA - TUFANBEYLİ - Kayarcık Ortaokulu',
    'ADANA - TUFANBEYLİ - Demiroluk İlkokulu',
    'ADANA - TUFANBEYLİ - Şehit Sadık Özkan İlkokulu',
    'ADANA - TUFANBEYLİ - Karsavuran İlkokulu',
    'ADANA - TUFANBEYLİ - Tufanbeyli Öğretmenevi ve Akşam Sanat Okulu',
    'ADANA - TUFANBEYLİ - Şehit Mehmet Ali Zorca Ortaokulu',
    'ADANA - TUFANBEYLİ - Şehit İsmail Moğol Ortaokulu',
    'ADANA - TUFANBEYLİ - DOĞANLI ORTAOKULU',
    'ADANA - TUFANBEYLİ - DOĞANLI İLKOKULU',
    'ADANA - TUFANBEYLİ - Enerjisa Tufanbeyli Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - TUFANBEYLİ - Şehit Ahmet Batkı Anaokulu',
    'ADANA - TUFANBEYLİ - Tufanbeyli Bilim ve Sanat Merkezi',
    'ADANA - YUMURTALIK - Atatürk Ortaokulu',
    'ADANA - YUMURTALIK - Ganime Erzenci Ortaokulu',
    'ADANA - YUMURTALIK - Gölovası İlkokulu',
    'ADANA - YUMURTALIK - Yumurtalık Halk Eğitimi Merkezi',
    'ADANA - YUMURTALIK - Kuzupınarı Hacımüminler Ortaokulu',
    'ADANA - YUMURTALIK - Yumurtalık Çok Programlı Anadolu Lisesi',
    'ADANA - YUMURTALIK - Meryem-Ali Öztürk İlkokulu',
    'ADANA - YUMURTALIK - Kaldırım Ortaokulu',
    'ADANA - YUMURTALIK - Kaldırım İlkokulu',
    'ADANA - YUMURTALIK - Asmalı İlkokulu',
    'ADANA - YUMURTALIK - Asmalı Göbeören İlkokulu',
    'ADANA - YUMURTALIK - Deveciuşağı İlkokulu',
    'ADANA - YUMURTALIK - Ganime Erzenci İlkokulu',
    'ADANA - YUMURTALIK - Meryem-Ali Öztürk Ortaokulu',
    'ADANA - YUMURTALIK - Kuzupınarı Zeynepli İlkokulu',
    'ADANA - YUMURTALIK - Kuzupınarı Hacımüminler İlkokulu',
    'ADANA - YUMURTALIK - Kuzupınarı Zeynepli Ortaokulu',
    'ADANA - YUMURTALIK - Şehit Cavit Tamtürk İlkokulu',
    'ADANA - YUMURTALIK - Kırmızıdam İlkokulu',
    'ADANA - YUMURTALIK - Şehit Harun Arslanbay İlkokulu',
    'ADANA - YUMURTALIK - Şehit Samet Kaya İmam Hatip Ortaokulu',
    'ADANA - YUMURTALIK - Barbaros İlkokulu',
    'ADANA - YUMURTALIK - Gölovası Ortaokulu',
    'ADANA - YUMURTALIK - Yumurtalık Barbaros Anaokulu',
    'ADANA - YUMURTALIK - Haylazlı İlkokulu',
    'ADANA - YÜREĞİR - 75.Yıl Anadolu Lisesi',
    'ADANA - YÜREĞİR - Adana Lions Kulübü Cumhuriyet Savcısı Özer Kaya Anaokulu',
    'ADANA - YÜREĞİR - Akpınar İlkokulu',
    'ADANA - YÜREĞİR - Albay İbrahim Karaoğlanoğlu İlkokulu',
    'ADANA - YÜREĞİR - Anadolu Efes İlkokulu',
    'ADANA - YÜREĞİR - Camili Akarca İlkokulu',
    'ADANA - YÜREĞİR - Camili Akarca Ortaokulu',
    'ADANA - YÜREĞİR - Hatice Hatun Anaokulu',
    'ADANA - YÜREĞİR - Cırık İlkokulu',
    'ADANA - YÜREĞİR - Yüreğir Cumhuriyet Halk Eğitimi Merkezi',
    'ADANA - YÜREĞİR - Cumhuriyet Ortaokulu',
    'ADANA - YÜREĞİR - Çamlıbel Ortaokulu',
    'ADANA - YÜREĞİR - Şehit Emre Mücahit Topal İlkokulu',
    'ADANA - YÜREĞİR - Dadaloğlu Anadolu Lisesi',
    'ADANA - YÜREĞİR - Doğankent Anaokulu',
    'ADANA - YÜREĞİR - Sazak İlkokulu',
    'ADANA - YÜREĞİR - Emine Özgüler Gürsu İmam Hatip Ortaokulu',
    'ADANA - YÜREĞİR - Enver Kurttepeli Anadolu Lisesi',
    'ADANA - YÜREĞİR - Farabi Anadolu Lisesi',
    'ADANA - YÜREĞİR - Gazeteci Adem Yavuz İlkokulu',
    'ADANA - YÜREĞİR - Hakkı Polat Kız Anadolu İmam Hatip Lisesi',
    'ADANA - YÜREĞİR - Yüreğir Halk Eğitimi Merkezi',
    'ADANA - YÜREĞİR - Goncagül Anaokulu',
    'ADANA - YÜREĞİR - Havutlu Bedii Topçu Ortaokulu',
    'ADANA - YÜREĞİR - Hayme Ana Anaokulu',
    'ADANA - YÜREĞİR - Gökçeli İlkokulu',
    'ADANA - YÜREĞİR - Çetin Topçuoğlu İlkokulu',
    'ADANA - YÜREĞİR - Gökvelioğlu İlkokulu',
    'ADANA - YÜREĞİR - Karacaoğlan Ortaokulu',
    'ADANA - YÜREĞİR - Mahıpeyker-Fatma Bağcivan Anaokulu',
    'ADANA - YÜREĞİR - Karşıyaka İlkokulu',
    'ADANA - YÜREĞİR - Karşıyaka Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - YÜREĞİR - İsmail Sefa Özler Ortaokulu',
    'ADANA - YÜREĞİR - Kiremithane Şehit Kadir Görgülü İlkokulu',
    'ADANA - YÜREĞİR - Kiremithane Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - YÜREĞİR - Kaşlıca İlkokulu',
    'ADANA - YÜREĞİR - Koza Ortaokulu',
    'ADANA - YÜREĞİR - Köklüce Ortaokulu',
    'ADANA - YÜREĞİR - Kumrulu Huriye Filik İlkokulu',
    'ADANA - YÜREĞİR - Lokman Hekim Anadolu Lisesi',
    'ADANA - YÜREĞİR - Mareşal Çakmak İlkokulu',
    'ADANA - YÜREĞİR - Mehmet Ali Yılmaz İlkokulu',
    'ADANA - YÜREĞİR - Mehmetçik Anaokulu',
    'ADANA - YÜREĞİR - Melikşah Anadolu Lisesi',
    'ADANA - YÜREĞİR - Kütüklü İlkokulu',
    'ADANA - YÜREĞİR - Mimar Sinan İlkokulu',
    'ADANA - YÜREĞİR - Mobil A.Ş. Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - YÜREĞİR - Suat Güçlü Ortaokulu',
    'ADANA - YÜREĞİR - Mutlu İlkokulu',
    'ADANA - YÜREĞİR - Ömer Refika Halıcılar İlkokulu',
    'ADANA - YÜREĞİR - Prof.Dr.Salih Öven Çolakoğlu İlkokulu',
    'ADANA - YÜREĞİR - Recep Ünlükurt İlkokulu',
    'ADANA - YÜREĞİR - Yüreğir Rehberlik ve Araştırma Merkezi',
    'ADANA - YÜREĞİR - Sabiha Gökçen Anaokulu',
    'ADANA - YÜREĞİR - Seyhan Rotary Anadolu Lisesi',
    'ADANA - YÜREĞİR - Solaklı Atatürk İlkokulu',
    'ADANA - YÜREĞİR - Solaklı Şehit Özkan Altınok İlkokulu',
    'ADANA - YÜREĞİR - Sunar Nuri Çomu Anadolu Lisesi',
    'ADANA - YÜREĞİR - Şehit Abdullah Aydın Emer Anadolu Lisesi',
    'ADANA - YÜREĞİR - Yüreğir Şehit Samet Saraç Halk Eğitimi Merkezi',
    'ADANA - YÜREĞİR - Ticaret Borsası İlkokulu',
    'ADANA - YÜREĞİR - TOKİ Köprülü Ortaokulu',
    'ADANA - YÜREĞİR - Ulubatlı Hasan İlkokulu',
    'ADANA - YÜREĞİR - Vehbi Necip Savaşan İlkokulu',
    'ADANA - YÜREĞİR - Yakapınar Selahattin Afşar Anadolu Lisesi',
    'ADANA - YÜREĞİR - Yavuzlar Ortaokulu',
    'ADANA - YÜREĞİR - Yenice İlkokulu',
    'ADANA - YÜREĞİR - Yukarı Çiçekli İlkokulu',
    'ADANA - YÜREĞİR - Doğankent Anadolu Lisesi',
    'ADANA - YÜREĞİR - Yüreğir Halıcılar Anadolu Lisesi',
    'ADANA - YÜREĞİR - Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - YÜREĞİR - Recep Ünlükurt Ortaokulu',
    'ADANA - YÜREĞİR - Köklüce İlkokulu',
    'ADANA - YÜREĞİR - Yüreğir İmam Hatip Ortaokulu',
    'ADANA - YÜREĞİR - Mehmet Adil İkiz İmam Hatip Ortaokulu',
    'ADANA - YÜREĞİR - Yakapınar Peyami Safa Ortaokulu',
    'ADANA - YÜREĞİR - Seniha Çobanoğlu İlkokulu',
    'ADANA - YÜREĞİR - Adana Eczacı Odası Anaokulu',
    'ADANA - YÜREĞİR - Tuğrulbey Ortaokulu',
    'ADANA - YÜREĞİR - Karacaoğlan İlkokulu',
    'ADANA - YÜREĞİR - Sabancı Ailesi İmam Hatip Ortaokulu',
    'ADANA - YÜREĞİR - Çotlu Ortaokulu',
    'ADANA - YÜREĞİR - Kışla Şehit Orçun Kubat İlkokulu',
    'ADANA - YÜREĞİR - Kazım Karabekir Ortaokulu',
    'ADANA - YÜREĞİR - Koza İlkokulu',
    'ADANA - YÜREĞİR - Şehit Öğretmen Sait Korkmaz Ortaokulu',
    'ADANA - YÜREĞİR - Atakent Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - YÜREĞİR - Dervişler Şehit Cevdet Özdaş İlkokulu',
    'ADANA - YÜREĞİR - Cengiz Topel İlkokulu',
    'ADANA - YÜREĞİR - Ethem Kuzucu İlkokulu',
    'ADANA - YÜREĞİR - Anadolu Ortaokulu',
    'ADANA - YÜREĞİR - Mustafa Cahit Kıraç İlkokulu',
    'ADANA - YÜREĞİR - Yüreğir Mesleki Eğitim Merkezi',
    'ADANA - YÜREĞİR - Şehit Avukat Mehmet Özel İlkokulu',
    'ADANA - YÜREĞİR - Süleyman Şah Ortaokulu',
    'ADANA - YÜREĞİR - Dervişler Ortaokulu',
    'ADANA - YÜREĞİR - Çatalpınar İlkokulu',
    'ADANA - YÜREĞİR - Makimsan İlkokulu',
    'ADANA - YÜREĞİR - Alihocalı İlkokulu',
    'ADANA - YÜREĞİR - İstiklal İlkokulu',
    'ADANA - YÜREĞİR - TOKİ Köprülü Anadolu Lisesi',
    'ADANA - YÜREĞİR - Makimsan Ortaokulu',
    'ADANA - YÜREĞİR - TOKİ Köprülü İlkokulu',
    'ADANA - YÜREĞİR - Tahsilli Şehit Hulisi Emre Dilci İlkokulu',
    'ADANA - YÜREĞİR - Şehit Muharrem Erdoğan İlkokulu',
    'ADANA - YÜREĞİR - Gazi Osman Paşa İlkokulu',
    'ADANA - YÜREĞİR - Şehit Muharrem Erdoğan Ortaokulu',
    'ADANA - YÜREĞİR - Bayram Karadağ İlkokulu',
    'ADANA - YÜREĞİR - Camili İlkokulu',
    'ADANA - YÜREĞİR - Sakıp Sabancı Ortaokulu',
    'ADANA - YÜREĞİR - Şehit Ali Gaffar Okkan İlkokulu',
    'ADANA - YÜREĞİR - İmadettin Levent İlkokulu',
    'ADANA - YÜREĞİR - Çatalpınar Ortaokulu',
    'ADANA - YÜREĞİR - Fevziye Çelik Ortaokulu',
    'ADANA - YÜREĞİR - Çotlu İlkokulu',
    'ADANA - YÜREĞİR - Havutlu İlkokulu',
    'ADANA - YÜREĞİR - Yakapınar Peyami Safa İlkokulu',
    'ADANA - YÜREĞİR - Semerkant İlkokulu',
    'ADANA - YÜREĞİR - Şehit Mustafa Turanlı Ortaokulu',
    'ADANA - YÜREĞİR - Kazime Özler Ortaokulu',
    'ADANA - YÜREĞİR - Mehmet Adil İkiz Ortaokulu',
    'ADANA - YÜREĞİR - Kazime Özler İlkokulu',
    'ADANA - YÜREĞİR - Fatin Rüştü Zorlu Ortaokulu',
    'ADANA - YÜREĞİR - Güney Sanayi Çalışanları İlkokulu',
    'ADANA - YÜREĞİR - Adana Rotary Kulübü Anaokulu',
    'ADANA - YÜREĞİR - Cumhuriyet Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - YÜREĞİR - Mehmet Akif İnan Anadolu Lisesi',
    'ADANA - YÜREĞİR - Medine Müdafii Fahreddin Paşa İmam Hatip Lisesi',
    'ADANA - YÜREĞİR - Emine Türkan İkiz İlkokulu',
    'ADANA - YÜREĞİR - Karşıyaka Orhan Çobanoğlu Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - YÜREĞİR - Şehit Mustafa Altan İlkokulu',
    'ADANA - YÜREĞİR - Şehit Mustafa Altan Ortaokulu',
    'ADANA - YÜREĞİR - Veysel Karani Ortaokulu',
    'ADANA - YÜREĞİR - Doğankent Celil Çavuşoğlu İlkokulu',
    'ADANA - YÜREĞİR - Yenihacıali Ortaokulu',
    'ADANA - YÜREĞİR - Doğankent Kemal Uludağ Ortaokulu',
    'ADANA - YÜREĞİR - Şehit Erdoğan Türkel İlkokulu',
    'ADANA - YÜREĞİR - Yenihacıali İlkokulu',
    'ADANA - YÜREĞİR - Irmakbaşı İlkokulu',
    'ADANA - YÜREĞİR - Hacı Bayram Veli İmam Hatip Ortaokulu',
    'ADANA - YÜREĞİR - Yahya Kemal Beyatlı 100.Yıl İlkokulu',
    'ADANA - YÜREĞİR - Efendi Halil Ortaokulu',
    'ADANA - YÜREĞİR - Necmiye Coşkuntuncel İlkokulu',
    'ADANA - YÜREĞİR - Kadıköy İlkokulu',
    'ADANA - YÜREĞİR - Kayarlı İlkokulu',
    'ADANA - YÜREĞİR - Damar Arıkoğlu İlkokulu',
    'ADANA - YÜREĞİR - Çağırkanlı Tanrıverdi İlkokulu',
    'ADANA - YÜREĞİR - Çağırkanlı İlkokulu',
    'ADANA - YÜREĞİR - Bayram Karadağ Ortaokulu',
    'ADANA - YÜREĞİR - Necla-Mithat Öztüre İlkokulu',
    'ADANA - YÜREĞİR - Necla-Mithat Öztüre Ortaokulu',
    'ADANA - YÜREĞİR - Camili Ortaokulu',
    'ADANA - YÜREĞİR - Doğankent İlkokulu',
    'ADANA - YÜREĞİR - Kılıçarslan Ortaokulu',
    'ADANA - YÜREĞİR - Vali Ziyapaşa Anadolu Lisesi',
    'ADANA - YÜREĞİR - Mavi Çocuk Utku Anaokulu',
    'ADANA - YÜREĞİR - Cahit Zarifoğlu Ortaokulu',
    'ADANA - YÜREĞİR - Hayret Efendi Anadolu İmam Hatip Lisesi',
    'ADANA - YÜREĞİR - Çamlıbel Şehit Kamil Yelmen Anadolu Lisesi',
    'ADANA - YÜREĞİR - NASRETTİN HOCA ANAOKULU',
    'ADANA - YÜREĞİR - Çakabey Ortaokulu',
    'ADANA - YÜREĞİR - Ömer Refika Halıcılar Ortaokulu',
    'ADANA - YÜREĞİR - Atatürk Mesleki ve Teknik Anadolu Lisesi',
    'ADANA - YÜREĞİR - Piri Reis Anaokulu',
    'ADANA - YÜREĞİR - KARACAOĞLAN ANAOKULU',
    'ADANA - YÜREĞİR - Kılavuz Hatice Anaokulu',
    'ADANA - YÜREĞİR - Gizem Akdeniz Anaokulu',
    'ADANA - YÜREĞİR - Kaşgarlı Mahmut Ortaokulu',
    'ADANA - YÜREĞİR - Yüreğir Özel Eğitim Uygulama Okulu I. Kademe',
    'ADANA - YÜREĞİR - NURETTİN TOPÇU İMAM HATİP ORTAOKULU',
    'ADANA - YÜREĞİR - AZİZ SANCAR MESLEKİ VE TEKNİK ANADOLU LİSESİ',
    'ADANA - YÜREĞİR - Yeşilbağlar İlkokulu',
    'ADANA - YÜREĞİR - AHMED-İ HANİ ORTAOKULU',
    'ADANA - YÜREĞİR - GEVHER NESİBE MESLEKİ VE TEKNİK ANADOLU LİSESİ',
    'ADANA - YÜREĞİR - Doğankent Anadolu İmam Hatip Lisesi',
    'ADANA - YÜREĞİR - NİZAMÜLMÜLK ANADOLU İMAM HATİP LİSESİ',
    'ADANA - YÜREĞİR - ŞEHİT AKİF HATUNOĞLU ANAOKULU',
    'ADANA - YÜREĞİR - Şehit Mustafa Göksal Anadolu Lisesi',
    'ADANA - YÜREĞİR - Şehit Nurettin Yıldırım Ortaokulu',
    'ADANA - YÜREĞİR - Şehit Cihan Çetinkaya Anaokulu',
    'ADANA - YÜREĞİR - Şehit Ayhan Güngör Anadolu Lisesi',
    'ADANA - YÜREĞİR - Şehit Süleyman Özcan Ortaokulu',
    'ADANA - YÜREĞİR - Şehit Kadir Kırbaç Kız Anadolu Lisesi',
    'ADANA - YÜREĞİR - Yüreğir Özel Eğitim Uygulama Okulu II. Kademe',
    'ADANA - YÜREĞİR - Oğuzcan Hasan Muratlı İlkokulu',
    'ADANA - YÜREĞİR - Karşıyaka Ortaokulu',
    'ADANA - YÜREĞİR - Karşıyaka Atatürk Anadolu Lisesi',
    'ADANA - YÜREĞİR - Yüreğir Anadolu Lisesi',
    'ADANA - YÜREĞİR - Kazım Karabekir Anadolu Lisesi',
    'ADANA - YÜREĞİR - Şehit Abdullah Yıldırım Anadolu Lisesi',
    'ADANA - YÜREĞİR - Çakabey İlkokulu',
    'ADANA - YÜREĞİR - Doğankent Ortaokulu',
    'ADANA - YÜREĞİR - Doğankent Ümmü Gülsüm Hilmi Cananoğlu İlkokulu',
    'ADANA - YÜREĞİR - Şehit Hilmi Bardakçı Ortaokulu',
    'ADANA - YÜREĞİR - Solaklı Ortaokulu',
    'ADANA - YÜREĞİR - Yüreğir Özel Eğitim Anaokulu',
    'ADANA - YÜREĞİR - Atakent Özel Eğitim Uygulama Okulu III. Kademe',
    'ADANA - YÜREĞİR - Yüreğir Şehit Cihan Çetinkaya Özel Eğitim Anaokulu',
    'ADANA - YÜREĞİR - Ahmed-i Hani Özel Eğitim Meslek Okulu',
    'ADANA - YÜREĞİR - Yüreğir Bilim ve Sanat Merkezi',
    'ADANA - YÜREĞİR - Ceylan Gülibrahimoğlu Kızılay Anaokulu',
    'ADANA - YÜREĞİR - Adalet Anaokulu',
    'ADANA - YÜREĞİR - Çetin Topçuoğlu Anaokulu',
    'ADANA - YÜREĞİR - Gazi Osman Paşa Anaokulu',
    'ADANA - YÜREĞİR - İmadettin Levent Anaokulu',
    'ADANA - YÜREĞİR - İstiklal Anaokulu',
    'ADANA - YÜREĞİR - Mehmet Ali Yılmaz Anaokulu',
    'ADANA - YÜREĞİR - Mustafa Cahit Kıraç Anaokulu',
    'ADANA - YÜREĞİR - Şehit Nurettin Yıldırım Anaokulu',
    'ADANA - YÜREĞİR - Ticaret Borsası Anaokulu',
    'ADANA - YÜREĞİR - Pekmezhöyüğü İlkokulu',
    'ADANA - YÜREĞİR - Dervişler Şehit Cevdet Özdaş Anaokulu',
    'ADANA - YÜREĞİR - Prof. Dr. Salih Öven Çolakoğlu Anaokulu',
    'ADANA - YÜREĞİR - Danışment İlkokulu',
    'ADANA - YÜREĞİR - Esenler İlkokulu',
    'ADANA - YÜREĞİR - Ağzıbüyük İlkokulu',
    'ADANA - YÜREĞİR - Yahşiler İlkokulu',
    'ADANA - YÜREĞİR - Cengiz Topel Anaokulu',
    'ADANA - YÜREĞİR - Semerkant Anaokulu',
    'ADANA - YÜREĞİR - Karşıyaka Anaokulu',
    'ADANA - YÜREĞİR - Yahya Kemal Beyatlı 100.Yıl Anaokulu',
    'ADANA - YÜREĞİR - Mimar Sinan Özel Eğitim Anaokulu',
    'ADANA - YÜREĞİR - Rahime Hatun Anaokulu',
  ];
}
