class AdiyamanSchools{
 List<String> _list = ['ADIYAMAN - BESNİ - Aşağısöğütlü İlkokulu',
'ADIYAMAN - BESNİ - Merinos Ali Erdemoğlu Fen Lisesi',
'ADIYAMAN - BESNİ - Besni İbn - i Sina Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - BESNİ - Besni Mustafa Erdemoğlu Anadolu Lisesi',
'ADIYAMAN - BESNİ - Şehit Mehmet Yağmur Anadolu İmam Hatip Lisesi',
'ADIYAMAN - BESNİ - Besni Osman İsot Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - BESNİ - Besni Şehit Eren Kupal Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - BESNİ - Çakırhöyük İlkokulu',
'ADIYAMAN - BESNİ - Dikilitaş Halil Ağar İlkokulu',
'ADIYAMAN - BESNİ - Besni Halk Eğitimi Merkezi',
'ADIYAMAN - BESNİ - Besni Anadolu İmam Hatip Lisesi',
'ADIYAMAN - BESNİ - İstiklal Anaokulu',
'ADIYAMAN - BESNİ - İznik İlkokulu',
'ADIYAMAN - BESNİ - Şehit Er Serdar Küpeli Ortaokulu',
'ADIYAMAN - BESNİ - Köseceli İlkokulu',
'ADIYAMAN - BESNİ - Şehit Recep İnce Ortaokulu',
'ADIYAMAN - BESNİ - M.Sadık PACCI Anaokulu',
'ADIYAMAN - BESNİ - Namık Kemal İlkokulu',
'ADIYAMAN - BESNİ - Şehit Hakan Bali İlkokulu',
'ADIYAMAN - BESNİ - Şehit Hakan Bali Ortaokulu',
'ADIYAMAN - BESNİ - Besni Rehberlik ve Araştırma Merkezi',
'ADIYAMAN - BESNİ - Sarıkaya İlkokulu',
'ADIYAMAN - BESNİ - Sarıkaya Ortaokulu',
'ADIYAMAN - BESNİ - Sarıyaprak Çok Programlı Anadolu Lisesi',
'ADIYAMAN - BESNİ - Sayören İlkokulu',
'ADIYAMAN - BESNİ - Şambayat Anaokulu',
'ADIYAMAN - BESNİ - Şambayat Çok Programlı Anadolu Lisesi',
'ADIYAMAN - BESNİ - Vakkas Kumral İlkokulu',
'ADIYAMAN - BESNİ - Tuğsuz Ali Ağa Ortaokulu',
'ADIYAMAN - BESNİ - Üçgöz İlkokulu',
'ADIYAMAN - BESNİ - Üçgöz Ortaokulu',
'ADIYAMAN - BESNİ - Yayıklı İlkokulu',
'ADIYAMAN - BESNİ - Yoldüzü İlkokulu',
'ADIYAMAN - BESNİ - Suvarlı Serap Gül Ortaokulu',
'ADIYAMAN - BESNİ - Şehit Er Serdar Küpeli İlkokulu',
'ADIYAMAN - BESNİ - Ahmet-Emine Çil Özel Eğitim Ortaokulu',
'ADIYAMAN - BESNİ - Çaykaya İlkokulu',
'ADIYAMAN - BESNİ - Ahmet-Emine Çil Özel Eğitim İlkokulu',
'ADIYAMAN - BESNİ - Yazıkarakuyu Ortaokulu',
'ADIYAMAN - BESNİ - Ahmet-Emine Çil Özel Eğitim Mesleki Eğitim Merkezi (Okulu)',
'ADIYAMAN - BESNİ - Karagüveç Ortaokulu',
'ADIYAMAN - BESNİ - Çetinkaya-Biran Şendil İlkokulu',
'ADIYAMAN - BESNİ - Çetinkaya-Biran Şendil Ortaokulu',
'ADIYAMAN - BESNİ - Sarıyaprak İlkokulu',
'ADIYAMAN - BESNİ - Besni Köseceli Çok Programlı Lisesi',
'ADIYAMAN - BESNİ - Aşağıçöplü İlkokulu',
'ADIYAMAN - BESNİ - Toklu Köyü İlkokulu',
'ADIYAMAN - BESNİ - 15 Temmuz Şehitleri Ortaokulu',
'ADIYAMAN - BESNİ - Şehit Abidin Tanrıkolu Anadolu Lisesi',
'ADIYAMAN - BESNİ - Besni Çakırhöyük Çok Programlı Anadolu Lisesi',
'ADIYAMAN - BESNİ - Geçitli İlkokulu',
'ADIYAMAN - BESNİ - Gülüsüm-İbrahim Erdemoğlu İlkokulu',
'ADIYAMAN - BESNİ - Çomak İlkokulu',
'ADIYAMAN - BESNİ - Şambayat Merkez Ortaokulu',
'ADIYAMAN - BESNİ - Dumlupınar Ortaokulu',
'ADIYAMAN - BESNİ - Şehit Bekir Oruçtutan İlkokulu',
'ADIYAMAN - BESNİ - Besni Servi Erdemoğlu Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - BESNİ - Besni İlkokulu',
'ADIYAMAN - BESNİ - Şehit Mehmet Demir İlkokulu',
'ADIYAMAN - BESNİ - Akdurak İlkokulu',
'ADIYAMAN - BESNİ - Boybeypınarı İlkokulu',
'ADIYAMAN - BESNİ - Tekağaç İlkokulu',
'ADIYAMAN - BESNİ - Şehit İmam Tan Ortaokulu',
'ADIYAMAN - BESNİ - Şehit İmam Tan İlkokulu',
'ADIYAMAN - BESNİ - İzollu İlkokulu',
'ADIYAMAN - BESNİ - İzollu Ortaokulu',
'ADIYAMAN - BESNİ - Şehit Abdurrahman Eraslan Ortaokulu',
'ADIYAMAN - BESNİ - Şehit Abdurrahman Eraslan İlkokulu',
'ADIYAMAN - BESNİ - Yukarısöğütlü İlkokulu',
'ADIYAMAN - BESNİ - Uzunkuyu Ortaokulu',
'ADIYAMAN - BESNİ - Uzunkuyu İlkokulu',
'ADIYAMAN - BESNİ - Safyün Hatice Gölbaşı Ortaokulu',
'ADIYAMAN - BESNİ - Atatürk Ortaokulu',
'ADIYAMAN - BESNİ - Safyün Hatice Gölbaşı İlkokulu',
'ADIYAMAN - BESNİ - Alişar İlkokulu',
'ADIYAMAN - BESNİ - Tetirli İlkokulu',
'ADIYAMAN - BESNİ - Kutluca Ortaokulu',
'ADIYAMAN - BESNİ - Hacıhalil İlkokulu',
'ADIYAMAN - BESNİ - Kutluca İlkokulu',
'ADIYAMAN - BESNİ - Suvarlı Çok Programlı Anadolu Lisesi',
'ADIYAMAN - BESNİ - Besni Eğitim Vakfı İlkokulu',
'ADIYAMAN - BESNİ - Camuşcu İlkokulu',
'ADIYAMAN - BESNİ - A.C.Yamazaki İlkokulu',
'ADIYAMAN - BESNİ - Mehmet Akif Ersoy Ortaokulu',
'ADIYAMAN - BESNİ - Yoldüzü Ortaokulu',
'ADIYAMAN - BESNİ - Necip Fazıl Kısakürek Ortaokulu',
'ADIYAMAN - BESNİ - Dörtyol Köyü İlkokulu',
'ADIYAMAN - BESNİ - Şehit Hasan Gülten İlkokulu',
'ADIYAMAN - BESNİ - Karnacık İlkokulu',
'ADIYAMAN - BESNİ - Kurugöl İlkokulu',
'ADIYAMAN - BESNİ - Topkapı Köyü İlkokulu',
'ADIYAMAN - BESNİ - Kesmetepe Ortaokulu',
'ADIYAMAN - BESNİ - Şambayat Atatürk İlkokulu',
'ADIYAMAN - BESNİ - Balka İlkokulu',
'ADIYAMAN - BESNİ - Oyalı İlkokulu',
'ADIYAMAN - BESNİ - Bereketli İlkokulu',
'ADIYAMAN - BESNİ - Sarıyaprak Ortaokulu',
'ADIYAMAN - BESNİ - Berete İlkokulu',
'ADIYAMAN - BESNİ - Aktepe Köyü İlkokulu',
'ADIYAMAN - BESNİ - Beşyol İlkokulu',
'ADIYAMAN - BESNİ - Abımıstık İlkokulu',
'ADIYAMAN - BESNİ - Ümmü Tuğsuz Anaokulu',
'ADIYAMAN - BESNİ - Çorak İlkokulu',
'ADIYAMAN - BESNİ - Karagüveç İlkokulu',
'ADIYAMAN - BESNİ - Kargalı İlkokulu',
'ADIYAMAN - BESNİ - Dikilitaş Halil Ağar Ortaokulu',
'ADIYAMAN - BESNİ - Eğerli İlkokulu',
'ADIYAMAN - BESNİ - Osman Ertürk İlkokulu',
'ADIYAMAN - BESNİ - Sayören Ortaokulu',
'ADIYAMAN - BESNİ - Yazıkarakuyu İlkokulu',
'ADIYAMAN - BESNİ - Çakırhöyük Ortaokulu',
'ADIYAMAN - BESNİ - Ören İlkokulu',
'ADIYAMAN - BESNİ - Toklu Köyü Ortaokulu',
'ADIYAMAN - BESNİ - Çamlıca İlkokulu',
'ADIYAMAN - BESNİ - Zormağara İlkokulu',
'ADIYAMAN - BESNİ - Akyazı İlkokulu',
'ADIYAMAN - BESNİ - Kızılkaya İlkokulu',
'ADIYAMAN - BESNİ - Kesmetepe İlkokulu',
'ADIYAMAN - BESNİ - Levzin İlkokulu',
'ADIYAMAN - BESNİ - Kızılin Yılmaz Yığılı İlkokulu',
'ADIYAMAN - BESNİ - Kızılin Yılmaz Yığılı Ortaokulu',
'ADIYAMAN - BESNİ - Nohudanlı İlkokulu',
'ADIYAMAN - BESNİ - Çomak Ortaokulu',
'ADIYAMAN - BESNİ - MUSTAFA BABA İLKOKULU',
'ADIYAMAN - BESNİ - BESNİ İMAM HATİP ORTAOKULU',
'ADIYAMAN - BESNİ - BESNİ KIZ ANADOLU İMAM HATİP LİSESİ',
'ADIYAMAN - BESNİ - Kızılin Çok Programlı Anadolu Lisesi',
'ADIYAMAN - BESNİ - Şehit Enes Sarıaslan İlkokulu',
'ADIYAMAN - BESNİ - Aysel Erdemoğlu Anadolu Lisesi',
'ADIYAMAN - BESNİ - FATİH SULTAN MEHMET İLKOKULU',
'ADIYAMAN - BESNİ - Yeniköy İlkokulu',
'ADIYAMAN - BESNİ - Fatih Sultan Mehmet Ortaokulu',
'ADIYAMAN - BESNİ - Çilboğaz İlkokulu',
'ADIYAMAN - BESNİ - Besni Abidin Baba Mesleki Eğitim Merkezi',
'ADIYAMAN - BESNİ - Besni Bilim ve Sanat Merkezi',
'ADIYAMAN - BESNİ - Zübeyde Hanım Anaokulu',
'ADIYAMAN - BESNİ - Besni Özel Eğitim Uygulama Okulu I. Kademe',
'ADIYAMAN - BESNİ - Şehit Bekir Oruçtutan Anaokulu',
'ADIYAMAN - BESNİ - A.C.Yamazaki Anaokulu',
'ADIYAMAN - BESNİ - Çilek Anaokulu',
'ADIYAMAN - BESNİ - Besni Anaokulu',
'ADIYAMAN - BESNİ - Fatih Sultan Mehmet Anaokulu',
'ADIYAMAN - BESNİ - Besni Özel Eğitim Anaokulu',
'ADIYAMAN - BESNİ - Besni Özel Eğitim Uygulama Okulu II. Kademe',
'ADIYAMAN - ÇELİKHAN - Aksu İlkokulu',
'ADIYAMAN - ÇELİKHAN - Atatürk İlkokulu',
'ADIYAMAN - ÇELİKHAN - Barbaros İlkokulu',
'ADIYAMAN - ÇELİKHAN - Çelikhan Çok Programlı Anadolu Lisesi',
'ADIYAMAN - ÇELİKHAN - Çelikhan Pınarbaşı Çok Programlı Anadolu Lisesi',
'ADIYAMAN - ÇELİKHAN - Çelikhan Halk Eğitimi Merkezi',
'ADIYAMAN - ÇELİKHAN - Korucak İlkokulu',
'ADIYAMAN - ÇELİKHAN - Şehit Er Erdal Şireci İlkokulu',
'ADIYAMAN - ÇELİKHAN - Şehit Şeyho Şişman Anadolu Lisesi',
'ADIYAMAN - ÇELİKHAN - Pınarbaşı Ortaokulu',
'ADIYAMAN - ÇELİKHAN - Pınarbaşı İlkokulu',
'ADIYAMAN - ÇELİKHAN - Yunus Emre İmam Hatip Ortaokulu',
'ADIYAMAN - ÇELİKHAN - Cumhuriyet Ortaokulu',
'ADIYAMAN - ÇELİKHAN - Cumhuriyet İlkokulu',
'ADIYAMAN - ÇELİKHAN - Mutlu İlkokulu',
'ADIYAMAN - ÇELİKHAN - Yeşiltepe Ortaokulu',
'ADIYAMAN - ÇELİKHAN - Yeşiltepe İlkokulu',
'ADIYAMAN - ÇELİKHAN - Taşdamlar İlkokulu',
'ADIYAMAN - ÇELİKHAN - Şehit Mehmet Yerlikaya Anadolu İmam Hatip Lisesi',
'ADIYAMAN - ÇELİKHAN - Askerhan İlkokulu',
'ADIYAMAN - ÇELİKHAN - Askerhan İmam Hatip Ortaokulu',
'ADIYAMAN - ÇELİKHAN - Balıkburnu İlkokulu',
'ADIYAMAN - ÇELİKHAN - ÇELİKHAN ANAOKULU',
'ADIYAMAN - ÇELİKHAN - FATİH İLKOKULU',
'ADIYAMAN - ÇELİKHAN - ÇELİKHAN ORTAOKULU',
'ADIYAMAN - ÇELİKHAN - Şehit Mesut Çelik Ortaokulu',
'ADIYAMAN - ÇELİKHAN - Şehit Mesut Çelik İlkokulu',
'ADIYAMAN - ÇELİKHAN - Çelikhan Öğretmenevi ve Akşam Sanat Okulu',
'ADIYAMAN - ÇELİKHAN - İnönü İlkokulu',
'ADIYAMAN - ÇELİKHAN - Fatih Ortaokulu',
'ADIYAMAN - ÇELİKHAN - Vatan Anaokulu',
'ADIYAMAN - ÇELİKHAN - Çelikhan Fen Lisesi',
'ADIYAMAN - ÇELİKHAN - Çelikhan İlkokulu',
'ADIYAMAN - GERGER - Ağaçlı İlkokulu',
'ADIYAMAN - GERGER - Aşağıdağlıca İlkokulu',
'ADIYAMAN - GERGER - Bayik İlkokulu',
'ADIYAMAN - GERGER - Cumhuriyet İlkokulu',
'ADIYAMAN - GERGER - Gerger Anaokulu',
'ADIYAMAN - GERGER - Atatürk Ortaokulu',
'ADIYAMAN - GERGER - Gerger Çok Programlı Anadolu Lisesi',
'ADIYAMAN - GERGER - Gözpınar İlkokulu',
'ADIYAMAN - GERGER - Gölyurt Ortaokulu',
'ADIYAMAN - GERGER - Gömük İlkokulu',
'ADIYAMAN - GERGER - Gümüşkaşık İlkokulu',
'ADIYAMAN - GERGER - Gürgenli Ortaokulu',
'ADIYAMAN - GERGER - Gürgenli İlkokulu',
'ADIYAMAN - GERGER - Güzelsu İlkokulu',
'ADIYAMAN - GERGER - Güzelsu Ortaokulu',
'ADIYAMAN - GERGER - Gerger Halk Eğitimi Merkezi',
'ADIYAMAN - GERGER - Helül İlkokulu',
'ADIYAMAN - GERGER - Kırmızı Tarla İlkokulu',
'ADIYAMAN - GERGER - Köklüce İlkokulu',
'ADIYAMAN - GERGER - Kütüklü İlkokulu',
'ADIYAMAN - GERGER - Gerger Öğretmenevi ve Akşam Sanat Okulu',
'ADIYAMAN - GERGER - Pamuluk İlkokulu',
'ADIYAMAN - GERGER - Piyanko İlkokulu',
'ADIYAMAN - GERGER - Şamani İlkokulu',
'ADIYAMAN - GERGER - Sengeto İlkokulu',
'ADIYAMAN - GERGER - Tırsık İlkokulu',
'ADIYAMAN - GERGER - Yağmurlu İlkokulu',
'ADIYAMAN - GERGER - Yukarıdağlıca İlkokulu',
'ADIYAMAN - GERGER - Beybostan İlkokulu',
'ADIYAMAN - GERGER - Gerger Anadolu İmam Hatip Lisesi',
'ADIYAMAN - GERGER - Yenibardak İlkokulu',
'ADIYAMAN - GERGER - Ortaca İlkokulu',
'ADIYAMAN - GERGER - Döşnik İlkokulu',
'ADIYAMAN - GERGER - Konacık İlkokulu',
'ADIYAMAN - GERGER - Çobanpınarı İlkokulu',
'ADIYAMAN - GERGER - Dallarca İlkokulu',
'ADIYAMAN - GERGER - Seyitmahmut İlkokulu',
'ADIYAMAN - GERGER - Oymaklı İlkokulu',
'ADIYAMAN - GERGER - Beşgöze İlkokulu',
'ADIYAMAN - GERGER - Çamik İlkokulu',
'ADIYAMAN - GERGER - Gölyurt İlkokulu',
'ADIYAMAN - GERGER - Kağındak İlkokulu',
'ADIYAMAN - GERGER - Dağdeviren İlkokulu',
'ADIYAMAN - GERGER - Sutepe İlkokulu',
'ADIYAMAN - GERGER - Güngörmüş İlkokulu',
'ADIYAMAN - GERGER - Ağaçlı Ortaokulu',
'ADIYAMAN - GERGER - Özkuran İlkokulu',
'ADIYAMAN - GERGER - OYMAKLI ORTAOKULU',
'ADIYAMAN - GERGER - Gerger Ortaokulu',
'ADIYAMAN - GERGER - GÖLYURT ÇOK PROGRAMLI ANADOLU LİSESİ',
'ADIYAMAN - GERGER - GERGER İMAM HATİP ORTAOKULU',
'ADIYAMAN - GERGER - FATİH İLKOKULU',
'ADIYAMAN - GERGER - Helül Ortaokulu',
'ADIYAMAN - GERGER - Çobanpınar imam Hatip Ortaokulu',
'ADIYAMAN - GERGER - Kıringöl İlkokulu',
'ADIYAMAN - GERGER - Gölyurt İmam Hatip Ortaokulu',
'ADIYAMAN - GERGER - Güzelsu İmam Hatip Ortaokulu',
'ADIYAMAN - GERGER - Gerger Oymaklı İmam Hatip Ortaokulu',
'ADIYAMAN - GERGER - Çifthisar İlkokulu',
'ADIYAMAN - GÖLBAŞI - 1 Nisan Anaokulu',
'ADIYAMAN - GÖLBAŞI - Akçabel İlkokulu',
'ADIYAMAN - GÖLBAŞI - Aşağı Nasırlı İlkokulu',
'ADIYAMAN - GÖLBAŞI - Atatürk İlkokulu',
'ADIYAMAN - GÖLBAŞI - Atatürk Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Belören İlkokulu',
'ADIYAMAN - GÖLBAŞI - Belören Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Gölbaşı Anadolu Lisesi',
'ADIYAMAN - GÖLBAŞI - Gölbaşı Anaokulu',
'ADIYAMAN - GÖLBAŞI - Gölbaşı Harmanlı İlkokulu',
'ADIYAMAN - GÖLBAŞI - Gölbaşı Harmanlı Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Gölbaşı Yunus Emre Anadolu Lisesi',
'ADIYAMAN - GÖLBAŞI - Gölkent İlkokulu',
'ADIYAMAN - GÖLBAŞI - Adıyaman Gölbaşi Halk Eğitimi Merkezi',
'ADIYAMAN - GÖLBAŞI - Mehmet Tevfik Göksu Anadolu İmam Hatip Lisesi',
'ADIYAMAN - GÖLBAŞI - Şehit Ahmet Demir Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Yavuz İlkokulu',
'ADIYAMAN - GÖLBAŞI - Şehit Ümit Özet Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Mehmet Akif Ersoy İlkokulu',
'ADIYAMAN - GÖLBAŞI - Şehit Musa Vuruşkan Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Mimar Sinan Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Şehit Özer Salik İlkokulu',
'ADIYAMAN - GÖLBAŞI - Gazi İlkokulu',
'ADIYAMAN - GÖLBAŞI - Mühendis Serhan Selçuk Nariçi Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Cumhuriyet İlkokulu',
'ADIYAMAN - GÖLBAŞI - Yukarı Nasırlı Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Yukarı Nasırlı İlkokulu',
'ADIYAMAN - GÖLBAŞI - Mehmet Ayrık Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Mehmet Ayrık İlkokulu',
'ADIYAMAN - GÖLBAŞI - Mikdat Sümer Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Yukarıkarakuyu İlkokulu',
'ADIYAMAN - GÖLBAŞI - Kurugeçit Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Aşağıkarakuyu İlkokulu',
'ADIYAMAN - GÖLBAŞI - Balkar Şehit Fuat Özer Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Balkar İlkokulu',
'ADIYAMAN - GÖLBAŞI - Kurugeçit İlkokulu',
'ADIYAMAN - GÖLBAŞI - Aşağıazaplı İlkokulu',
'ADIYAMAN - GÖLBAŞI - Yeşilova İlkokulu',
'ADIYAMAN - GÖLBAŞI - Gölkent Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Savran Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Savran İlkokulu',
'ADIYAMAN - GÖLBAŞI - Şehit Ahmet Demir İlkokulu',
'ADIYAMAN - GÖLBAŞI - Çatalağaç Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Çatalağaç İlkokulu',
'ADIYAMAN - GÖLBAŞI - Karaburun İlkokulu',
'ADIYAMAN - GÖLBAŞI - Karaburun Ortaokulu',
'ADIYAMAN - GÖLBAŞI - Hamzalar İlkokulu',
'ADIYAMAN - GÖLBAŞI - Gölbaşı Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - GÖLBAŞI - Gölbaşı Belören Çok Programlı Anadolu Lisesi',
'ADIYAMAN - GÖLBAŞI - Gölbaşı İbn - i Sina Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - GÖLBAŞI - NAR ÇİÇEĞİ ANAOKULU',
'ADIYAMAN - GÖLBAŞI - SALKIM ANAOKULU',
'ADIYAMAN - GÖLBAŞI - GEDİKLİ İLKOKULU',
'ADIYAMAN - GÖLBAŞI - GÖLBAŞI İMAM HATİP ORTAOKULU',
'ADIYAMAN - GÖLBAŞI - GÖLBAŞI FEN LİSESİ',
'ADIYAMAN - GÖLBAŞI - BELÖREN İMAM HATİP ORTAOKULU',
'ADIYAMAN - GÖLBAŞI - Meydan İlkokulu',
'ADIYAMAN - GÖLBAŞI - Şehit Özer Salik Anaokulu',
'ADIYAMAN - GÖLBAŞI - Gölkent Anaokulu',
'ADIYAMAN - KAHTA - Kahta Borsa İstanbul Kız Anadolu İmam Hatip Lisesi',
'ADIYAMAN - KAHTA - Kifiri İlkokulu',
'ADIYAMAN - KAHTA - Akıncılar İlkokulu',
'ADIYAMAN - KAHTA - Akıncılar Ortaokulu',
'ADIYAMAN - KAHTA - Akıncılar Çok Programlı Lisesi',
'ADIYAMAN - KAHTA - Kahta Gelincik Anaokulu',
'ADIYAMAN - KAHTA - Alidam İlkokulu',
'ADIYAMAN - KAHTA - Alidam Ortaokulu',
'ADIYAMAN - KAHTA - Menzil İlkokulu',
'ADIYAMAN - KAHTA - Kahta Halk Eğitimi Merkezi',
'ADIYAMAN - KAHTA - Kahta Anadolu Lisesi',
'ADIYAMAN - KAHTA - Kahta Fen Lisesi',
'ADIYAMAN - KAHTA - Kahta Anadolu İmam Hatip Lisesi',
'ADIYAMAN - KAHTA - Borsa İstanbul Anadolu Lisesi',
'ADIYAMAN - KAHTA - Kahta GAP Anadolu Lisesi',
'ADIYAMAN - KAHTA - Kahta Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - KAHTA - Kahta Cendere Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - KAHTA - Karacaveren İlkokulu',
'ADIYAMAN - KAHTA - Mevlana İlkokulu',
'ADIYAMAN - KAHTA - Narince İlkokulu',
'ADIYAMAN - KAHTA - Narince Ortaokulu',
'ADIYAMAN - KAHTA - Kahta Rehberlik ve Araştırma Merkezi',
'ADIYAMAN - KAHTA - Şehit Medet Mat Ortaokulu',
'ADIYAMAN - KAHTA - Zini-Abdullah ASLAN Anaokulu',
'ADIYAMAN - KAHTA - Kubilay Ortaokulu',
'ADIYAMAN - KAHTA - Bölükyayla Ortaokulu',
'ADIYAMAN - KAHTA - Kahta Sıraca 125. Yıl Ortaokulu',
'ADIYAMAN - KAHTA - Haceri İlkokulu',
'ADIYAMAN - KAHTA - Kahta İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Damlacık Ortaokulu',
'ADIYAMAN - KAHTA - Damlacık İlkokulu',
'ADIYAMAN - KAHTA - Esendere Ortaokulu',
'ADIYAMAN - KAHTA - Esendere İlkokulu',
'ADIYAMAN - KAHTA - Körgüden İlkokulu',
'ADIYAMAN - KAHTA - Yelkovan İlkokulu',
'ADIYAMAN - KAHTA - Bölükyayla İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Yavuz Selim İlkokulu',
'ADIYAMAN - KAHTA - Şehit Mehmet Özbek İlkokulu',
'ADIYAMAN - KAHTA - Vali Özbilgin İlkokulu',
'ADIYAMAN - KAHTA - Gazi Ortaokulu',
'ADIYAMAN - KAHTA - Kahta Özel Eğitim Uygulama Merkezi I.Kademe',
'ADIYAMAN - KAHTA - Yelkovan Ortaokulu',
'ADIYAMAN - KAHTA - Şehit Mehmet Ali Bozkurt İlkokulu',
'ADIYAMAN - KAHTA - Girne Ortaokulu',
'ADIYAMAN - KAHTA - Çataltepe İlkokulu',
'ADIYAMAN - KAHTA - Celal Bayar Ortaokulu',
'ADIYAMAN - KAHTA - Kahta Özel Eğitim Uygulama Merkezi II. Kademe',
'ADIYAMAN - KAHTA - Ebu Sadık Anadolu İmam Hatip Lisesi',
'ADIYAMAN - KAHTA - Çataltepe Ortaokulu',
'ADIYAMAN - KAHTA - Kahta Sıraca 125. Yıl İlkokulu',
'ADIYAMAN - KAHTA - Bölükyayla İlkokulu',
'ADIYAMAN - KAHTA - Salkımbağı İlkokulu',
'ADIYAMAN - KAHTA - Şehit Osman Köse Ortaokulu',
'ADIYAMAN - KAHTA - Şehit Murat Toprak Ortaokulu',
'ADIYAMAN - KAHTA - Şeyhbaba İlkokulu',
'ADIYAMAN - KAHTA - Mülk İlkokulu',
'ADIYAMAN - KAHTA - Mülk Ortaokulu',
'ADIYAMAN - KAHTA - Şehit Abdulgani Adalı İlkokulu',
'ADIYAMAN - KAHTA - Öğretmen Evi ve Akşam Sanat Okulu',
'ADIYAMAN - KAHTA - Sabahattin Zaim İlkokulu',
'ADIYAMAN - KAHTA - Çardak İlkokulu',
'ADIYAMAN - KAHTA - Karadut Ortaokulu',
'ADIYAMAN - KAHTA - Bağbaşı Ortaokulu',
'ADIYAMAN - KAHTA - Bağbaşı İlkokulu',
'ADIYAMAN - KAHTA - Elbeyi İlkokulu',
'ADIYAMAN - KAHTA - Belenlı Ortaokulu',
'ADIYAMAN - KAHTA - Yapraklı İlkokulu',
'ADIYAMAN - KAHTA - Belenlı İlkokulu',
'ADIYAMAN - KAHTA - Titan İlkokulu',
'ADIYAMAN - KAHTA - Kahta Yavuz Selim İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Eskitaş Şehit Nihat Deniz Ortaokulu',
'ADIYAMAN - KAHTA - Hacı Bey Ortaokulu',
'ADIYAMAN - KAHTA - Sultanmağara İlkokulu',
'ADIYAMAN - KAHTA - Çıralık Ortaokulu',
'ADIYAMAN - KAHTA - Karadut İlkokulu',
'ADIYAMAN - KAHTA - Bozpınar İlkokulu',
'ADIYAMAN - KAHTA - Eskitaş Şehit Nihat Deniz İlkokulu',
'ADIYAMAN - KAHTA - Çıralık İlkokulu',
'ADIYAMAN - KAHTA - Yahya Kemal İlkokulu',
'ADIYAMAN - KAHTA - Mevlana Ortaokulu',
'ADIYAMAN - KAHTA - Karaman İlkokulu',
'ADIYAMAN - KAHTA - Göçeri Ortaokulu',
'ADIYAMAN - KAHTA - Göçeri İlkokulu',
'ADIYAMAN - KAHTA - Abdullah Öztürk Çok Programlı Anadolu Lisesi',
'ADIYAMAN - KAHTA - Kocahisar İlkokulu',
'ADIYAMAN - KAHTA - Sırakaya İlkokulu',
'ADIYAMAN - KAHTA - Kahta Hürriyet İlkokulu',
'ADIYAMAN - KAHTA - Çobanlı İlkokulu',
'ADIYAMAN - KAHTA - Türkiye Petrolleri Kahta Kız Anadolu İmam Hatip Lisesi',
'ADIYAMAN - KAHTA - Kubilay İlkokulu',
'ADIYAMAN - KAHTA - Fatih Sultan Mehmet İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Çaybaşı Ortaokulu',
'ADIYAMAN - KAHTA - Çaybaşı İlkokulu',
'ADIYAMAN - KAHTA - Erikli Aktoprak Ortaokulu',
'ADIYAMAN - KAHTA - Erikli Aktoprak İlkokulu',
'ADIYAMAN - KAHTA - Bostanlı Köyü Ortaokulu',
'ADIYAMAN - KAHTA - Ballı İlkokulu',
'ADIYAMAN - KAHTA - Köseler Ortaokulu',
'ADIYAMAN - KAHTA - Köseler İlkokulu',
'ADIYAMAN - KAHTA - Turgut Özal Anaokulu',
'ADIYAMAN - KAHTA - Bostanlı Köyü İlkokulu',
'ADIYAMAN - KAHTA - Vilayetler Hizmet Birliği Anaokulu',
'ADIYAMAN - KAHTA - Damlacık İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Körgüden Ortaokulu',
'ADIYAMAN - KAHTA - Geldibuldu İlkokulu',
'ADIYAMAN - KAHTA - Akdoğan Köyü İlkokulu',
'ADIYAMAN - KAHTA - Arılı İlkokulu',
'ADIYAMAN - KAHTA - Aydınpınar İlkokulu',
'ADIYAMAN - KAHTA - Koçtepe İlkokulu',
'ADIYAMAN - KAHTA - Sabiha Gökçen Anaokulu',
'ADIYAMAN - KAHTA - Salkımbağı İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Büyükbağ Ortaokulu',
'ADIYAMAN - KAHTA - Büyükbağ İlkokulu',
'ADIYAMAN - KAHTA - Turgut Özal İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Doluca İlkokulu',
'ADIYAMAN - KAHTA - Hasköy İlkokulu',
'ADIYAMAN - KAHTA - Akkuş İlkokulu',
'ADIYAMAN - KAHTA - Teğmenli İlkokulu',
'ADIYAMAN - KAHTA - Taşlıca İlkokulu',
'ADIYAMAN - KAHTA - ÇALTILI İLKOKULU',
'ADIYAMAN - KAHTA - GÖLGELİ İLKOKULU',
'ADIYAMAN - KAHTA - Dumlu İlkokulu',
'ADIYAMAN - KAHTA - GÜDÜLGE İLKOKULU',
'ADIYAMAN - KAHTA - Hayme Ana Anaokulu',
'ADIYAMAN - KAHTA - Akkavak İlkokulu',
'ADIYAMAN - KAHTA - ÇAMLICA İLKOKULU',
'ADIYAMAN - KAHTA - Girne Çok Programlı Anadolu Lisesi',
'ADIYAMAN - KAHTA - BOĞAZKAYA İLKOKULU',
'ADIYAMAN - KAHTA - BAĞLAR İLKOKULU',
'ADIYAMAN - KAHTA - T.P.A.O. ATATÜRK İLKOKULU',
'ADIYAMAN - KAHTA - Kahta Narince Çok Programlı Anadolu Lisesi',
'ADIYAMAN - KAHTA - ERİKDERE İLKOKULU',
'ADIYAMAN - KAHTA - MEHMET AKİF ERSOY İLKOKULU',
'ADIYAMAN - KAHTA - İKİZCE YENİCE İLKOKULU',
'ADIYAMAN - KAHTA - KARATİLBE İLKOKULU',
'ADIYAMAN - KAHTA - Melgosi İlkokulu',
'ADIYAMAN - KAHTA - KAVAKLI İLKOKULU',
'ADIYAMAN - KAHTA - KOZAĞAÇ İLKOKULU',
'ADIYAMAN - KAHTA - Narince İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - ORTANCA İLKOKULU',
'ADIYAMAN - KAHTA - Yassıkaya İlkokulu',
'ADIYAMAN - KAHTA - TÜTENOCAK İLKOKULU',
'ADIYAMAN - KAHTA - ELMALI İLKOKULU',
'ADIYAMAN - KAHTA - Çukurtaş İlkokulu',
'ADIYAMAN - KAHTA - AKÇAVERAN İLKOKULU',
'ADIYAMAN - KAHTA - Cumhuriyet Köyü İlkokulu',
'ADIYAMAN - KAHTA - Şehit Sevgi Yeşilyurt Anaokulu',
'ADIYAMAN - KAHTA - Yavuz Selim Ortaokulu',
'ADIYAMAN - KAHTA - Atatürk İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Kahta Mesleki Eğitim Merkezi',
'ADIYAMAN - KAHTA - Kahta Özel Eğitim Uygulama Okulu III. Kademe',
'ADIYAMAN - KAHTA - MENZİL İMAM HATİP ORTAOKULU',
'ADIYAMAN - KAHTA - Şehit Muhammet Fatih Safitürk İlkokulu',
'ADIYAMAN - KAHTA - NAZE-BEDİR METİNER ANAOKULU',
'ADIYAMAN - KAHTA - Kahta Şehit Nazif Kaplan İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - ŞEHİT CENNET YİĞİT ANAOKULU',
'ADIYAMAN - KAHTA - ŞEHİT MUSA ÖZALKAN ORTAOKULU',
'ADIYAMAN - KAHTA - Erikli Aktoprak İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - MUSTAFA YARDIMCI ANADOLU LİSESİ',
'ADIYAMAN - KAHTA - Besele İlkokulu',
'ADIYAMAN - KAHTA - Tepebaşı İlkokulu',
'ADIYAMAN - KAHTA - Kerkah İlkokulu',
'ADIYAMAN - KAHTA - Yolaltı İlkokulu',
'ADIYAMAN - KAHTA - Cumhuriyet İlkokulu',
'ADIYAMAN - KAHTA - Kahta Bilim ve Sanat Merkezi',
'ADIYAMAN - KAHTA - Şehit Yunus Uğur Anadolu Lisesi',
'ADIYAMAN - KAHTA - Fatma-Mehmet Altıntaş Anaokulu',
'ADIYAMAN - KAHTA - Kahta Bilim Sanat Merkezi Anaokulu',
'ADIYAMAN - KAHTA - Hacı Bey İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Koçtepe Ortaokulu',
'ADIYAMAN - KAHTA - Göçeri İmam Hatip Ortaokulu',
'ADIYAMAN - KAHTA - Çağdaş Yaşam Engin Meriç İlkokulu',
'ADIYAMAN - KAHTA - Kesertaş İlkokulu',
'ADIYAMAN - KAHTA - Kubilay Anaokulu',
'ADIYAMAN - KAHTA - Şehit Mehmet Ali Bozkurt Anaokulu',
'ADIYAMAN - KAHTA - Celal Bayar Anaokulu',
'ADIYAMAN - KAHTA - T.P.A.O. Atatürk Anaokulu',
'ADIYAMAN - KAHTA - Yavuz Selim Anaokulu',
'ADIYAMAN - KAHTA - Şehit Muhammet Fatih Safitürk Anaokulu',
'ADIYAMAN - KAHTA - Kahta Özel Eğitim Anaokulu',
'ADIYAMAN - KAHTA - Girne Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - KAHTA - Şehit Şükrü Özmen Anaokulu',
'ADIYAMAN - MERKEZ - 23 Nisan İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Akif Güleş İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - Adıyaman Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Esentepe Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Adıyaman Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Adıyaman Fen Lisesi',
'ADIYAMAN - MERKEZ - Borsa İstanbul İlkokulu',
'ADIYAMAN - MERKEZ - Adıyaman Türkiye Petrolleri Ortaokulu',
'ADIYAMAN - MERKEZ - Adıyaman Mesleki Eğitim Merkezi',
'ADIYAMAN - MERKEZ - Adıyaman Yunus Emre Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Adıyaman Ticaret Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Altınşehir İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Fatih Doğan Güzel Sanatlar Lisesi',
'ADIYAMAN - MERKEZ - Adıyaman Anadolu İmam Hatip Lisesi',
'ADIYAMAN - MERKEZ - Atakent Çok Programlı Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Atatürk İlkokulu',
'ADIYAMAN - MERKEZ - Atatürk Kız Anadolu İmam Hatip Lisesi',
'ADIYAMAN - MERKEZ - Bahar Anaokulu',
'ADIYAMAN - MERKEZ - Bilgi Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Abuzer-Hatice Yıldırım İlkokulu',
'ADIYAMAN - MERKEZ - Cengiz Topel Ortaokulu',
'ADIYAMAN - MERKEZ - Çokpınar İlkokulu',
'ADIYAMAN - MERKEZ - Düzce İlkokulu',
'ADIYAMAN - MERKEZ - Ayyıldız İlkokulu',
'ADIYAMAN - MERKEZ - Adıyaman Erdemir Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Fatih Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Fevzi Çakmak Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Gül Anaokulu',
'ADIYAMAN - MERKEZ - Gümüşkaya İlkokulu',
'ADIYAMAN - MERKEZ - Halide Edip Anaokulu',
'ADIYAMAN - MERKEZ - Hürriyet İlkokulu',
'ADIYAMAN - MERKEZ - Hüsnü M.Özyeğin Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Ilıcak İlkokulu',
'ADIYAMAN - MERKEZ - Borsa İstanbul Anadolu Lisesi',
'ADIYAMAN - MERKEZ - İncebağ İlkokulu',
'ADIYAMAN - MERKEZ - İnönü İlkokulu',
'ADIYAMAN - MERKEZ - Karacaoğlan Ortaokulu',
'ADIYAMAN - MERKEZ - Kayatepe İlkokulu',
'ADIYAMAN - MERKEZ - Dumlupınar Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Korucular Anaokulu',
'ADIYAMAN - MERKEZ - Kömür İlkokulu',
'ADIYAMAN - MERKEZ - Kuyucak Bucağı Ortaokulu',
'ADIYAMAN - MERKEZ - Külafhöyük İlkokulu',
'ADIYAMAN - MERKEZ - Latife Hanım Anaokulu',
'ADIYAMAN - MERKEZ - Şehit Turan Çelik İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - Menderes İlkokulu',
'ADIYAMAN - MERKEZ - Adıyaman Mimar Sinan Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Mustafa Yücel Özbilgin İlkokulu',
'ADIYAMAN - MERKEZ - Mevlana Ortaokulu',
'ADIYAMAN - MERKEZ - Paşamezrası İlkokulu',
'ADIYAMAN - MERKEZ - Pınaryayla Ortaokulu',
'ADIYAMAN - MERKEZ - Sarıharman İlkokulu',
'ADIYAMAN - MERKEZ - Sevgi Anaokulu',
'ADIYAMAN - MERKEZ - Sümer Anaokulu',
'ADIYAMAN - MERKEZ - Şehit Cem Özgül İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Ramazan Özen Anaokulu',
'ADIYAMAN - MERKEZ - Tekpınar İlkokulu',
'ADIYAMAN - MERKEZ - Toybelen İlkokulu',
'ADIYAMAN - MERKEZ - Uzunpınar İlkokulu',
'ADIYAMAN - MERKEZ - Yarmakaya Ortaokulu',
'ADIYAMAN - MERKEZ - Yasıkaya İlkokulu',
'ADIYAMAN - MERKEZ - Yazıbaşı Ortaokulu',
'ADIYAMAN - MERKEZ - Yiğit Ali Çavuş Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Yunus Emre Anaokulu',
'ADIYAMAN - MERKEZ - Yunus Emre İlkokulu',
'ADIYAMAN - MERKEZ - Yunus Emre Ortaokulu',
'ADIYAMAN - MERKEZ - Zübeyde Hanım Anaokulu',
'ADIYAMAN - MERKEZ - Fatma Uslu Anaokulu',
'ADIYAMAN - MERKEZ - Polis Amca İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - Birsen Esensoy İlkokulu',
'ADIYAMAN - MERKEZ - Kayatepe Ortaokulu',
'ADIYAMAN - MERKEZ - Kızılcapınar Ortaokulu',
'ADIYAMAN - MERKEZ - Kızılcapınar İlkokulu',
'ADIYAMAN - MERKEZ - Doyran Ortaokulu',
'ADIYAMAN - MERKEZ - Şehit Mehmet Kılınç İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Mahmut Güleş İlkokulu',
'ADIYAMAN - MERKEZ - Adıyaman Lisesi',
'ADIYAMAN - MERKEZ - Gazi İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - Külafhöyük Ortaokulu',
'ADIYAMAN - MERKEZ - Namık Kemal İlkokulu',
'ADIYAMAN - MERKEZ - İncekoz Mezrası İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Yunus Gül Ortaokulu',
'ADIYAMAN - MERKEZ - Rekabet Kurumu Ortaokulu',
'ADIYAMAN - MERKEZ - Yenigüven İlkokulu',
'ADIYAMAN - MERKEZ - Mehmet Akif Ersoy Kız Anadolu İmam Hatip Lisesi',
'ADIYAMAN - MERKEZ - Elmacık Ortaokulu',
'ADIYAMAN - MERKEZ - Şerefli Ortaokulu',
'ADIYAMAN - MERKEZ - Akpınar Ortaokulu',
'ADIYAMAN - MERKEZ - Şerefli İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Necati Sayın Anadolu İmam Hatip Lisesi',
'ADIYAMAN - MERKEZ - Adıyaman Özel Eğitim Uygulama Merkezi I. Kademe',
'ADIYAMAN - MERKEZ - Cumhuriyet İlkokulu',
'ADIYAMAN - MERKEZ - Adıyaman TOKİ Ortaokulu',
'ADIYAMAN - MERKEZ - Fevzi Çakmak Ortaokulu',
'ADIYAMAN - MERKEZ - Mehmetçik İlkokulu',
'ADIYAMAN - MERKEZ - Adıyaman TOKİ İlkokulu',
'ADIYAMAN - MERKEZ - Adıyaman Özel Eğitim Uygulama Merkezi II.Kademe',
'ADIYAMAN - MERKEZ - Hatice Taşar Özel Eğitim Uygulama Okulu III. Kademe',
'ADIYAMAN - MERKEZ - Adıyaman Demokrasi İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Abdurrahman Doğan Ortaokulu',
'ADIYAMAN - MERKEZ - Mimar Sinan Ortaokulu',
'ADIYAMAN - MERKEZ - Mehmet Akif Ersoy İlkokulu',
'ADIYAMAN - MERKEZ - Malazgirt İlkokulu',
'ADIYAMAN - MERKEZ - Adıyaman İlkokulu',
'ADIYAMAN - MERKEZ - TOBB Yavuz Selim Ortaokulu',
'ADIYAMAN - MERKEZ - Yavuz Selim İlkokulu',
'ADIYAMAN - MERKEZ - Orhangazi Ortaokulu',
'ADIYAMAN - MERKEZ - Kaşköy İlkokulu',
'ADIYAMAN - MERKEZ - Kaşköy Ortaokulu',
'ADIYAMAN - MERKEZ - Zeynep Turgut İlkokulu',
'ADIYAMAN - MERKEZ - Sezai Karakoç İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - Menderes Ortaokulu',
'ADIYAMAN - MERKEZ - Boğazözü İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Rıza Fırat İlkokulu',
'ADIYAMAN - MERKEZ - Nene Hatun Anaokulu',
'ADIYAMAN - MERKEZ - Adıyaman Rehberlik ve Araştırma Merkezi',
'ADIYAMAN - MERKEZ - Biraralık Ortaokulu',
'ADIYAMAN - MERKEZ - Şehit Abdurrahman Doğan İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Cem Özgül Ortaokulu',
'ADIYAMAN - MERKEZ - Ertuğrul Gazi Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Aydınoluk İlkokulu',
'ADIYAMAN - MERKEZ - Boztepe İlkokulu',
'ADIYAMAN - MERKEZ - Bahçecik İlkokulu',
'ADIYAMAN - MERKEZ - Palanlı İlkokulu',
'ADIYAMAN - MERKEZ - Atakent İlkokulu',
'ADIYAMAN - MERKEZ - Agikan İlkokulu',
'ADIYAMAN - MERKEZ - Ağveren İlkokulu',
'ADIYAMAN - MERKEZ - Bozhüyük Ortaokulu',
'ADIYAMAN - MERKEZ - Burç İlkokulu',
'ADIYAMAN - MERKEZ - Börgenek Ortaokulu',
'ADIYAMAN - MERKEZ - Atakent Ortaokulu',
'ADIYAMAN - MERKEZ - Çatalağaç İlkokulu',
'ADIYAMAN - MERKEZ - Göm İlkokulu',
'ADIYAMAN - MERKEZ - Dandırmaz Polis Amca İlkokulu',
'ADIYAMAN - MERKEZ - Çamyurdu İlkokulu',
'ADIYAMAN - MERKEZ - Hasankendi Ortaokulu',
'ADIYAMAN - MERKEZ - Hasankendi İlkokulu',
'ADIYAMAN - MERKEZ - Hasancık İlkokulu',
'ADIYAMAN - MERKEZ - Kuyulu Ortaokulu',
'ADIYAMAN - MERKEZ - Gümüşkaya Ortaokulu',
'ADIYAMAN - MERKEZ - Damlıca İlkokulu',
'ADIYAMAN - MERKEZ - Esence İlkokulu',
'ADIYAMAN - MERKEZ - Altınşehir Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Kuştepe İlkokulu',
'ADIYAMAN - MERKEZ - Kuyucak Bucağı İlkokulu',
'ADIYAMAN - MERKEZ - Zey Ortaokulu',
'ADIYAMAN - MERKEZ - Kömür Ortaokulu',
'ADIYAMAN - MERKEZ - Koçali Ortaokulu',
'ADIYAMAN - MERKEZ - Kuyulu İlkokulu',
'ADIYAMAN - MERKEZ - İnceler Ortaokulu',
'ADIYAMAN - MERKEZ - İnceler Şehit Bahri Çetin İlkokulu',
'ADIYAMAN - MERKEZ - Koçali İlkokulu',
'ADIYAMAN - MERKEZ - Kuştepe Ortaokulu',
'ADIYAMAN - MERKEZ - Kınık İlkokulu',
'ADIYAMAN - MERKEZ - Karagöl İlkokulu',
'ADIYAMAN - MERKEZ - Börgenek İlkokulu',
'ADIYAMAN - MERKEZ - Karahöyük İlkokulu',
'ADIYAMAN - MERKEZ - Vartana İlkokulu',
'ADIYAMAN - MERKEZ - Yaylakonak Ortaokulu',
'ADIYAMAN - MERKEZ - Sarıharman Ortaokulu',
'ADIYAMAN - MERKEZ - Yukarıkuşakkaya Ortaokulu',
'ADIYAMAN - MERKEZ - Yukarıkuşakkaya İlkokulu',
'ADIYAMAN - MERKEZ - Yarmakaya İlkokulu',
'ADIYAMAN - MERKEZ - Bozhüyük İlkokulu',
'ADIYAMAN - MERKEZ - Toptepe İlkokulu',
'ADIYAMAN - MERKEZ - Tekpınar Ortaokulu',
'ADIYAMAN - MERKEZ - Emniyet Ortaokulu',
'ADIYAMAN - MERKEZ - Özel İdare İlkokulu',
'ADIYAMAN - MERKEZ - Malazgirt Özel Eğitim Uygulama Okulu I. Kademe',
'ADIYAMAN - MERKEZ - Elmacık İlkokulu',
'ADIYAMAN - MERKEZ - Özelevler İlkokulu',
'ADIYAMAN - MERKEZ - TOKİ Akşemseddin İlkokulu',
'ADIYAMAN - MERKEZ - TOKİ Akşemseddin Ortaokulu',
'ADIYAMAN - MERKEZ - Adıyaman Halk Eğitimi Merkezi',
'ADIYAMAN - MERKEZ - Öğretmenevi ve Akşam Sanat Okulu',
'ADIYAMAN - MERKEZ - Pınaryayla İlkokulu',
'ADIYAMAN - MERKEZ - Mehmet Akif Ersoy Ortaokulu',
'ADIYAMAN - MERKEZ - FATİH İMAM HATİP ORTAOKULU',
'ADIYAMAN - MERKEZ - Adıyaman Spor Lisesi',
'ADIYAMAN - MERKEZ - Malazgirt Özel Eğitim Uygulama Okulu II. Kademe',
'ADIYAMAN - MERKEZ - Hacı Sakine Acar Özel Eğitim Meslek Okulu',
'ADIYAMAN - MERKEZ - OSMANGAZİ ORTAOKULU',
'ADIYAMAN - MERKEZ - Altınşehir Anaokulu',
'ADIYAMAN - MERKEZ - İlk Adım Anaokulu',
'ADIYAMAN - MERKEZ - Adıyaman Fatih Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - MERKEZ - SAFVAN ANADOLU İMAM HATİP LİSESİ',
'ADIYAMAN - MERKEZ - BAĞDERE İLKOKULU',
'ADIYAMAN - MERKEZ - Kömür Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Malazgirt Anaokulu',
'ADIYAMAN - MERKEZ - ŞİRİNLER ÖZEL EĞİTİM ANAOKULU',
'ADIYAMAN - MERKEZ - VİLAYETLER HİZMET BİRLİĞİ ANAOKULU',
'ADIYAMAN - MERKEZ - Adıyaman Bilim ve Sanat Merkezi',
'ADIYAMAN - MERKEZ - Eskisaray Anaokulu',
'ADIYAMAN - MERKEZ - NASRETTİN HOCA ANAOKULU',
'ADIYAMAN - MERKEZ - TOYBELEN ORTAOKULU',
'ADIYAMAN - MERKEZ - Türkiye Odalar ve Borsalar Birliği Kız Anadolu İmam Hatip Lisesi',
'ADIYAMAN - MERKEZ - ŞEHİT FAZIL GÜRS İMAM HATİP ORTAOKULU',
'ADIYAMAN - MERKEZ - Süleyman Şah Ortaokulu',
'ADIYAMAN - MERKEZ - Hasan Taşar İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - 15 TEMMUZ ŞEHİTLER ORTAOKULU',
'ADIYAMAN - MERKEZ - ŞEHİT ENGİN TİLBAÇ ANAOKULU',
'ADIYAMAN - MERKEZ - Serintepe İlkokulu',
'ADIYAMAN - MERKEZ - Şehit Hasan Aydoğdu Anadolu İmam Hatip Lisesi',
'ADIYAMAN - MERKEZ - Yenimahalle İlkokulu',
'ADIYAMAN - MERKEZ - MİLLİ İRADE ORTAOKULU',
'ADIYAMAN - MERKEZ - ALTINŞEHİR İMAM HATİP ORTAOKULU',
'ADIYAMAN - MERKEZ - Adıyaman Perre Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - MERKEZ - YUVAM ANAOKULU',
'ADIYAMAN - MERKEZ - Fuat Sezgin Ortaokulu',
'ADIYAMAN - MERKEZ - Kemerkaya İlkokulu',
'ADIYAMAN - MERKEZ - Güzelyurt İlkokulu',
'ADIYAMAN - MERKEZ - Ağcin İlkokulu',
'ADIYAMAN - MERKEZ - Kartı İlkokulu',
'ADIYAMAN - MERKEZ - Ormaniçi İlkokulu',
'ADIYAMAN - MERKEZ - Ağıllı İlkokulu',
'ADIYAMAN - MERKEZ - Davuthan İlkokulu',
'ADIYAMAN - MERKEZ - Yazıbaşı İlkokulu',
'ADIYAMAN - MERKEZ - Yaylakonak İlkokulu',
'ADIYAMAN - MERKEZ - Uludam İlkokulu',
'ADIYAMAN - MERKEZ - Akpınar İlkokulu',
'ADIYAMAN - MERKEZ - Zey İlkokulu',
'ADIYAMAN - MERKEZ - Kalburcu İlkokulu',
'ADIYAMAN - MERKEZ - Gökçay İlkokulu',
'ADIYAMAN - MERKEZ - Karacaoğlan İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - Kuyulu İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - TOBB Yavuz Selim İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - İnceler İmam Hatip Ortaokulu',
'ADIYAMAN - MERKEZ - Cahit Zarifoğlu Ortaokulu',
'ADIYAMAN - MERKEZ - Cahit Zarifoğlu İlkokulu',
'ADIYAMAN - MERKEZ - Gazi Ortaokulu',
'ADIYAMAN - MERKEZ - Öğretmenim İlkokulu',
'ADIYAMAN - MERKEZ - Pınar Anaokulu',
'ADIYAMAN - MERKEZ - Necip Fazıl Kısakürek Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Şehit Hasan Aydoğdu Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Şehit Taha Uluçay İlkokulu',
'ADIYAMAN - MERKEZ - Şeref Cengiz İlkokulu',
'ADIYAMAN - MERKEZ - Adıyaman Ziraat Teknolojileri Mesleki ve Teknik Anadolu Lisesi',
'ADIYAMAN - MERKEZ - Fevzi Çakmak İlkokulu',
'ADIYAMAN - MERKEZ - Uğurca İlkokulu',
'ADIYAMAN - MERKEZ - Kayaönü İlkokulu',
'ADIYAMAN - MERKEZ - Uzunköy İlkokulu',
'ADIYAMAN - MERKEZ - Koru İlkokulu',
'ADIYAMAN - MERKEZ - Kovuk İlkokulu',
'ADIYAMAN - MERKEZ - Olgunlar İlkokulu',
'ADIYAMAN - MERKEZ - Ova Kuyucak İlkokulu',
'ADIYAMAN - MERKEZ - Millik İlkokulu',
'ADIYAMAN - MERKEZ - Dardağan Mustafa Yücel Özbilgin İlkokulu',
'ADIYAMAN - MERKEZ - Çimenke İlkokulu',
'ADIYAMAN - MERKEZ - Akyazı İlkokulu',
'ADIYAMAN - MERKEZ - Oluklu İlkokulu',
'ADIYAMAN - MERKEZ - Safvan Özel Eğitim Anaokulu',
'ADIYAMAN - MERKEZ - Ayyıldız Anaokulu',
'ADIYAMAN - MERKEZ - Birsen Esensoy Anaokulu',
'ADIYAMAN - MERKEZ - Tomurcuk Anaokulu',
'ADIYAMAN - MERKEZ - Yavuz Selim Anaokulu',
'ADIYAMAN - MERKEZ - Borsa İstanbul Anaokulu',
'ADIYAMAN - MERKEZ - 23 Nisan Anaokulu',
'ADIYAMAN - MERKEZ - Cumhuriyet Anaokulu',
'ADIYAMAN - MERKEZ - Menderes Anaokulu',
'ADIYAMAN - MERKEZ - İnönü Anaokulu',
'ADIYAMAN - MERKEZ - Şehit Cem Özgül Anaokulu',
'ADIYAMAN - MERKEZ - Mehmetçik Anaokulu',
'ADIYAMAN - MERKEZ - Abdulgafur Büyükfırat Anaokulu',
'ADIYAMAN - MERKEZ - Hürriyet Anaokulu',
'ADIYAMAN - MERKEZ - Neşeli Çocuklar Anaokulu',
'ADIYAMAN - MERKEZ - Adıyaman Anaokulu',
'ADIYAMAN - MERKEZ - TOKİ Akşemseddin Anaokulu',
'ADIYAMAN - MERKEZ - Abuzer-Hatice Yıldırım Anaokulu',
'ADIYAMAN - MERKEZ - Mehmet Akif Ersoy Anaokulu',
'ADIYAMAN - MERKEZ - Şehit Şahin Kaya Anaokulu',
'ADIYAMAN - MERKEZ - İstiklal İlkokulu',
'ADIYAMAN - MERKEZ - İSTİKLAL ORTAOKULU',
'ADIYAMAN - MERKEZ - Ağaçkonak İlkokulu',
'ADIYAMAN - MERKEZ - 100. Yıl İlkokulu',
'ADIYAMAN - MERKEZ - Vatan İlkokulu',
'ADIYAMAN - MERKEZ - Vefa İlkokulu',
'ADIYAMAN - MERKEZ - Umut İlkokulu',
'ADIYAMAN - MERKEZ - 100. Yıl Ortaokulu',
'ADIYAMAN - MERKEZ - Vefa Ortaokulu',
'ADIYAMAN - SAMSAT - Samsat Halk Eğitimi Merkezi',
'ADIYAMAN - SAMSAT - Samsat Safvan Bin Muattal Anadolu İmam Hatip Lisesi',
'ADIYAMAN - SAMSAT - Merkez İlkokulu',
'ADIYAMAN - SAMSAT - Uzuntepe İlkokulu',
'ADIYAMAN - SAMSAT - Gölpınar İlkokulu',
'ADIYAMAN - SAMSAT - Şehit Fırat Demir Ortaokulu',
'ADIYAMAN - SAMSAT - Samsat İmam Hatip Ortaokulu',
'ADIYAMAN - SAMSAT - Samsat Anaokulu',
'ADIYAMAN - SAMSAT - Yarımbağ İlkokulu',
'ADIYAMAN - SAMSAT - Yarımbağ Ortaokulu',
'ADIYAMAN - SAMSAT - Uzuntepe Ortaokulu',
'ADIYAMAN - SAMSAT - Örentaş Ortaokulu',
'ADIYAMAN - SAMSAT - Taşkuyu İlkokulu',
'ADIYAMAN - SAMSAT - Taşkuyu Ortaokulu',
'ADIYAMAN - SAMSAT - Doğanca İlkokulu',
'ADIYAMAN - SAMSAT - Samsat Çok Programlı Anadolu Lisesi',
'ADIYAMAN - SAMSAT - ZEYNEL ASLAN İLKOKULU',
'ADIYAMAN - SAMSAT - Örentaş Şehit Yusuf Atal İlkokulu',
'ADIYAMAN - SİNCİK - Çatbahçe Ortaokulu',
'ADIYAMAN - SİNCİK - Çavçuk İlkokulu',
'ADIYAMAN - SİNCİK - Sincik Çok Programlı Anadolu Lisesi',
'ADIYAMAN - SİNCİK - Sincik Halk Eğitimi Merkezi',
'ADIYAMAN - SİNCİK - Hazaz İlkokulu',
'ADIYAMAN - SİNCİK - Sincik İnlice Şehit Mehmet Satılmış Çok Programlı Anadolu Lisesi',
'ADIYAMAN - SİNCİK - 15 Temmuz Ortaokulu',
'ADIYAMAN - SİNCİK - Çamdere Ortaokulu',
'ADIYAMAN - SİNCİK - Sincik İmam Hatip Ortaokulu',
'ADIYAMAN - SİNCİK - Çam İlkokul',
'ADIYAMAN - SİNCİK - Atatürk İlkokulu',
'ADIYAMAN - SİNCİK - Söğütlü Cumhuriyet İlkokulu',
'ADIYAMAN - SİNCİK - Dilektepe İlkokulu',
'ADIYAMAN - SİNCİK - Sincik Anaokulu',
'ADIYAMAN - SİNCİK - İnlice İlkokulu',
'ADIYAMAN - SİNCİK - Dilektepe Ortaokulu',
'ADIYAMAN - SİNCİK - Yarpuzlu Ortaokulu',
'ADIYAMAN - SİNCİK - Hüseyin ÇELİK Öğretmenevi ve Akşam Sanat Okulu',
'ADIYAMAN - SİNCİK - Alancık İlkokulu',
'ADIYAMAN - SİNCİK - Peyizge İlkokulu',
'ADIYAMAN - SİNCİK - Taşlıca İlkokulu',
'ADIYAMAN - SİNCİK - Hasanlı İlkokulu',
'ADIYAMAN - SİNCİK - Yarpuzlu Eskiköy İlkokulu',
'ADIYAMAN - SİNCİK - Şehit Tahir Yetkin İlkokulu',
'ADIYAMAN - SİNCİK - Pınarbaşı İlkokulu',
'ADIYAMAN - SİNCİK - Sakız İlkokulu',
'ADIYAMAN - SİNCİK - Çamdere İlkokulu',
'ADIYAMAN - SİNCİK - Yarpuzlu İlkokulu',
'ADIYAMAN - SİNCİK - Alancık Ortaokulu',
'ADIYAMAN - SİNCİK - SİNCİK ANADOLU İMAM HATİP LİSESİ',
'ADIYAMAN - SİNCİK - DİLEKTEPE İMAM HATİP ORTAOKULU',
'ADIYAMAN - SİNCİK - ALANCIK İMAM HATİP ORTAOKULU',
'ADIYAMAN - SİNCİK - İnlice Ortaokulu',
'ADIYAMAN - SİNCİK - Atatürk Ortaokulu',
'ADIYAMAN - SİNCİK - Sincik İnlice İmam Hatip Ortaokulu',
'ADIYAMAN - SİNCİK - Aksu Hürmer İlkokulu',
'ADIYAMAN - SİNCİK - Çatbahçe İlkokulu',
'ADIYAMAN - SİNCİK - Aksu Şehit Yusuf Çoban İlkokulu',
'ADIYAMAN - SİNCİK - Serince İlkokulu',
'ADIYAMAN - SİNCİK - Atatürk Anaokulu',
'ADIYAMAN - TUT - Tut Halk Eğitimi Merkezi',
'ADIYAMAN - TUT - Meryemuşağı İlkokulu',
'ADIYAMAN - TUT - Tut Çok Programlı Anadolu Lisesi',
'ADIYAMAN - TUT - Tut Nene Hatun Anaokulu',
'ADIYAMAN - TUT - Atatürk Ortaokulu',
'ADIYAMAN - TUT - Ayşe Aydın İlkokulu',
'ADIYAMAN - TUT - Kaşlıca Ortaokulu',
'ADIYAMAN - TUT - Fatih Ortaokulu',
'ADIYAMAN - TUT - Fatih İlkokulu',
'ADIYAMAN - TUT - Şehit Polis Mahmut Kayan İlkokulu',
'ADIYAMAN - TUT - Dağyalankoz İlkokulu',
'ADIYAMAN - TUT - Kaşlıca İlkokulu',
'ADIYAMAN - TUT - Yaylımlı Şehit Onur BOZTEMİR İlkokulu',
'ADIYAMAN - TUT - Yaylımlı Abuzer Yıldırım Ortaokulu',
'ADIYAMAN - TUT - Öğütlü İlkokulu',
'ADIYAMAN - TUT - Öğütlü Ortaokulu',
'ADIYAMAN - TUT - Tepecik İlkokulu',
'ADIYAMAN - TUT - Akçatepe İlkokulu',
'ADIYAMAN - TUT - Boyundere İlkokulu',
'ADIYAMAN - TUT - Abuzer Yıldırım Anadolu İmam Hatip Lisesi',
'ADIYAMAN - TUT - AKÇATEPE ORTAOKULU',
'ADIYAMAN - TUT - Boyundere Hatice Yıldırım Ortaokulu',
'ADIYAMAN - TUT - Tut Kaşlıca İmam Hatip Ortaokulu'];

 List<String> get list=>_list;

}