class AfyonSchools{
  List<String> _list=[
    'AFYONKARAHİSAR - BAŞMAKÇI - Başmakçı Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - BAŞMAKÇI - Başmakçı Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - BAŞMAKÇI - Cumhuriyet İlkokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Öğretmen Habibe Eren Anaokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Fatih İlkokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Şehit Öğretmen Birol İrfan Aşkar İlkokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Çığrı Ortaokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Yaka Ortaokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Atatürk Ortaokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Akkeçili Ortaokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Akkeçili İlkokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Çığrı İlkokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - Aşağı Beltarla İlkokulu',
    'AFYONKARAHİSAR - BAŞMAKÇI - YAKA İLKOKULU',
    'AFYONKARAHİSAR - BAŞMAKÇI - Başmakçı Şehit Hakan Köroğlu Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - BAŞMAKÇI - YASSIÖREN İLKOKULU',
    'AFYONKARAHİSAR - BAŞMAKÇI - Yukarı Beltarla Karacaören İlkokulu',
    'AFYONKARAHİSAR - BAYAT - Akpınar İlkokulu',
    'AFYONKARAHİSAR - BAYAT - Atatürk İlkokulu',
    'AFYONKARAHİSAR - BAYAT - Bayat Şehit Bahadır Özenç Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - BAYAT - Afyonkarahisar Bayat Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - BAYAT - Bayat Terkan Hatun Anaokulu',
    'AFYONKARAHİSAR - BAYAT - Bayat Yatılı Bölge Ortaokulu',
    'AFYONKARAHİSAR - BAYAT - Derbent İlkokulu',
    'AFYONKARAHİSAR - BAYAT - İmrallı Öğretmen Mustafa Mumcu İlkokulu',
    'AFYONKARAHİSAR - BAYAT - Cumhuriyet İlkokulu',
    'AFYONKARAHİSAR - BAYAT - Cumhuriyet Ortaokulu',
    'AFYONKARAHİSAR - BAYAT - Derbent Ortaokulu',
    'AFYONKARAHİSAR - BAYAT - Mimar Sinan İlkokulu',
    'AFYONKARAHİSAR - BAYAT - Atatürk Ortaokulu',
    'AFYONKARAHİSAR - BAYAT - Aşağı Çaybelen İlkokulu',
    'AFYONKARAHİSAR - BAYAT - Yukarı Çaybelen İlkokulu',
    'AFYONKARAHİSAR - BAYAT - İmrallı Ortaokulu',
    'AFYONKARAHİSAR - BAYAT - Hacı Ali- Kadir Özaktan Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Hamidiye İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Şehit Teğmen Muzaffer Gümüş Özel Eğitim Anaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Rehberlik ve Araştırma Merkezi',
    'AFYONKARAHİSAR - BOLVADİN - Ahmet Emet İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Akçeşme İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Alparslan İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Bahçelievler Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Anadolu Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Mesleki Eğitim Merkezi',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Sıddıka Metin Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Selçuklu Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Derekarabağ Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Dişli İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Hacı Ali-Meryem Birdane Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Mustafa-Keziban Bayramer İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Mustafa Hüsnü Gemici Anadolu Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Öğretmen Evi ve Akşam Sanat Okulu',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Yakup Şevki Paşa Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Kocatepe İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Cirit Şehit Ali Duman İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - 24 Eylül Şehit Nuri Başaran Anaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Kemerkaya Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Hasan Gemici Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Dişli Atatürk Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Yörükkaracaören Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Atatürk İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Şehit Abdülkadir Kocatürk Anadolu Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Güney İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Ceylan Emet İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Gazi Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Yörükkaracaören İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Büyükkarabağ İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Naciye Nurettin Taktak İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Ayfer-Ceylan EMET Fen Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Taşağıl 100. Yıl İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Büyükkarabağ Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Fatih Sultan Mehmet İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Karayokuş Şehit Abdil Kılınç İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Karayokuş Şehit Yaşar Özyörük Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Şehit Teğmen Muzaffer Gümüş Özel Eğitim Uygulama Okulu III. Kademe',
    'AFYONKARAHİSAR - BOLVADİN - Özburun İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Özburun Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - İbrahim Karasekreter Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Şehit Carullah Kalkan Ortaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Kemalettin Sami Paşa İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Derekarabağ İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - ALPARSLAN ORTAOKULU',
    'AFYONKARAHİSAR - BOLVADİN - ALKASAN ORTAOKULU',
    'AFYONKARAHİSAR - BOLVADİN - Kurucaova İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - KURUCAOVA ORTAOKULU',
    'AFYONKARAHİSAR - BOLVADİN - ALKASAN İLKOKULU',
    'AFYONKARAHİSAR - BOLVADİN - Şehit Teğmen Muzaffer Gümüş Özel Eğitim Uygulama Okulu I. Kademe',
    'AFYONKARAHİSAR - BOLVADİN - ŞEHİT TEĞMEN MUZAFFER GÜMÜŞ ÖZEL EĞİTİM UYGULAMA MERKEZİ II. KADEME',
    'AFYONKARAHİSAR - BOLVADİN - DİPEVLER İLKOKULU',
    'AFYONKARAHİSAR - BOLVADİN - KEMERKAYA İLKOKULU',
    'AFYONKARAHİSAR - BOLVADİN - Kırkgöz Anaokulu',
    'AFYONKARAHİSAR - BOLVADİN - Raziye Sultan-Yusuf Kayabaşı Sosyal Bilimler Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Şehit Bekir Kaynak İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Yörükzade Ahmet Fevzi Kız Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - BOLVADİN - BOLVADİN 100.YIL HATİCE BAYRAM KILINÇ ORTAOKULU',
    'AFYONKARAHİSAR - BOLVADİN - BOLVADİN ŞEHİT RAMAZAN EMET İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Hatice Habib Soydan İlkokulu',
    'AFYONKARAHİSAR - BOLVADİN - Bolvadin Bilim ve Sanat Merkezi',
    'AFYONKARAHİSAR - ÇAY - Çay Gevher Nesibe Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - ÇAY - Çay Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - ÇAY - Çay Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - ÇAY - Çay Borsa İstanbul Anadolu Lisesi',
    'AFYONKARAHİSAR - ÇAY - Çay Karacaören Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - ÇAY - Çay Nene Hatun Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - ÇAY - Çay Mesleki Eğitim Merkezi',
    'AFYONKARAHİSAR - ÇAY - Çay Şehit Ahmet Şahin Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - ÇAY - Vali Ahmet Özyurt İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Gazi Mustafa Kemal Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Çay Şehit Kamil Tuna Kurtuluş İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Çay Çağlayan Şehit Mustafa Civelek İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Atatürk Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Koçbeyli Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Çay Öğretmen Evi ve Akşam Sanat Okulu',
    'AFYONKARAHİSAR - ÇAY - Çay İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Koçbeyli İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Çay Anadolu Lisesi',
    'AFYONKARAHİSAR - ÇAY - İnli İlkokulu',
    'AFYONKARAHİSAR - ÇAY - İnli Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Seka İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Akkonak Şehit Gökhan Şengül Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Akkonak Cumhuriyet Şehit Uğur Gencelli İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Karamık Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Karacaören Yunus Emre Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Deresinek İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Çay Pazarağaç Ali Necip Altan Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Karamık Karacaören İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Şehit Cengiz Karataş İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Karamık İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Yeşilyurt Ortaokulu',
    'AFYONKARAHİSAR - ÇAY - Yeşilyurt İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Melek Sultan Anaokulu',
    'AFYONKARAHİSAR - ÇAY - Devederesi İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Maltepe İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Çayıryazı İlkokulu',
    'AFYONKARAHİSAR - ÇAY - Çayırpınar Şehit Mehmet Şimşek İlkokulu',
    'AFYONKARAHİSAR - ÇAY - PAZARAĞAÇ İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - ÇAY - PAZARAĞAÇ İLKOKULU',
    'AFYONKARAHİSAR - ÇOBANLAR - Çobanlar Çok Programlı Lise',
    'AFYONKARAHİSAR - ÇOBANLAR - Göynük İlkokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Göynük Ortaokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Kale Şehit Cüneyt Taşyürek İlkokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Çobanlar Ortaokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Çobanlar İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Akkoyunlu İlkokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Kocaöz Ortaokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Çobanlar Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - ÇOBANLAR - Kocaöz İlkokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Fatih İlkokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Çobanlar Büşra Özen Anaokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Zafer İlkokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - Atatürk İlkokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - AHMET ÖZYURT İLKOKULU',
    'AFYONKARAHİSAR - ÇOBANLAR - KALE ORTAOKULU',
    'AFYONKARAHİSAR - ÇOBANLAR - Zafer Ortaokulu',
    'AFYONKARAHİSAR - ÇOBANLAR - ÇOBANLAR ANAOKULU',
    'AFYONKARAHİSAR - ÇOBANLAR - ÇOBANLAR YAVUZ SELİM ORTAOKULU',
    'AFYONKARAHİSAR - ÇOBANLAR - ÇOBANLAR 15 TEMMUZ ŞEHİTLERİ İLKOKULU',
    'AFYONKARAHİSAR - DAZKIRI - Arıköy İlkokulu',
    'AFYONKARAHİSAR - DAZKIRI - Dazkırı Ahmet - Zübeyde Turba Anadolu Lisesi',
    'AFYONKARAHİSAR - DAZKIRI - Dazkırı Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - DAZKIRI - Dazkırı Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - DAZKIRI - Dazkırı İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - DAZKIRI - Dazkırı Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - DAZKIRI - Dazkırı Öğretmenevi ve Akşam Sanat Okulu',
    'AFYONKARAHİSAR - DAZKIRI - Karaağaçkuyusu İlkokulu',
    'AFYONKARAHİSAR - DAZKIRI - Kızılören İlkokulu',
    'AFYONKARAHİSAR - DAZKIRI - Yüreğil Koralkim İlkokulu',
    'AFYONKARAHİSAR - DAZKIRI - Karaağaçkuyusu Ortaokulu',
    'AFYONKARAHİSAR - DAZKIRI - Yüreğil Koralkim Ortaokulu',
    'AFYONKARAHİSAR - DAZKIRI - Alkim Ortaokulu',
    'AFYONKARAHİSAR - DAZKIRI - Alkim İlkokulu',
    'AFYONKARAHİSAR - DAZKIRI - Cumhuriyet İlkokulu',
    'AFYONKARAHİSAR - DAZKIRI - Dazkırı Alkim Anaokulu',
    'AFYONKARAHİSAR - DAZKIRI - Kızılören Ortaokulu',
    'AFYONKARAHİSAR - DAZKIRI - DAZKIRI ÇAMLIK ORTAOKULU',
    'AFYONKARAHİSAR - DAZKIRI - Dazkırı Şerife Memiş Uçar İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Menderes Özel Eğitim Anaokulu',
    'AFYONKARAHİSAR - DİNAR - TATARLI İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - DİNAR - Bağcılar İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Çiçektepe İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Haydarlı İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar 125. Yıl Anaokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - DİNAR - Dinar Anadolu Lisesi',
    'AFYONKARAHİSAR - DİNAR - Dinar Yavuz Sultan Selim Anadolu Lisesi',
    'AFYONKARAHİSAR - DİNAR - Dinar Fen Lisesi',
    'AFYONKARAHİSAR - DİNAR - Dinar Mehmet Çavuş Anadolu Lisesi',
    'AFYONKARAHİSAR - DİNAR - Dinar Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - DİNAR - Doğanlı İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Göçerli Şehit Piyade Er Yavuz Öztürk Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Haydarlı Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - DİNAR - Okçular İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Pınarlı İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Gevher Nesibe Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - DİNAR - Uluköy İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Yıprak Şehit Şafak Evran İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Tatarlı İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Tatarlı Cumhuriyet İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Menderes İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Atatürk Yatılı Bölge Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Çiçektepe Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Tatarlı Cumhuriyet Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Haydarlı Borsa İstanbul Yatılı Bölge Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Kadılar İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Yeniyol İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Şehit Piyade Uzman Çavuş Selçuk Gürdal Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Fatih Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Sermaye Piyasası Kurulu Yatılı Bölge Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Şakir Ünver İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Alparslan İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Cengiz Topel İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Uluköy Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Yıprak Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Kınık İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Göçerli Şehit Piyade Er Yavuz Öztürk İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Şehit İzzet Taşbaş İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Öğretmenevi ve Akşam Sanat Okulu',
    'AFYONKARAHİSAR - DİNAR - Haydarlı İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Şehit Süleyman Şahin İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Doğanlı Ortaokulu',
    'AFYONKARAHİSAR - DİNAR - Tatarlı Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - DİNAR - Dinar Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - DİNAR - Karahacılı İlkokulu',
    'AFYONKARAHİSAR - DİNAR - DUMAN İLKOKULU',
    'AFYONKARAHİSAR - DİNAR - Yunus Emre İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Merkez Anaokulu',
    'AFYONKARAHİSAR - DİNAR - HAYDARLI OCAKLI İLKOKULU',
    'AFYONKARAHİSAR - DİNAR - DİNAR HÜRRİYET İLKOKULU',
    'AFYONKARAHİSAR - DİNAR - ŞEHİT ŞÜKRÜ BAYRAKCI KIZ ANADOLU İMAM HATİP LİSESİ',
    'AFYONKARAHİSAR - DİNAR - DİNAR BİLİM VE SANAT MERKEZİ',
    'AFYONKARAHİSAR - DİNAR - DİNAR MESLEKİ EĞİTİM MERKEZİ',
    'AFYONKARAHİSAR - DİNAR - Yeşilhüyük İlkokulu',
    'AFYONKARAHİSAR - DİNAR - Yıprak Yusuf Sultan Güçlü Anaokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Rehberlik ve Araştırma Merkezi',
    'AFYONKARAHİSAR - DİNAR - Dinar Şehit Muhammet Bayram Anaokulu',
    'AFYONKARAHİSAR - DİNAR - Dinar Şehit Şükrü Bayrakcı Hafız İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Yüreğil Döneli İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Yeniköy İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Veysel İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Cumhuriyet İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Davulga İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Emirdağ Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - EMİRDAĞ - Emirdağ Aziziye Anadolu Lisesi',
    'AFYONKARAHİSAR - EMİRDAĞ - Emirdağ Merkez Anaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Fatih İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Emirdağ Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - EMİRDAĞ - Metin-Zülbiye Sarı Anadolu Lisesi',
    'AFYONKARAHİSAR - EMİRDAĞ - Perihan Kemal Çuna İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Aziziye İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Mithat Paşa Ortaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Davulga Ortaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Adayazı İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Adayazı Ortaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Emirdağ Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - EMİRDAĞ - Şükrü Mola İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Tez İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Mehmet Akif Ersoy Ortaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Yukarı Kurudere İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Türkmen İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Emirdağ Gülsüm Hatun Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - EMİRDAĞ - Atatürk Ortaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Çatallı İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - ÖĞRETMEN EVİ VE AKŞAM SANAT OKULU',
    'AFYONKARAHİSAR - EMİRDAĞ - AŞAĞIPİRİBEYLİ İLKOKULU',
    'AFYONKARAHİSAR - EMİRDAĞ - Çiftlik İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Gömü İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - GÖMÜ ORTAOKULU',
    'AFYONKARAHİSAR - EMİRDAĞ - Yüreğil İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - MEHMET AKİF ERSOY İLKOKULU',
    'AFYONKARAHİSAR - EMİRDAĞ - EMİRDAĞ ANADOLU LİSESİ',
    'AFYONKARAHİSAR - EMİRDAĞ - ÇAYKIŞLA İLKOKULU',
    'AFYONKARAHİSAR - EMİRDAĞ - GÜVEÇCİ ORTAOKULU',
    'AFYONKARAHİSAR - EMİRDAĞ - Ali Rıza ve Havva Kara Anaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - EMİRDAĞ ŞEHİT MUHAMMET TUFAN ORTAOKULU',
    'AFYONKARAHİSAR - EMİRDAĞ - EMİRDAĞ MUSTAFA ÇEKİÇ ORTAOKULU',
    'AFYONKARAHİSAR - EMİRDAĞ - Güneysaray İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Fadime Derviş Uyar Anaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Emirdağ Emsal-Mustafa Şahin Anaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Emirdağ Fidan-Ali Altıntaş Anaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Yenikapı İlkokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Emirdağ Rabia-Recep Kuş Anaokulu',
    'AFYONKARAHİSAR - EMİRDAĞ - Türkmen Akören İlkokulu',
    'AFYONKARAHİSAR - EVCİLER - Evciler Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - EVCİLER - Evciler Şehit Uzman Onbaşı Atakan Birgül Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - EVCİLER - Gökçek Şehit Osman Öz Ortaokulu',
    'AFYONKARAHİSAR - EVCİLER - Gökçek Doktor Sadık Ahmet İlkokulu',
    'AFYONKARAHİSAR - EVCİLER - Şehit Hüdayi Çınar Ortaokulu',
    'AFYONKARAHİSAR - EVCİLER - Nedim Turan İlkokulu',
    'AFYONKARAHİSAR - EVCİLER - Baraklı Şehit Ali Serttaş İlkokulu',
    'AFYONKARAHİSAR - EVCİLER - MADENLER İLKOKULU',
    'AFYONKARAHİSAR - EVCİLER - EVCİLER İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - EVCİLER - EVCİLER ANAOKULU',
    'AFYONKARAHİSAR - EVCİLER - Altınova İlkokulu',
    'AFYONKARAHİSAR - HOCALAR - Çalca İlkokulu',
    'AFYONKARAHİSAR - HOCALAR - Hocalar Şehit Kamil Tunç Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - HOCALAR - Hocalar Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - HOCALAR - Hocalar Şehit Hasan Yalın İlkokulu',
    'AFYONKARAHİSAR - HOCALAR - Yeşilhisar Yunus Emre İlkokulu',
    'AFYONKARAHİSAR - HOCALAR - Yeşilhisar Yunus Emre Ortaokulu',
    'AFYONKARAHİSAR - HOCALAR - Hocalar Şehit Ahmet Sarıdaş Yatılı Bölge Ortaokulu',
    'AFYONKARAHİSAR - HOCALAR - Devlethan Şehit Murat Korkmaz İlkokulu',
    'AFYONKARAHİSAR - HOCALAR - Hocalar İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - HOCALAR - DAVILGI İLKOKULU',
    'AFYONKARAHİSAR - HOCALAR - GÜRE İLKOKULU',
    'AFYONKARAHİSAR - HOCALAR - ÇEPNİ ORTAOKULU',
    'AFYONKARAHİSAR - HOCALAR - AVGANCIK İLKOKULU',
    'AFYONKARAHİSAR - HOCALAR - Akçadere 15 Temmuz Şehitleri İlkokulu',
    'AFYONKARAHİSAR - HOCALAR - Çepni İlkokulu',
    'AFYONKARAHİSAR - HOCALAR - KOCAGÖL İLKOKULU',
    'AFYONKARAHİSAR - HOCALAR - ULUKÖY İLKOKULU',
    'AFYONKARAHİSAR - HOCALAR - HOCALAR ÖZLEM ÖZKURT ANAOKULU',
    'AFYONKARAHİSAR - İHSANİYE - Ablak İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - İğdemir İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - İhsaniye İbn - i Sina Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - İHSANİYE - Atatürk İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Beyköy Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - İhsaniye Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - İHSANİYE - İhsaniye Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - İHSANİYE - İhsaniye Anadolu Lisesi',
    'AFYONKARAHİSAR - İHSANİYE - Kayıhan İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Döğer Yunus Emre İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Karacaahmet İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Karacaahmet Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Döğer İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Yukarıtandır İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Yukarıtandır Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Döğer Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - İHSANİYE - İhsaniye Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - İHSANİYE - Atatürk Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Muratlar İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Muratlar Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Ayazini İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Ayazini Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - İhsaniye Akören İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - İhsaniye Akören Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Yaylabağı Şehit Ahmet Öztürk İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Bozhüyük Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Döğer Fatih İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Osmanköy İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Osmanköy Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Yaylabağı Şehit Ahmet Öztürk Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Hacıbeyli İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Hacıbeyli Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Beyköy İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Bozhüyük İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Gazlıgöl İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Gazlıgöl Belce İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Döğer Fatih Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Kıyır İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Eynehan Öksüzler İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - İhsaniye İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Gazlıgöl Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Kayıhan Kunduzlu İlkokulu',
    'AFYONKARAHİSAR - İHSANİYE - Kayıhan Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - GAZLIGÖL İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - İHSANİYE - İhsaniye Anaokulu',
    'AFYONKARAHİSAR - İHSANİYE - İHSANİYE MEHMET AKİF İNAN KIZ ANADOLU İMAM HATİP LİSESİ',
    'AFYONKARAHİSAR - İHSANİYE - Döğer Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - İHSANİYE - Bozhüyük İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - İHSANİYE - Bayramaliler İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Fadime ve Halil Öksüz Mesleki Eğitim Merkezi',
    'AFYONKARAHİSAR - İSCEHİSAR - Faruk Öksüz Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - İSCEHİSAR - Fatih İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Hacı Döne Demirel Anaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - İscehisar İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - İscehisar Mehmet Çakmak Anadolu Lisesi',
    'AFYONKARAHİSAR - İSCEHİSAR - İscehisar Baddal Aygün Anadolu Lisesi',
    'AFYONKARAHİSAR - İSCEHİSAR - Karakaya İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Karakaya Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Konarı İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - İscehisar İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - İscehisar Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - İSCEHİSAR - Karaağaç Merkez İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Konarı Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Fatih Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Şehit Ahmet Kaplan İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Şehit Ahmet Kaplan Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Cevizli İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Cevizli Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Mercan Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Olukpınar İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Olukpınar Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Doğanlar İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - İscehisar Şehit İsa Doğan Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Alanyurt İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Alanyurt Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Seydiler Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Seydiler İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Selçuklu İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Karakaya Kavruklar İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Çatağıl Latif Aydın İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - ATATÜRK İLKOKULU',
    'AFYONKARAHİSAR - İSCEHİSAR - OLUKPINAR ÖLDÜMLER İLKOKULU',
    'AFYONKARAHİSAR - İSCEHİSAR - ÇALIŞLAR İLKOKULU',
    'AFYONKARAHİSAR - İSCEHİSAR - Çalışlar Şehit Halil Kemal Efendi Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - İSCEHİSAR ŞEHİT VURAL ŞAHİN İLKOKULU',
    'AFYONKARAHİSAR - İSCEHİSAR - İSCEHİSAR KIZ ANADOLU İMAM HATİP LİSESİ',
    'AFYONKARAHİSAR - İSCEHİSAR - İscehisar Karamehmet İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - İSCEHİSAR HACI SÜLEYMAN SELEK MESLEKİ VE TEKNİK ANADOLU LİSESİ',
    'AFYONKARAHİSAR - İSCEHİSAR - KARAAĞAÇ İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - İSCEHİSAR - Karamehmet Aliye Ana İlkokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Karamehmet Aliye Ana Ortaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - İscehisar Anaokulu',
    'AFYONKARAHİSAR - İSCEHİSAR - Çatağıl Latif Aydın Ortaokulu',
    'AFYONKARAHİSAR - KIZILÖREN - İsmet Attila İlkokulu',
    'AFYONKARAHİSAR - KIZILÖREN - Kızılören Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - KIZILÖREN - İsmet Attila Ortaokulu',
    'AFYONKARAHİSAR - KIZILÖREN - KIZILÖREN İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - KIZILÖREN - Kızılören Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Belediyesi Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Beyyazı Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Olgunlaşma Enstitüsü',
    'AFYONKARAHİSAR - MERKEZ - İnaz İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Atatürk Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Hisarbank Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Kocatepe Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Erenler Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Sülün Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Mareşal Fevzi Çakmak Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Hoca Ahmet Yesevi Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Şehit Murat Saraç İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - 27 Ağustos İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Ahi Evran Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Afyon Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Anafartalar Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Şehit Yunus Çiçek Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Ali Çağlar Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - İbrahim Evren Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Atatürk Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Atatürk Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Beyyazı İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Cumhuriyet Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Çayırbağ İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Çıkrık Öğretmen Hamza Kesman Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Emir Murat Özdilek Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Ertuğrulgazi İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Ertuğrulgazi Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Fatih Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Fethibey İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Fethibey Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Gebeceler İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Gedik Ahmet Paşa İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - MERKEZ - Hoca Ahmet Yesevi Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Huriye Aşkar Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Kocatepe Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Köprülü Sabiha Toros İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Mehmet Akif Ersoy Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Merkez TOKİ İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Mesleki Eğitim Merkezi',
    'AFYONKARAHİSAR - MERKEZ - Nurten Telek İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Oruçoğlu İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Abdürrahim Mısri Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Şehit Kerim Üye İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Osman Attila Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Osmangazi Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Öğretmen Saniye Sayıoğlu İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Rehberlik ve Araştırma Merkezi',
    'AFYONKARAHİSAR - MERKEZ - Sahipata İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Salim Pancar İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Selçuklu İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Susuz Atatürk İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Susuz Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Süleyman Demirel Fen Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Sülümenli İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Şemsettin Karahisari Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Ticaret Borsası Şehit Ömer Halisdemir İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - TOKİ Fatma Aliye Hanım Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - TOKİ Sosyal Bilimler Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Uydukent Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Akçin İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Ataköy Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Cumhuriyet İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Nuribey İsmet Atilla Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Hacı Ahmet Özsoy Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Fatih İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Kadaifçioğlu İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Büyükkalecik Kocatepe İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Salar Atatürk İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Beyazıt Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Beyazıt İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Methiye Dumlu Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Sadıkbey Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Işıklar Dumlupınar İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Ayşegül Arsoy İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Büyükkalecik Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Salar Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Kızıldağ İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Erkmen İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Çavdarlı Şehit Er Hüseyin Öğüt İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Değirmenayvalı İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Ali Çetinkaya Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Çavdarlı Şehit Musa Demir Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Hoca Ahmet Yesevi İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Yunus Emre Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Kocatepe Özel Eğitim Uygulama Okulu I. Kademe',
    'AFYONKARAHİSAR - MERKEZ - Mareşal Fevzi Çakmak Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Mareşal Fevzi Çakmak İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Erenler Şehit Ömer Sayar Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Erenler İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Salar Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Ataköy İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Bayraktepe Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Kocatepe Özel Eğitim Uygulama Okulu II. Kademe',
    'AFYONKARAHİSAR - MERKEZ - Kocatepe Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Kadınana İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Atatürk İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Beyyazı Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Bostanlı İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Mehmet Yağcıoğlu İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Hüseyin Türkmen İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Değirmenayvalı Ahmet Bayram Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Erkmen Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Kazım Özer İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Şehit Şükrü Karadirek Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Hacı Hayriye Özsoy Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Küçük Çobanlı İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Susuz Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Salar İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Nasreddin Hoca Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Çıkrık İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Sülümenli Yavuz Selim İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Yavuz Selim İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - 125. Yıl Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Hacı Hayriye Özsoy İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Namık Kemal İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Şehit Sami Çifci İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Sadıkbey İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Işıklar Kocatepe Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Öğretmenevi ve Akşam Sanat Okulu',
    'AFYONKARAHİSAR - MERKEZ - Gebeceler Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Yüksel Varlı İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Yüksel Varlı Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Sülün Balı-Mubahat Açıkgözoğlu Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Sülün Balı-Mubahat Açıkgözoğlu İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Sülümenli İsmet Attila Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Bozdoğan Halımoru İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Sarık İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Köprülü Şehit Ramiz Demir Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Karaaslan İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Anıtkaya Faik Deniz İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Anıtkaya Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Kışlacık Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Karaaslan Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Gazi Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Asım Kocabıyık Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Kışlacık İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Zübeyde Hanım Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Emine Efiloğlu Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Ekrem Yavuz Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Ekrem Yavuz İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Özlem Özyurt Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - ÇAYIRBAĞ GAZİ ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - ÇAYIRBAĞ İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - Neriman-İbrahim Küçükkurt Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - VİLAYETLER HİZMET BİRLİĞİ ANAOKULU',
    'AFYONKARAHİSAR - MERKEZ - Hürriyet İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Hüseyin Sümer Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Şehit Murat Hasırcıoğlu Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Hisarbank 100. Yıl İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Bozdoğan Halımoru Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Ali Çetinkaya İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Işıklar Şeker Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - SARAYDÜZÜ ŞEHİT ER OĞUZ AKDAĞ İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - Kozluca İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - AKÇİN YÖRÜKOĞLU ATİLLA MİLLİK ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - DEĞİRMENDERE İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - KOCATEPE İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - Nuribey İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Nurettin Karaman İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - BELKARACAÖREN İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - Büyükkalecik Bahçederesi İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - MELEK PEYKER ANAOKULU',
    'AFYONKARAHİSAR - MERKEZ - IŞIKLAR BALI SULTAN İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - Şehit Mehmet Dama Yatılı Bölge Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Güzel Sanatlar Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Yusuf Özer Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - ATAKÖY İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - NAİME GEVHER ANAOKULU',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Hattat Ahmet Karahisari Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - MERKEZ - ANITKAYA İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - KÜÇÜKÇOBANLI ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - MEHMET AKİF ERSOY İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Kız Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - MERKEZ - SALAR İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - KAMİL MİRAS ANADOLU LİSESİ',
    'AFYONKARAHİSAR - MERKEZ - Ayşegül Arsoy Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - BÜYÜKKALECİK İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - ŞÜKRÜ ÇELİKALAY İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - Asiye Sultan Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Sülümenli İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Şemsettin Güneş İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Işıklar İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Nene Hatun Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Erkmen TOKİ Nurullah Oymak İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Şehit Mustafa Sezer Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Karşıyaka İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - DUMLUPINAR BİLİM VE SANAT MERKEZİ',
    'AFYONKARAHİSAR - MERKEZ - Özerler Özel Eğitim Meslek Okulu',
    'AFYONKARAHİSAR - MERKEZ - ŞEHİT YAKUP SUNA İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - DEĞİRMENAYVALI İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - SADIKBEY İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - BÜYÜKKALECİK İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar TOBB Kız Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - MERKEZ - FATİH SULTAN MEHMET İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - Şehit Ayhan Sarıçiçek İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - MECİDİYE İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - SUSUZ İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - ORHANGAZİ İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - 15 TEMMUZ ŞEHİTLER ANAOKULU',
    'AFYONKARAHİSAR - MERKEZ - BEYYAZI İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Spor Lisesi',
    'AFYONKARAHİSAR - MERKEZ - ERKMEN İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - ŞEHİT YASİN MERGEN İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - ŞEHİT YASİN MERGEN ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - SARIK ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - ŞEHİT ÖMER HALİSDEMİR İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - SUSUZ İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - NURİBEY İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - Işıklar Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - DEMİRÇEVRE İLKOKULU',
    'AFYONKARAHİSAR - MERKEZ - TOKİ MEVLANA ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - ÇIKRIK İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - Maver Kemal Arsoy Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Maver - Kemal Arsoy İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - Toki Mevlana İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - IŞIKLAR ÇOK PROGRAMLI ANADOLU LİSESİ',
    'AFYONKARAHİSAR - MERKEZ - SÜLÜN İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - FETHİBEY İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - VEDİHA-AHMET KIZILKAYA ANAOKULU',
    'AFYONKARAHİSAR - MERKEZ - GEBECELER İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - MERKEZ - RECEP TAYYİP ERDOĞAN ANADOLU LİSESİ',
    'AFYONKARAHİSAR - MERKEZ - Mimar Sinan Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Kızıldağ Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Salar Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Özel Eğitim Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Hacı Sultan Hüsnü Ulu Kız Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - MERKEZ - Ahmet Ömer Kocaşaban İlkokulu',
    'AFYONKARAHİSAR - MERKEZ - İbrahim Keser Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Zeynur Çetinkaya Kızılay Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Fatih Ortaokulu',
    'AFYONKARAHİSAR - MERKEZ - Afyonkarahisar Şehit Soner Hayta Adalet Meslekî Eğitim Merkezi',
    'AFYONKARAHİSAR - MERKEZ - Hacı Lütfiye Kocaşaban Anaokulu',
    'AFYONKARAHİSAR - MERKEZ - Sedat Gökdemir Özel Eğitim Uygulama Okulu I. Kademe',
    'AFYONKARAHİSAR - MERKEZ - Sedat Gökdemir Özel Eğitim Uygulama Okulu III. Kademe',
    'AFYONKARAHİSAR - MERKEZ - Sedat Gökdemir Özel Eğitim Uygulama Okulu II. Kademe',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Rehberlik ve Araştırma Merkezi',
    'AFYONKARAHİSAR - SANDIKLI - Akharım Anaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Baştepe İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Hatice Turan Anaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Yavuz Selim Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Şehit Gökhan Orhan Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Hisar Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Yunus Emre Anadolu Lisesi',
    'AFYONKARAHİSAR - SANDIKLI - Kusura Şehit Mustafa Şimşek İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Kusura Şehit Mustafa Şimşek Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Mustafa Kemal Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Kızık Mehmet Yaşar İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Çiğiltepe İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Çiğiltepe Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Kızık Mehmet Yaşar Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Sorkun Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Bekteş İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Bekteş Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Akharım İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Yunusemre Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Yunusemre İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Cumhuriyet Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Ali Çetinkaya Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Menteş İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Yavaşlar İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Yavaşlar Şehit Teğmen Uğur Acar Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Yaşarlar Zekiye Ana İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Atatürk İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Mesleki Eğitim Merkezi',
    'AFYONKARAHİSAR - SANDIKLI - Mehmet Akif Ersoy İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Ballık İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Miralay Reşatbey İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Ballık Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Mustafa Kemal İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Akharım Atatürk Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Kınık İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Karacaören İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Hüdai Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Öğretmen Evi ve Akşam Sanat Okulu',
    'AFYONKARAHİSAR - SANDIKLI - Şehit Ahmet Yumak Anaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Örenkaya İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Örenkaya Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Koçhisar İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - SANDIKLI - Reşadiye Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Reşadiye İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Çevrepınar İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Zübeyde Hanım Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - SANDIKLI - Barbaros Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - Kızılca İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Hırka İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - 75. Yıl İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - KARKIN İLKOKULU',
    'AFYONKARAHİSAR - SANDIKLI - Sorkun İlkokulu',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Özçınar Özel Eğitim Uygulama Okulu I. Kademe',
    'AFYONKARAHİSAR - SANDIKLI - YAŞARLAR ZEKİYE ANA ORTAOKULU',
    'AFYONKARAHİSAR - SANDIKLI - DODURGA İLKOKULU',
    'AFYONKARAHİSAR - SANDIKLI - SANDIKLI ÖZÇINAR ÖZEL EĞİTİM UYGULAMA MERKEZİ II. KADEME',
    'AFYONKARAHİSAR - SANDIKLI - SANDIKLI ÖZÇINAR ÖZEL EĞİTİM İŞ UYGULAMA MERKEZİ (OKULU)',
    'AFYONKARAHİSAR - SANDIKLI - SANDIKLI TÜRK TELEKOM FEN LİSESİ',
    'AFYONKARAHİSAR - SANDIKLI - Aktürkler İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - SANDIKLI - SANDIKLI KIZ ANADOLU İMAM HATİP LİSESİ',
    'AFYONKARAHİSAR - SANDIKLI - KOZVAN İLKOKULU',
    'AFYONKARAHİSAR - SANDIKLI - FATİH SULTAN MEHMET İLKOKULU',
    'AFYONKARAHİSAR - SANDIKLI - SANDIKLI BARBAROS İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - SANDIKLI - AKHARIM ŞEHİT BÜLENT ERDOĞAN İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - SANDIKLI - Sandıklı Bilim ve Sanat Merkezi',
    'AFYONKARAHİSAR - SİNANPAŞA - Karacaören İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Düzağaç İstiklal İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Muzaffer Yılmaz Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Sinanpaşa Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - SİNANPAŞA - Taşoluk Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - SİNANPAŞA - Tınaztepe Atatürk İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Tınaztepe Çok Programlı Lisesi',
    'AFYONKARAHİSAR - SİNANPAŞA - Akören Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Akören İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Tokuşlar Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Taşoluk Şehit Yunus Emre Aral İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Ahmetpaşa Atatürk İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Bulca Şehit Necati Yatkak Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Güney Ayşe Zeynep Kocabıyık Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Bulca İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Ahmet Mesut Yılmaz Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Ahmetpaşa Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Taşoluk Fatih Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Güney İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Serban Kazım Özer Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Nuh İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Garipçe Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - 27 Ağustos Sinanpaşa Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Kırka Şehit Ramazan Bağlan Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Kılıçarslan İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Atatürk İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Kınık Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Kınık İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Düzağaç Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Boyalı Şöhret Hanım İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Kayadibi İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Tınaztepe Zafer İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - 27 Ağustos Sinanpaşa İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Boyalı Sevim Turunç Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Serban Kazım Özer İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Küçükhüyük İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Garipçe İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Küçükhüyük Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - KIRKA İLKOKULU',
    'AFYONKARAHİSAR - SİNANPAŞA - TINAZTEPE İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - SİNANPAŞA - Tokuşlar İlkokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - SİNANPAŞA ANAOKULU',
    'AFYONKARAHİSAR - SİNANPAŞA - Taşoluk İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - ÇOBANÖZÜ İLKOKULU',
    'AFYONKARAHİSAR - SİNANPAŞA - Sinanpaşa Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - SİNANPAŞA - Sinanpaşa Anadolu Lisesi',
    'AFYONKARAHİSAR - SİNANPAŞA - Çiğiltepe Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - SİNANPAŞA - Akören İmam Hatip Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Kayadibi Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Çobanözü Ortaokulu',
    'AFYONKARAHİSAR - SİNANPAŞA - Balmahmut İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Ağzıkara İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Akyuva İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Atatürk İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Çakırözü İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Gazipaşa Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Şuhut Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - ŞUHUT - Şuhut Şehit Yasin Çubuk Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - ŞUHUT - Karaadilli Çok Programlı Anadolu Lisesi',
    'AFYONKARAHİSAR - ŞUHUT - Karaadilli İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Kurtuluş İhsan Küçükarslan İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Ortapınar Şehit Muammer Çanta İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Şuhut Anadolu Lisesi',
    'AFYONKARAHİSAR - ŞUHUT - Piri Reis Muhsin Düğüncü Anaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Şuhut Şehit İbrahim Imış Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - ŞUHUT - Yarışlı İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Zaferyolu İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Senir İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Dadak Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Dadak İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Atlıhisar İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Çakırözü Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Cumhuriyet İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Atatürk Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Kurtuluş İhsan Küçükarslan Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Mahmut Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Fatih Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Fatih İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - İcikli İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Hallaç İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Balçıkhisar İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Yarışlı Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Efe İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Efe Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Mahmut İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Akyuva Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Ortapınar Şehit Muammer Çanta Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - Karacaören İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Başören Şehit Yusuf Erol İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Başören Şehit Yusuf Erol Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - ÖĞRETMEN EVİ VE AKŞAM SANAT OKULU',
    'AFYONKARAHİSAR - ŞUHUT - ATLIHİSAR ORTAOKULU',
    'AFYONKARAHİSAR - ŞUHUT - KARAADİLLİ İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - ŞUHUT - KAVAKLI İLKOKULU',
    'AFYONKARAHİSAR - ŞUHUT - ANAYURT İLKOKULU',
    'AFYONKARAHİSAR - ŞUHUT - AYDIN İLKOKULU',
    'AFYONKARAHİSAR - ŞUHUT - ŞUHUT ZAFER ANADOLU LİSESİ',
    'AFYONKARAHİSAR - ŞUHUT - Karaadilli Ortaokulu',
    'AFYONKARAHİSAR - ŞUHUT - ŞUHUT KIZ ANADOLU İMAM HATİP LİSESİ',
    'AFYONKARAHİSAR - ŞUHUT - Arızlı Kılıçkaya İlkokulu',
    'AFYONKARAHİSAR - ŞUHUT - Karaadilli Anadolu Lisesi',
    'AFYONKARAHİSAR - SULTANDAĞI - Karapınar İlkokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Sultandağı Halk Eğitimi Merkezi',
    'AFYONKARAHİSAR - SULTANDAĞI - Sultandağı Anadolu İmam Hatip Lisesi',
    'AFYONKARAHİSAR - SULTANDAĞI - Selçuk İlkokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Sultandağı Anaokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Sultandağı Anadolu Lisesi',
    'AFYONKARAHİSAR - SULTANDAĞI - Şehit Yılmaz Tankül Mesleki ve Teknik Anadolu Lisesi',
    'AFYONKARAHİSAR - SULTANDAĞI - Yakasenek İlkokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Dereçine İlkokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Üçkuyu İlkokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Dereçine Ortaokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - İshaklı Ortaokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Kırca İlkokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Kırca Ortaokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Yeşilçiftlik Ortaokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - Yeşilçiftlik İlkokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - 75. Yıl İlkokulu',
    'AFYONKARAHİSAR - SULTANDAĞI - SULTANDAĞI İMAM HATİP ORTAOKULU',
    'AFYONKARAHİSAR - SULTANDAĞI - Çamözü İlkokulu',
  ];

  List<String> get list=>_list;
}