class AgriSchools {
  final List<String> _list=['AĞRI - DİYADİN - Atayolu İlkokulu',
    'AĞRI - DİYADİN - Cemal Kaya Anadolu Lisesi',
    'AĞRI - DİYADİN - Cumhuriyet İlkokulu',
    'AĞRI - DİYADİN - Heybeliyurt İlkokulu',
    'AĞRI - DİYADİN - Karapazar Ortaokulu',
    'AĞRI - DİYADİN - Kaymakam Özgür Azer Kurak Anaokulu',
    'AĞRI - DİYADİN - Tendürek Dağı Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - DİYADİN - Tavla İlkokulu',
    'AĞRI - DİYADİN - Ulukent İlkokulu',
    'AĞRI - DİYADİN - Öğretmen Evi ve Akşam Sanat Okulu',
    'AĞRI - DİYADİN - Şehit İlhan Demir Yatılı Bölge Ortaokulu',
    'AĞRI - DİYADİN - Mehmet Melik Özmen İlkokulu',
    'AĞRI - DİYADİN - Mehmet Melik Özmen Ortaokulu',
    'AĞRI - DİYADİN - Sürenkök Akçay İlkokulu',
    'AĞRI - DİYADİN - Diyadin Anadolu İmam Hatip Lisesi',
    'AĞRI - DİYADİN - Davut Ortaokulu',
    'AĞRI - DİYADİN - Yeşildurak İlkokulu',
    'AĞRI - DİYADİN - Türk Telekom Ortaokulu',
    'AĞRI - DİYADİN - Hacıhalit İlkokulu',
    'AĞRI - DİYADİN - Merkez Gazi İlkokulu',
    'AĞRI - DİYADİN - Taşbasamak İlkokulu',
    'AĞRI - DİYADİN - Burgulu İlkokulu',
    'AĞRI - DİYADİN - Budak İlkokulu',
    'AĞRI - DİYADİN - Hacıhalit Ortaokulu',
    'AĞRI - DİYADİN - Mutlu İlkokulu',
    'AĞRI - DİYADİN - Mollakara İlkokulu',
    'AĞRI - DİYADİN - Günbuldu İlkokulu',
    'AĞRI - DİYADİN - Akyolaç İlkokulu',
    'AĞRI - DİYADİN - Yukarıdalören İlkokulu',
    'AĞRI - DİYADİN - Kuşlu İlkokulu',
    'AĞRI - DİYADİN - Taşbasamak Ortaokulu',
    'AĞRI - DİYADİN - Pirali İlkokulu',
    'AĞRI - DİYADİN - Yeniçadır Ortaokulu',
    'AĞRI - DİYADİN - Yeniçadır İlkokulu',
    'AĞRI - DİYADİN - Dokuztaş İlkokulu',
    'AĞRI - DİYADİN - Kapanca İlkokulu',
    'AĞRI - DİYADİN - Kuşburnu İlkokulu',
    'AĞRI - DİYADİN - Sürenkök İlkokulu',
    'AĞRI - DİYADİN - Şahinşah Cumhuriyet İlkokulu',
    'AĞRI - DİYADİN - 14 Nisan İlkokulu',
    'AĞRI - DİYADİN - 14 Nisan Ortaokulu',
    'AĞRI - DİYADİN - Altınkilit İlkokulu',
    'AĞRI - DİYADİN - Oğuloba İlkokulu',
    'AĞRI - DİYADİN - Yörükaltı İlkokulu',
    'AĞRI - DİYADİN - Yuva İlkokulu',
    'AĞRI - DİYADİN - Kocaçoban İlkokulu',
    'AĞRI - DİYADİN - Toklucak İlkokulu',
    'AĞRI - DİYADİN - Omuzbaşı İlkokulu',
    'AĞRI - DİYADİN - Taşkesen İlkokulu',
    'AĞRI - DİYADİN - Taşkesen Ortaokulu',
    'AĞRI - DİYADİN - Yatılı Bölge Ortaokulu',
    'AĞRI - DİYADİN - Diyadin Halk Eğitimi Merkezi',
    'AĞRI - DİYADİN - Dibekli İlkokulu',
    'AĞRI - DİYADİN - Diyadin Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - DİYADİN - Şehit Ömer Halisdemir Anadolu Lisesi',
    'AĞRI - DİYADİN - Diyadin İmam Hatip Ortaokulu',
    'AĞRI - DİYADİN - Ulukent Ortaokulu',
    'AĞRI - DİYADİN - Aşağı Dalören İlkokulu',
    'AĞRI - DİYADİN - Yıldızlı İlkokulu',
    'AĞRI - DİYADİN - ATATÜRK ORTAOKULU',
    'AĞRI - DİYADİN - Yanıkçukur İlkokulu',
    'AĞRI - DİYADİN - BOYALAN İLKOKULU',
    'AĞRI - DİYADİN - RAHMANKULU İLKOKULU',
    'AĞRI - DİYADİN - Diyadin İlkokulu',
    'AĞRI - DİYADİN - DİYADİN ANAOKULU',
    'AĞRI - DİYADİN - ŞEHİT POLİS GÖKHAN KİRAZLI ORTAOKULU',
    'AĞRI - DİYADİN - MEHMET AKİF ERSOY İLKOKULU',
    'AĞRI - DİYADİN - Sürmelikoç İlkokulu',
    'AĞRI - DİYADİN - YUKARI AKPAZAR İLKOKULU',
    'AĞRI - DİYADİN - AŞAĞI SATICILAR İLKOKULU',
    'AĞRI - DİYADİN - Karapazar İlkokulu',
    'AĞRI - DİYADİN - AHMED-İ HANİ İLKOKULU',
    'AĞRI - DİYADİN - YUKARI SATICILAR İLKOKULU',
    'AĞRI - DİYADİN - Mollakara Ortaokulu',
    'AĞRI - DİYADİN - KARATAŞ İLKOKULU',
    'AĞRI - DİYADİN - HÜSEYİN ÖNER İLKOKULU',
    'AĞRI - DİYADİN - GÜNBULDU ORTAOKULU',
    'AĞRI - DİYADİN - DAVUT İLKOKULU',
    'AĞRI - DİYADİN - BATIBEYLİ İLKOKULU',
    'AĞRI - DİYADİN - Aşağı Kardeşli İlkokulu',
    'AĞRI - DİYADİN - Kotancı İlkokulu',
    'AĞRI - DİYADİN - Taşkesen Cumhuriyet İlkokulu',
    'AĞRI - DİYADİN - Büvetli İlkokulu',
    'AĞRI - DİYADİN - Tazekent İlkokulu',
    'AĞRI - DİYADİN - Dedebulak Kaynaklı İlkokulu',
    'AĞRI - DİYADİN - Gedik İlkokulu',
    'AĞRI - DİYADİN - Kardelen Anaokulu',
    'AĞRI - DİYADİN - Şehit Polis Tufan Kansuva İlkokulu',
    'AĞRI - DİYADİN - Mutlu Ortaokulu',
    'AĞRI - DİYADİN - Şekerbulak İlkokulu',
    'AĞRI - DİYADİN - Hüseyin Öner Anaokulu',
    'AĞRI - DİYADİN - Batıbeyli Tarlabaşı İlkokulu',
    'AĞRI - DİYADİN - Yolcupınar İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Ahmedi Hani Anadolu Lisesi',
    'AĞRI - DOĞUBAYAZIT - Halife Yusuf İmam Hatip Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - 14 Nisan İlkokulu',
    'AĞRI - DOĞUBAYAZIT - 14 Nisan Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - A Takımı-Savaş Ay Anadolu Lisesi',
    'AĞRI - DOĞUBAYAZIT - Bereket İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Bereket Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Çiftlik İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Dağdelen İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Dalbahçe İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Hüsnü M.Özyeğin İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Muhammed Celali Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - DOĞUBAYAZIT - Şehit Polis Fethi Sekin Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - DOĞUBAYAZIT - Doğubeyazıt Rıza Ertuğrul Eryılmaz Anadolu Lisesi',
    'AĞRI - DOĞUBAYAZIT - Gevher Nesibe Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - DOĞUBAYAZIT - Dr. Reşat Erden Anadolu Lisesi',
    'AĞRI - DOĞUBAYAZIT - Gazi İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Doğubayazıt Halk Eğitimi Merkezi',
    'AĞRI - DOĞUBAYAZIT - Fatımatü Zehra Kız Anadolu İmam Hatip Lisesi',
    'AĞRI - DOĞUBAYAZIT - İncesu İlkokulu',
    'AĞRI - DOĞUBAYAZIT - İshakpaşa Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Kazan İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Kemalpaşa İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Kemalpaşa Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Küçük Yılanlı İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Doğubayazıt Mesleki Eğitim Merkezi',
    'AĞRI - DOĞUBAYAZIT - Nuhun Gemisi Anaokulu',
    'AĞRI - DOĞUBAYAZIT - Öğretmen Evi ve Akşam Sanat Okulu',
    'AĞRI - DOĞUBAYAZIT - Örtülü İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Sarıbıyık İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Somkaya Hüsnü M.Özyeğin İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Tutak İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Tutumlu İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yanoba İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yukarı Tavla İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Zirve Anaokulu',
    'AĞRI - DOĞUBAYAZIT - Şehit Gürhan Yardım İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yaygınyurt İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Binkaya İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Ayrancı İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Doğubayazıt Suluçem Yatılı Bölge Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Mustafa Yassuboğa İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Fatih Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Fatih İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Şehit Gürhan Yardım Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Ortadirek İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Ortakent İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yatılı Bölge Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Kargakonmaz İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Ortadirek Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Gölyüzü İlkokulu',
    'AĞRI - DOĞUBAYAZIT - 75. Yıl İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yeniköy Nazire Eryılmaz İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Karaburun İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Günyolu İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Dolaklı İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Çetenli İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Çetenli Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Gürbulak Atatürk İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Sağdıç İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Hüseyin Celal Yardımcı Kurtuluş İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Atatürk İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Sağdıç Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Sarıgül İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Sarıgül Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Dolaklı Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Atabakan İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Hasan Çoktin Cumhuriyet Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Kalecik İlkokulu',
    'AĞRI - DOĞUBAYAZIT - İshakpaşa İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yılanlı İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Topcatan İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Dostali İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Karakent İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yığınçal İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Ahmedi Hani Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Mustafa Yassuboğa Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Hüseyin Celal Yardımcı Kurtuluş Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Ahmedi Hani İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yığınçal Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Demirtepe İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Türkmen İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Mehmet Akif Ersoy İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Gürbulak Atatürk Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Cemile Yassuboğa İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Savcı Hakan Kılıç Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Bardaklı Hüsnü M.Özyeğin Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Bardaklı Hüsnü M.Özyeğin İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Karabulak Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Kızılkaya Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Kızılkaya İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Atatürk Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Somkaya Hüsnü M.Özyeğin Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Savcı Hakan Kılıç İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Mehmet Akif Ersoy Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Tanıktepe İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yalınsaz İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Bayır İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Esnemez Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Pullutarla İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Esnemez İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Buyuretti İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Hani Baba Anaokulu',
    'AĞRI - DOĞUBAYAZIT - Üçgöze İlkokulu',
    'AĞRI - DOĞUBAYAZIT - 75.Yıl Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Dalbahçe Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Uzunyazı İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Üzengili İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Çiftlik İbrahim Ağa Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Uğrak İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Güllüce İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Sağlıksuyu Cevan Eydın Konyar İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Gültepe İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Gözükara İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Akçukur İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Fevzi Çakmak İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Bozkurt İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Karakent Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Alıntepe İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Garnizon Telçeker Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Aşağı Telçeker İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Öğretmen Aysun Karalar Anaokulu',
    'AĞRI - DOĞUBAYAZIT - Karaca İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Garnizon Telçeker İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Yolüstü İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Seslitaş İlkokul',
    'AĞRI - DOĞUBAYAZIT - Başkent İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Çömçeli İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Hallaç İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Hüsnü M.Özyeğin Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Mescit İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Ortaca İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Samanlı İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Subeşiği İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Ömerbey İlkokulu',
    'AĞRI - DOĞUBAYAZIT - BAYIR ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - Suluçem İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Kalecik Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - KARABULAK İLKOKULU',
    'AĞRI - DOĞUBAYAZIT - Sağlıksuyu Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - SUBEŞİĞİ ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - Tanıktepe Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Güllüce Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - NUHUN GEMİSİ ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - Medine Müdafii Fahrettin Paşa Anadolu İmam Hatip Lisesi',
    'AĞRI - DOĞUBAYAZIT - SAİD-İ NURSİ İMAM HATİP ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - DOĞUBAYAZIT ÖZEL EĞİTİM UYGULAMA MERKEZİ I. KADEME',
    'AĞRI - DOĞUBAYAZIT - DOĞUBAYAZIT ÖZEL EĞİTİM UYGULAMA MERKEZİ II. KADEME',
    'AĞRI - DOĞUBAYAZIT - DOĞUBAYAZIT ÖZEL EĞİTİM İŞ UYGULAMA MERKEZİ (OKULU)',
    'AĞRI - DOĞUBAYAZIT - Mehmet Bayar İlkokulu',
    'AĞRI - DOĞUBAYAZIT - MEHMET BAYAR ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - Mevlana Celaleddin - i Rumi İmam Hatip Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - İBN-İ HALDUN İMAM HATİP ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - FATİH İMAM HATİP ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - TUTAK KÖYÜ İMAM HATİP ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - GARNİZON TELÇEKER İMAM HATİP ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - Çiftlik İbrahim Ağa İmam Hatip Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - TEPELİ İLKOKULU',
    'AĞRI - DOĞUBAYAZIT - Suluçem İmam Hatip Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - GAZİ İMAM HATİP ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - MEHMET BAYAR İMAM HATİP ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - 75. YIL İMAM HATİP ORTAOKULU',
    'AĞRI - DOĞUBAYAZIT - Mehmet Akif Ersoy İmam Hatip Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Hüseyin Celal Yardımcı Kurtuluş İmam Hatip Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Çetenli İmam Hatip Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - 18 Mart İmam Hatip Ortaokulu',
    'AĞRI - DOĞUBAYAZIT - Yunus Emre Anadolu Lisesi',
    'AĞRI - DOĞUBAYAZIT - Şehit Emniyet Müdürü Zafer Koyuncu İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Göller İlkokulu',
    'AĞRI - DOĞUBAYAZIT - Zafer Koyuncu İmam Hatip Ortaokulu',
    'AĞRI - DOĞUBEYAZIT - Doğubayazıt Bilim ve Sanat Merkezi',
    'AĞRI - DOĞUBEYAZIT - İlkadım Anaokulu',
    'AĞRI - DOĞUBEYAZIT - Doğubayazıt Rehberlik ve Araştırma Merkezi',
    'AĞRI - DOĞUBEYAZIT - Çay Mezrası İlkokulu',
    'AĞRI - DOĞUBEYAZIT - Aşağı Tavla İlkokulu',
    'AĞRI - DOĞUBEYAZIT - Ağrı Dağı İlkokulu',
    'AĞRI - DOĞUBEYAZIT - Ağrı Dağı Ortaokulu',
    'AĞRI - DOĞUBEYAZIT - Selahaddin Eyyubi Ortaokulu',
    'AĞRI - DOĞUBEYAZIT - Ömer Çoktin Fen Lisesi',
    'AĞRI - DOĞUBEYAZIT - Şehit Emniyet Müdürü Zafer KOYUNCU Yatılı Bölge Ortaokulu',
    'AĞRI - DOĞUBEYAZIT - Bezirhane İlkokulu',
    'AĞRI - DOĞUBEYAZIT - Ahmedi Hani Anaokulu',
    'AĞRI - DOĞUBEYAZIT - Cemile Yassuboğa Anaokulu',
    'AĞRI - DOĞUBEYAZIT - 14 Nisan Anaokulu',
    'AĞRI - DOĞUBEYAZIT - Ağrı Dağı Anaokulu',
    'AĞRI - DOĞUBEYAZIT - Mehmet Akif Ersoy Anaokulu',
    'AĞRI - ELEŞKİRT - Değirmenoluğu İlkokulu',
    'AĞRI - ELEŞKİRT - Eleşkirt 70. Yıl Cumhuriyet Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - ELEŞKİRT - Eleşkirt Anadolu Lisesi',
    'AĞRI - ELEŞKİRT - Eleşkirt Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - ELEŞKİRT - 16 Nisan Anaokulu',
    'AĞRI - ELEŞKİRT - Cemaleddin Öztürk Ortaokulu',
    'AĞRI - ELEŞKİRT - Atatürk İlkokulu',
    'AĞRI - ELEŞKİRT - Yeşilova İlkokulu',
    'AĞRI - ELEŞKİRT - Türk Telekom Tahir İlkokulu',
    'AĞRI - ELEŞKİRT - Söbetaş İlkokulu',
    'AĞRI - ELEŞKİRT - Eleşkirt İmam Hatip Ortaokulu',
    'AĞRI - ELEŞKİRT - Aşağı Cihanbey İlkokulu',
    'AĞRI - ELEŞKİRT - Eleşkirt Ortaokulu',
    'AĞRI - ELEŞKİRT - Dalkılıç İlkokulu',
    'AĞRI - ELEŞKİRT - Sultanabat İlkokulu',
    'AĞRI - ELEŞKİRT - Sarıcan İlkokulu',
    'AĞRI - ELEŞKİRT - Düzyayla İlkokulu',
    'AĞRI - ELEŞKİRT - Yelkesen İlkokulu',
    'AĞRI - ELEŞKİRT - Uzunyazı İlkokulu',
    'AĞRI - ELEŞKİRT - Yanıkdere İlkokulu',
    'AĞRI - ELEŞKİRT - Alagün İlkokulu',
    'AĞRI - ELEŞKİRT - Hürriyet İlkokulu',
    'AĞRI - ELEŞKİRT - Güvence İlkokulu',
    'AĞRI - ELEŞKİRT - Mollasüleyman Gazi İlkokulu',
    'AĞRI - ELEŞKİRT - Dolutaş İlkokulu',
    'AĞRI - ELEŞKİRT - Goncalı Ortaokulu',
    'AĞRI - ELEŞKİRT - İkizgeçe İlkokulu',
    'AĞRI - ELEŞKİRT - Sadaklı İlkokulu',
    'AĞRI - ELEŞKİRT - Sadaklı Ortaokulu',
    'AĞRI - ELEŞKİRT - Pirabat İlkokulu',
    'AĞRI - ELEŞKİRT - Toprakkale Ortaokulu',
    'AĞRI - ELEŞKİRT - Türkeli İlkokulu',
    'AĞRI - ELEŞKİRT - Güneykaya İlkokulu',
    'AĞRI - ELEŞKİRT - Gökçayır İlkokulu',
    'AĞRI - ELEŞKİRT - Değirmengeçidi İlkokulu',
    'AĞRI - ELEŞKİRT - Mollasüleyman Gazi Ortaokulu',
    'AĞRI - ELEŞKİRT - Ergözü ilkokulu',
    'AĞRI - ELEŞKİRT - Ergözü Ortaokulu',
    'AĞRI - ELEŞKİRT - Haydaroğlu İlkokulu',
    'AĞRI - ELEŞKİRT - Süzgeçli İlkokulu',
    'AĞRI - ELEŞKİRT - Çetinsu İlkokulu',
    'AĞRI - ELEŞKİRT - Cengiz Topel İlkokulu',
    'AĞRI - ELEŞKİRT - Aydıntepe İlkokulu',
    'AĞRI - ELEŞKİRT - Pirabat ortaokulu',
    'AĞRI - ELEŞKİRT - Esentepe İlkokulu',
    'AĞRI - ELEŞKİRT - Toprakkale ilkokulu',
    'AĞRI - ELEŞKİRT - Goncalı İlkokulu',
    'AĞRI - ELEŞKİRT - Yeşilova Ortaokulu',
    'AĞRI - ELEŞKİRT - Cesim Bayram Ortaokulu',
    'AĞRI - ELEŞKİRT - 100. Yıl İlkokulu',
    'AĞRI - ELEŞKİRT - Ramazan İlkokulu',
    'AĞRI - ELEŞKİRT - İkizgeçe Ortaokulu',
    'AĞRI - ELEŞKİRT - Cengiz Topel Ortaokulu',
    'AĞRI - ELEŞKİRT - 100. Yıl Ortaokulu',
    'AĞRI - ELEŞKİRT - Cemaleddin Öztürk İlkokulu',
    'AĞRI - ELEŞKİRT - Değirmenoluğu Ortaokulu',
    'AĞRI - ELEŞKİRT - Oklavalı İlkokulu',
    'AĞRI - ELEŞKİRT - Hasanpınar İlkokulu',
    'AĞRI - ELEŞKİRT - Oklavalı Ortaokulu',
    'AĞRI - ELEŞKİRT - Aşağı Kopuz İlkokulu',
    'AĞRI - ELEŞKİRT - Uludal İlkokulu',
    'AĞRI - ELEŞKİRT - Abdi İlkokulu',
    'AĞRI - ELEŞKİRT - İndere İlkokulu',
    'AĞRI - ELEŞKİRT - Çatalpınar İlkokulu',
    'AĞRI - ELEŞKİRT - Karşıyaka İlkokulu',
    'AĞRI - ELEŞKİRT - Karşıyaka Ortaokulu',
    'AĞRI - ELEŞKİRT - Yığıntaş İlkokulu',
    'AĞRI - ELEŞKİRT - Türk Telekom Tahir Ortaokulu',
    'AĞRI - ELEŞKİRT - Salkımlı İlkokulu',
    'AĞRI - ELEŞKİRT - Çatkösedağ İlkokulu',
    'AĞRI - ELEŞKİRT - Afacanlar Anaokulu',
    'AĞRI - ELEŞKİRT - Hayrangöl İlkokulu',
    'AĞRI - ELEŞKİRT - Yücekapı Ortaokulu',
    'AĞRI - ELEŞKİRT - Yücekapı ilkokulu',
    'AĞRI - ELEŞKİRT - Aydoğdu İlkokulu',
    'AĞRI - ELEŞKİRT - Çok Programlı Anadolu Lisesi',
    'AĞRI - ELEŞKİRT - Öğretmen Evi ve Akşam Sanat Okulu',
    'AĞRI - ELEŞKİRT - Eleşkirt Halk Eğitimi Merkezi',
    'AĞRI - ELEŞKİRT - ELEŞKİRT İLKOKULU',
    'AĞRI - ELEŞKİRT - Recep Tayyip Erdoğan Anadolu İmam Hatip Lisesi',
    'AĞRI - ELEŞKİRT - KEMAL ÖZTÜRK ANADOLU LİSESİ',
    'AĞRI - ELEŞKİRT - MEHMET AKİF ERSOY İLKOKULU',
    'AĞRI - ELEŞKİRT - YÜCEKAPI BELDESİ İMAM HATİP ORTAOKULU',
    'AĞRI - ELEŞKİRT - Osman Gazi İmam Hatip Ortaokulu',
    'AĞRI - ELEŞKİRT - MEHMET AKİF ERSOY ORTAOKULU',
    'AĞRI - ELEŞKİRT - Akyumak İlkokulu',
    'AĞRI - ELEŞKİRT - Çetinsu Ortaokulu',
    'AĞRI - ELEŞKİRT - Goncalı Köyü İmam Hatip Ortaokulu',
    'AĞRI - ELEŞKİRT - Cemaleddin Öztürk İmam Hatip Ortaokulu',
    'AĞRI - HAMUR - Adımova Ortaokulu',
    'AĞRI - HAMUR - Alakoyun İlkokulu',
    'AĞRI - HAMUR - Aşağı Gözlüce İlkokulu',
    'AĞRI - HAMUR - Aşağı Karabal Halis Özdemir İlkokulu',
    'AĞRI - HAMUR - Aşağı Karabal Halis Özdemir Ortaokulu',
    'AĞRI - HAMUR - Ayvacık Musabey İlkokulu',
    'AĞRI - HAMUR - Çağlayan İlkokulu',
    'AĞRI - HAMUR - Demirkapı İlkokulu',
    'AĞRI - HAMUR - Ekincik İlkokulu',
    'AĞRI - HAMUR - Hamur Halk Eğitimi Merkezi',
    'AĞRI - HAMUR - Hamur Çok Programlı Anadolu Lisesi',
    'AĞRI - HAMUR - Hamur Yatılı Bölge Ortaokulu',
    'AĞRI - HAMUR - Kandildağı İlkokulu',
    'AĞRI - HAMUR - Karlıca İlkokulu',
    'AĞRI - HAMUR - Başsavcı İhsan Eroğul Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - HAMUR - Özdirek İlkokulu',
    'AĞRI - HAMUR - Özdirek Oluklu İlkokulu',
    'AĞRI - HAMUR - Sarıbuğday İlkokulu',
    'AĞRI - HAMUR - Seslidoğan İlkokulu',
    'AĞRI - HAMUR - Seyithanbey İlkokulu',
    'AĞRI - HAMUR - Süleyman Kümbet Yukarı Koyuncu İlkokulu',
    'AĞRI - HAMUR - Süleymankümbet İlkokulu',
    'AĞRI - HAMUR - Yoğunhisar İlkokulu',
    'AĞRI - HAMUR - Yukarı Gözlüce Öğretmen Burçin Özdemir İlkokulu',
    'AĞRI - HAMUR - Yukarı Yenigün İlkokulu',
    'AĞRI - HAMUR - Yukarı Yenigün Yeşil İlkokulu',
    'AĞRI - HAMUR - Buzhane İlkokulu',
    'AĞRI - HAMUR - Kılıç Ortaokulu',
    'AĞRI - HAMUR - Kılıç İlkokulu',
    'AĞRI - HAMUR - Baldere İlkokulu',
    'AĞRI - HAMUR - Osman Gazi Ortaokulu',
    'AĞRI - HAMUR - Osman Gazi İlkokulu',
    'AĞRI - HAMUR - Kaçmaz İlkokulu',
    'AĞRI - HAMUR - Yukarı Gözlüce Öğretmen Burçin Özdemir Ortaokulu',
    'AĞRI - HAMUR - Kaçmaz Ortaokulu',
    'AĞRI - HAMUR - Danakıran İlkokulu',
    'AĞRI - HAMUR - Yukarı Deredibi İlkokulu',
    'AĞRI - HAMUR - Karaseyitali İlkokulu',
    'AĞRI - HAMUR - Ekincik Ortaokulu',
    'AĞRI - HAMUR - Gümüşkuşak Boztepe İlkokulu',
    'AĞRI - HAMUR - Tükenmez İlkokulu',
    'AĞRI - HAMUR - Hatunkomu İlkokulu',
    'AĞRI - HAMUR - Beklemez İlkokulu',
    'AĞRI - HAMUR - Gültepe İlkokulu',
    'AĞRI - HAMUR - Ekincik Yamaç İlkokulu',
    'AĞRI - HAMUR - Aşağı Aladağ İlkokulu',
    'AĞRI - HAMUR - Karakazan İlkokulu',
    'AĞRI - HAMUR - Yukarı Aladağ İlkokulu',
    'AĞRI - HAMUR - Kaynaklı İlkokulu',
    'AĞRI - HAMUR - Yapılı İlkokulu',
    'AĞRI - HAMUR - Beklemez Kardeşler İlkokulu',
    'AĞRI - HAMUR - Süleyman Kümbet Aşağı Yurt İlkokulu',
    'AĞRI - HAMUR - Yuvacık İlkokulu',
    'AĞRI - HAMUR - Adımova İlkokulu',
    'AĞRI - HAMUR - Kandildağı Ortaokulu',
    'AĞRI - HAMUR - Karadoğu İlkokulu',
    'AĞRI - HAMUR - Aşağı Yenigün İlkokulu',
    'AĞRI - HAMUR - Hamur Öğretmenevi ve Akşam Sanat Okulu',
    'AĞRI - HAMUR - Soğanlıtepe İlkokulu',
    'AĞRI - HAMUR - Seyithanbey Ortaokulu',
    'AĞRI - HAMUR - YAĞMUR ANAOKULU',
    'AĞRI - HAMUR - KARLICA EVLİYA ÇELEBİ ORTAOKULU',
    'AĞRI - HAMUR - Şehit Polis Yıldırım Günay İmam Hatip Ortaokulu',
    'AĞRI - HAMUR - YUKARI DEREDİBİ ORTAOKULU',
    'AĞRI - HAMUR - AŞAĞI DEREDİBİ İLKOKULU',
    'AĞRI - HAMUR - ÖZDİREK ORTAOKULU',
    'AĞRI - HAMUR - 15 TEMMUZ ŞEHİTLERİ İLKOKULU',
    'AĞRI - HAMUR - Mevlana İlkokulu',
    'AĞRI - HAMUR - Şehit Polis Yıldırım Günay Anadolu İmam Hatip Lisesi',
    'AĞRI - HAMUR - Köşk İlkokulu',
    'AĞRI - HAMUR - Gültepe Yoğurtçu İlkokulu',
    'AĞRI - HAMUR - Çevre İlkokulu',
    'AĞRI - HAMUR - Esenören İlkokulu',
    'AĞRI - HAMUR - Gümüşkuşak ilkokulu',
    'AĞRI - HAMUR - Ayvacık İlkokulu',
    'AĞRI - HAMUR - Nallıkonak İlkokulu',
    'AĞRI - HAMUR - Nallıkonak Güllüce İlkokulu',
    'AĞRI - HAMUR - Uğurtaş İlkokulu',
    'AĞRI - HAMUR - Karakazan Ortaokulu',
    'AĞRI - MERKEZ - Yukarı Ağadeve İlkokulu',
    'AĞRI - MERKEZ - Ağrı Anadolu İmam-Hatip Lisesi',
    'AĞRI - MERKEZ - 15 Temmuz Şehitleri Anadolu Lisesi',
    'AĞRI - MERKEZ - Türk Telekom Sosyal Bilimler Lisesi',
    'AĞRI - MERKEZ - Ağrı Dağı Anadolu Lisesi',
    'AĞRI - MERKEZ - Ağrı Hüseyin Celal Yardımcı Fen Lisesi',
    'AĞRI - MERKEZ - Nurettin Dolgun Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - MERKEZ - Ahmet Alagöz İlkokulu',
    'AĞRI - MERKEZ - Ahmet Alagöz Ortaokulu',
    'AĞRI - MERKEZ - Ali İbrahimağaoğlu Anaokulu',
    'AĞRI - MERKEZ - Şeyh Edebali İlkokulu',
    'AĞRI - MERKEZ - Atatürk Anaokulu',
    'AĞRI - MERKEZ - Baloluk İsmet Bulut İlkokulu',
    'AĞRI - MERKEZ - Cumhuriyet Anadolu Lisesi',
    'AĞRI - MERKEZ - Cumhuriyet İlkokulu',
    'AĞRI - MERKEZ - Fatih Sultan Mehmet Ortaokulu',
    'AĞRI - MERKEZ - Hayrettin Atmaca Anadolu Lisesi',
    'AĞRI - MERKEZ - Hürriyet İlkokulu',
    'AĞRI - MERKEZ - İMKB Gazi Ortaokulu',
    'AĞRI - MERKEZ - Kadir Has Ortaokulu',
    'AĞRI - MERKEZ - Karasu İlkokulu',
    'AĞRI - MERKEZ - Öğretmen Nurgül Gelturan Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - MERKEZ - Mehmet Şerafettin Yaltkaya İlkokulu',
    'AĞRI - MERKEZ - Aslangazi İlkokulu',
    'AĞRI - MERKEZ - Merkez 100.Yıl Ortaokulu',
    'AĞRI - MERKEZ - Ozanlar Yatılı Bölge Ortaokulu',
    'AĞRI - MERKEZ - Ağrı Mesleki Eğitim Merkezi',
    'AĞRI - MERKEZ - Mustafa Kemal Atatürk İlkokulu',
    'AĞRI - MERKEZ - Naci Gökçe Anadolu Lisesi',
    'AĞRI - MERKEZ - Öğretmenler Anadolu Lisesi',
    'AĞRI - MERKEZ - Piyade Onbaşı Bülent Avşin Anaokulu',
    'AĞRI - MERKEZ - 15 Temmuz Şehitleri İlkokulu',
    'AĞRI - MERKEZ - Şemsi Türkmen Anadolu Lisesi',
    'AĞRI - MERKEZ - Şerife Bacı Kız Teknik ve Meslek Lisesi',
    'AĞRI - MERKEZ - Yavuz Selim İlkokulu',
    'AĞRI - MERKEZ - Yolluyazı İlkokulu',
    'AĞRI - MERKEZ - Yoncalı İlkokulu',
    'AĞRI - MERKEZ - Zübeyde Hanım Anaokulu',
    'AĞRI - MERKEZ - Alpaslan Ortaokulu',
    'AĞRI - MERKEZ - Bölükbaşı İlkokulu',
    'AĞRI - MERKEZ - 15 Nisan İlkokulu',
    'AĞRI - MERKEZ - Murat Kız Yatılı Bölge Ortaokulu',
    'AĞRI - MERKEZ - İsmet Ömeroğlu İlkokulu',
    'AĞRI - MERKEZ - Balıksu İlkokulu',
    'AĞRI - MERKEZ - Aşağı Küpkıran İlkokulu',
    'AĞRI - MERKEZ - Ertuğrul Gazi Ortaokulu',
    'AĞRI - MERKEZ - Yukarı Küpkıran Ortaokulu',
    'AĞRI - MERKEZ - Kaymakam Özgür Azer Kurak Ortaokulu',
    'AĞRI - MERKEZ - Ağrı Halk Eğitimi Merkezi',
    'AĞRI - MERKEZ - Yazılı Ortaokulu',
    'AĞRI - MERKEZ - Şehit Hikmet Koman İlkokulu',
    'AĞRI - MERKEZ - Seyit Ali Onbaşı Anaokulu',
    'AĞRI - MERKEZ - Hıdır İlkokulu',
    'AĞRI - MERKEZ - Beşiktepe İlkokulu',
    'AĞRI - MERKEZ - Kuva-i Milliye İlkokulu',
    'AĞRI - MERKEZ - Şehit Harun Aslan Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - MERKEZ - Fatih Sultan Mehmet İlkokulu',
    'AĞRI - MERKEZ - Çukuralan İlkokulu',
    'AĞRI - MERKEZ - Eliaçık İlkokulu',
    'AĞRI - MERKEZ - Balıksu Ortaokulu',
    'AĞRI - MERKEZ - 75.Yıl Ortaokulu',
    'AĞRI - MERKEZ - Şehit Uzman Çavuş Tuncer Doğan İmam Hatip Ortaokulu',
    'AĞRI - MERKEZ - Güvenli İlkokulu',
    'AĞRI - MERKEZ - Yakınca İlkokulu',
    'AĞRI - MERKEZ - Semerkant Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - MERKEZ - İpekyolu Ortaokulu',
    'AĞRI - MERKEZ - 100.Yıl Gazi İlkokulu',
    'AĞRI - MERKEZ - İstiklal İlkokulu',
    'AĞRI - MERKEZ - Kazım Karabekir Ortaokulu',
    'AĞRI - MERKEZ - Atatürk İlkokulu',
    'AĞRI - MERKEZ - Yolugüzel İlkokulu',
    'AĞRI - MERKEZ - Başçavuş İlkokulu',
    'AĞRI - MERKEZ - Yakınca Ortaokulu',
    'AĞRI - MERKEZ - Cemil Meriç Ortaokulu',
    'AĞRI - MERKEZ - İbrahim Çeçen İlkokulu',
    'AĞRI - MERKEZ - Kalender İlkokulu',
    'AĞRI - MERKEZ - Cumaçay İlkokulu',
    'AĞRI - MERKEZ - Bezirhane 50 Yıl İlkokulu',
    'AĞRI - MERKEZ - Ballıbostan Ortaokulu',
    'AĞRI - MERKEZ - Vali Ali Yerlikaya Ortaokulu',
    'AĞRI - MERKEZ - Kazım Karabekir İlkokulu',
    'AĞRI - MERKEZ - Yukarı Küpkıran İlkokulu',
    'AĞRI - MERKEZ - Çakıroba İlkokulu',
    'AĞRI - MERKEZ - Yukarı Pamuktaş İlkokulu',
    'AĞRI - MERKEZ - Uzunveli İlkokulu',
    'AĞRI - MERKEZ - Kayabey İlkokulu',
    'AĞRI - MERKEZ - Çukurçayır İlkokulu',
    'AĞRI - MERKEZ - Murathan İlkokulu',
    'AĞRI - MERKEZ - Şehit Korgeneral İsmail Selen İlkokulu',
    'AĞRI - MERKEZ - Şehit Korgeneral İsmail Selen Ortaokulu',
    'AĞRI - MERKEZ - Çukuralan Ortaokulu',
    'AĞRI - MERKEZ - Eskiharman İlkokulu',
    'AĞRI - MERKEZ - Eskiharman Ortaokulu',
    'AĞRI - MERKEZ - Eğribelen İlkokulu',
    'AĞRI - MERKEZ - Selçuk Ortaokulu',
    'AĞRI - MERKEZ - Gümüşyazı İlkokulu',
    'AĞRI - MERKEZ - Yazılı İlkokulu',
    'AĞRI - MERKEZ - Söğütlü İlkokulu',
    'AĞRI - MERKEZ - Aşağı Pamuktaş İlkokulu',
    'AĞRI - MERKEZ - Başkent İlkokulu',
    'AĞRI - MERKEZ - Esen İlkokulu',
    'AĞRI - MERKEZ - Akbulgur İlkokulu',
    'AĞRI - MERKEZ - Şehit Er Vefa Çelik Ortaokulu',
    'AĞRI - MERKEZ - Badilli İlkokulu',
    'AĞRI - MERKEZ - Ballıbostan İlkokulu',
    'AĞRI - MERKEZ - Eliaçık Ortaokulu',
    'AĞRI - MERKEZ - Kasım Bayram Ortaokulu',
    'AĞRI - MERKEZ - Dedemaksut İlkokulu',
    'AĞRI - MERKEZ - Aslangazi Ortaokulu',
    'AĞRI - MERKEZ - Boztoprak Ali Yorulmaz İlkokulu',
    'AĞRI - MERKEZ - Sarıdoğan İlkokulu',
    'AĞRI - MERKEZ - Baloluk İsmet Bulut Ortaokulu',
    'AĞRI - MERKEZ - Karasu Ortaokulu',
    'AĞRI - MERKEZ - Cumhuriyet Ortaokulu',
    'AĞRI - MERKEZ - Çamurlu İlkokulu',
    'AĞRI - MERKEZ - Sevimli Anaokulu',
    'AĞRI - MERKEZ - Ortayokuş İlkokulu',
    'AĞRI - MERKEZ - Yalnızkonak İlkokulu',
    'AĞRI - MERKEZ - Öğretmenevi ve Akşam Sanat Okulu',
    'AĞRI - MERKEZ - 23 Nisan Anaokulu',
    'AĞRI - MERKEZ - Kavak İlkokulu',
    'AĞRI - MERKEZ - Kumlugeçit Genç Demokratlar Derneği İlkokulu',
    'AĞRI - MERKEZ - Oğlaklı 1. Boğaziçi İlkokulu',
    'AĞRI - MERKEZ - Anakaya İlkokulu',
    'AĞRI - MERKEZ - Doğutepe İlkokulu',
    'AĞRI - MERKEZ - Yukarı Saklıca İlkokulu',
    'AĞRI - MERKEZ - Geçitalan İlkokulu',
    'AĞRI - MERKEZ - Dönerdere İlkokulu',
    'AĞRI - MERKEZ - Uçarkaya İlkokulu',
    'AĞRI - MERKEZ - Beşbulak İlkokulu',
    'AĞRI - MERKEZ - Tezeren 4. Boğaziçi Ortaokulu',
    'AĞRI - MERKEZ - Tezeren 4. Boğaziçi İlkokulu',
    'AĞRI - MERKEZ - Yazıcı İlkokulu',
    'AĞRI - MERKEZ - Kazlı İlkokulu',
    'AĞRI - MERKEZ - Taştekne Şehit Polis Yalçın Demir İlkokulu',
    'AĞRI - MERKEZ - Taştekne Şehit Polis Yalçın Demir Ortaokulu',
    'AĞRI - MERKEZ - Güvendik İlkokulu',
    'AĞRI - MERKEZ - Aşağı Saklıca İlkokulu',
    'AĞRI - MERKEZ - Aşağı Dormeli İlkokulu',
    'AĞRI - MERKEZ - Aşağı Yoldüzü İlkokulu',
    'AĞRI - MERKEZ - Yurtpınar İlkokulu',
    'AĞRI - MERKEZ - Ağrı Rehberlik ve Araştırma Merkezi',
    'AĞRI - MERKEZ - Özveren İlkokulu',
    'AĞRI - MERKEZ - Arakonak İlkokulu',
    'AĞRI - MERKEZ - RAMİZ ERDEM İLKOKULU',
    'AĞRI - MERKEZ - Kardelen Anaokulu',
    'AĞRI - MERKEZ - Selahaddin Eyyubi İlkokulu',
    'AĞRI - MERKEZ - İMKB GAZİ İLKOKULU',
    'AĞRI - MERKEZ - Erol Parlak Güzel Sanatlar Lisesi',
    'AĞRI - MERKEZ - Ağrı Spor Lisesi',
    'AĞRI - MERKEZ - PİRİ REİS ORTAOKULU',
    'AĞRI - MERKEZ - AHMETBEY İLKOKULU',
    'AĞRI - MERKEZ - Yunus Emre İlkokulu',
    'AĞRI - MERKEZ - KARABOĞA İLKOKULU',
    'AĞRI - MERKEZ - Mehmet Akif Ersoy Ortaokulu',
    'AĞRI - MERKEZ - BOZTOPRAK ALİ YORULMAZ ORTAOKULU',
    'AĞRI - MERKEZ - Necip Fazıl Kısakürek Anadolu İmam Hatip Lisesi',
    'AĞRI - MERKEZ - Ağrı Özel Eğitim Uygulama Okulu I. Kademe',
    'AĞRI - MERKEZ - Vali Recep Yazıcıoğlu Ortaokulu',
    'AĞRI - MERKEZ - SOMA 13 MAYIS MADENCİLERİ İLKOKULU',
    'AĞRI - MERKEZ - SELAHADDİN EYYUBİ ORTAOKULU',
    'AĞRI - MERKEZ - YILMAZ HATUNOĞLU ANADOLU LİSESİ',
    'AĞRI - MERKEZ - MUHAMMED CELALİ İMAM HATİP ORTAOKULU',
    'AĞRI - MERKEZ - AĞRI BİLİM VE SANAT MERKEZİ',
    'AĞRI - MERKEZ - ŞEREF SARAÇOĞLU İLKOKULU',
    'AĞRI - MERKEZ - AKŞEMSETTİN İLKOKULU',
    'AĞRI - MERKEZ - AKŞEMSETTİN ORTAOKULU',
    'AĞRI - MERKEZ - Şinasi Ünsal Kız Anadolu İmam Hatip Lisesi',
    'AĞRI - MERKEZ - ŞEHİT POLİS YALÇIN DEMİR ANAOKULU',
    'AĞRI - MERKEZ - SERHAT İLKOKULU',
    'AĞRI - MERKEZ - HAYRETTİN ATMACA KIZ ANADOLU İMAM HATİP LİSESİ',
    'AĞRI - MERKEZ - TURGUT ÖZAL İMAM HATİP ORTAOKULU',
    'AĞRI - MERKEZ - Yukarı Yolduzu İlkokulu',
    'AĞRI - MERKEZ - YAVUZ SELİM ORTAOKULU',
    'AĞRI - MERKEZ - Çatalipaşa 3. Boğaziçi İlkokulu',
    'AĞRI - MERKEZ - Ozanlar İlkokulu',
    'AĞRI - MERKEZ - Sabuncu İlkokulu',
    'AĞRI - MERKEZ - Ağrı Özel Eğitim Meslek Okulu',
    'AĞRI - MERKEZ - Ağrı Özel Eğitim Uygulama Okulu II. Kademe',
    'AĞRI - MERKEZ - Ağrı Özel Eğitim Uygulama Okulu III. Kademe',
    'AĞRI - MERKEZ - Aşağı Kent İlkokulu',
    'AĞRI - MERKEZ - Tekstil Kent Anaokulu',
    'AĞRI - MERKEZ - Şerife Bacı Anadolu Lisesi',
    'AĞRI - MERKEZ - Ağrı Burçin Uysal Öğretmenevi ve Akşam Sanat Okulu',
    'AĞRI - MERKEZ - Ağrı Özel Eğitim Anaokulu',
    'AĞRI - MERKEZ - Gökkuşağı Anaokulu',
    'AĞRI - MERKEZ - TOBB Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - MERKEZ - Ortakent İlkokulu',
    'AĞRI - MERKEZ - Güneysu İlkokulu',
    'AĞRI - MERKEZ - Mehmet Metin Tekdal İlkokulu',
    'AĞRI - MERKEZ - Mustafa Tekdal Ortaokulu',
    'AĞRI - MERKEZ - Fatma Hamit İlidi İlkokulu',
    'AĞRI - MERKEZ - Şehit Er Vefa Çelik İlkokulu',
    'AĞRI - MERKEZ - Önder Baydar İmam Hatip Ortaokulu',
    'AĞRI - MERKEZ - Bilsem Anaokulu',
    'AĞRI - MERKEZ - Önder Baydar İlkokulu',
    'AĞRI - MERKEZ - Hanoba İlkokulu',
    'AĞRI - MERKEZ - 15 Nisan Anaokulu',
    'AĞRI - MERKEZ - Şehit Uzman Çavuş Tuncer Doğan Anaokulu',
    'AĞRI - MERKEZ - Fatih Sultan Mehmet Anaokulu',
    'AĞRI - MERKEZ - Mehmet Şerafettin Yaltkaya Anaokulu',
    'AĞRI - MERKEZ - Şehit Er Vefa Çelik Anaokulu',
    'AĞRI - MERKEZ - Selahaddin Eyyubi Anaokulu',
    'AĞRI - MERKEZ - İbrahim Çeçen Anaokulu',
    'AĞRI - MERKEZ - Soma 13 Mayıs Madencileri Anaokulu',
    'AĞRI - MERKEZ - Kaymakam Özgür Azer Kurak Özel Eğitim Anaokulu',
    'AĞRI - MERKEZ - Sarıca İlkokulu',
    'AĞRI - MERKEZ - Balkaynak İlkokulu',
    'AĞRI - PATNOS - 125.Yıl Anaokulu',
    'AĞRI - PATNOS - 14 Nisan İlkokulu',
    'AĞRI - PATNOS - Akdilek Sebahattin Yıldız İlkokulu',
    'AĞRI - PATNOS - Akdilek Sebahattin Yıldız Ortaokulu',
    'AĞRI - PATNOS - Çavuş İlkokulu',
    'AĞRI - PATNOS - Doğansu İlkokulu',
    'AĞRI - PATNOS - Doğansu Kız Yatılı Bölge Ortaokulu',
    'AĞRI - PATNOS - Eskikonak Sebahattin Yıldız Ortaokulu',
    'AĞRI - PATNOS - Karatoklu İlkokulu',
    'AĞRI - PATNOS - Kazanbey İlkokulu',
    'AĞRI - PATNOS - Kazanbey Ortaokulu',
    'AĞRI - PATNOS - Patnos Fatih Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - PATNOS - Kızkapan İlkokulu',
    'AĞRI - PATNOS - Patnos Alparslan Anadolu Lisesi',
    'AĞRI - PATNOS - 15 Temmuz Şehitleri Anadolu İmam Hatip Lisesi',
    'AĞRI - PATNOS - Patnos Anadolu Lisesi',
    'AĞRI - PATNOS - İbn - i Sina Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - PATNOS - Patnos Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - PATNOS - Adnan Menderes Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - PATNOS - Sütlüpınar İlkokulu',
    'AĞRI - PATNOS - Taşkın İlkokulu',
    'AĞRI - PATNOS - Tepeli İlkokulu',
    'AĞRI - PATNOS - Yatılı Bölge Ortaokulu',
    'AĞRI - PATNOS - Taşkın Ortaokulu',
    'AĞRI - PATNOS - Yukarı Göçmez Cumhuriyet İlkokulu',
    'AĞRI - PATNOS - Dedeli Sebahattin Yıldız İlkokulu',
    'AĞRI - PATNOS - Kiptaş Ortaokulu',
    'AĞRI - PATNOS - Bozoğlak İlkokulu',
    'AĞRI - PATNOS - Dedeli Sebahattin Yıldız Ortaokulu',
    'AĞRI - PATNOS - Tanyeli İlkokulu',
    'AĞRI - PATNOS - Cumhuriyet Ortaokulu',
    'AĞRI - PATNOS - Atatürk Ortaokulu',
    'AĞRI - PATNOS - Atatürk İlkokulu',
    'AĞRI - PATNOS - Eskikonak Sebahattin Yıldız İlkokulu',
    'AĞRI - PATNOS - Tes-İş İlkokulu',
    'AĞRI - PATNOS - Tes-İş Ortaokulu',
    'AĞRI - PATNOS - Aşağı Kamışlı İlkokulu',
    'AĞRI - PATNOS - Kürekli İlkokulu',
    'AĞRI - PATNOS - Ertuğrul Gazi Ortaokulu',
    'AĞRI - PATNOS - Yukarı Damla İlkokulu',
    'AĞRI - PATNOS - Gökçeali İlkokulu',
    'AĞRI - PATNOS - Patnos Çortali Zeki Keşan İlkokulu',
    'AĞRI - PATNOS - Sağrıca İlkokulu',
    'AĞRI - PATNOS - Ortadamla Ortaokulu',
    'AĞRI - PATNOS - Cumhuriyet İlkokulu',
    'AĞRI - PATNOS - Çavuş Gürcübulak İlkokulu',
    'AĞRI - PATNOS - Konakbey İlkokulu',
    'AĞRI - PATNOS - Özdemir İlkokulu',
    'AĞRI - PATNOS - Suluca İlkokulu',
    'AĞRI - PATNOS - Ertuğrul Gazi İlkokulu',
    'AĞRI - PATNOS - Özdemir Ortaokulu',
    'AĞRI - PATNOS - Ergençli Mecnun Gölü İlkokulu',
    'AĞRI - PATNOS - Ürküt İlkokulu',
    'AĞRI - PATNOS - Ürküt Ortaokulu',
    'AĞRI - PATNOS - Gençali İlkokulu',
    'AĞRI - PATNOS - Ortadamla İlkokulu',
    'AĞRI - PATNOS - Patnos İMKB Ortaokulu',
    'AĞRI - PATNOS - Tepeli Ortaokulu',
    'AĞRI - PATNOS - Tanyeli Ortaokulu',
    'AĞRI - PATNOS - Zirekli Ortaokulu',
    'AĞRI - PATNOS - Zirekli İlkokulu',
    'AĞRI - PATNOS - Bozoğlak Arpacık İlkokulu',
    'AĞRI - PATNOS - Dağalan Bağbaşı İlkokulu',
    'AĞRI - PATNOS - Uzunca İlkokulu',
    'AĞRI - PATNOS - Çakırbey İlkokulu',
    'AĞRI - PATNOS - Çakırbey Ortaokulu',
    'AĞRI - PATNOS - İbrahim Karaoğlanoğlu İlkokulu',
    'AĞRI - PATNOS - Dedeli Yatılı Bölge Ortaokulu',
    'AĞRI - PATNOS - Konakbey Ortaokulu',
    'AĞRI - PATNOS - Güllüce İlkokulu',
    'AĞRI - PATNOS - Kuşkaya İlkokulu',
    'AĞRI - PATNOS - Kuşkaya Ortaokulu',
    'AĞRI - PATNOS - Patnos İMKB İlkokulu',
    'AĞRI - PATNOS - Patnos Mesleki Eğitim Merkezi',
    'AĞRI - PATNOS - Koçaklar İlkokulu',
    'AĞRI - PATNOS - Andaçlı Ortaokulu',
    'AĞRI - PATNOS - Yukarı Kamışlı İlkokulu',
    'AĞRI - PATNOS - 75.Yıl İlkokulu',
    'AĞRI - PATNOS - Yunus Emre İlkokulu',
    'AĞRI - PATNOS - Aşağı Göçmez İlkokulu',
    'AĞRI - PATNOS - Kızıltepe İlkokulu',
    'AĞRI - PATNOS - Çavuş Ortaokulu',
    'AĞRI - PATNOS - Susuz İlkokulu',
    'AĞRI - PATNOS - Yunus Emre Ortaokulu',
    'AĞRI - PATNOS - Süphan İlkokulu',
    'AĞRI - PATNOS - Andaçlı İlkokulu',
    'AĞRI - PATNOS - Budak İlkokulu',
    'AĞRI - PATNOS - Gönlüaçık Karabulak İlkokulu',
    'AĞRI - PATNOS - Bozoğlak Çavuşlu İlkokulu',
    'AĞRI - PATNOS - Kuruyaka İlkokulu',
    'AĞRI - PATNOS - Gençali Ortaokulu',
    'AĞRI - PATNOS - Karbasan Balcılar İlkokulu',
    'AĞRI - PATNOS - Örendik İlkokulu',
    'AĞRI - PATNOS - Yeşil Hisar İlkokulu',
    'AĞRI - PATNOS - Kerem Şahin İlkokulu',
    'AĞRI - PATNOS - Kerem Şahin Ortaokulu',
    'AĞRI - PATNOS - Demirören İlkokulu',
    'AĞRI - PATNOS - Çukurbağ İlkokulu',
    'AĞRI - PATNOS - Çaputlu Ortaokulu',
    'AĞRI - PATNOS - Sütlüpınar Ortaokulu',
    'AĞRI - PATNOS - Zincirkale İlkokulu',
    'AĞRI - PATNOS - Gönlüaçık İlkokulu',
    'AĞRI - PATNOS - Çukurbağ Ortaokulu',
    'AĞRI - PATNOS - Yurtöven İlkokulu',
    'AĞRI - PATNOS - Akçaören İlkokulu',
    'AĞRI - PATNOS - Derecik İlkokulu',
    'AĞRI - PATNOS - Çaputlu İlkokulu',
    'AĞRI - PATNOS - Bozoğlak Ortaokulu',
    'AĞRI - PATNOS - Edremit İlkokulu',
    'AĞRI - PATNOS - Oyacık Bağdışan İlkokulu',
    'AĞRI - PATNOS - Molla İbrahim İlkokulu',
    'AĞRI - PATNOS - Günbeli İlkokulu',
    'AĞRI - PATNOS - Yeşilova İlkokulu',
    'AĞRI - PATNOS - Usluca İlkokulu',
    'AĞRI - PATNOS - Patnos Halk Eğitimi Merkezi',
    'AĞRI - PATNOS - Güvercinli İlkokulu',
    'AĞRI - PATNOS - Süphandağı Anadolu Lisesi',
    'AĞRI - PATNOS - Değirmendüzü Ortaokulu',
    'AĞRI - PATNOS - Değirmendüzü İlkokulu',
    'AĞRI - PATNOS - Gökoğlu İlkokulu',
    'AĞRI - PATNOS - Yukarı Kulecik İlkokulu',
    'AĞRI - PATNOS - Alatay Ortaokulu',
    'AĞRI - PATNOS - Alatay İlkokulu',
    'AĞRI - PATNOS - Yalçınkaya İlkokulu',
    'AĞRI - PATNOS - Yalçınkaya Ortaokulu',
    'AĞRI - PATNOS - Dağalan Bağbaşı Ortaokulu',
    'AĞRI - PATNOS - Gazi Anaokulu',
    'AĞRI - PATNOS - Pirömer Sebahattin Yıldız Ortaokulu',
    'AĞRI - PATNOS - Pirömer Sebahattin Yıldız İlkokulu',
    'AĞRI - PATNOS - Karçiçeği Anaokulu',
    'AĞRI - PATNOS - Ergençli İlkokulu',
    'AĞRI - PATNOS - Ergençli Ortaokulu',
    'AĞRI - PATNOS - Süphan Ortaokulu',
    'AĞRI - PATNOS - Aktepe Yatılı Bölge Ortaokulu',
    'AĞRI - PATNOS - Cengiz Topel İlkokulu',
    'AĞRI - PATNOS - Uzungün Hanife İlkokulu',
    'AĞRI - PATNOS - Patnos Rehberlik ve Araştırma Merkezi',
    'AĞRI - PATNOS - Öğretmen Evi ve Akşam Sanat Okulu',
    'AĞRI - PATNOS - Dizginkale İlkokulu',
    'AĞRI - PATNOS - Koçaklar Ortaokulu',
    'AĞRI - PATNOS - Doğansu Ortaokulu',
    'AĞRI - PATNOS - Yürekveren İlkokulu',
    'AĞRI - PATNOS - Baba Ocağı Anaokulu',
    'AĞRI - PATNOS - Yukarı Göçmez İlkokulu',
    'AĞRI - PATNOS - Yukarı Göçmez Ortaokulu',
    'AĞRI - PATNOS - Sarıdibek İlkokulu',
    'AĞRI - PATNOS - Yalçınkaya Cumhuriyet İlkokulu',
    'AĞRI - PATNOS - Hacılar İlkokulu',
    'AĞRI - PATNOS - Yürekveren Ortaokulu',
    'AĞRI - PATNOS - Şehit Kaymakam Muhammed Fatih Safitürk Ortaokulu',
    'AĞRI - PATNOS - Çamurlu İlkokulu',
    'AĞRI - PATNOS - Köseler Adilova İlkokulu',
    'AĞRI - PATNOS - 75. Yıl Ortaokulu',
    'AĞRI - PATNOS - Tozlubulan İlkokulu',
    'AĞRI - PATNOS - Düzceli İlkokulu',
    'AĞRI - PATNOS - Meydandağı İlkokulu',
    'AĞRI - PATNOS - Demirören Ortaokulu',
    'AĞRI - PATNOS - Akdilek Cumhuriyet İlkokulu',
    'AĞRI - PATNOS - Akdilek Bahçeli İlkokulu',
    'AĞRI - PATNOS - Aladağ İlkokulu',
    'AĞRI - PATNOS - Suluca Ortaokulu',
    'AĞRI - PATNOS - Selahaddin Eyyubi İlkokulu',
    'AĞRI - PATNOS - DEDELİ ÜZÜMLÜ İLKOKULU',
    'AĞRI - PATNOS - PATNOS SELAHADDİN EYYUBİ FEN LİSESİ',
    'AĞRI - PATNOS - YUKARI DAMLA ORTAOKULU',
    'AĞRI - PATNOS - GÖKOĞLU ORTAOKULU',
    'AĞRI - PATNOS - PATNOS ÖZEL EĞİTİM UYGULAMA MERKEZİ II. KADEME',
    'AĞRI - PATNOS - CENGİZ ÇIKRIK ORTAOKULU',
    'AĞRI - PATNOS - CENGİZ ÇIKRIK İLKOKULU',
    'AĞRI - PATNOS - Patnos Özel Eğitim Uygulama Okulu I. Kademe',
    'AĞRI - PATNOS - Selahaddin Eyyubi Ortaokulu',
    'AĞRI - PATNOS - Nadir Bayar Ortaokulu',
    'AĞRI - PATNOS - Değirmendüzü İmam Hatip Ortaokulu',
    'AĞRI - PATNOS - SÜTLÜPINAR İMAM HATİP ORTAOKULU',
    'AĞRI - PATNOS - KEREM ŞAHİN İMAM HATİP ORTAOKULU',
    'AĞRI - PATNOS - ŞEHİT ASTSUBAY EMRAH ÇELEBİ İLKOKULU',
    'AĞRI - PATNOS - Şehit Polis Taha Yasin Biçer İmam Hatip Ortaokulu',
    'AĞRI - PATNOS - ÖZDEMİR İMAM HATİP ORTAOKULU',
    'AĞRI - PATNOS - Kaş İlkokulu',
    'AĞRI - PATNOS - Karbasan İlkokulu',
    'AĞRI - PATNOS - Armutlu İlkokulu',
    'AĞRI - PATNOS - Karbasan Derekomu İlkokulu',
    'AĞRI - PATNOS - Aktepe İlkokulu',
    'AĞRI - PATNOS - Çatmaoluk İlkokulu',
    'AĞRI - PATNOS - Hasandolu İlkokulu',
    'AĞRI - PATNOS - Kartanesi Anaokulu',
    'AĞRI - PATNOS - Dedeli İmam Hatip Ortaokulu',
    'AĞRI - PATNOS - Zirekli İmam Hatip Ortaokulu',
    'AĞRI - PATNOS - Aktepe İmam Hatip Ortaokulu',
    'AĞRI - PATNOS - Ergençli Yılanlı İlkokulu',
    'AĞRI - PATNOS - Budak Ortaokulu',
    'AĞRI - PATNOS - Patnos Özel Eğitim Uygulama Okulu III. Kademe',
    'AĞRI - PATNOS - Mimar Sinan Anadolu Lisesi',
    'AĞRI - PATNOS - Dedeli Cumhuriyet İlkokulu',
    'AĞRI - PATNOS - 14 Nisan Ortaokulu',
    'AĞRI - PATNOS - Kucak İlkokulu',
    'AĞRI - PATNOS - Prof. Dr. Fuat Sezgin Anadolu Lisesi',
    'AĞRI - PATNOS - Bahri Ergenç İlkokulu',
    'AĞRI - PATNOS - Mehmet Akif Ersoy Ortaokulu',
    'AĞRI - PATNOS - Mehmet Akif Ersoy İlkokulu',
    'AĞRI - PATNOS - Patnos Bilim ve Sanat Merkezi',
    'AĞRI - PATNOS - Şehit Polis Taha Yasin Biçer Kız Anadolu İmam Hatip Lisesi',
    'AĞRI - PATNOS - Süphan Anaokulu',
    'AĞRI - PATNOS - Cengiz Topel Anaokulu',
    'AĞRI - PATNOS - Esenbel İlkokulu',
    'AĞRI - PATNOS - Keçelbaba İlkokulu',
    'AĞRI - PATNOS - Yüncüler İlkokulu',
    'AĞRI - TAŞLIÇAY - Düzgören İlkokulu',
    'AĞRI - TAŞLIÇAY - Bayıraltı İlkokulu',
    'AĞRI - TAŞLIÇAY - Gözucu İlkokulu',
    'AĞRI - TAŞLIÇAY - Taşlıçay Halk Eğitimi Merkezi',
    'AĞRI - TAŞLIÇAY - İkiyamaç İlkokulu',
    'AĞRI - TAŞLIÇAY - Kır Çiçekleri Anaokulu',
    'AĞRI - TAŞLIÇAY - Mehmet Akif Ersoy İlkokulu',
    'AĞRI - TAŞLIÇAY - Taşlıçay Anadolu Lisesi',
    'AĞRI - TAŞLIÇAY - Yardımcılar İlkokulu',
    'AĞRI - TAŞLIÇAY - Yavuz Selim Ortaokulu',
    'AĞRI - TAŞLIÇAY - Taşlıçay Yatılı Bölge Ortaokulu',
    'AĞRI - TAŞLIÇAY - Atatürk Ortaokulu',
    'AĞRI - TAŞLIÇAY - Geçitveren İlkokulu',
    'AĞRI - TAŞLIÇAY - Geçitveren Ortaokulu',
    'AĞRI - TAŞLIÇAY - Aşağı Esen İlkokulu',
    'AĞRI - TAŞLIÇAY - Yukarı Dumanlı İlkokulu',
    'AĞRI - TAŞLIÇAY - Taşlıçay İmam Hatip Ortaokulu',
    'AĞRI - TAŞLIÇAY - Taşlıçay Anadolu İmam Hatip Lisesi',
    'AĞRI - TAŞLIÇAY - Yardımcılar Ortaokulu',
    'AĞRI - TAŞLIÇAY - Çöğürlü İlkokulu',
    'AĞRI - TAŞLIÇAY - Şehit Er Mehmet Salih Bora İlkokulu',
    'AĞRI - TAŞLIÇAY - Şehit Uzman Çavuş Hüseyin Kaya İlkokulu',
    'AĞRI - TAŞLIÇAY - Çökelge İlkokulu',
    'AĞRI - TAŞLIÇAY - Yassıkaya İlkokulu',
    'AĞRI - TAŞLIÇAY - Aşağı Dumanlı Ortaokulu',
    'AĞRI - TAŞLIÇAY - Aşağı Dumanlı İlkokulu',
    'AĞRI - TAŞLIÇAY - Gözucu Satıkomu İlkokulu',
    'AĞRI - TAŞLIÇAY - Şehit Uzman Çavuş Hüseyin Kaya Ortaokulu',
    'AĞRI - TAŞLIÇAY - Aşağı Toklu İlkokulu',
    'AĞRI - TAŞLIÇAY - Alakoçlu İlkokulu',
    'AĞRI - TAŞLIÇAY - Yukarı Esen İlkokulu',
    'AĞRI - TAŞLIÇAY - Yukarı Esen Ortaokulu',
    'AĞRI - TAŞLIÇAY - Kumlubucak İlkokulu',
    'AĞRI - TAŞLIÇAY - Yeltepe İlkokulu',
    'AĞRI - TAŞLIÇAY - Şehit Er Bülent Afşin İlkokulu',
    'AĞRI - TAŞLIÇAY - Bayramyazı İlkokulu',
    'AĞRI - TAŞLIÇAY - Yukarı Düzmeydan İlkokulu',
    'AĞRI - TAŞLIÇAY - Aras İlkokulu',
    'AĞRI - TAŞLIÇAY - Aşağı Düzmeydan İlkokulu',
    'AĞRI - TAŞLIÇAY - Güneysöğüt İlkokulu',
    'AĞRI - TAŞLIÇAY - Karagöz İlkokulu',
    'AĞRI - TAŞLIÇAY - Tanrıverdi İlkokulu',
    'AĞRI - TAŞLIÇAY - Şehit Er Kemal Ayhan İlkokulu',
    'AĞRI - TAŞLIÇAY - Dilekyazı İlkokulu',
    'AĞRI - TAŞLIÇAY - Yeltepe Gümüşlü İlkokulu',
    'AĞRI - TAŞLIÇAY - Kumluca Anaokulu',
    'AĞRI - TAŞLIÇAY - BALIK GÖLÜ İLKOKULU',
    'AĞRI - TAŞLIÇAY - ÖĞRETMEN EVİ VE AKŞAM SANAT OKULU',
    'AĞRI - TAŞLIÇAY - DÜZGÖREN ORTAOKULU',
    'AĞRI - TAŞLIÇAY - SELAHADDİN EYYUBİ ORTAOKULU',
    'AĞRI - TAŞLIÇAY - TAŞLIÇAY İLKOKULU',
    'AĞRI - TAŞLIÇAY - ALAKOÇLU ORTAOKULU',
    'AĞRI - TAŞLIÇAY - Şehit Er Osman Koç İlkokulu',
    'AĞRI - TAŞLIÇAY - Selahaddin Eyyubi İlkokulu',
    'AĞRI - TAŞLIÇAY - Çöğürlü Ortaokulu',
    'AĞRI - TAŞLIÇAY - Nurali Turan Ortaokulu',
    'AĞRI - TAŞLIÇAY - Fatma Turan İlkokulu',
    'AĞRI - TAŞLIÇAY - Yanalyol İlkokulu',
    'AĞRI - TAŞLIÇAY - Kumluca Yeniköy İlkokulu',
    'AĞRI - TAŞLIÇAY - Gündoğdu İlkokulu',
    'AĞRI - TAŞLIÇAY - Kağnılı İlkokulu',
    'AĞRI - TAŞLIÇAY - Samanyolu İlkokulu',
    'AĞRI - TAŞLIÇAY - Yukarı Düzmeydan Ortaokulu',
    'AĞRI - TUTAK - Erdal İlkokulu',
    'AĞRI - TUTAK - Fatih Sultan Mehmet İlkokulu',
    'AĞRI - TUTAK - Tutak Anadolu İmam Hatip Lisesi',
    'AĞRI - TUTAK - Öğretmen Evi ve Akşam Sanat Okulu',
    'AĞRI - TUTAK - Mehmet Şükrü Balcı Anadolu Lisesi',
    'AĞRI - TUTAK - Tutak Çok Programlı Anadolu Lisesi',
    'AĞRI - TUTAK - Burnubulak İlkokulu',
    'AĞRI - TUTAK - Çukurkonak İlkokulu',
    'AĞRI - TUTAK - Hürriyet İlkokulu',
    'AĞRI - TUTAK - 14 Nisan Ortaokulu',
    'AĞRI - TUTAK - Bayındır İlkokulu',
    'AĞRI - TUTAK - Suvar İlkokulu',
    'AĞRI - TUTAK - Karaağaç İlkokulu',
    'AĞRI - TUTAK - Erdal Ortaokulu',
    'AĞRI - TUTAK - Oğlaksuyu Ortaokulu',
    'AĞRI - TUTAK - Oğlaksuyu İlkokulu',
    'AĞRI - TUTAK - Adakent İlkokulu',
    'AĞRI - TUTAK - Ozanpınar İlkokulu',
    'AĞRI - TUTAK - Taşbudak İlkokulu',
    'AĞRI - TUTAK - Şehit Uzman Ömer Güç Ortaokulu',
    'AĞRI - TUTAK - Kazım Karabekir Ortaokulu',
    'AĞRI - TUTAK - Gülçimen İlkokulu',
    'AĞRI - TUTAK - Dönertaş İlkokulu',
    'AĞRI - TUTAK - Ortayamaç İlkokulu',
    'AĞRI - TUTAK - Atabindi İlkokulu',
    'AĞRI - TUTAK - Yukarı Karahalit İlkokulu',
    'AĞRI - TUTAK - Şehit Adem Tunç İlkokulu',
    'AĞRI - TUTAK - Karacan İlkokulu',
    'AĞRI - TUTAK - Çobanoba İlkokulu',
    'AĞRI - TUTAK - Hacıyusuf İlkokulu',
    'AĞRI - TUTAK - Uzunöz İlkokulu',
    'AĞRI - TUTAK - Sorguçlu İlkokulu',
    'AĞRI - TUTAK - Geçimli İlkokulu',
    'AĞRI - TUTAK - Aşağı Karahalit İlkokulu',
    'AĞRI - TUTAK - Şehit Piyade Komando Er Lütfi Şenlik İlkokulu',
    'AĞRI - TUTAK - Aşağı Kulecik İlkokulu',
    'AĞRI - TUTAK - Adalet İlkokulu',
    'AĞRI - TUTAK - Yeniköy İlkokulu',
    'AĞRI - TUTAK - Yayıklı İlkokulu',
    'AĞRI - TUTAK - Sincan İlkokulu',
    'AĞRI - TUTAK - Yatılı Bölge Ortaokulu',
    'AĞRI - TUTAK - Yukarı Köşk İlkokulu',
    'AĞRI - TUTAK - Karaağaç Ortaokulu',
    'AĞRI - TUTAK - Dorukdibi İlkokulu',
    'AĞRI - TUTAK - Karahan İlkokulu',
    'AĞRI - TUTAK - Tutak Halk Eğitimi Merkezi',
    'AĞRI - TUTAK - Otluca İlkokulu',
    'AĞRI - TUTAK - Mızrak İlkokulu',
    'AĞRI - TUTAK - Bintosun İlkokulu',
    'AĞRI - TUTAK - Bolaşlı İlkokulu',
    'AĞRI - TUTAK - Karacan Ortaokulu',
    'AĞRI - TUTAK - Burnubulak Ortaokulu',
    'AĞRI - TUTAK - Dayıpınar İlkokulu',
    'AĞRI - TUTAK - Gazi İlkokulu',
    'AĞRI - TUTAK - Dikme İlkokulu',
    'AĞRI - TUTAK - Daldalık İlkokulu',
    'AĞRI - TUTAK - Dağlıca İlkokulu',
    'AĞRI - TUTAK - Çırpılı Ortaokulu',
    'AĞRI - TUTAK - Dikbıyık İlkokulu',
    'AĞRI - TUTAK - Dikbıyık Ortaokulu',
    'AĞRI - TUTAK - SARIGÖZE İLKOKULU',
    'AĞRI - TUTAK - BOZKAŞ İLKOKULU',
    'AĞRI - TUTAK - DAMLAKAYA İLKOKULU',
    'AĞRI - TUTAK - HACIYUSUF ORTAOKULU',
    'AĞRI - TUTAK - AŞAĞI KARGALIK İLKOKULU',
    'AĞRI - TUTAK - SOĞUKPINAR İLKOKULU',
    'AĞRI - TUTAK - SOĞUKPINAR ORTAOKULU',
    'AĞRI - TUTAK - AKYELE İLKOKULU',
    'AĞRI - TUTAK - Esmer İlkokulu',
    'AĞRI - TUTAK - Döşkaya İlkokulu',
    'AĞRI - TUTAK - SULTAN ALPARSLAN ORTAOKULU',
    'AĞRI - TUTAK - SULTAN MELİKŞAH İLKOKULU',
    'AĞRI - TUTAK - ŞEHİT PİYADE ER AYDIN ÇETİN İLKOKULU',
    'AĞRI - TUTAK - İPEKKUŞAK İLKOKULU',
    'AĞRI - TUTAK - PALANDÖKEN İLKOKULU',
    'AĞRI - TUTAK - Batmış İlkokulu',
    'AĞRI - TUTAK - Güneşgören İlkokulu',
    'AĞRI - TUTAK - Tutak Mesleki ve Teknik Anadolu Lisesi',
    'AĞRI - TUTAK - Palandöken Köyü Aksu Mezrası İlkokulu',
    'AĞRI - TUTAK - Ekincek İlkokulu',
    'AĞRI - TUTAK - Tutak İmam Hatip Ortaokulu',
    'AĞRI - TUTAK - Aşağı Köşk Ortaokulu',
    'AĞRI - TUTAK - Çırpılı İlkokulu',
    'AĞRI - TUTAK - Öndül İlkokulu',
    'AĞRI - TUTAK - Esat Demir İlkokulu',
    'AĞRI - TUTAK - Bintosun Ortaokulu',
    'AĞRI - TUTAK - Minik Kalpler Anaokulu',
    'AĞRI - TUTAK - Raif Ateş Sönmez İlkokulu',
    'AĞRI - TUTAK - Tutak Anadolu Lisesi',
    'AĞRI - TUTAK - Kaşönü İlkokulu',
    'AĞRI - TUTAK - Bişi İlkokulu',
    'AĞRI - TUTAK - Kılıçgediği İlkokulu',
    'AĞRI - TUTAK - Gültepe İlkokulu',
    'AĞRI - TUTAK - Karacan Kuşkaya İlkokulu',
    'AĞRI - TUTAK - Dibelek İlkokulu',
    'AĞRI - TUTAK - Yukarı Özdek İlkokulu',
  ];

  List<String> get list=>_list;

}

