class AmasyaSchools{
  final List<String> list=[
  'AMASYA - GÖYNÜCEK - Atatürk İlkokulu',
  'AMASYA - GÖYNÜCEK - Gediksaray Şehit Satılmış Salatacı İlkokulu',
  'AMASYA - GÖYNÜCEK - Göynücek 70. Yıl Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - GÖYNÜCEK - Şehit Erkan Karaçoban Çok Programlı Anadolu Lisesi',
  'AMASYA - GÖYNÜCEK - Göynücek Halk Eğitimi Merkezi',
  'AMASYA - GÖYNÜCEK - Atatürk Ortaokulu',
  'AMASYA - GÖYNÜCEK - Karaşar İlkokulu',
  'AMASYA - GÖYNÜCEK - Karaşar Ortaokulu',
  'AMASYA - GÖYNÜCEK - Şehit Lokman Cansız İlkokulu',
  'AMASYA - GÖYNÜCEK - Şehit Tuncay Kurt İmam Hatip Ortaokulu',
  'AMASYA - GÖYNÜCEK - Gediksaray Şehit Satılmış Salatacı Ortaokulu',
  'AMASYA - GÖYNÜCEK - Alan İlkokulu',
  'AMASYA - GÖYNÜCEK - GÖYNÜCEK ANADOLU İMAM HATİP LİSESİ',
  'AMASYA - GÜMÜŞHACIKÖY - Gümüşhacıköy Hasan Coci Anadolu Lisesi',
  'AMASYA - GÜMÜŞHACIKÖY - Çal İlkokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Gümüşhacıköy Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - GÜMÜŞHACIKÖY - Gümüş İlkokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Gümüş Ortaokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Gümüşhacıköy Şehit Sercan Koç Çok Programlı Anadolu Lisesi',
  'AMASYA - GÜMÜŞHACIKÖY - Gümüşhacıköy Merkez Anaokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Gümüşhacıköy Halk Eğitimi Merkezi',
  'AMASYA - GÜMÜŞHACIKÖY - Gümüşhacıköy Anadolu İmam Hatip Lisesi',
  'AMASYA - GÜMÜŞHACIKÖY - Kağnıcı İlkokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Gümüşhacıköy Mesleki Eğitim Merkezi',
  'AMASYA - GÜMÜŞHACIKÖY - Öğretmen Evi ve Akşam Sanat Okulu',
  'AMASYA - GÜMÜŞHACIKÖY - Kemalpaşa İlkokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Şehit Teğmen Ahmet Çıtak İlkokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Işık İlkokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Ülkü Ortaokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Mehmet Paşa Ortaokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Kızılca Ortaokulu',
  'AMASYA - GÜMÜŞHACIKÖY - Kızılca İlkokulu',
  'AMASYA - GÜMÜŞHACIKÖY - GÜMÜŞHACIKÖY İMAM HATİP ORTAOKULU',
  'AMASYA - GÜMÜŞHACIKÖY - KIZILCA İMAM HATİP ORTAOKULU',
  'AMASYA - GÜMÜŞHACIKÖY - ŞEHİT ÜMİT ÇOBAN İLKOKULU',
  'AMASYA - GÜMÜŞHACIKÖY - ŞEHİT ÜMİT ÇOBAN ORTAOKULU',
  'AMASYA - HAMAMÖZÜ - Atatürk İlkokulu',
  'AMASYA - HAMAMÖZÜ - Hamamözü Halk Eğitimi Merkezi',
  'AMASYA - HAMAMÖZÜ - Hamit Kaplan Ortaokulu',
  'AMASYA - HAMAMÖZÜ - Adil Candemir Çok Programlı Anadolu Lisesi',
  'AMASYA - HAMAMÖZÜ - İMAM HATİP ORTAOKULU',
  'AMASYA - HAMAMÖZÜ - Adil Candemir Anadolu Lisesi',
  'AMASYA - MERKEZ - Alptekin Anadolu Lisesi',
  'AMASYA - MERKEZ - Amasya Anadolu Lisesi',
  'AMASYA - MERKEZ - Amasya Sosyal Bilimler Lisesi',
  'AMASYA - MERKEZ - Amasya Sabuncuoğlu Şerefeddin Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERKEZ - Şehit Gültekin Tırpan Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERKEZ - Şehit Ferhat Ünelli Bilim ve Sanat Merkezi',
  'AMASYA - MERKEZ - Amasya Güzel Sanatlar Lisesi',
  'AMASYA - MERKEZ - Amasya Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERKEZ - Amasya Lisesi',
  'AMASYA - MERKEZ - Torumtay Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERKEZ - Amasya Vedia Zeren Anaokulu',
  'AMASYA - MERKEZ - Aşağı Kızseki İlkokulu',
  'AMASYA - MERKEZ - Atatürk İlkokulu',
  'AMASYA - MERKEZ - Aydınca Şehit Hüsamettin Gökçe İlkokulu',
  'AMASYA - MERKEZ - Boğa İlkokulu',
  'AMASYA - MERKEZ - Cumhuriyet Ortaokulu',
  'AMASYA - MERKEZ - Doğantepe Şehit Kağan Kılıç İlkokulu',
  'AMASYA - MERKEZ - Ezinepazar İlkokulu',
  'AMASYA - MERKEZ - Gazi Ortaokulu',
  'AMASYA - MERKEZ - Gökhöyük Şehit Cemalettin Özdemir Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERKEZ - İl Özel İdaresi Anaokulu',
  'AMASYA - MERKEZ - Şehit Ahmet Özsoy Anadolu İmam Hatip Lisesi',
  'AMASYA - MERKEZ - Büyük Kızılca İlkokulu',
  'AMASYA - MERKEZ - Macit Zeren Fen Lisesi',
  'AMASYA - MERKEZ - Mehmet Varinli İlkokulu',
  'AMASYA - MERKEZ - Şehit Yılmaz Zengin Mesleki Eğitim Merkezi',
  'AMASYA - MERKEZ - Nihat Bayramoğlu İlkokulu',
  'AMASYA - MERKEZ - Ovasaray İlkokulu',
  'AMASYA - MERKEZ - Ovasaray Ortaokulu',
  'AMASYA - MERKEZ - Öğretmenevi ve Akşam Sanat Okulu',
  'AMASYA - MERKEZ - Plevne Ortaokulu',
  'AMASYA - MERKEZ - Amasya Rehberlik ve Araştırma Merkezi',
  'AMASYA - MERKEZ - Tuğgeneral Hikmet Akıncı Ortaokulu',
  'AMASYA - MERKEZ - Vali Hüseyin Poroy İlkokulu',
  'AMASYA - MERKEZ - Yeşilırmak Ortaokulu',
  'AMASYA - MERKEZ - Ziyaret İlkokulu',
  'AMASYA - MERKEZ - Zübeyde Hanım Anaokulu',
  'AMASYA - MERKEZ - Fatih İlkokulu',
  'AMASYA - MERKEZ - Abdurrahman Kamil Ortaokulu',
  'AMASYA - MERKEZ - Kılıçarslan Özel Eğitim Uygulama Okulu I. Kademe',
  'AMASYA - MERKEZ - Mehmetçik İlkokulu',
  'AMASYA - MERKEZ - Yıkılgan İlkokulu',
  'AMASYA - MERKEZ - Serdar Zeren Ortaokulu',
  'AMASYA - MERKEZ - Sarıalan İlkokulu',
  'AMASYA - MERKEZ - Serdar Zeren İlkokulu',
  'AMASYA - MERKEZ - Mehmetçik Ortaokulu',
  'AMASYA - MERKEZ - 12 Haziran Anadolu Lisesi',
  'AMASYA - MERKEZ - Tatar İlkokulu',
  'AMASYA - MERKEZ - Aydınca Şehit Şaban Gökçe Ortaokulu',
  'AMASYA - MERKEZ - Yavuz Selim Ortaokulu',
  'AMASYA - MERKEZ - Zübeyde Hanım Üçler İlkokulu',
  'AMASYA - MERKEZ - 75. Yıl Borsa İstanbul Bayezıt İlkokulu',
  'AMASYA - MERKEZ - İlyasköy Şehit Hakan Gül İlkokulu',
  'AMASYA - MERKEZ - Ziyapaşa Ortaokulu',
  'AMASYA - MERKEZ - Uygur Şehit Eraslan Güngör Ortaokulu',
  'AMASYA - MERKEZ - Kayabaşı Şehit Veysel Aslan İlkokulu',
  'AMASYA - MERKEZ - Osman Yıldırım Özel Eğitim Meslek Okulu',
  'AMASYA - MERKEZ - Kayabaşı Şehit Veysel Aslan Ortaokulu',
  'AMASYA - MERKEZ - İlduş Hatun Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERKEZ - Yeşil Yenice İlkokulu',
  'AMASYA - MERKEZ - Müftü Mehmed Tevfik Ortaokulu',
  'AMASYA - MERKEZ - Vali Hüseyin Poroy Ortaokulu',
  'AMASYA - MERKEZ - Kılıçarslan Özel Eğitim Uygulama Okulu II. Kademe',
  'AMASYA - MERKEZ - Bahçeleriçi Şehit Recep Gülen İlkokulu',
  'AMASYA - MERKEZ - Albayrak Şehit Yusuf Kaya Ortaokulu',
  'AMASYA - MERKEZ - Albayrak Şehit Yusuf Kaya İlkokulu',
  'AMASYA - MERKEZ - Büyük Kızılca Ortaokulu',
  'AMASYA - MERKEZ - İlyasköy Şehit Hakan Gül Ortaokulu',
  'AMASYA - MERKEZ - Amasya Şehit Mehmet Gök Halk Eğitimi Merkezi',
  'AMASYA - MERKEZ - Şehitler İlkokulu',
  'AMASYA - MERKEZ - Şehitler Ortaokulu',
  'AMASYA - MERKEZ - Kızılkışlacık İlkokulu',
  'AMASYA - MERKEZ - Ezine Pazar Atatürk İlkokulu',
  'AMASYA - MERKEZ - Akşemsettin İlkokulu',
  'AMASYA - MERKEZ - Boğaz İlkokulu',
  'AMASYA - MERKEZ - Aydınlık İlkokulu',
  'AMASYA - MERKEZ - Yeşil Yenice Ortaokulu',
  'AMASYA - MERKEZ - Lokman Hekim İşitme Engelliler Ortaokulu',
  'AMASYA - MERKEZ - Tuğgeneral Hikmet Akıncı İlkokulu',
  'AMASYA - MERKEZ - Lokman Hekim İşitme Engelliler İlkokulu',
  'AMASYA - MERKEZ - Abdurrahman Kamil İlkokulu',
  'AMASYA - MERKEZ - Kale Çavuşhan İlkokulu',
  'AMASYA - MERKEZ - Uygur Şehit Eraslan Güngör İlkokulu',
  'AMASYA - MERKEZ - Ezine Pazar Atatürk Ortaokulu',
  'AMASYA - MERKEZ - Boğaz Ortaokulu',
  'AMASYA - MERKEZ - Ziyaret Ortaokulu',
  'AMASYA - MERKEZ - Doğantepe Şehit Kağan Kılıç Ortaokulu',
  'AMASYA - MERKEZ - Direkli İlkokulu',
  'AMASYA - MERKEZ - Merkez 65 Bin Dev Öğrenci Sevgi Anaokulu',
  'AMASYA - MERKEZ - Karaköprü Bölmebük Şehit Mustafa Tuluk İlkokulu',
  'AMASYA - MERKEZ - ATATÜRK ANADOLU LİSESİ',
  'AMASYA - MERKEZ - Ziyaret TOKİ İlkokulu',
  'AMASYA - MERKEZ - ÇİĞDEMLİK İLKOKULU',
  'AMASYA - MERKEZ - YHKB ZEYNEP HATUN ANAOKULU',
  'AMASYA - MERKEZ - Ziyaret TOKİ Ortaokulu',
  'AMASYA - MERKEZ - Şehzade Özel Eğitim Uygulama Okulu III. Kademe',
  'AMASYA - MERKEZ - Şehit Ferhat Erdin Spor Lisesi',
  'AMASYA - MERKEZ - Aydınca Şehit Recep Bodur Çok Programlı Anadolu Lisesi',
  'AMASYA - MERKEZ - Amasya Çelebi Mehmet Ortaokulu',
  'AMASYA - MERKEZ - KUZGEÇE İLKOKULU',
  'AMASYA - MERKEZ - BÜLBÜL HATUN KIZ ANADOLU İMAM HATİP LİSESİ',
  'AMASYA - MERKEZ - HATTAT HAMDULLAH İMAM HATİP ORTAOKULU',
  'AMASYA - MERKEZ - Kumru Hatun Anaokulu',
  'AMASYA - MERKEZ - FINDIKLI TOKİ İLKOKULU',
  'AMASYA - MERKEZ - Şeyhcui Şehit Aziz Sağlam İmam Hatip Ortaokulu',
  'AMASYA - MERKEZ - Şehit Hüseyin Hatipoğlu İmam Hatip Ortaokulu',
  'AMASYA - MERKEZ - AMASYA ÜNİVERSİTESİ DR. HİKMET DEVELİ ANAOKULU',
  'AMASYA - MERKEZ - TÜRK TELEKOM ANADOLU İMAM HATİP LİSESİ',
  'AMASYA - MERKEZ - Gökmedrese Şehit Şenay Aybüke Yalçın İlkokulu',
  'AMASYA - MERKEZ - Şehit Selçuk Özarı Özel Eğitim Anaokulu',
  'AMASYA - MERKEZ - Müftü Mehmed Tevfik İlkokulu',
  'AMASYA - MERKEZ - Şehit Ferhat Ünelli Bilim ve Sanat Merkezi Anaokulu',
  'AMASYA - MERKEZ - Ayşe-Kadir Kutlu Kızılay Anaokulu',
  'AMASYA - MERKEZ - Sevincer İlkokulu',
  'AMASYA - MERKEZ - Sarımeşe İlkokulu',
  'AMASYA - MERKEZ - Mihri Hatun Anaokulu',
  'AMASYA - MERKEZ - Mehmet Varinli Ortaokulu',
  'AMASYA - MERZİFON - Abidehatun İlkokulu',
  'AMASYA - MERZİFON - Merzifon Anadolu Lisesi',
  'AMASYA - MERZİFON - Atatürk İlkokulu',
  'AMASYA - MERZİFON - Fatih İlkokulu',
  'AMASYA - MERZİFON - Merzifon Şehit Abdulmuttalip Kesikbaş Halk Eğitimi Merkezi',
  'AMASYA - MERZİFON - Mehmet Çelebi İlkokulu',
  'AMASYA - MERZİFON - Mehmetçik İlkokulu',
  'AMASYA - MERZİFON - Merzifon Anadolu İmam Hatip Lisesi',
  'AMASYA - MERZİFON - İrfanlı Anadolu Lisesi',
  'AMASYA - MERZİFON - Merzifon Şehit Dursun Özsaraç Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERZİFON - Merzifon Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERZİFON - Haşim Dülger Özel Eğitim Uygulama Okulu I. Kademe',
  'AMASYA - MERZİFON - Merzifon Fen Lisesi',
  'AMASYA - MERZİFON - Merzifon Ziya Paşa Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERZİFON - Merzifon Abide Hatun Anadolu Lisesi',
  'AMASYA - MERZİFON - Mithatpaşa Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - MERZİFON - Şehit Murat Demirci Mesleki Eğitim Merkezi',
  'AMASYA - MERZİFON - Öğretmen Evi ve Akşam Sanat Okulu',
  'AMASYA - MERZİFON - Sarıbuğday Ortaokulu',
  'AMASYA - MERZİFON - Şehit Öğretmen Mehmet Kapusuz İlkokulu',
  'AMASYA - MERZİFON - Zübeyde Hanım Anaokulu',
  'AMASYA - MERZİFON - İstiklal İlkokulu',
  'AMASYA - MERZİFON - Merzifon Sevinç-Orhan Erzengin Özel Eğitim İlkokulu',
  'AMASYA - MERZİFON - Cumhuriyet Ortaokulu',
  'AMASYA - MERZİFON - Şehit Polis Muzaffer Öztaş İlkokulu',
  'AMASYA - MERZİFON - Şehit Polis Halim Çalkan İlkokulu',
  'AMASYA - MERZİFON - Namık Kemal Ortaokulu',
  'AMASYA - MERZİFON - Merzifon Rehberlik ve Araştırma Merkezi',
  'AMASYA - MERZİFON - TOKİ Kara Mustafa Paşa Ortaokulu',
  'AMASYA - MERZİFON - Şehit Binbaşı Arslan Kulaksız Ortaokulu',
  'AMASYA - MERZİFON - Mehmet Akif Ersoy İlkokulu',
  'AMASYA - MERZİFON - Alıcık Şehit İlker Atan Ortaokulu',
  'AMASYA - MERZİFON - Kayadüzü Işık Ortaokulu',
  'AMASYA - MERZİFON - Şehit Öğretmen Mehmet Kapusuz Ortaokulu',
  'AMASYA - MERZİFON - Resmiye Mehmet Karaöz İlkokulu',
  'AMASYA - MERZİFON - Abidehatun Ortaokulu',
  'AMASYA - MERZİFON - Vali Hüseyin Poroy Ortaokulu',
  'AMASYA - MERZİFON - Merzifon Şehit Kubilay Er İmam Hatip Ortaokulu',
  'AMASYA - MERZİFON - Kızıleğrek Şehit Ahmet Aygül İlkokulu',
  'AMASYA - MERZİFON - Alıcık Şehit İlker Atan İlkokulu',
  'AMASYA - MERZİFON - Ahmet Faruk Çörekçi Ortaokulu',
  'AMASYA - MERZİFON - Ahmet Faruk Çörekçi İlkokulu',
  'AMASYA - MERZİFON - Muşruf İlkokulu',
  'AMASYA - MERZİFON - Gazi Ortaokulu',
  'AMASYA - MERZİFON - Akören İlkokulu',
  'AMASYA - MERZİFON - Merzifon Sevinç - Orhan Erzengin Özel Eğitim Meslek Okulu',
  'AMASYA - MERZİFON - Merzifon Sevinç-Orhan Erzengin Özel Eğitim Ortaokulu',
  'AMASYA - MERZİFON - Sarıbuğday İlkokulu',
  'AMASYA - MERZİFON - Mehmet Çelebi Ortaokulu',
  'AMASYA - MERZİFON - Haşim Dülger Özel Eğitim Uygulama Okulu II. Kademe',
  'AMASYA - MERZİFON - Haşim Dülger Özel Eğitim Uygulama Okulu III. Kademe',
  'AMASYA - MERZİFON - Şehit Ahmet Özsoy Kız Anadolu İmam Hatip Lisesi',
  'AMASYA - MERZİFON - Şehit Komiser Zeynep Sağır İmam Hatip Ortaokulu',
  'AMASYA - MERZİFON - MERZİFON ATATÜRK BİLİM VE SANAT MERKEZİ',
  'AMASYA - MERZİFON - Nuriye Hatun Anaokulu',
  'AMASYA - MERZİFON - Kayadüzü Işık İlkokulu',
  'AMASYA - MERZİFON - Merzifon Atatürk Bilim ve Sanat Merkezi Anaokulu',
  'AMASYA - MERZİFON - Merzifon Özel Eğitim Anaokulu',
  'AMASYA - SULUOVA - Akören İlkokulu',
  'AMASYA - SULUOVA - Armutlu İlkokulu',
  'AMASYA - SULUOVA - Atatürk Ortaokulu',
  'AMASYA - SULUOVA - Cumhuriyet Ortaokulu',
  'AMASYA - SULUOVA - Çeltek Madeni İlkokulu',
  'AMASYA - SULUOVA - Çeltek Madeni Ortaokulu',
  'AMASYA - SULUOVA - Gazi Ortaokulu',
  'AMASYA - SULUOVA - Suluova Hacı Bayram Özel Eğitim Meslek Okulu',
  'AMASYA - SULUOVA - Suluova Şehit Hüseyin Düzenli Halk Eğitimi Merkezi',
  'AMASYA - SULUOVA - Şehit Ercan Kurt Hürriyet Ortaokulu',
  'AMASYA - SULUOVA - Suluova Mesleki Eğitim Merkezi',
  'AMASYA - SULUOVA - Öğretmen Evi ve Akşam Sanat Okulu',
  'AMASYA - SULUOVA - Suluova Şehit Erkan Ayas Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - SULUOVA - Şehit Hüseyin Kavaklı Fen Lisesi',
  'AMASYA - SULUOVA - Şehit Recep İnce İmam Hatip Ortaokulu',
  'AMASYA - SULUOVA - Suluova Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - SULUOVA - Şehit Yüzbaşı Alper Kalem Ortaokulu',
  'AMASYA - SULUOVA - Suluova Lokman Hekim Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - SULUOVA - Suluova Şehit Metehan Atmaca Anadolu Lisesi',
  'AMASYA - SULUOVA - Suluova Mihri Hatun Anaokulu',
  'AMASYA - SULUOVA - Şeker Ortaokulu',
  'AMASYA - SULUOVA - Şeker İlkokulu',
  'AMASYA - SULUOVA - Eraslan Şehit Fatih Mehmet Keleş Ortaokulu',
  'AMASYA - SULUOVA - Bolat İlkokulu',
  'AMASYA - SULUOVA - Fatih Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - SULUOVA - TOKİ Çelebi Mehmet İlkokulu',
  'AMASYA - SULUOVA - Mehmet Bilgili Ortaokulu',
  'AMASYA - SULUOVA - Mehmet Bilgili İlkokulu',
  'AMASYA - SULUOVA - Suluova Adnan Menderes Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - SULUOVA - Şehit Osman Şeker İlkokulu',
  'AMASYA - SULUOVA - Eraslan Şehit Fatih Mehmet Keleş İlkokulu',
  'AMASYA - SULUOVA - Şehit Aydın Korkmaz Ortaokulu',
  'AMASYA - SULUOVA - Murat Deniz İlkokulu',
  'AMASYA - SULUOVA - Suluova Şehit Muharrem Saygün Anadolu Lisesi',
  'AMASYA - SULUOVA - Yunus Emre İlkokulu',
  'AMASYA - SULUOVA - Şehit Osman Karakuş Anadolu İmam - Hatip Lisesi',
  'AMASYA - SULUOVA - Cevizdibi Şehit Serhat Yurtbaşı İlkokulu',
  'AMASYA - SULUOVA - Cevizdibi Şehit Serhat Yurtbaşı Ortaokulu',
  'AMASYA - SULUOVA - Şehit Aydın Korkmaz İlkokulu',
  'AMASYA - SULUOVA - Zübeyde Hanım İlkokulu',
  'AMASYA - SULUOVA - Suluova 65 Bin Dev Öğrenci Sevgi Anaokulu',
  'AMASYA - SULUOVA - Halit Osman Otçu Ortaokulu',
  'AMASYA - SULUOVA - Halit Osman Otçu İlkokulu',
  'AMASYA - SULUOVA - YUNUS EMRE ORTAOKULU',
  'AMASYA - SULUOVA - Şehit Süleyman Aydın Kız Anadolu İmam Hatip Lisesi',
  'AMASYA - SULUOVA - 15 TEMMUZ MİLLİ İRADE İMAM HATİP ORTAOKULU',
  'AMASYA - SULUOVA - ŞEHİT MUSTAFA BİLGİLİ İLKOKULU',
  'AMASYA - SULUOVA - Şehit Mustafa Bilgili Ortaokulu',
  'AMASYA - SULUOVA - Suluova Bilim ve Sanat Merkezi',
  'AMASYA - TAŞOVA - Akınoğlu Ortaokulu',
  'AMASYA - TAŞOVA - Alpaslan Ortaokulu',
  'AMASYA - TAŞOVA - Esençay İlkokulu',
  'AMASYA - TAŞOVA - Belevi Ortaokulu',
  'AMASYA - TAŞOVA - Alpaslan İlkokulu',
  'AMASYA - TAŞOVA - Cumhuriyet İlkokulu',
  'AMASYA - TAŞOVA - Çaydibi Şehit Lütfi Aras Ortaokulu',
  'AMASYA - TAŞOVA - Esençay Ortaokulu',
  'AMASYA - TAŞOVA - Taşova Şehit Himmet Aydemir Halk Eğitimi Merkezi',
  'AMASYA - TAŞOVA - Öğretmen Evi ve Akşam Sanat Okulu',
  'AMASYA - TAŞOVA - Özbaraklı Şehit Özcan Özen İlkokulu',
  'AMASYA - TAŞOVA - Özkan Ağış İlkokulu',
  'AMASYA - TAŞOVA - Sepetli İlkokulu',
  'AMASYA - TAŞOVA - Şehit Bekir Özdemir Anadolu İmam Hatip Lisesi',
  'AMASYA - TAŞOVA - Şehit İdris Bolat Anadolu Lisesi',
  'AMASYA - TAŞOVA - Taşova Süleyman Bursalı Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - TAŞOVA - Taşova Şehit Polis Ahmet Yaşar Mesleki ve Teknik Anadolu Lisesi',
  'AMASYA - TAŞOVA - 15 Temmuz Şehitler Anaokulu',
  'AMASYA - TAŞOVA - Yaylasaray Şehit Er Arif Burçak İlkokulu',
  'AMASYA - TAŞOVA - Yerkozlu Şehit Ali Öztürk İlkokulu',
  'AMASYA - TAŞOVA - Yeşilırmak Şehit Ferhat Bolat İlkokulu',
  'AMASYA - TAŞOVA - Uluköy Şehit Komiser Mustafa Düzgün Ortaokulu',
  'AMASYA - TAŞOVA - Uluköy Şehit Komiser Mustafa Düzgün İlkokulu',
  'AMASYA - TAŞOVA - Şehit Adem Sezgin Yatılı Bölge Ortaokulu',
  'AMASYA - TAŞOVA - Atatürk Ortaokulu',
  'AMASYA - TAŞOVA - Cumhuriyet Ortaokulu',
  'AMASYA - TAŞOVA - Belevi İlkokulu',
  'AMASYA - TAŞOVA - Akınoğlu İlkokulu',
  'AMASYA - TAŞOVA - Çaydibi Şehit Lütfi Aras İlkokulu',
  'AMASYA - TAŞOVA - Hacıbey İlkokulu',
  'AMASYA - TAŞOVA - Destek Ortaokulu',
  'AMASYA - TAŞOVA - Destek İlkokulu',
  'AMASYA - TAŞOVA - Şehit Orhan Gülmez Çok Programlı Anadolu Lisesi',
  'AMASYA - TAŞOVA - Ballıdere Ömer Saray İlkokulu',
  'AMASYA - TAŞOVA - Ballıdere Ömer Saray Ortaokulu',
  'AMASYA - TAŞOVA - Emine Bursalı İmam Hatip Ortaokulu',
  'AMASYA - TASOVA - Boraboy İlkokulu',
  'AMASYA - TASOVA - Kavaloluğu İlkokulu',
  'AMASYA - TASOVA - Mercimek İlkokulu',
  ];
}