class AntalyaSchools{
  final List<String> list=[
  'ANTALYA - AKSEKİ - Akseki Anadolu Lisesi',
  'ANTALYA - AKSEKİ - Cevizli İlkokulu',
  'ANTALYA - AKSEKİ - Cevizli Ortaokulu',
  'ANTALYA - AKSEKİ - Akseki Halk Eğitimi Merkezi',
  'ANTALYA - AKSEKİ - Akseki Şahinler Meslekî ve Teknik Anadolu Lisesi',
  'ANTALYA - AKSEKİ - Akseki Ali-Hasan Coşkun Kardeşler İlkokulu',
  'ANTALYA - AKSEKİ - Taşlıca Ahmet Hamdi Akseki Ortaokulu',
  'ANTALYA - AKSEKİ - Taşlıca Ahmet Hamdi Akseki İlkokulu',
  'ANTALYA - AKSEKİ - Akseki Aysel Güleç Anaokulu',
  'ANTALYA - AKSEKİ - Akseki Cevizli Kaya Özen Çok Programlı Anadolu Lisesi',
  'ANTALYA - AKSEKİ - AKSEKİ ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - AKSEKİ - AKSEKİ EMİNE-AHMET BÜKÜŞOĞLU ORTAOKULU',
  'ANTALYA - AKSEKİ - Akseki Öğretmenevi ve Akşam Sanat Okulu Müdürlüğü',
  'ANTALYA - AKSEKİ - Vehbi Güleç Anaokulu',
  'ANTALYA - AKSU - Aksu Fen Lisesi',
  'ANTALYA - AKSU - Boztepe İlkokulu',
  'ANTALYA - AKSU - Boztepe Ortaokulu',
  'ANTALYA - AKSU - Aksu İncikpınar İlkokulu',
  'ANTALYA - AKSU - Dumanlar İlkokulu',
  'ANTALYA - AKSU - Dumanlar Ortaokulu',
  'ANTALYA - AKSU - Banu Cömertoğlu İlkokulu',
  'ANTALYA - AKSU - Halk Eğitimi Merkezi',
  'ANTALYA - AKSU - Aysel Akın - Klaus Wagner Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - AKSU - Kurşunlu İnci Kalender İlkokulu',
  'ANTALYA - AKSU - Solak İlkokulu',
  'ANTALYA - AKSU - Solak Ortaokulu',
  'ANTALYA - AKSU - Şeref Ülker İlkokulu',
  'ANTALYA - AKSU - Murtuna Gazi İlkokulu',
  'ANTALYA - AKSU - Murtuna Gazi Ortaokulu',
  'ANTALYA - AKSU - Yurtpınar Yenimahalle İlkokulu',
  'ANTALYA - AKSU - Alaylı Ortaokulu',
  'ANTALYA - AKSU - Alaylı İlkokulu',
  'ANTALYA - AKSU - Karaöz İlkokulu',
  'ANTALYA - AKSU - Ertuğrul Gazi Ortaokulu',
  'ANTALYA - AKSU - Banu-Ufuk Cömertoğlu İlkokulu',
  'ANTALYA - AKSU - Çalkaya 75.Yıl Cumhuriyet İlkokulu',
  'ANTALYA - AKSU - Çalkaya 75. Yıl Cumhuriyet Ortaokulu',
  'ANTALYA - AKSU - Karaöz Ortaokulu',
  'ANTALYA - AKSU - Rabiye -Mehmet Ülger Ortaokulu',
  'ANTALYA - AKSU - Rabiye-Mehmet Ülger İlkokulu',
  'ANTALYA - AKSU - Aksu İlkokulu',
  'ANTALYA - AKSU - Aksu Ortaokulu',
  'ANTALYA - AKSU - Mehmet Nazif Günal İlkokulu',
  'ANTALYA - AKSU - Mehmet Nazif Günal Ortaokulu',
  'ANTALYA - AKSU - Mustafa Kemal Özel Eğitim Meslek Okulu',
  'ANTALYA - AKSU - Kumköy Ortaokulu',
  'ANTALYA - AKSU - Kumköy İlkokulu',
  'ANTALYA - AKSU - Aksu Vali Ertokuş Bey Anadolu İmam Hatip Lisesi',
  'ANTALYA - AKSU - Aksu Hacıaliler Ortaokulu',
  'ANTALYA - AKSU - Aksu Hacıaliler İlkokulu',
  'ANTALYA - AKSU - Pınarlı Cumhuriyet Ortaokulu',
  'ANTALYA - AKSU - Pınarlı Cumhuriyet İlkokulu',
  'ANTALYA - AKSU - Celal Sönmez İlkokulu',
  'ANTALYA - AKSU - Kurşunlu İnci Kalender Ortaokulu',
  'ANTALYA - AKSU - Celal Sönmez Ortaokulu',
  'ANTALYA - AKSU - Topallı İlkokulu',
  'ANTALYA - AKSU - Şehit Yüksel Kılınç Ortaokulu',
  'ANTALYA - AKSU - Kocabelen İlkokulu',
  'ANTALYA - AKSU - Kocabelen Ortaokulu',
  'ANTALYA - AKSU - Nurcan - Rüstem Cömertoğlu Ortaokulu',
  'ANTALYA - AKSU - Cihadiye İlkokulu',
  'ANTALYA - AKSU - Cihadiye Ortaokulu',
  'ANTALYA - AKSU - Süleyman Erten İlkokulu',
  'ANTALYA - AKSU - Süleyman Erten Ortaokulu',
  'ANTALYA - AKSU - Yeşilkaraman Emin Gülmez İlkokulu',
  'ANTALYA - AKSU - Aksu Anadolu Lisesi',
  'ANTALYA - AKSU - GÖKDERE ATATÜRK ORTAOKULU',
  'ANTALYA - AKSU - GÖKDERE ATATÜRK İLKOKULU',
  'ANTALYA - AKSU - Aksu Melek - Mustafa Hamursuz Anaokulu',
  'ANTALYA - AKSU - Nurcan Cömertoğlu Ortaokulu',
  'ANTALYA - AKSU - Aksu Uçak Bakım Teknolojisi Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - AKSU - AKSU KIZ ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - AKSU - MURTUNA GAZİ İMAM HATİP ORTAOKULU',
  'ANTALYA - AKSU - Cihadiye İmam Hatip Ortaokulu',
  'ANTALYA - AKSU - PINARLI CUMHURİYET İMAM HATİP ORTAOKULU',
  'ANTALYA - AKSU - KOCABELEN İMAM HATİP ORTAOKULU',
  'ANTALYA - AKSU - KARAÖZ İMAM HATİP ORTAOKULU',
  'ANTALYA - AKSU - NECATİ BAŞKIRT İLKOKULU',
  'ANTALYA - AKSU - NECATİ BAŞKIRT ORTAOKULU',
  'ANTALYA - AKSU - YURTPINAR YENİMAHALLE İMAM HATİP ORTAOKULU',
  'ANTALYA - AKSU - Aksu İncikpınar Ortaokulu',
  'ANTALYA - AKSU - AKSU PERGE ORTAOKULU',
  'ANTALYA - AKSU - Nurcan Rüstem Cömertoğlu İmam Hatip Ortaokulu',
  'ANTALYA - AKSU - Vali Ertokuş Bey Anadolu Lisesi',
  'ANTALYA - AKSU - Süleyman Erten Anadolu Lisesi',
  'ANTALYA - AKSU - Aksu Belediyesi Şahin Harun Kırbıyık Anaokulu',
  'ANTALYA - AKSU - Aksu Özel Eğitim Anaokulu',
  'ANTALYA - AKSU - Aksu İncikpınar Anaokulu',
  'ANTALYA - AKSU - Banu- Ufuk Cömertoğlu Anaokulu',
  'ANTALYA - AKSU - Süleyman Erten Anaokulu',
  'ANTALYA - AKSU - Çalkaya 75. Yıl Cumhuriyet Anaokulu',
  'ANTALYA - AKSU - Aksu Anaokulu',
  'ANTALYA - ALANYA - A. Fevzi Alaettinoğlu Anadolu Lisesi',
  'ANTALYA - ALANYA - Abdurrahman Alaattinoğlu Anadolu Lisesi',
  'ANTALYA - ALANYA - Alaattin Keykubat Anaokulu',
  'ANTALYA - ALANYA - Şehit Abdullah Ümit Sercan Anadolu Lisesi',
  'ANTALYA - ALANYA - Alanya Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - ALANYA - Alanya Lisesi',
  'ANTALYA - ALANYA - Alanya Rehberlik Araştırma Merkezi',
  'ANTALYA - ALANYA - Rıfat Azakoğlu Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - ALANYA - Arıkan Yılmaz Dim Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - ALANYA - Avsallar Halıcı Orhan Ortaokulu',
  'ANTALYA - ALANYA - Avsallar Recep KARACA Çok Programlı Anadolu Lisesi',
  'ANTALYA - ALANYA - Parlayüksel İlkokulu',
  'ANTALYA - ALANYA - Can Anaokulu',
  'ANTALYA - ALANYA - Şehit Zekeriya Zencirli İlkokulu',
  'ANTALYA - ALANYA - Değirmendere İlkokulu',
  'ANTALYA - ALANYA - Hacıkadiroğlu Ortaokulu',
  'ANTALYA - ALANYA - Alanya Halk Eğitimi Merkezi',
  'ANTALYA - ALANYA - Hasan Çolak Anadolu Lisesi',
  'ANTALYA - ALANYA - Hüseyin Girenes Fen Lisesi',
  'ANTALYA - ALANYA - Alanya Kız Anadolu İmam Hatip Lisesi',
  'ANTALYA - ALANYA - Kestel Akdeniz İlkokulu',
  'ANTALYA - ALANYA - Konaklı Gazi İlkokulu',
  'ANTALYA - ALANYA - Mahmutlar 50.yıl Ahmet Keşoğlu İlkokulu',
  'ANTALYA - ALANYA - Mahmutlar Halil Ülker İlkokulu',
  'ANTALYA - ALANYA - Mahmutlar İlkokulu',
  'ANTALYA - ALANYA - Mahmutlar Şükrü Kaptanoğlu Anadolu Lisesi',
  'ANTALYA - ALANYA - Meziyet Köseoğlu Mesleki Eğitim Merkezi',
  'ANTALYA - ALANYA - Mustafa-Mürüvvet Alaattinoğlu Anadolu Lisesi',
  'ANTALYA - ALANYA - Alanya Nezihe Soydan Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - ALANYA - Nimet Alaettinoğlu Anadolu Lisesi',
  'ANTALYA - ALANYA - Obaköy Ortaokulu',
  'ANTALYA - ALANYA - Sahire Tüzün Anaokulu',
  'ANTALYA - ALANYA - Türkler Borsa İstanbul Sosyal Bilimler Lisesi',
  'ANTALYA - ALANYA - Alanya Ümit Altay Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - ALANYA - Zübeyde Hanım Anaokulu',
  'ANTALYA - ALANYA - Kemal Şuberi İlkokulu',
  'ANTALYA - ALANYA - Dereköy İlkokulu',
  'ANTALYA - ALANYA - Dereköy Ortaokulu',
  'ANTALYA - ALANYA - Mahmutlar Halil Ülker Ortaokulu',
  'ANTALYA - ALANYA - Okurcalar Berat Hayriye Cömertoğlu İlkokulu',
  'ANTALYA - ALANYA - Okurcalar Berat Hayriye Cömertoğlu Ortaokulu',
  'ANTALYA - ALANYA - Sema Eray Erdem Ortaokulu',
  'ANTALYA - ALANYA - Barbaros Azakoğlu Ortaokulu',
  'ANTALYA - ALANYA - Nezihat - Abdullah Doğan İlkokulu',
  'ANTALYA - ALANYA - Atatürk Ortaokulu',
  'ANTALYA - ALANYA - Jülide Akça İlkokulu',
  'ANTALYA - ALANYA - Hacıkura İlkokulu',
  'ANTALYA - ALANYA - Konaklı Kemal Atlı İlkokulu',
  'ANTALYA - ALANYA - Cikcilli Mehmet Emine Öncü İlkokulu',
  'ANTALYA - ALANYA - Şehit Ahmet Gündoğmuş Ortaokulu',
  'ANTALYA - ALANYA - Konaklı Kemal Atlı Ortaokulu',
  'ANTALYA - ALANYA - Alaaddin Keykubat İlkokulu',
  'ANTALYA - ALANYA - Obaköy İlkokulu',
  'ANTALYA - ALANYA - Öğretmenevi ve Akşam Sanat Ok.',
  'ANTALYA - ALANYA - Melahat Seher İlkokulu',
  'ANTALYA - ALANYA - Hayate Hanım Ortaokulu',
  'ANTALYA - ALANYA - Hayate Hanım İlkokulu',
  'ANTALYA - ALANYA - Tırılar Ortaokulu',
  'ANTALYA - ALANYA - Kestel Akdeniz Ortaokulu',
  'ANTALYA - ALANYA - Fatma Özmüftüoğlu Anadolu İmam Hatip Lisesi',
  'ANTALYA - ALANYA - Avsallar Ayhan Şahenk Anaokulu',
  'ANTALYA - ALANYA - Aşağıoba Hasan Atıcı İlkokulu',
  'ANTALYA - ALANYA - Değirmendere Ortaokulu',
  'ANTALYA - ALANYA - Mahmutlar Kılıçaslan İlkokulu',
  'ANTALYA - ALANYA - Kestel Alantur Ayhan Şahenk Ortaokulu',
  'ANTALYA - ALANYA - Kargıcak Ortaokulu',
  'ANTALYA - ALANYA - Kargıcak Vahapoğlu İlkokulu',
  'ANTALYA - ALANYA - Kestel Ortaokulu',
  'ANTALYA - ALANYA - Kestel İlkokulu',
  'ANTALYA - ALANYA - Payallar İlkokulu',
  'ANTALYA - ALANYA - Tosmur Fatma Özmüftüoğlu İlkokulu',
  'ANTALYA - ALANYA - Hidayet Görgün Ortaokulu',
  'ANTALYA - ALANYA - Gönül Kemal Reisoğlu İlkokulu',
  'ANTALYA - ALANYA - Emişbeleni Ortaokulu',
  'ANTALYA - ALANYA - Emişbeleni İlkokulu',
  'ANTALYA - ALANYA - Yaylalı İlkokulu',
  'ANTALYA - ALANYA - Yaylalı Ortaokulu',
  'ANTALYA - ALANYA - Alara Şevket Demirel İlkokulu',
  'ANTALYA - ALANYA - Alara Şevket Demirel Ortaokulu',
  'ANTALYA - ALANYA - Cumhuriyet İlkokulu',
  'ANTALYA - ALANYA - Toslak Sabir Erkin Ortaokulu',
  'ANTALYA - ALANYA - Dr.Şahin-Birsel Biçer Ortaokulu',
  'ANTALYA - ALANYA - Dr.Şahin-Birsel Biçer İlkokulu',
  'ANTALYA - ALANYA - Abdurrahman Alaattinoğlu Ortaokulu',
  'ANTALYA - ALANYA - Payallar Günay Demirel Ortaokulu',
  'ANTALYA - ALANYA - Payallar Büyükyer İlkokulu',
  'ANTALYA - ALANYA - Oba Nazmi Yılmaz Anadolu Lisesi',
  'ANTALYA - ALANYA - Ali Nazım Köseoğlu Ortaokulu',
  'ANTALYA - ALANYA - Türkler Aynur Hasan Sipahioğlu İlkokulu',
  'ANTALYA - ALANYA - Türkler Aynur Hasan Sipahioğlu Ortaokulu',
  'ANTALYA - ALANYA - Kızılcaşehir İlkokulu',
  'ANTALYA - ALANYA - Şehit Mehmet Sevimler İlkokulu',
  'ANTALYA - ALANYA - Şehit Necip Ali Şatıroğlu Ortaokulu',
  'ANTALYA - ALANYA - Sami Bekar İlkokulu',
  'ANTALYA - ALANYA - Hamit Özçelik Ortaokulu',
  'ANTALYA - ALANYA - Hamit Özçelik İlkokulu',
  'ANTALYA - ALANYA - Toslak Nebile Hacıkadiroğlu İlkokulu',
  'ANTALYA - ALANYA - Bilgi Bulut İlkokulu',
  'ANTALYA - ALANYA - Yeşilöz İlkokulu',
  'ANTALYA - ALANYA - Yeşilöz Ortaokulu',
  'ANTALYA - ALANYA - Ayşen-Cengiz Urfalıoğlu İlkokulu',
  'ANTALYA - ALANYA - Ayşen-Cengiz Urfalıoğlu Ortaokulu',
  'ANTALYA - ALANYA - Elikesik Güllü Özbağı Ortaokulu',
  'ANTALYA - ALANYA - Elikesik Şehit İlyas Güzel İlkokulu',
  'ANTALYA - ALANYA - Nimet Alaattinoğlu İlkokulu',
  'ANTALYA - ALANYA - Nimet Alaattinoğlu Ortaokulu',
  'ANTALYA - ALANYA - İnönü İlkokulu',
  'ANTALYA - ALANYA - Hamdullah Emin Paşa Ortaokulu',
  'ANTALYA - ALANYA - Hamdullah Emin Paşa İlkokulu',
  'ANTALYA - ALANYA - Demirtaş Çok Programlı Anadolu Lisesi',
  'ANTALYA - ALANYA - Mahmutlar İmam Hatip Ortaokulu',
  'ANTALYA - ALANYA - Fatma Alaettinoğlu İlkokulu',
  'ANTALYA - ALANYA - Şükrü Mülazımoğlu Ortaokulu',
  'ANTALYA - ALANYA - Demirtaş İlkokulu',
  'ANTALYA - ALANYA - Toslak Ketenlik İlkokulu',
  'ANTALYA - ALANYA - Toslak Ketenlik Ortaokulu',
  'ANTALYA - ALANYA - Cemile Kuyumcu Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - ALANYA - Berat - Hayriye Cömertoğlu Çok Programlı Anadolu Lisesi',
  'ANTALYA - ALANYA - KONAKLI MENDERES İLKOKULU',
  'ANTALYA - ALANYA - İNCEKUM ÖZTAŞ İLKOKULU',
  'ANTALYA - ALANYA - ALANYA MEHMET ARİF TÜRKTAŞ ANADOLU LİSESİ',
  'ANTALYA - ALANYA - Milli Eğitim Vakfı Güleç Demirel Ortaokulu',
  'ANTALYA - ALANYA - AVSALLAR ORTAOKULU',
  'ANTALYA - ALANYA - AKDAM İLKOKULU',
  'ANTALYA - ALANYA - SOĞUKPINAR İLKOKULU',
  'ANTALYA - ALANYA - SUGÖZÜ CEMAL COŞKUN ORTAOKULU',
  'ANTALYA - ALANYA - Avsallar Halıcı Orhan İlkokulu',
  'ANTALYA - ALANYA - Demirtaş Anadolu İmam Hatip Lisesi',
  'ANTALYA - ALANYA - İncekum Esentepe Ortaokulu',
  'ANTALYA - ALANYA - KARAMANLAR İLKOKULU',
  'ANTALYA - ALANYA - BEYRELİ İLKOKULU',
  'ANTALYA - ALANYA - MAHMUTLAR SELÇUKLU ORTAOKULU',
  'ANTALYA - ALANYA - Sakine Nesibe Zamanoğlu Özel Eğitim Uygulama Okulu I. Kademe',
  'ANTALYA - ALANYA - Eczacı Güzin-Velittin Bekrioğlu Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - ALANYA - Ali İhsan Dimçay İlkokulu',
  'ANTALYA - ALANYA - DİMÇAYI ORTAOKULU',
  'ANTALYA - ALANYA - PAYALLAR ÇOK PROGRAMLI ANADOLU LİSESİ',
  'ANTALYA - ALANYA - TÜRKLER GÜZEL SANATLAR LİSESİ',
  'ANTALYA - ALANYA - NEBAHAT ŞİFA ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - ALANYA - Alanya Şehit Cennet Yiğit Anaokulu',
  'ANTALYA - ALANYA - TAHİR TULUK ORTAOKULU',
  'ANTALYA - ALANYA - DEMİRTAŞ NİHAL DEMİREL ORTAOKULU',
  'ANTALYA - ALANYA - Sakine Nesibe Zamanoğlu Özel Eğitim Uygulama Okulu II. Kademe',
  'ANTALYA - ALANYA - Sakine Nesibe Zamanoğlu Özel Eğitim Uygulama Okulu III. Kademe',
  'ANTALYA - ALANYA - Kestel Sultan Alparslan Anadolu Lisesi',
  'ANTALYA - ALANYA - ALANYA ANAOKULU',
  'ANTALYA - ALANYA - ALANYA BİLİM VE SANAT MERKEZİ',
  'ANTALYA - ALANYA - TOSLAK İLKOKULU',
  'ANTALYA - ALANYA - TIRILAR İLKOKULU',
  'ANTALYA - ALANYA - Alanya Özel Eğitim Meslek Okulu',
  'ANTALYA - ALANYA - ŞEHİT COŞKUN NAZİLLİ İLKOKULU',
  'ANTALYA - ALANYA - ŞEHİT ÖMER HALİSDEMİR ORTAOKULU',
  'ANTALYA - ALANYA - 15 TEMMUZ ŞEHİTLER ANADOLU LİSESİ',
  'ANTALYA - ALANYA - KONAKLI İMAM HATİP ORTAOKULU',
  'ANTALYA - ALANYA - EMİŞBELENİ İMAM HATİP ORTAOKULU',
  'ANTALYA - ALANYA - AVSALLAR İMAM HATİP ORTAOKULU',
  'ANTALYA - ALANYA - ALANYA MEVLÜT ÇAVUŞOĞLU SPOR LİSESİ',
  'ANTALYA - ALANYA - ALANYA ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - ALANYA - NEZİHE TÜRKTAŞ ORTAOKULU',
  'ANTALYA - ALANYA - ALANYA MEHMET AKİF ERSOY ORTAOKULU',
  'ANTALYA - ALANYA - ALANYA ÖZEL EĞİTİM ANAOKULU',
  'ANTALYA - ALANYA - Kestel Alantur Ayhan Şahenk İlkokulu',
  'ANTALYA - ALANYA - ALANYA FATİH SULTAN MEHMET ORTAOKULU',
  'ANTALYA - ALANYA - MAHMUTLAR ANAOKULU',
  'ANTALYA - ALANYA - Atatürk İlkokulu',
  'ANTALYA - ALANYA - Ayşe Melahat Erkin Ortaokulu',
  'ANTALYA - ALANYA - Çıplaklı İlkokulu',
  'ANTALYA - ALANYA - Gülseren-Hüseyin Doğan İlkokulu',
  'ANTALYA - ALANYA - Alanya Şehit Yusuf Önder Anaokulu',
  'ANTALYA - ALANYA - Konaklı Menderes Anaokulu',
  'ANTALYA - ALANYA - Fatma Alaettinoğlu Anaokulu',
  'ANTALYA - ALANYA - Cikcilli Mehmet Emine Öncü Anaokulu',
  'ANTALYA - ALANYA - Hacıkura Anaokulu',
  'ANTALYA - ALANYA - Konaklı Gazi Anaokulu',
  'ANTALYA - ALANYA - Kılıçarslan Anaokulu',
  'ANTALYA - ALANYA - Yanıklar Özel Eğitim Uygulama Okulu I. Kademe',
  'ANTALYA - BÜYÜKŞEHİR - Ögretmen Evi ve Akşam Sanat Ok.',
  'ANTALYA - DEMRE - 80. Yıl Cumhuriyet İlkokulu',
  'ANTALYA - DEMRE - 80. Yıl Cumhuriyet Ortaokulu',
  'ANTALYA - DEMRE - Demre Anadolu İmam Hatip Lisesi',
  'ANTALYA - DEMRE - Demre Anadolu Lisesi',
  'ANTALYA - DEMRE - Hacımusaoğlu Anaokulu',
  'ANTALYA - DEMRE - Demre Halk Eğitimi Merkezi',
  'ANTALYA - DEMRE - Demre Mesleki Eğitim Merkezi',
  'ANTALYA - DEMRE - Yunus Emre İlkokulu',
  'ANTALYA - DEMRE - Demre Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - DEMRE - Köşkerler İlkokulu',
  'ANTALYA - DEMRE - Atatürk Ortaokulu',
  'ANTALYA - DEMRE - Beymelek İlkokulu',
  'ANTALYA - DEMRE - Beymelek Şehit Abdurrahman Esen Ortaokulu',
  'ANTALYA - DEMRE - Yaylakaya İlkokulu',
  'ANTALYA - DEMRE - Karabucak İlkokulu',
  'ANTALYA - DEMRE - Şehit Hüseyin Topkaya Ortaokulu',
  'ANTALYA - DEMRE - Demre Öğretmenevi ve Akşam Sanat Okulu',
  'ANTALYA - DEMRE - Karabucak Ortaokulu',
  'ANTALYA - DEMRE - Çevreli Bozoğlu-Tarkun İlkokulu',
  'ANTALYA - DEMRE - Çevreli Bozoğlu-Tarkun Ortaokulu',
  'ANTALYA - DEMRE - Yusuf Ozek İlkokulu',
  'ANTALYA - DEMRE - Beymelek Ayşe Öğretmen Anaokulu',
  'ANTALYA - DEMRE - Atatürk İlkokulu',
  'ANTALYA - DEMRE - DEMRE SALİH KAPLAN ANAOKULU',
  'ANTALYA - DEMRE - Demre Beymelek İmam Hatip Ortaokulu',
  'ANTALYA - DEMRE - ÇEVRELİ BOZOĞLU-TARKUN İMAM HATİP ORTAOKULU',
  'ANTALYA - DEMRE - Şehit Adem Akın Ortaokulu',
  'ANTALYA - DEMRE - Demre Anaokulu',
  'ANTALYA - DEMRE - Beymelek Ortaokulu',
  'ANTALYA - DEMRE - Beymelek Şehit Abdurrahman Esen İlkokulu',
  'ANTALYA - DEMRE - 15 Temmuz Milli Egemenlik Anaokulu',
  'ANTALYA - DEMRE - Demre Özel Eğitim Anaokulu',
  'ANTALYA - DÖŞEMEALTI - Albay Süleyman Külahçı Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Antalya Erünal Sosyal Bilimler Lisesi',
  'ANTALYA - DÖŞEMEALTI - Döşemealtı Halil Akyüz Anadolu Lisesi',
  'ANTALYA - DÖŞEMEALTI - Saime - Salih Konca Anaokulu',
  'ANTALYA - DÖŞEMEALTI - Yeşilbayır Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - DÖŞEMEALTI - Yukarıkaraman Perge Rotary İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Yeşilbayır İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Yukarıkaraman Perge Rotary Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Yusuf Ziya Öner Fen Lisesi',
  'ANTALYA - DÖŞEMEALTI - Kömürcüler İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Yeniköy İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Yeniköy Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Albay Süleyman Külahçı İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Emine İlhan Kadam Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - DÖŞEMEALTI - Osman Ali Cingöz İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Mustafa Ayten Aydın Anadolu Lisesi',
  'ANTALYA - DÖŞEMEALTI - Döşemealtı Halk Eğitimi Merkezi',
  'ANTALYA - DÖŞEMEALTI - Kovanlık İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Kovanlık Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Ayşe Sak Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Kömürcüler Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Osman Ali Cingöz Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Dağ İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Dağ Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Ilıcaköy Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Nursel-Ayhan Kadam İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Nursel-Ayhan Kadam Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Hilmi Caner Saraçoğlu İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Hilmi Caner Saraçoğlu Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Güngör Gencer İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Döşemealtı Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - DÖŞEMEALTI - Killik Şehit Hamza Uzguç Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Killik Şehit Hamza Uzguç İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Döşemealtı TOKİ Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Döşemealtı TOKİ İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Mustafa-Ayşe Altun İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Bademağacı Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - Döşemealtı Anadolu İmam Hatip Lisesi',
  'ANTALYA - DÖŞEMEALTI - KARATAŞ İLKOKULU',
  'ANTALYA - DÖŞEMEALTI - KARAVELİLER İLKOKULU',
  'ANTALYA - DÖŞEMEALTI - DİLEK-RECEP ÖZER ORTAOKULU',
  'ANTALYA - DÖŞEMEALTI - ILICAKÖY İMAM HATİP ORTAOKULU',
  'ANTALYA - DÖŞEMEALTI - ŞEHİT VOLKAN CANÖZ ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - DÖŞEMEALTI - Ayşe Sak İmam Hatip Ortaokulu',
  'ANTALYA - DÖŞEMEALTI - FATMA-YUSUF BİLGİÇ İLKOKULU',
  'ANTALYA - DÖŞEMEALTI - AYŞE-MEHMET ALİ ACAR ORTAOKULU',
  'ANTALYA - DÖŞEMEALTI - HİLMİ CANER SARAÇOĞLU İMAM HATİP ORTAOKULU',
  'ANTALYA - DÖŞEMEALTI - Bademağacı İlkokulu',
  'ANTALYA - DÖŞEMEALTI - Döşemealtı Özel Eğitim Anaokulu',
  'ANTALYA - DÖŞEMEALTI - Yeniköy Anaokulu',
  'ANTALYA - DÖŞEMEALTI - Yeşilbayır Anaokulu',
  'ANTALYA - ELMALI - Akçay Ortaokulu',
  'ANTALYA - ELMALI - Şehit Yakup Bozdağ Anaokulu',
  'ANTALYA - ELMALI - İbrahim Bedrettin Elmalı Fen Lisesi',
  'ANTALYA - ELMALI - Elmalı Anadolu İmam Hatip Lisesi',
  'ANTALYA - ELMALI - Muhammed Hamdi Yazır Anadolu Lisesi',
  'ANTALYA - ELMALI - Elmalı Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - ELMALI - Girne İlkokulu',
  'ANTALYA - ELMALI - Elmalı Halk Eğitimi Merkezi',
  'ANTALYA - ELMALI - Ayşe Çınar Özaydın Mesleki Eğitim Merkezi',
  'ANTALYA - ELMALI - Özdemir Ortaokulu',
  'ANTALYA - ELMALI - Özdemir İlkokulu',
  'ANTALYA - ELMALI - Yusuf Önertoy Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - ELMALI - Yuva İlkokulu',
  'ANTALYA - ELMALI - Yuva Ortaokulu',
  'ANTALYA - ELMALI - Osman Nuri Çınar Ortaokulu',
  'ANTALYA - ELMALI - Salur İlkokulu',
  'ANTALYA - ELMALI - Bozhuyuk İlkokulu',
  'ANTALYA - ELMALI - Mehmet Subaşı İlkokulu',
  'ANTALYA - ELMALI - Eskihisar Ortaokulu',
  'ANTALYA - ELMALI - Sebahat Çınar İlkokulu',
  'ANTALYA - ELMALI - Durmuş Yener İlkokulu',
  'ANTALYA - ELMALI - Durmuş Yener Ortaokulu',
  'ANTALYA - ELMALI - Zümrütova İlkokulu',
  'ANTALYA - ELMALI - Muhammed Hamdi Yazır Ortaokulu',
  'ANTALYA - ELMALI - Yakacıftlık İlkokulu',
  'ANTALYA - ELMALI - Akçay İlkokulu',
  'ANTALYA - ELMALI - Ali Mumcu İlkokulu',
  'ANTALYA - ELMALI - Ali Mumcu Ortaokulu',
  'ANTALYA - ELMALI - Tekke Abdal Musa İlkokulu',
  'ANTALYA - ELMALI - Tekke Abdal Musa Ortaokulu',
  'ANTALYA - ELMALI - Mehmet Topçu İlkokulu',
  'ANTALYA - ELMALI - Atatürk İlkokulu',
  'ANTALYA - ELMALI - ELMALI ÖĞRETMENEVİ VE AKŞAM SANAT OKULU',
  'ANTALYA - ELMALI - Sinan - ı Ümmi İmam Hatip Ortaokulu',
  'ANTALYA - ELMALI - Ömerpaşa Ortaokulu',
  'ANTALYA - ELMALI - Eskihisar Şehit Nuri Çavdar İlkokulu',
  'ANTALYA - ELMALI - YUVA İMAM HATİP ORTAOKULU',
  'ANTALYA - ELMALI - DURMUŞ YENER İMAM HATİP ORTAOKULU',
  'ANTALYA - ELMALI - Eskihisar Şehit Nuri Çavdar İmam Hatip Ortaokulu',
  'ANTALYA - ELMALI - Zümrütova Ortaokulu',
  'ANTALYA - ELMALI - Mehmet Topçu Anaokulu',
  'ANTALYA - ELMALI - Elmalı Özel Eğitim Anaokulu',
  'ANTALYA - FİNİKE - Arif Şehit Osman Çelik İlkokulu',
  'ANTALYA - FİNİKE - Atatürk İlkokulu',
  'ANTALYA - FİNİKE - Bağyaka Şehit Turgut Burkay Korkmaz İlkokulu',
  'ANTALYA - FİNİKE - Emin Akın İlkokulu',
  'ANTALYA - FİNİKE - Finike 50. Yıl Anaokulu',
  'ANTALYA - FİNİKE - Finike Anadolu Lisesi',
  'ANTALYA - FİNİKE - Finike Cumhuriyet Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - FİNİKE - Finike Halk Eğitimi Merkezi',
  'ANTALYA - FİNİKE - Hasyurt Kolaklar İlkokulu',
  'ANTALYA - FİNİKE - Hasyurt Yarbaşı Ortaokulu',
  'ANTALYA - FİNİKE - Finike Mesleki Eğitim Merkezi',
  'ANTALYA - FİNİKE - Şehit İsmail Çalkan İlkokulu',
  'ANTALYA - FİNİKE - Seyit Onbaşı İlkokulu',
  'ANTALYA - FİNİKE - Canan - Yavuz Gürkan Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - FİNİKE - Çavdır Ortaokulu',
  'ANTALYA - FİNİKE - Çavdır Şehit Mehmet Özyurt İlkokulu',
  'ANTALYA - FİNİKE - Hasyurt İlkokulu',
  'ANTALYA - FİNİKE - Hasyurt Ortaokulu',
  'ANTALYA - FİNİKE - Cengiz Topel Ortaokulu',
  'ANTALYA - FİNİKE - Turunçova Şehit Nurettin Tek Ortaokulu',
  'ANTALYA - FİNİKE - Yeşilyurt Şehit Adem Ovar İlkokulu',
  'ANTALYA - FİNİKE - İsmail Erol Ortaokulu',
  'ANTALYA - FİNİKE - İncirağacı Şehit Şaban Özdemir Tankut İlkokulu',
  'ANTALYA - FİNİKE - Yalnız İlkokulu',
  'ANTALYA - FİNİKE - İsmail Erol İlkokulu',
  'ANTALYA - FİNİKE - Finike Eroğlu Nuri Anadolu İmam Hatip Lisesi',
  'ANTALYA - FİNİKE - Atatürk Ortaokulu',
  'ANTALYA - FİNİKE - Hasyurt Yarbaşı İlkokulu',
  'ANTALYA - FİNİKE - Hasyurt Kolaklar Ortaokulu',
  'ANTALYA - FİNİKE - Arif Ortaokulu',
  'ANTALYA - FİNİKE - Finike Gıyaseddin Keyhüsrev Anadolu Lisesi',
  'ANTALYA - FİNİKE - FİNİKE BİLİM SANAT MERKEZİ',
  'ANTALYA - FİNİKE - Finike Şehit Ömer Halisdemir İmam Hatip Ortaokulu',
  'ANTALYA - FİNİKE - GÜNÇALI İLKOKULU',
  'ANTALYA - FİNİKE - İNCİRAĞACI İMAM HATİP ORTAOKULU',
  'ANTALYA - FİNİKE - ŞEHİT İSMAİL ÇALKAN İMAM HATİP ORTAOKULU',
  'ANTALYA - FİNİKE - Gökbük İlkokulu',
  'ANTALYA - FİNİKE - Emin Akın Anaokulu',
  'ANTALYA - FİNİKE - Finike Hacı Abdullah Onur Özel Eğitim Uygulama Okulu I. Kademe',
  'ANTALYA - FİNİKE - Finike Hacı Abdullah Onur Özel Eğitim Uygulama Okulu II. Kademe',
  'ANTALYA - FİNİKE - Finike Hacı Abdullah Onur Özel Eğitim Uygulama Okulu III. Kademe',
  'ANTALYA - FİNİKE - Finike 15 Temmuz Demokrasi Özel Eğitim Anaokulu',
  'ANTALYA - FİNİKE - Finike Hacı Zehra Onur Anaokulu',
  'ANTALYA - FİNİKE - Finike Atatürk Anaokulu',
  'ANTALYA - GAZİPAŞA - Akalan İlkokulu',
  'ANTALYA - GAZİPAŞA - Akalan Ortaokulu',
  'ANTALYA - GAZİPAŞA - Zeliha Tuncer Anadolu İmam Hatip Lisesi',
  'ANTALYA - GAZİPAŞA - Gazipaşa Anadolu Lisesi',
  'ANTALYA - GAZİPAŞA - Gazipaşa Anaokulu',
  'ANTALYA - GAZİPAŞA - Gazipaşa Av. Kemal Akça Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - GAZİPAŞA - Gazipaşa Merkez Anadolu Lisesi',
  'ANTALYA - GAZİPAŞA - Gazipaşa Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - GAZİPAŞA - Gazipaşa Halk Eğitimi Merkezi',
  'ANTALYA - GAZİPAŞA - İstiklal Şehit Süleyman Gür İlkokulu',
  'ANTALYA - GAZİPAŞA - Karalar Hüseyinli Ortaokulu',
  'ANTALYA - GAZİPAŞA - Gazipaşa Mesleki Eğitim Merkezi',
  'ANTALYA - GAZİPAŞA - Naile Bilgiç Büyükballı Anaokulu',
  'ANTALYA - GAZİPAŞA - Öğretmen evi ve Akşam Sanat Okulu',
  'ANTALYA - GAZİPAŞA - İstiklal Şehit Süleyman Gür Ortaokulu',
  'ANTALYA - GAZİPAŞA - Burhan İlkokulu',
  'ANTALYA - GAZİPAŞA - Karalar Hüseyinli İlkokulu',
  'ANTALYA - GAZİPAŞA - Beyrebucak İlkokulu',
  'ANTALYA - GAZİPAŞA - Beyrebucak Ortaokulu',
  'ANTALYA - GAZİPAŞA - Kahyalar Asarcık İlkokulu',
  'ANTALYA - GAZİPAŞA - Burhan Ortaokulu',
  'ANTALYA - GAZİPAŞA - Gazi Mustafa Kemal Ortaokulu',
  'ANTALYA - GAZİPAŞA - Gazi Mustafa Kemal İlkokulu',
  'ANTALYA - GAZİPAŞA - Aydıncık İlkokulu',
  'ANTALYA - GAZİPAŞA - Fadime Tuncer Ortaokulu',
  'ANTALYA - GAZİPAŞA - Atatürk İlkokulu',
  'ANTALYA - GAZİPAŞA - Atatürk Ortaokulu',
  'ANTALYA - GAZİPAŞA - Çobanlar İlkokulu',
  'ANTALYA - GAZİPAŞA - Çobanlar Ortaokulu',
  'ANTALYA - GAZİPAŞA - Cumhuriyet Ortaokulu',
  'ANTALYA - GAZİPAŞA - Cumhuriyet İlkokulu',
  'ANTALYA - GAZİPAŞA - Kahyalar İlkokulu',
  'ANTALYA - GAZİPAŞA - Muzkent İlkokulu',
  'ANTALYA - GAZİPAŞA - Ahmet Tuncer İlkokulu',
  'ANTALYA - GAZİPAŞA - Ahmet Tuncer Ortaokulu',
  'ANTALYA - GAZİPAŞA - Yakacık Mehmet Oğuz Galadran İlkokulu',
  'ANTALYA - GAZİPAŞA - Yakacık Mehmet Oğuz Galadran Ortaokulu',
  'ANTALYA - GAZİPAŞA - Ekmel Şehit Mesut Yılmaz İlkokulu',
  'ANTALYA - GAZİPAŞA - Ekmel Şehit Mesut Yılmaz Ortaokulu',
  'ANTALYA - GAZİPAŞA - Av. Kemal Akça Ortaokulu',
  'ANTALYA - GAZİPAŞA - Av.Kemal Akça İlkokulu',
  'ANTALYA - GAZİPAŞA - Fadime Tuncer İlkokulu',
  'ANTALYA - GAZİPAŞA - Şehit Demet Sezen Kız Anadolu İmam Hatip Lisesi',
  'ANTALYA - GAZİPAŞA - Çalıpınar İlkokulu',
  'ANTALYA - GAZİPAŞA - Macar Fahri Özçelik Ortaokulu',
  'ANTALYA - GAZİPAŞA - Macar Fahri Özçelik İlkokulu',
  'ANTALYA - GAZİPAŞA - Karatepe İlkokulu',
  'ANTALYA - GAZİPAŞA - Karatepe Ortaokulu',
  'ANTALYA - GAZİPAŞA - Yeniköy Bozerkek İlkokulu',
  'ANTALYA - GAZİPAŞA - Doğanca Şehit Fatih Uysal Ortaokulu',
  'ANTALYA - GAZİPAŞA - Doğanca Şehit Fatih Uysal İlkokulu',
  'ANTALYA - GAZİPAŞA - MUZKENT ORTAOKULU',
  'ANTALYA - GAZİPAŞA - ANTALYA BÜYÜKŞEHİR BELEDİYESİ GAZİPAŞA ANAOKULU',
  'ANTALYA - GAZİPAŞA - BEYREBUCAK İMAM HATİP ORTAOKULU',
  'ANTALYA - GAZİPAŞA - GAZİPAŞA FEN LİSESİ',
  'ANTALYA - GAZİPAŞA - KARALAR HÜSEYİNLİ İMAM HATİP ORTAOKULU',
  'ANTALYA - GAZİPAŞA - Gazipaşa Özel Eğitim Uygulama Okulu I. Kademe',
  'ANTALYA - GAZİPAŞA - Gazipaşa Özel Eğitim Uygulama Okulu II. Kademe',
  'ANTALYA - GAZİPAŞA - Gazipaşa Özel Eğitim Anaokulu',
  'ANTALYA - GAZİPAŞA - İstiklal Şehit Süleyman Gür Anaokulu',
  'ANTALYA - GAZİPAŞA - Av.Kemal Akça Anaokulu',
  'ANTALYA - GAZİPAŞA - Ahmet Tuncer Anaokulu',
  'ANTALYA - GAZİPAŞA - Gazipaşa Cumhuriyet Anaokulu',
  'ANTALYA - GÜNDOĞMUŞ - Çok Programlı Anadolu Lisesi',
  'ANTALYA - GÜNDOĞMUŞ - Gündoğmuş Halk Eğitimi Merkezi',
  'ANTALYA - GÜNDOĞMUŞ - Köprülü Ayşe Güven İlkokulu',
  'ANTALYA - GÜNDOĞMUŞ - Şehit Orman Mühendisi Abdullah Aydın Yatılı Bölge Ortaokulu',
  'ANTALYA - GÜNDOĞMUŞ - Ümütlü İlkokulu',
  'ANTALYA - GÜNDOĞMUŞ - Merkez İlkokulu',
  'ANTALYA - GÜNDOĞMUŞ - Bedan İlkokulu',
  'ANTALYA - GÜNDOĞMUŞ - Gündoğmuş Anadolu Lisesi',
  'ANTALYA - GÜNDOĞMUŞ - GÜNDOĞMUŞ İMAM HATİP ORTAOKULU',
  'ANTALYA - GÜNDOĞMUŞ - Gündoğmuş Kardelen Anaokulu',
  'ANTALYA - GÜNDOĞMUŞ - Köprülü Ayşe Güven Ortaokulu',
  'ANTALYA - İBRADI - Necla - Yaşar Duru Çok Programlı Anadolu Lisesi',
  'ANTALYA - İBRADI - Nefise Yılmaz İpek Ortaokulu',
  'ANTALYA - İBRADI - İbradı Halk Eğitimi Merkezi',
  'ANTALYA - İBRADI - Avni Erdoğan Anaokulu',
  'ANTALYA - İBRADI - MUSTAFA NAZMİ DEMİRÖZ İLKOKULU',
  'ANTALYA - İBRADİ - Nefise Yılmaz İpek İlkokulu',
  'ANTALYA - KAŞ - Emin Kasapoğlu Çok Programlı Anadolu Lisesi',
  'ANTALYA - KAŞ - İsmet Köroğlu Anadolu Lisesi',
  'ANTALYA - KAŞ - Kaş Çok Programlı Anadolu Lisesi',
  'ANTALYA - KAŞ - Kaş 15 Temmuz Şehitleri Anaokulu',
  'ANTALYA - KAŞ - Şehit Adnan Kısar Çok Programlı Anadolu Lisesi',
  'ANTALYA - KAŞ - Kınık Yurdusev Ulus İlkokulu',
  'ANTALYA - KAŞ - Patara İlkokulu',
  'ANTALYA - KAŞ - Yeşilköy Mesleki Eğitim Merkezi',
  'ANTALYA - KAŞ - Kaş Çavdır Anaokulu',
  'ANTALYA - KAŞ - Karadağ Ortaokulu',
  'ANTALYA - KAŞ - Durmuş-Gülser Gedikoğlu Ortaokulu',
  'ANTALYA - KAŞ - Durmuş - Gülser Gedikoğlu İlkokulu',
  'ANTALYA - KAŞ - Kalkan Ortaokulu',
  'ANTALYA - KAŞ - Şehit Öğretmen Ali Boşgelmez İlkokulu',
  'ANTALYA - KAŞ - Süleyman Yılmaz Anaokulu',
  'ANTALYA - KAŞ - Kınık Yurdusev Ulus Ortaokulu',
  'ANTALYA - KAŞ - Sarıbelen İlkokulu',
  'ANTALYA - KAŞ - Sarıbelen Ortaokulu',
  'ANTALYA - KAŞ - Ova Ortaokulu',
  'ANTALYA - KAŞ - Ova İlkokulu',
  'ANTALYA - KAŞ - Palamut İlkokulu',
  'ANTALYA - KAŞ - Palamut Ortaokulu',
  'ANTALYA - KAŞ - Kaş Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KAŞ - Mustafa Kocakaya Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KAŞ - Karadağ İlkokulu',
  'ANTALYA - KAŞ - Çayköy Ortaokulu',
  'ANTALYA - KAŞ - Üzümlü İlkokulu',
  'ANTALYA - KAŞ - Yeşilköy Hilmi Toksoy İlkokulu',
  'ANTALYA - KAŞ - Üzümlü Ortaokulu',
  'ANTALYA - KAŞ - Kaş Anadolu İmam Hatip Lisesi',
  'ANTALYA - KAŞ - Kasaba Şehit Yusuf Polat Yatılı Bölge Ortaokulu',
  'ANTALYA - KAŞ - Çavdır İlkokulu',
  'ANTALYA - KAŞ - Çavdır Ortaokulu',
  'ANTALYA - KAŞ - Kaş Ova Anaokulu',
  'ANTALYA - KAŞ - Kaş Halk Eğitimi Merkezi',
  'ANTALYA - KAŞ - Yeşilköy Hilmi Toksoy Ortaokulu',
  'ANTALYA - KAŞ - Atatürk Ortaokulu',
  'ANTALYA - KAŞ - Atatürk İlkokulu',
  'ANTALYA - KAŞ - Şehit Öğretmen Ali Boşgelmez Ortaokulu',
  'ANTALYA - KAŞ - Kasaba Şehit Yusuf Polat İlkokulu',
  'ANTALYA - KAŞ - Sütleğen Yatılı Bölge Ortaokulu',
  'ANTALYA - KAŞ - Gömbe İlkokulu',
  'ANTALYA - KAŞ - Gömbe Ortaokulu',
  'ANTALYA - KAŞ - Sütleğen İlkokulu',
  'ANTALYA - KAŞ - Dirgenler İlkokulu',
  'ANTALYA - KAŞ - Merkez İlkokulu',
  'ANTALYA - KAŞ - Kınık İlkokulu',
  'ANTALYA - KAŞ - Kınık Ortaokulu',
  'ANTALYA - KAŞ - Merkez Ortaokulu',
  'ANTALYA - KAŞ - Çayköy İlkokulu',
  'ANTALYA - KAŞ - Kalkan İlkokulu',
  'ANTALYA - KAŞ - KINIK ANAOKULU',
  'ANTALYA - KAŞ - SABRİYE TOKSOY ANAOKULU',
  'ANTALYA - KAŞ - TURAN ERDOĞAN YILMAZ FEN LİSESİ',
  'ANTALYA - KAŞ - Kaş Şehit Ömer Halisdemir İlkokulu',
  'ANTALYA - KAŞ - MEHMET AKİF ERSOY İLKOKULU',
  'ANTALYA - KAŞ - OVA İMAM HATİP ORTAOKULU',
  'ANTALYA - KAŞ - KASABA ŞEHİT YUSUF POLAT İMAM HATİP ORTAOKULU',
  'ANTALYA - KAŞ - Gömbe İmam Hatip Ortaokulu',
  'ANTALYA - KAŞ - KAŞ TOROSLAR ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - KAŞ - KAŞ ÇAVDIR ANADOLU LİSESİ',
  'ANTALYA - KAŞ - Sütleğen İmam Hatip Ortaokulu',
  'ANTALYA - KAŞ - Kaş Bilim ve Sanat Merkezi',
  'ANTALYA - KAŞ - Hacı Osman Mehmet Çelebioğlu Anadolu Lisesi',
  'ANTALYA - KEMER - Ahu Aysal Anaokulu',
  'ANTALYA - KEMER - Arslanbucak Anaokulu',
  'ANTALYA - KEMER - Göynük Fen Lisesi',
  'ANTALYA - KEMER - Kemer Anadolu Lisesi',
  'ANTALYA - KEMER - Kemer Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEMER - Özgül Canik Anaokulu',
  'ANTALYA - KEMER - Kemer Merkez Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEMER - Ünal Aysal Anadolu Lisesi',
  'ANTALYA - KEMER - Rukiye Koç Ortaokulu',
  'ANTALYA - KEMER - Beycik İlkokulu',
  'ANTALYA - KEMER - Halk Eğitimi Merkezi',
  'ANTALYA - KEMER - Göynük Atatürk İlkokulu',
  'ANTALYA - KEMER - Göynük Ortaokulu',
  'ANTALYA - KEMER - Mustafa Rüştü Tuncer İlkokulu',
  'ANTALYA - KEMER - Arslanbucak Ortaokulu',
  'ANTALYA - KEMER - Şeker İlkokulu',
  'ANTALYA - KEMER - Hacı Mehmet Saygın İlkokulu',
  'ANTALYA - KEMER - Hacı Mehmet Saygın Ortaokulu',
  'ANTALYA - KEMER - Kemer Merkez İlkokulu',
  'ANTALYA - KEMER - Çamyuva Silkar İlkokulu',
  'ANTALYA - KEMER - Tekirova Halit Narin İlkokulu',
  'ANTALYA - KEMER - Tekirova Halit Narin Ortaokulu',
  'ANTALYA - KEMER - Hakkı Saygan Hacı Hafize Saygan-3 Ortaokulu',
  'ANTALYA - KEMER - Beldibi Ortaokulu',
  'ANTALYA - KEMER - Beldibi İlkokulu',
  'ANTALYA - KEMER - Gülçin Ersoy Anaokulu',
  'ANTALYA - KEMER - Kemer Anadolu İmam Hatip Lisesi',
  'ANTALYA - KEMER - GÖYNÜK İMAM HATİP ORTAOKULU',
  'ANTALYA - KEMER - Ulupınar Çıralı İlkokulu',
  'ANTALYA - KEMER - Kemer Özel Eğitim Anaokulu',
  'ANTALYA - KEPEZ - Düden Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Yedi Kuyular İlkokulu',
  'ANTALYA - KEPEZ - Antalya Ticaret ve Sanayi Odası Güzel Sanatlar Lisesi',
  'ANTALYA - KEPEZ - Atatürk Anadolu Lisesi',
  'ANTALYA - KEPEZ - Ayten Çağıran Çok Programlı Anadolu Lisesi',
  'ANTALYA - KEPEZ - Şehit Selahattin Aysan İlkokulu',
  'ANTALYA - KEPEZ - Hamdullah Suphi Tanrıöver Anaokulu',
  'ANTALYA - KEPEZ - İsmail Hakkı Kaya İlkokulu',
  'ANTALYA - KEPEZ - Hayriye Kaya Ortaokulu',
  'ANTALYA - KEPEZ - Kepez Şehit Celal Özcan Anadolu Lisesi',
  'ANTALYA - KEPEZ - Kepez Özel Eğitim Meslek Lisesi',
  'ANTALYA - KEPEZ - Mehmet Akif Ersoy Anaokulu',
  'ANTALYA - KEPEZ - Odabaşı İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Nevzat Saygan-Levent Saygan Anadolu Lisesi',
  'ANTALYA - KEPEZ - Şehit Binbaşı Turgut Cengiz Toytunç Anaokulu',
  'ANTALYA - KEPEZ - Şehit Yüzbaşı İbrahim Barış Yurtseven İlkokulu',
  'ANTALYA - KEPEZ - Şehit Serhat Genç İlkokulu',
  'ANTALYA - KEPEZ - Antalya Akdeniz Sanayi Sitesi Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Şehit Ömer Dikmen Çok Programlı Anadolu Lisesi',
  'ANTALYA - KEPEZ - Kepez Teomanpaşa Halk Eğitimi Merkezi',
  'ANTALYA - KEPEZ - Toros Anadolu Lisesi',
  'ANTALYA - KEPEZ - Varsak İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Kamile Metin Yapar İlkokulu',
  'ANTALYA - KEPEZ - Varsak Şelale İlkokulu',
  'ANTALYA - KEPEZ - Bolat Yıldırım İlkokulu',
  'ANTALYA - KEPEZ - Kepez Sütçüler Anadolu İmam Hatip Lisesi',
  'ANTALYA - KEPEZ - Emine - İsmail Ataoğlu Anaokulu',
  'ANTALYA - KEPEZ - Antalya Bilim ve Sanat Merkezi',
  'ANTALYA - KEPEZ - Alaeddin Keykubat Ortaokulu',
  'ANTALYA - KEPEZ - Alirıza Altıntaş Ortaokulu',
  'ANTALYA - KEPEZ - Ersoy İlkokulu',
  'ANTALYA - KEPEZ - Antalya Spor Lisesi',
  'ANTALYA - KEPEZ - Kepez Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Karatay Anadolu Lisesi',
  'ANTALYA - KEPEZ - Hızır Reis Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Atatürk Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Hüseyin Avni Çöllü Ortaokulu',
  'ANTALYA - KEPEZ - Ünsal İlkokulu',
  'ANTALYA - KEPEZ - Fatma Parıltı Ortaokulu',
  'ANTALYA - KEPEZ - Şehit Özcan Şenol Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Kepez Rehberlik ve Araştırma Merkezi',
  'ANTALYA - KEPEZ - Kirişçiler İlkokulu',
  'ANTALYA - KEPEZ - Kepez Ortaokulu',
  'ANTALYA - KEPEZ - İrenoğulları Şehit Atila Nizam İlkokulu',
  'ANTALYA - KEPEZ - Cengiz Topel İlkokulu',
  'ANTALYA - KEPEZ - Çağlayan Anadolu Lisesi',
  'ANTALYA - KEPEZ - İsmail İltemir İlkokulu',
  'ANTALYA - KEPEZ - Ayşe-Ahmet Atmaca Ortaokulu',
  'ANTALYA - KEPEZ - Varsak Ruhi Göksoy Ortaokulu',
  'ANTALYA - KEPEZ - Antalya Eczacılar Ortaokulu',
  'ANTALYA - KEPEZ - Süleyman Demirel İlkokulu',
  'ANTALYA - KEPEZ - Antalya Eczacılar İlkokulu',
  'ANTALYA - KEPEZ - Mimar Sinan İlkokulu',
  'ANTALYA - KEPEZ - Nebi Güney İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Şehit İlyas Acar İlkokulu',
  'ANTALYA - KEPEZ - Göçerler Ortaokulu',
  'ANTALYA - KEPEZ - Mareşal Fevzi Çakmak Ortaokulu',
  'ANTALYA - KEPEZ - Mareşal Fevzi Çakmak İlkokulu',
  'ANTALYA - KEPEZ - Şahinevler Ortaokulu',
  'ANTALYA - KEPEZ - Aslanlar İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Gülveren İlkokulu',
  'ANTALYA - KEPEZ - Süleyman Demirel Ortaokulu',
  'ANTALYA - KEPEZ - Hüseyin Ak Ortaokulu',
  'ANTALYA - KEPEZ - Sütçüler İlkokulu',
  'ANTALYA - KEPEZ - Varsak İlkokulu',
  'ANTALYA - KEPEZ - Ahmet Coşkun Bulut Ortaokulu',
  'ANTALYA - KEPEZ - Varsak Ortaokulu',
  'ANTALYA - KEPEZ - Ahmet-Leman Baydar Ortaokulu',
  'ANTALYA - KEPEZ - Altınova Ortaokulu',
  'ANTALYA - KEPEZ - 100. Yıl Ortaokulu',
  'ANTALYA - KEPEZ - Altınova İlkokulu',
  'ANTALYA - KEPEZ - Altınova Ruhi Sunar İlkokulu',
  'ANTALYA - KEPEZ - Fatma Parıltı İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Ersoy Ortaokulu',
  'ANTALYA - KEPEZ - İsmet İnönü Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Turgut Reis Ortaokulu',
  'ANTALYA - KEPEZ - Fikret Haluk Saraçoğlu İlkokulu',
  'ANTALYA - KEPEZ - Şehit Cemal Yalın İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Nazime Baki Saatçioğlu Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Kepez Özel Eğitim Uygulama Merkezi I. Kademe',
  'ANTALYA - KEPEZ - Prof.İhsan Koz İlkokulu',
  'ANTALYA - KEPEZ - Aslanlar İlkokulu',
  'ANTALYA - KEPEZ - Ernur - Faik Koparan Ortaokulu',
  'ANTALYA - KEPEZ - İbrahim Doğaner İlkokulu',
  'ANTALYA - KEPEZ - Şehit Yüzbaşı İbrahim Barış Yurtseven İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Aslanlar Ortaokulu',
  'ANTALYA - KEPEZ - Prof. Dr. Tuğgeneral Cevdet Demirkol - Ayhan Demirkol Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Sefa Akın Ortaokulu',
  'ANTALYA - KEPEZ - Mobil Ortaokulu',
  'ANTALYA - KEPEZ - Hüseyin Ak İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Hüseyin Ak İlkokulu',
  'ANTALYA - KEPEZ - Mehmet Kemal Dedeman İlkokulu',
  'ANTALYA - KEPEZ - Neşe Arif Sönmez Anaokulu',
  'ANTALYA - KEPEZ - Şehit Ali Daniyar Ortaokulu',
  'ANTALYA - KEPEZ - Abdülkadir Özkan İlkokulu',
  'ANTALYA - KEPEZ - Kepez Gıyaseddin Keyhüsrev Anadolu İmam Hatip Lisesi',
  'ANTALYA - KEPEZ - Varsak Şelale Ortaokulu',
  'ANTALYA - KEPEZ - Yıldırım Bayezid İlkokulu',
  'ANTALYA - KEPEZ - Gülgün-Nihat Ömür İlkokulu',
  'ANTALYA - KEPEZ - Gülgün-Nihat Ömür Ortaokulu',
  'ANTALYA - KEPEZ - Kepez Özel Eğitim Uygulama Merkezi II. Kademe',
  'ANTALYA - KEPEZ - Halil Akyüz Ortaokulu',
  'ANTALYA - KEPEZ - Metin Çiviler Anadolu Lisesi',
  'ANTALYA - KEPEZ - Kültür İlkokulu',
  'ANTALYA - KEPEZ - Perihan-Esat Aral Ortaokulu',
  'ANTALYA - KEPEZ - Beşkonak İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Kepez Şehit Hakan Karakaya İlkokulu',
  'ANTALYA - KEPEZ - Kaan Turan İlkokulu',
  'ANTALYA - KEPEZ - Duraliler İlkokulu',
  'ANTALYA - KEPEZ - Duraliler Ortaokulu',
  'ANTALYA - KEPEZ - Şehit Jandarma Üsteğmen Gökhan Korkut İlkokulu',
  'ANTALYA - KEPEZ - Şehit Jandarma Üsteğmen Gökhan Korkut Ortaokulu',
  'ANTALYA - KEPEZ - Mustafa Adıyaman Ortaokulu',
  'ANTALYA - KEPEZ - Özen Külahçıoğlu Kızılay Anaokulu',
  'ANTALYA - KEPEZ - Şerife Tufan İlkokulu',
  'ANTALYA - KEPEZ - Ahmet-Leman Baydar İlkokulu',
  'ANTALYA - KEPEZ - Ali Uyaroğlu İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Şehit Yüzbaşı İbrahim Barış Yurtseven Ortaokulu',
  'ANTALYA - KEPEZ - Sunay-Gönül-Türkan-Saadet Saygan Kardeşler-5 Anaokulu',
  'ANTALYA - KEPEZ - Kepez Çamlıbel Halk Eğitimi Merkezi',
  'ANTALYA - KEPEZ - Kepez Şehit Fırat Yıldırım Ortaokulu',
  'ANTALYA - KEPEZ - Altınova Esen İlkokulu',
  'ANTALYA - KEPEZ - Gaziler İlkokulu',
  'ANTALYA - KEPEZ - Gaziler Ortaokulu',
  'ANTALYA - KEPEZ - Mevlana İlkokulu',
  'ANTALYA - KEPEZ - Demirgül Ortaokulu',
  'ANTALYA - KEPEZ - Kepez Şehit Hüseyin Gökhan Eriç İlkokulu',
  'ANTALYA - KEPEZ - Beşkonak İlkokulu',
  'ANTALYA - KEPEZ - Kepez Şehit Ali Yılmaz İlkokulu',
  'ANTALYA - KEPEZ - General Şadi Çetinkaya İlkokulu',
  'ANTALYA - KEPEZ - Kızıllı İlkokulu',
  'ANTALYA - KEPEZ - Kızıllı Ortaokulu',
  'ANTALYA - KEPEZ - Kepez İlkokulu',
  'ANTALYA - KEPEZ - Hüsniye Özdilek Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Göksu İlkokulu',
  'ANTALYA - KEPEZ - Şehit Kadir Can Ortaokulu',
  'ANTALYA - KEPEZ - Beşkonak Ortaokulu',
  'ANTALYA - KEPEZ - Baraj Ortaokulu',
  'ANTALYA - KEPEZ - Kepez İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - HACI EKREM-ŞERİFE YAZAROĞLU ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - KEPEZ - Varsak Anadolu Lisesi',
  'ANTALYA - KEPEZ - Odabaşı Sevinç Fahri Aydın İlkokulu',
  'ANTALYA - KEPEZ - BAŞKÖY ORTAOKULU',
  'ANTALYA - KEPEZ - BAŞKÖY İLKOKULU',
  'ANTALYA - KEPEZ - Şehit Çetin Çakmak Anadolu İmam Hatip Lisesi',
  'ANTALYA - KEPEZ - Alpay Kalkandelen Anaokulu',
  'ANTALYA - KEPEZ - Makbule-Mehmet Karabacak Anaokulu',
  'ANTALYA - KEPEZ - ŞEHİT KAHRAMAN ÇELİKBAŞ ORTAOKULU',
  'ANTALYA - KEPEZ - Amine Hatun Kız Anadolu İmam Hatip Lisesi',
  'ANTALYA - KEPEZ - EMİNE-FATMA ÇEVİK ANAOKULU',
  'ANTALYA - KEPEZ - Yüzbaşı Mustafa Ertuğrul İlkokulu',
  'ANTALYA - KEPEZ - FATMA NUR ÇELİK İMAM HATİP ORTAOKULU',
  'ANTALYA - KEPEZ - KEPEZ MAHMUT CELALETTİN ÖKTEN ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - KEPEZ - GÜLVEREN İMAM HATİP ORTAOKULU',
  'ANTALYA - KEPEZ - Şehit Muhittin Talha Çalışkan Anadolu Lisesi',
  'ANTALYA - KEPEZ - ŞEHİT KAZIM ESMER İLKOKULU',
  'ANTALYA - KEPEZ - Turgut Reis İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - Ernur - Faik Koparan İmam Hatip Ortaokulu',
  'ANTALYA - KEPEZ - ANTALYA TÜRKİYE ODALAR VE BORSALAR BİRLİĞİ FEN LİSESİ',
  'ANTALYA - KEPEZ - YUNUS EMRE İMAM HATİP ORTAOKULU',
  'ANTALYA - KEPEZ - GÜLSÜM AHMET ŞİMŞEK ANAOKULU',
  'ANTALYA - KEPEZ - GAZİLER İMAM HATİP ORTAOKULU',
  'ANTALYA - KEPEZ - ALTINOVA İMAM HATİP ORTAOKULU',
  'ANTALYA - KEPEZ - MOBİL İMAM HATİP ORTAOKULU',
  'ANTALYA - KEPEZ - HABİBLER İMAM HATİP ORTAOKULU',
  'ANTALYA - KEPEZ - Neriman-Erol Yılmaz Sosyal Bilimler Lisesi',
  'ANTALYA - KEPEZ - GÜLVEREN ANADOLU LİSESİ',
  'ANTALYA - KEPEZ - PROF. DR. RAŞİT KÜÇÜK ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - KEPEZ - KEPEZ ÖZEL EĞİTİM MESLEK OKULU',
  'ANTALYA - KEPEZ - ŞEHİT BEBEK MUSTAFA BEDİRHAN KARAKAYA ANAOKULU',
  'ANTALYA - KEPEZ - KAAN TURAN ORTAOKULU',
  'ANTALYA - KEPEZ - ŞEHİT METİN DARBAŞ ORTAOKULU',
  'ANTALYA - KEPEZ - Kepez Özel Eğitim Uygulama Okulu III. Kademe',
  'ANTALYA - KEPEZ - Nergis Cömertoğlu Anaokulu',
  'ANTALYA - KEPEZ - Hacı Çetin Babüroğlu Ortaokulu',
  'ANTALYA - KEPEZ - Şehit Ufuk Baysan İlkokulu',
  'ANTALYA - KEPEZ - Akdeniz Sanayi Sitesi Anadolu Lisesi',
  'ANTALYA - KEPEZ - Nevin Ahmet Selçuk Anaokulu',
  'ANTALYA - KEPEZ - Gülşen - Mehmet Fehmi Diktaş Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KEPEZ - Salih Konca Anaokulu',
  'ANTALYA - KEPEZ - Ümmü Limon Anaokulu',
  'ANTALYA - KEPEZ - Ahmet -Bahriye Şenyurt Anaokulu',
  'ANTALYA - KEPEZ - Kepez Bilim ve Sanat Merkezi Anaokulu',
  'ANTALYA - KEPEZ - Kepez Meslekî Eğitim Merkezi',
  'ANTALYA - KEPEZ - Şehit Yusuf Önder Anaokulu',
  'ANTALYA - KEPEZ - Gülgün Nihat Ömür Anaokulu',
  'ANTALYA - KEPEZ - Gülveren Anaokulu',
  'ANTALYA - KEPEZ - Musa Buzkıran Anaokulu',
  'ANTALYA - KEPEZ - Mehmet Kemal Dedeman Anaokulu',
  'ANTALYA - KEPEZ - İbrahim Doğaner Anaokulu',
  'ANTALYA - KEPEZ - Bolat Yıldırım Anaokulu',
  'ANTALYA - KEPEZ - General Şadi Çetinkaya Anaokulu',
  'ANTALYA - KEPEZ - Yedi Kuyular Anaokulu',
  'ANTALYA - KEPEZ - Mareşal Fevzi Çakmak Anaokulu',
  'ANTALYA - KEPEZ - Kepez Şehit Hakan Karakaya Anaokulu',
  'ANTALYA - KEPEZ - Şehit Jandarma Üsteğmen Gökhan Korkut Anaokulu',
  'ANTALYA - KEPEZ - Varsak Şelale Anaokulu',
  'ANTALYA - KEPEZ - Fikret Haluk Saraçoğlu Anaokulu',
  'ANTALYA - KEPEZ - Mimar Sinan Anaokulu',
  'ANTALYA - KEPEZ - Ünsal Anaokulu',
  'ANTALYA - KEPEZ - Hüseyin Ak Anaokulu',
  'ANTALYA - KEPEZ - Mevlana Anaokulu',
  'ANTALYA - KEPEZ - İsmail Hakkı Kaya Anaokulu',
  'ANTALYA - KEPEZ - Şerife Tufan Anaokulu',
  'ANTALYA - KEPEZ - Turgut Reis Anaokulu',
  'ANTALYA - KEPEZ - Şehit Kahraman Çelikbaş Anaokulu',
  'ANTALYA - KEPEZ - Şehit İlyas Acar Anaokulu',
  'ANTALYA - KEPEZ - Kepez Şehit Ali Yılmaz Anaokulu',
  'ANTALYA - KEPEZ - Kamile Metin Yapar Anaokulu',
  'ANTALYA - KEPEZ - Duraliler Anaokulu',
  'ANTALYA - KEPEZ - İsmail İltemir Anaokulu',
  'ANTALYA - KEPEZ - Şehit Selahattin Aysan Anaokulu',
  'ANTALYA - KEPEZ - Şehit Ufuk Baysan Anaokulu',
  'ANTALYA - KEPEZ - Şehit Yüzbaşı İbrahim Barış Yurtseven Anaokulu',
  'ANTALYA - KEPEZ - Fatih Selek - Ali Işıkhan Anaokulu',
  'ANTALYA - KEPEZ - Kepez Özel Eğitim Anaokulu',
  'ANTALYA - KEPEZ - Şehit Çetin Çakmak Anaokulu',
  'ANTALYA - KEPEZ - Kübra - Mümün Soydal Ortaokulu',
  'ANTALYA - KEPEZ - Ahatlı Anaokulu',
  'ANTALYA - KONYAALTI - Akdeniz Anadolu Lisesi',
  'ANTALYA - KONYAALTI - Aşağıkaraman İlkokulu',
  'ANTALYA - KONYAALTI - Doyran Ayten-Şevket Gülveren İlkokulu',
  'ANTALYA - KONYAALTI - Dr.Günseli-Dr.Bülent Akınsal Özel Eğitim Ortaokulu',
  'ANTALYA - KONYAALTI - Fettah Tamince Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KONYAALTI - Saime Salih Konca Ortaokulu',
  'ANTALYA - KONYAALTI - Gökçam İlkokulu',
  'ANTALYA - KONYAALTI - Konyaaltı Halit Uluç İmam Hatip Ortaokulu',
  'ANTALYA - KONYAALTI - Konyaaltı Halk Eğitimi Merkezi',
  'ANTALYA - KONYAALTI - Z.Marsel - Z.Denizhan Öner Ortaokulu',
  'ANTALYA - KONYAALTI - Saime Salih Konca İlkokulu',
  'ANTALYA - KONYAALTI - Konyaaltı İmam Hatip Ortaokulu',
  'ANTALYA - KONYAALTI - Konyaaltı Rehberlik ve Araştırma Merkezi',
  'ANTALYA - KONYAALTI - Siteler Mahallesi İlkokulu',
  'ANTALYA - KONYAALTI - Z.Marsel-Z.Denizhan Öner İlkokulu',
  'ANTALYA - KONYAALTI - Leyla Kahraman Sevim Ertenü Ortaokulu',
  'ANTALYA - KONYAALTI - Konyaaltı Anadolu Lisesi',
  'ANTALYA - KONYAALTI - Şehit Abdulkadir Güler Ortaokulu',
  'ANTALYA - KONYAALTI - Bedriye Bileydi İlkokulu',
  'ANTALYA - KONYAALTI - Abdurrahman Neriman Bileydi İlkokulu',
  'ANTALYA - KONYAALTI - Abdurrahman-Neriman Bileydi Ortaokulu',
  'ANTALYA - KONYAALTI - Çakırlar Ortaokulu',
  'ANTALYA - KONYAALTI - Çakırlar İlkokulu',
  'ANTALYA - KONYAALTI - Dr. İlhami Tankut Anadolu Lisesi',
  'ANTALYA - KONYAALTI - Şehit Teğmen Ayfer Gök Anaokulu',
  'ANTALYA - KONYAALTI - Gazi Mustafa Kemal Ortaokulu',
  'ANTALYA - KONYAALTI - Dr.Cahit Ünver Ortaokulu',
  'ANTALYA - KONYAALTI - Dr.Cahit Ünver İlkokulu',
  'ANTALYA - KONYAALTI - Gazi Mustafa Kemal İlkokulu',
  'ANTALYA - KONYAALTI - Hasan-Fatma Çavlı Ortaokulu',
  'ANTALYA - KONYAALTI - Konyaaltı İlkokulu',
  'ANTALYA - KONYAALTI - Ayten Çağıran Ortaokulu',
  'ANTALYA - KONYAALTI - Alper Duru Anaokulu',
  'ANTALYA - KONYAALTI - Dr.Günseli - Dr.Bülent Akınsal Özel Eğitim Meslek Okulu',
  'ANTALYA - KONYAALTI - Aşağıkaraman Ortaokulu',
  'ANTALYA - KONYAALTI - Hasan-Fatma Çavlı İlkokulu',
  'ANTALYA - KONYAALTI - Doyran Ayten-Şevket Gülveren Ortaokulu',
  'ANTALYA - KONYAALTI - Konyaaltı Bahtılı Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KONYAALTI - KONYAALTI MEHMET ZEKİ BALCI MESLEKİ VE TEKNİK ANADOLU LİSESİ',
  'ANTALYA - KONYAALTI - MÜRÜVET ALPAGOT ANAOKULU',
  'ANTALYA - KONYAALTI - HURMA YARBAY PINAR İLKOKULU',
  'ANTALYA - KONYAALTI - UNCUALİ ANAOKULU',
  'ANTALYA - KONYAALTI - MUHİTTİN MUSTAFA BÖCEK ANADOLU LİSESİ',
  'ANTALYA - KONYAALTI - HAYME ANA KIZ ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - KONYAALTI - Şehit Cennet Yiğit Anaokulu',
  'ANTALYA - KONYAALTI - Konyaaltı Mehmet Zeki Balcı Öğretmenevi Müdürlüğü',
  'ANTALYA - KONYAALTI - Konyaaltı Çankırı Anadolu İmam Hatip Lisesi',
  'ANTALYA - KONYAALTI - ÇAKIRLAR İMAM HATİP ORTAOKULU',
  'ANTALYA - KONYAALTI - Akdeniz Üniversitesi Antalya Dev.Kon. Müzik ve Sahne Sanatları Lisesi',
  'ANTALYA - KONYAALTI - Akdeniz Üniversitesi Antalya Dev.Kon. Müzik ve Bale Ortaokulu',
  'ANTALYA - KONYAALTI - Akdeniz Üniversitesi Antalya Dev.Kon. Müzik ve Bale İlkokulu',
  'ANTALYA - KONYAALTI - Bahtılı Anadolu Lisesi',
  'ANTALYA - KONYAALTI - Özpınarlar Fahrettin Sert İlkokulu',
  'ANTALYA - KONYAALTI - Konyaaltı Bilim ve Sanat Merkezi',
  'ANTALYA - KONYAALTI - Bedriye Bileydi Anaokulu',
  'ANTALYA - KONYAALTI - Hurma Yarbay Pınar Anaokulu',
  'ANTALYA - KONYAALTI - Konyaaltı Özel Eğitim Anaokulu',
  'ANTALYA - KONYAALTI - Konyaaltı Anaokulu',
  'ANTALYA - KONYAALTI - Dr.Cahit Ünver Anaokulu',
  'ANTALYA - KONYAALTI - Özpınarlar Tenzile Sert Ortaokulu',
  'ANTALYA - KORKUTELİ - Avdan Şehit Ahmet Belen İlkokulu',
  'ANTALYA - KORKUTELİ - Bozova Şehit Öğretmen Metin Kaynar İlkokulu',
  'ANTALYA - KORKUTELİ - Şehit Yasin Naci Ağaroğlu Anadolu İmam Hatip Lisesi',
  'ANTALYA - KORKUTELİ - İmrahor İstiklal İlkokulu',
  'ANTALYA - KORKUTELİ - Korkuteli Nene Hatun Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KORKUTELİ - Hacı Ethem-Şerife Kavukçu Anadolu Lisesi',
  'ANTALYA - KORKUTELİ - Mesude - Erol Memioğlu Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KORKUTELİ - Korkuteli Lokman Hekim Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KORKUTELİ - Korkuteli Mesleki Eğitim Merkezi',
  'ANTALYA - KORKUTELİ - Küçükköy Şehit Adem Yörük İlkokulu',
  'ANTALYA - KORKUTELİ - Öğretmen Evi ve Akşam Sanat Okulu',
  'ANTALYA - KORKUTELİ - Yazır Fevziye Polat Ortaokulu',
  'ANTALYA - KORKUTELİ - Yazır Fevziye Polat İlkokulu',
  'ANTALYA - KORKUTELİ - Osman Önal İlkokulu',
  'ANTALYA - KORKUTELİ - Fatma Mehmet Cadıl Fen Lisesi',
  'ANTALYA - KORKUTELİ - Alaeddin İlkokulu',
  'ANTALYA - KORKUTELİ - Alaeddin Ortaokulu',
  'ANTALYA - KORKUTELİ - Büyükköy İlkokulu',
  'ANTALYA - KORKUTELİ - Arif Cebeci Ortaokulu',
  'ANTALYA - KORKUTELİ - Kızılcadağ İlkokulu',
  'ANTALYA - KORKUTELİ - Yaşar Sadi Tekin İlkokulu',
  'ANTALYA - KORKUTELİ - Korkuteli Sevim - Cevat Soyiç Halk Eğitimi Merkezi',
  'ANTALYA - KORKUTELİ - Dereköy Ortaokulu',
  'ANTALYA - KORKUTELİ - Dereköy İlkokulu',
  'ANTALYA - KORKUTELİ - Sülekler Şehit Semih Aldemir İlkokulu',
  'ANTALYA - KORKUTELİ - Sülekler Şehit Semih Aldemir Ortaokulu',
  'ANTALYA - KORKUTELİ - Bozova Şehit Öğretmen Metin Kaynar Ortaokulu',
  'ANTALYA - KORKUTELİ - Cumhuriyet Ortaokulu',
  'ANTALYA - KORKUTELİ - Akyar İlkokulu',
  'ANTALYA - KORKUTELİ - Yelten Dallar Ortaokulu',
  'ANTALYA - KORKUTELİ - Yelten Dallar İlkokulu',
  'ANTALYA - KORKUTELİ - Gümüşlü İlkokulu',
  'ANTALYA - KORKUTELİ - Erkunt Traktör Ortaokulu',
  'ANTALYA - KORKUTELİ - Fikriye-Ramazan Yalçın İlkokulu',
  'ANTALYA - KORKUTELİ - Yeşilyayla Ortaokulu',
  'ANTALYA - KORKUTELİ - Nadide-Ahmet Balaban Anaokulu',
  'ANTALYA - KORKUTELİ - Büyükköy Ortaokulu',
  'ANTALYA - KORKUTELİ - Yeşilyayla İlkokulu',
  'ANTALYA - KORKUTELİ - Tatköy Ramazan Karabağır İlkokulu',
  'ANTALYA - KORKUTELİ - Yaşar Yalçın İlkokulu',
  'ANTALYA - KORKUTELİ - Kozağacı İlkokulu',
  'ANTALYA - KORKUTELİ - İmrahor İstiklal Ortaokulu',
  'ANTALYA - KORKUTELİ - Kayabaş İlkokulu',
  'ANTALYA - KORKUTELİ - Şehit Tuncay Arslan İmam Hatip Ortaokulu',
  'ANTALYA - KORKUTELİ - ULUCAK ŞEHİT MUSTAFA DEMİR İLKOKULU',
  'ANTALYA - KORKUTELİ - Hasan Özdemirci Kız Anadolu İmam Hatip Lisesi',
  'ANTALYA - KORKUTELİ - Nazlı-İrfan Önal İmam Hatip Ortaokulu',
  'ANTALYA - KORKUTELİ - Fikriye Ramazan Yalçın İmam Hatip Ortaokulu',
  'ANTALYA - KORKUTELİ - Yeşilyayla İmam Hatip Ortaokulu',
  'ANTALYA - KORKUTELİ - DEREKÖY İMAM HATİP ORTAOKULU',
  'ANTALYA - KORKUTELİ - KÜÇÜKKÖY ŞEHİT ADEM YÖRÜK İMAM HATİP ORTAOKULU',
  'ANTALYA - KORKUTELİ - Erkunt Traktör İmam Hatip Ortaokulu',
  'ANTALYA - KORKUTELİ - SÜLEKLER ŞEHİT SEMİH ALDEMİR İMAM HATİP ORTAOKULU',
  'ANTALYA - KORKUTELİ - YAZIR FEVZİYE POLAT İMAM HATİP ORTAOKULU',
  'ANTALYA - KORKUTELİ - TATKÖY RAMAZAN KARABAĞIR İMAM HATİP ORTAOKULU',
  'ANTALYA - KORKUTELİ - KIZILCADAĞ İMAM HATİP ORTAOKULU',
  'ANTALYA - KORKUTELİ - ZEYNEP MUSTAFA KEMER ORTAOKULU',
  'ANTALYA - KORKUTELİ - Cumhuriyet Gülhizar-Osman Sarıca İmam Hatip Ortaokulu',
  'ANTALYA - KORKUTELİ - Kırkpınar İlkokulu',
  'ANTALYA - KORKUTELİ - Küçüklü Mareşal Fevzi Çakmak İlkokulu',
  'ANTALYA - KORKUTELİ - Çomaklı İlkokulu',
  'ANTALYA - KORKUTELİ - İmecik İlkokulu',
  'ANTALYA - KORKUTELİ - Bayat İlkokulu',
  'ANTALYA - KORKUTELİ - Korkuteli Özel Eğitim Anaokulu',
  'ANTALYA - KUMLUCA - 80. Yıl Beykonak Ortaokulu',
  'ANTALYA - KUMLUCA - Ahmet Avcıoğlu İlkokulu',
  'ANTALYA - KUMLUCA - Kumluca Anadolu İmam Hatip Lisesi',
  'ANTALYA - KUMLUCA - Kumluca Halk Eğitimi Merkezi',
  'ANTALYA - KUMLUCA - Karacaören Karabük İlkokulu',
  'ANTALYA - KUMLUCA - Kumluca Fatih Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KUMLUCA - Kumluca Sosyal Bilimler Lisesi',
  'ANTALYA - KUMLUCA - Kumluca Farabi Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KUMLUCA - Beykonak Anadolu Lisesi',
  'ANTALYA - KUMLUCA - Kumluca Şehit Ömer Halisdemir İmam Hatip Ortaokulu',
  'ANTALYA - KUMLUCA - Mavikent Mustafa-Ayşe Acarbulut Anadolu Lisesi',
  'ANTALYA - KUMLUCA - Kumluca Rehberlik ve Araştırma Merkezi',
  'ANTALYA - KUMLUCA - Mavikent Çanakçı 75.Yıl İlkokulu',
  'ANTALYA - KUMLUCA - Mavikent Ramazan Abacı İlkokulu',
  'ANTALYA - KUMLUCA - Kumluca Mesleki Eğitim Merkezi',
  'ANTALYA - KUMLUCA - Mimar Sinan İlkokulu',
  'ANTALYA - KUMLUCA - Münire-Osman Alkan İlkokulu',
  'ANTALYA - KUMLUCA - Sarıcasu Darıyemezler İlkokulu',
  'ANTALYA - KUMLUCA - Sarıcasu Darıyemezler Ortaokulu',
  'ANTALYA - KUMLUCA - Sultan Alparslan İlkokulu',
  'ANTALYA - KUMLUCA - Ziya Gökalp Yatılı Bölge Ortaokulu',
  'ANTALYA - KUMLUCA - Beykonak Sevim Öner İlkokulu',
  'ANTALYA - KUMLUCA - Beykonak Sevim Öner Ortaokulu',
  'ANTALYA - KUMLUCA - Kumluca Anadolu Lisesi',
  'ANTALYA - KUMLUCA - Adrasan Mehmet Akif Ersoy Ortaokulu',
  'ANTALYA - KUMLUCA - Salur İlkokulu',
  'ANTALYA - KUMLUCA - Mavikent Ramazan Abacı Ortaokulu',
  'ANTALYA - KUMLUCA - Atatürk Ortaokulu',
  'ANTALYA - KUMLUCA - Kumluca Gül-Çetin Kaur Anadolu Lisesi',
  'ANTALYA - KUMLUCA - Salur Ortaokulu',
  'ANTALYA - KUMLUCA - Ahmet Avcıoğlu Ortaokulu',
  'ANTALYA - KUMLUCA - Hacıveliler İlkokulu',
  'ANTALYA - KUMLUCA - Şehit Hasan Öztürk İlkokulu',
  'ANTALYA - KUMLUCA - Hacıveliler Ortaokulu',
  'ANTALYA - KUMLUCA - Barbaros İlkokulu',
  'ANTALYA - KUMLUCA - Barbaros Ortaokulu',
  'ANTALYA - KUMLUCA - Mavikent Durali Yazıcı İlkokulu',
  'ANTALYA - KUMLUCA - Mavikent Durali Yazıcı Ortaokulu',
  'ANTALYA - KUMLUCA - Cumhuriyet İlkokulu',
  'ANTALYA - KUMLUCA - Şehit Hasan Öztürk Ortaokulu',
  'ANTALYA - KUMLUCA - Öğretmen Evi ve Akşam Sanat Okulu',
  'ANTALYA - KUMLUCA - Atatürk İlkokulu',
  'ANTALYA - KUMLUCA - Kasapçayırı Ortaokulu',
  'ANTALYA - KUMLUCA - Adrasan Mehmet Akif Ersoy İlkokulu',
  'ANTALYA - KUMLUCA - 80. Yıl Beykonak İlkokulu',
  'ANTALYA - KUMLUCA - Cumhuriyet Ortaokulu',
  'ANTALYA - KUMLUCA - Kasapçayırı İlkokulu',
  'ANTALYA - KUMLUCA - Kumluca Anaokulu',
  'ANTALYA - KUMLUCA - Mimar Sinan Ortaokulu',
  'ANTALYA - KUMLUCA - Kumluca Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - KUMLUCA - HAVVA-SEDAT ATİLLA AVCIOĞLU FEN LİSESİ',
  'ANTALYA - KUMLUCA - Kumluca Sarıcasu Özel Eğitim Meslek Okulu',
  'ANTALYA - KUMLUCA - KUMLUCA KIZ ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - KUMLUCA - MAVİKENT ÇANAKÇI 75.YIL İMAM HATİP ORTAOKULU',
  'ANTALYA - KUMLUCA - Bayram Çiftçi İmam Hatip Ortaokulu',
  'ANTALYA - KUMLUCA - Kumluca Spor Lisesi',
  'ANTALYA - KUMLUCA - ADRASAN MEHMET AKİF ERSOY İMAM HATİP ORTAOKULU',
  'ANTALYA - KUMLUCA - KUMLUCA ÖZEL EĞİTİM UYGULAMA OKULU I. KADEME',
  'ANTALYA - KUMLUCA - KUMLUCA ÖZEL EĞİTİM UYGULAMA OKULU II. KADEME',
  'ANTALYA - KUMLUCA - Kumluca Portakal Çiçeği Anaokulu',
  'ANTALYA - KUMLUCA - Cumhuriyet Anaokulu',
  'ANTALYA - KUMLUCA - Kızılay Anaokulu',
  'ANTALYA - KUMLUCA - Mavikent Durali Yazıcı Anaokulu',
  'ANTALYA - KUMLUCA - Kumluca Özel Eğitim Anaokulu',
  'ANTALYA - KUMLUCA - Mavikent Ramazan Abacı Anaokulu',
  'ANTALYA - KUMLUCA - Sultan Alparslan Anaokulu',
  'ANTALYA - MANAVGAT - Şule - Muzaffer Büyük Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Dolbazlar İlkokulu',
  'ANTALYA - MANAVGAT - Dolbazlar Ortaokulu',
  'ANTALYA - MANAVGAT - Manavgat F. Yılmaz Sezer Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Manavgat Anadolu İmam-Hatip Lisesi',
  'ANTALYA - MANAVGAT - Manavgat Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Manavgat Lisesi',
  'ANTALYA - MANAVGAT - Manavgat Evliya Çelebi Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Manavgat Ticaret ve Sanayi Odası Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Manavgat Mesleki Eğitim Merkezi',
  'ANTALYA - MANAVGAT - Milli Egemenlik İlkokulu',
  'ANTALYA - MANAVGAT - Seki Köseoğlu Anaokulu',
  'ANTALYA - MANAVGAT - Ulukapı Merkez İlkokulu',
  'ANTALYA - MANAVGAT - Kızılağaç Ünal Akpınar Ortaokulu',
  'ANTALYA - MANAVGAT - Karabucak İlkokulu',
  'ANTALYA - MANAVGAT - Manavgat Kemer Fatma Turgut Şen Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Gebece İlkokulu',
  'ANTALYA - MANAVGAT - Çolaklı Yahya Kurt Ortaokulu',
  'ANTALYA - MANAVGAT - Çolaklı İlkokulu',
  'ANTALYA - MANAVGAT - Dr.Hüseyin Vural Özel Eğitim İlkokulu',
  'ANTALYA - MANAVGAT - Hacı Sultan Mehmet Kara Ortaokulu',
  'ANTALYA - MANAVGAT - Belenobası Ortaokulu',
  'ANTALYA - MANAVGAT - Karabük İlkokulu',
  'ANTALYA - MANAVGAT - Atatürk İlkokulu',
  'ANTALYA - MANAVGAT - Manavgat Halk Eğitimi Merkezi',
  'ANTALYA - MANAVGAT - Şelale Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Manavgat Taşağıl Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Evrenseki Ahmet Köseoğlu İlkokulu',
  'ANTALYA - MANAVGAT - Çavuşköy İlkokulu',
  'ANTALYA - MANAVGAT - Manavgat Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Manavgat Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Burmahan İlkokulu',
  'ANTALYA - MANAVGAT - Kemer Turgut Şen İlkokulu',
  'ANTALYA - MANAVGAT - Ilıca İlkokulu',
  'ANTALYA - MANAVGAT - Ilıca Ortaokulu',
  'ANTALYA - MANAVGAT - Ilıca Mehmet Ali Karamancı İlkokulu',
  'ANTALYA - MANAVGAT - Namık Karamancı Fen Lisesi',
  'ANTALYA - MANAVGAT - Yeşilbağ Cumhuriyet İlkokulu',
  'ANTALYA - MANAVGAT - Yeşilbağ Cumhuriyet Ortaokulu',
  'ANTALYA - MANAVGAT - Ilıca Mehmet Ali Karamancı Ortaokulu',
  'ANTALYA - MANAVGAT - 75. Yıl Cumhuriyet Ortaokulu',
  'ANTALYA - MANAVGAT - Hatıplar İlkokulu',
  'ANTALYA - MANAVGAT - 75. Yıl Cumhuriyet İlkokulu',
  'ANTALYA - MANAVGAT - Gündoğdu Düriye Duran İlkokulu',
  'ANTALYA - MANAVGAT - Gündoğdu Düriye Duran Ortaokulu',
  'ANTALYA - MANAVGAT - Toros Ortaokulu',
  'ANTALYA - MANAVGAT - Beşkonak Yatılı Bölge Ortaokulu',
  'ANTALYA - MANAVGAT - Ali İhsan Barut İlkokulu',
  'ANTALYA - MANAVGAT - Çağlayan Ortaokulu',
  'ANTALYA - MANAVGAT - Çağlayan İlkokulu',
  'ANTALYA - MANAVGAT - Borsa İstanbul İlkokulu',
  'ANTALYA - MANAVGAT - Çağlayan Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Sağırin İlkokulu',
  'ANTALYA - MANAVGAT - Sağırin Ortaokulu',
  'ANTALYA - MANAVGAT - Çardak Şehit Piyade Uzman Çavuş Mustafa Uysal Ortaokulu',
  'ANTALYA - MANAVGAT - Çardak Şehit Piyade Uzman Çavuş Mustafa Uysal İlkokulu',
  'ANTALYA - MANAVGAT - Çakış Ortaokulu',
  'ANTALYA - MANAVGAT - Iraz-Düriye Duran Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Mehmet Bozkurt İlkokulu',
  'ANTALYA - MANAVGAT - Kızılot Ahmet Yaşar İlkokulu',
  'ANTALYA - MANAVGAT - Kızılot Ahmet Yaşar Ortaokulu',
  'ANTALYA - MANAVGAT - Çakış İlkokulu',
  'ANTALYA - MANAVGAT - Çavuşköy Ortaokulu',
  'ANTALYA - MANAVGAT - Manavgat Rehberlik ve Araştırma Merkezi',
  'ANTALYA - MANAVGAT - Evrenseki Ahmet Köseoğlu Ortaokulu',
  'ANTALYA - MANAVGAT - Çeltikci İlkokulu',
  'ANTALYA - MANAVGAT - Çeltikci Ortaokulu',
  'ANTALYA - MANAVGAT - 60. Yıl İlkokulu',
  'ANTALYA - MANAVGAT - 60. Yıl Ortaokulu',
  'ANTALYA - MANAVGAT - Belenobası İlkokulu',
  'ANTALYA - MANAVGAT - Küçük Hasan İlkokulu',
  'ANTALYA - MANAVGAT - Hatice Sezer Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Denizyaka Ortaokulu',
  'ANTALYA - MANAVGAT - Denizyaka İlkokulu',
  'ANTALYA - MANAVGAT - Şehit Ahmet Ozan Şarlak Ortaokulu',
  'ANTALYA - MANAVGAT - Sarılar İlkokulu',
  'ANTALYA - MANAVGAT - Atatürk Ortaokulu',
  'ANTALYA - MANAVGAT - Toros İlkokulu',
  'ANTALYA - MANAVGAT - Odaönü Çallıoğlu Ortaokulu',
  'ANTALYA - MANAVGAT - Odaönü Çallıoğlu İlkokulu',
  'ANTALYA - MANAVGAT - Milli Egemenlik Ortaokulu',
  'ANTALYA - MANAVGAT - Kızılağaç Ünal Akpınar İlkokulu',
  'ANTALYA - MANAVGAT - Mehmet Bozkurt Ortaokulu',
  'ANTALYA - MANAVGAT - Çolaklı Anaokulu',
  'ANTALYA - MANAVGAT - Manavgat Anaokulu',
  'ANTALYA - MANAVGAT - Doğançam İlkokulu',
  'ANTALYA - MANAVGAT - Taşağıl İlkokulu',
  'ANTALYA - MANAVGAT - Şehit Mehmet Koparan Ortaokulu',
  'ANTALYA - MANAVGAT - Ramazan Tunç İlkokulu',
  'ANTALYA - MANAVGAT - Öğer Ortaokulu',
  'ANTALYA - MANAVGAT - Altınkaya İlkokulu',
  'ANTALYA - MANAVGAT - Yunus Emre Ortaokulu',
  'ANTALYA - MANAVGAT - Yunus Emre İlkokulu',
  'ANTALYA - MANAVGAT - Örenşehir Yalışehir İlkokulu',
  'ANTALYA - MANAVGAT - Karacalar Fatma Pakize Turhan Ortaokulu',
  'ANTALYA - MANAVGAT - Karacalar Fatma Pakize Turhan İlkokulu',
  'ANTALYA - MANAVGAT - Bucak Şeyhler İlkokulu',
  'ANTALYA - MANAVGAT - Cenger İlkokulu',
  'ANTALYA - MANAVGAT - Beydiğin İlkokulu',
  'ANTALYA - MANAVGAT - FATMA TEMEL TURHAN ANADOLU LİSESİ',
  'ANTALYA - MANAVGAT - Ayşe - Rıza Kasapoğlu Kız Anadolu İmam Hatip Lisesi',
  'ANTALYA - MANAVGAT - Kızıldağ Çorak İlkokulu',
  'ANTALYA - MANAVGAT - KIZILDAĞ İLKOKULU',
  'ANTALYA - MANAVGAT - KIRKKAVAK İLKOKULU',
  'ANTALYA - MANAVGAT - YAVRUDOĞAN ORTAOKULU',
  'ANTALYA - MANAVGAT - YAVRUDOĞAN İLKOKULU',
  'ANTALYA - MANAVGAT - BEREKET İLKOKULU',
  'ANTALYA - MANAVGAT - BEREKET ORTAOKULU',
  'ANTALYA - MANAVGAT - Manavgat Rukiye - Raşit Meşhur Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MANAVGAT - DR.HÜSEYİN VURAL ÖZEL EĞİTİM MESLEKİ EĞİTİM MERKEZİ (OKULU)',
  'ANTALYA - MANAVGAT - SAĞIRİN KEPEZ İLKOKULU',
  'ANTALYA - MANAVGAT - DEĞİRMENLİ İLKOKULU',
  'ANTALYA - MANAVGAT - HAYME HATUN ANAOKULU',
  'ANTALYA - MANAVGAT - HACI ŞAYESTE-MUSTAFA GÜNEŞ ANAOKULU',
  'ANTALYA - MANAVGAT - HACI ŞAYESTE-MUSTAFA GÜNEŞ ORTAOKULU',
  'ANTALYA - MANAVGAT - Ulukapı Sülek Şehit Halil İbrahim Mudul İlkokulu',
  'ANTALYA - MANAVGAT - Şehit Uğur Yıldız İmam Hatip Ortaokulu',
  'ANTALYA - MANAVGAT - Gül Salih Şenli İlkokulu',
  'ANTALYA - MANAVGAT - DEĞİRMENLİ ORTAOKULU',
  'ANTALYA - MANAVGAT - Gevher Nesibe Özel Eğitim Uygulama Okulu I. Kademe',
  'ANTALYA - MANAVGAT - Manavgat 15 Temmuz Şehitler İmam Hatip Ortaokulu',
  'ANTALYA - MANAVGAT - SÜLEK İLKOKULU',
  'ANTALYA - MANAVGAT - MANAVGAT ILICA ANAOKULU',
  'ANTALYA - MANAVGAT - YAVUZ SULTAN SELİM İMAM HATİP ORTAOKULU',
  'ANTALYA - MANAVGAT - Fatih Sultan Mehmet Anadolu Lisesi',
  'ANTALYA - MANAVGAT - HAVVA BAYAZ ANAOKULU',
  'ANTALYA - MANAVGAT - ERTUĞRUL GAZİ ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - MANAVGAT - ÇOLAKLI YAHYA KURT İMAM HATİP ORTAOKULU',
  'ANTALYA - MANAVGAT - MEHMET BOZKURT İMAM HATİP ORTAOKULU',
  'ANTALYA - MANAVGAT - ÇELTİKÇİ İMAM HATİP ORTAOKULU',
  'ANTALYA - MANAVGAT - GEVHER NESİBE ÖZEL EĞİTİM UYGULAMA OKULU II. KADEME',
  'ANTALYA - MANAVGAT - MANAVGAT BİLİM VE SANAT MERKEZİ',
  'ANTALYA - MANAVGAT - Düzağaç İlkokulu',
  'ANTALYA - MANAVGAT - Dr.Hüseyin Vural Özel Eğitim Ortaokulu',
  'ANTALYA - MANAVGAT - Yaylaalan İlkokulu',
  'ANTALYA - MANAVGAT - Beşkonak İlkokulu',
  'ANTALYA - MANAVGAT - Ilıca Gülsüm-Ramazan Öz Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Mehmet Akif Ersoy Anadolu Lisesi',
  'ANTALYA - MANAVGAT - Beşkonak İmam Hatip Ortaokulu',
  'ANTALYA - MANAVGAT - Hüseyin Görkem Göksoy Anaokulu',
  'ANTALYA - MANAVGAT - Safiye Kübra Avcı Anaokulu',
  'ANTALYA - MANAVGAT - 75. Yıl Cumhuriyet Anaokulu',
  'ANTALYA - MANAVGAT - 60. Yıl Anaokulu',
  'ANTALYA - MANAVGAT - Toros Anaokulu',
  'ANTALYA - MANAVGAT - Sarılar Anaokulu',
  'ANTALYA - MANAVGAT - Küçük Hasan Anaokulu',
  'ANTALYA - MANAVGAT - Atatürk Anaokulu',
  'ANTALYA - MANAVGAT - Manavgat Özel Eğitim Anaokulu',
  'ANTALYA - MANAVGAT - Taşağıl Anaokulu',
  'ANTALYA - MANAVGAT - Çağlayan Anaokulu',
  'ANTALYA - MANAVGAT - Çeltikçi Anaokulu',
  'ANTALYA - MANAVGAT - Milli Egemenlik Anaokulu',
  'ANTALYA - MURATPAŞA - Ramazan - Hatice Savaş Özel Eğitim Uygulama Okulu III. Kademe',
  'ANTALYA - MURATPAŞA - Fatmagül Özpınar İlkokulu',
  'ANTALYA - MURATPAŞA - Ermenek Ortaokulu',
  'ANTALYA - MURATPAŞA - Kazım Şanöz İlkokulu',
  'ANTALYA - MURATPAŞA - Nadire Konuk ve Ali Oğuz Konuk İlkokulu',
  'ANTALYA - MURATPAŞA - Şehit Serkan Çölkesen Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Yavuz Selim Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Adem-Tolunay Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Antalya Barosu Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Ermenek İlkokulu',
  'ANTALYA - MURATPAŞA - Gazi Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Hacı Hafize Hakkı Saygan İlkokulu',
  'ANTALYA - MURATPAŞA - Hanım-Ömer Çağıran İlkokulu',
  'ANTALYA - MURATPAŞA - Levent Aydın Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Mehmetçik İlkokulu',
  'ANTALYA - MURATPAŞA - Melahat Faraçlar İlkokulu',
  'ANTALYA - MURATPAŞA - Tez-Tur Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Muratpaşa İmam Hatip Ortaokulu',
  'ANTALYA - MURATPAŞA - Muratpaşa Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Muratpaşa Türk Telekom Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Muratpaşa Rehberlik ve Araştırma Merkezi',
  'ANTALYA - MURATPAŞA - Vali Hüsnü Tuğlu İlkokulu',
  'ANTALYA - MURATPAŞA - Yunus Emre İlkokulu',
  'ANTALYA - MURATPAŞA - Mehmet Kesikçi İlkokulu',
  'ANTALYA - MURATPAŞA - Antalya Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Güzeloba Ortaokulu',
  'ANTALYA - MURATPAŞA - Dr.İlhami Tankut İlkokulu',
  'ANTALYA - MURATPAŞA - Antalya Ticaret Borsası Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Güzeloba İlkokulu',
  'ANTALYA - MURATPAŞA - Dumlupınar Ortaokulu',
  'ANTALYA - MURATPAŞA - Aldemir- Atilla Konuk Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - İrfan İlk İlkokulu',
  'ANTALYA - MURATPAŞA - Şehit Gültekin Kubilay Atik İlkokulu',
  'ANTALYA - MURATPAŞA - Başöğretmen Atatürk Ortaokulu',
  'ANTALYA - MURATPAŞA - Şehit Ahmet Köse İlkokulu',
  'ANTALYA - MURATPAŞA - Mecdude Başakıncı Ortaokulu',
  'ANTALYA - MURATPAŞA - Necati Dölen Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Antalya Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Konuksever İlkokulu',
  'ANTALYA - MURATPAŞA - Şehit Ahmet Köse Ortaokulu',
  'ANTALYA - MURATPAŞA - Hacı Malike Mehmet Bileydi Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Muratpaşa Azize Kahraman Halk Eğitimi Merkezi',
  'ANTALYA - MURATPAŞA - Muratpaşa Yenigöl Ortaokulu',
  'ANTALYA - MURATPAŞA - Hacı Dudu - Mehmet Gebizli Kız Anadolu İmam Hatip Lisesi',
  'ANTALYA - MURATPAŞA - Ahmet Ferda Kahraman İlkokulu',
  'ANTALYA - MURATPAŞA - Ülkü-Seyfi Kandemir İlkokulu',
  'ANTALYA - MURATPAŞA - Ülkü-Seyfi Kandemir Ortaokulu',
  'ANTALYA - MURATPAŞA - Vali Hüsnü Tuğlu Ortaokulu',
  'ANTALYA - MURATPAŞA - Hacı Hafize Saygan 2 İlkokulu',
  'ANTALYA - MURATPAŞA - 75. Yıl Cumhuriyet Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Muratpaşa Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Metin-Nuran Çakallıklı Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Mustafa Asım Cula Ortaokulu',
  'ANTALYA - MURATPAŞA - Hasan Kaya Ortaokulu',
  'ANTALYA - MURATPAŞA - Nadire Konuk ve Ali Oğuz Konuk Ortaokulu',
  'ANTALYA - MURATPAŞA - Cengiz Topel Anaokulu',
  'ANTALYA - MURATPAŞA - Gültekin İlkokulu',
  'ANTALYA - MURATPAŞA - Güvenlik İlkokulu',
  'ANTALYA - MURATPAŞA - Mustafa Şimşek Anaokulu',
  'ANTALYA - MURATPAŞA - Halide Edip Adıvar Anaokulu',
  'ANTALYA - MURATPAŞA - Sabiha Gökçen Anaokulu',
  'ANTALYA - MURATPAŞA - Atatürk Ortaokulu',
  'ANTALYA - MURATPAŞA - Melahat Faraçlar Ortaokulu',
  'ANTALYA - MURATPAŞA - Barbaros Ortaokulu',
  'ANTALYA - MURATPAŞA - Ahmet Bileydi İlkokulu',
  'ANTALYA - MURATPAŞA - Saime Salih Konca Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Antalya Lisesi',
  'ANTALYA - MURATPAŞA - Namık Kemal Ortaokulu',
  'ANTALYA - MURATPAŞA - Vilayetler Hizmet Birliği Anaokulu',
  'ANTALYA - MURATPAŞA - Ayten Çağıran Anaokulu',
  'ANTALYA - MURATPAŞA - Kamile Çömlekçioğlu Ortaokulu',
  'ANTALYA - MURATPAŞA - Cumhuriyet İlkokulu',
  'ANTALYA - MURATPAŞA - İstiklal Ortaokulu',
  'ANTALYA - MURATPAŞA - Meryem Mustafa Ege Ortaokulu',
  'ANTALYA - MURATPAŞA - Piri Reis İlkokulu',
  'ANTALYA - MURATPAŞA - Antalya Anadolu İmam Hatip Lisesi',
  'ANTALYA - MURATPAŞA - Naciye Havva Manavuşak Ortaokulu',
  'ANTALYA - MURATPAŞA - Antalya Olgunlaşma Enstitüsü',
  'ANTALYA - MURATPAŞA - Emel Sevgi Taner İlkokulu',
  'ANTALYA - MURATPAŞA - Mustafa Kemal Ayanoğlu İlkokulu',
  'ANTALYA - MURATPAŞA - Muratpaşa Yenigöl İlkokulu',
  'ANTALYA - MURATPAŞA - Ertuğrul Gazi İlkokulu',
  'ANTALYA - MURATPAŞA - Fatih Ortaokulu',
  'ANTALYA - MURATPAŞA - Antbirlik İlkokulu',
  'ANTALYA - MURATPAŞA - Hakkı Tatoğlu İlkokulu',
  'ANTALYA - MURATPAŞA - Şehit Yasin Kurt Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Zübeyde Hanım Anaokulu',
  'ANTALYA - MURATPAŞA - Muratpaşa Ortaokulu',
  'ANTALYA - MURATPAŞA - Merkez Ortaokulu',
  'ANTALYA - MURATPAŞA - Necati Ve Fatma Dölen İlkokulu',
  'ANTALYA - MURATPAŞA - İnönü Ortaokulu',
  'ANTALYA - MURATPAŞA - Vali Saim Çotur İlkokulu',
  'ANTALYA - MURATPAŞA - İstiklal İlkokulu',
  'ANTALYA - MURATPAŞA - Vali Saim Çotur Ortaokulu',
  'ANTALYA - MURATPAŞA - Kocademir Ortaokulu',
  'ANTALYA - MURATPAŞA - Dr.Galip Kahraman Ortaokulu',
  'ANTALYA - MURATPAŞA - Faruk Tuğayoğlu İlkokulu',
  'ANTALYA - MURATPAŞA - Faruk Tugayoğlu Ortaokulu',
  'ANTALYA - MURATPAŞA - Kazım Şanöz Ortaokulu',
  'ANTALYA - MURATPAŞA - Falez Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Ramazan Savaş İlkokulu',
  'ANTALYA - MURATPAŞA - Ahmet Yesevi İlkokulu',
  'ANTALYA - MURATPAŞA - Mehmet Akif Ersoy İmam Hatip Ortaokulu',
  'ANTALYA - MURATPAŞA - DİLŞAD REFİZADE ANAOKULU',
  'ANTALYA - MURATPAŞA - DİLŞAD REFİZADE İLKOKULU',
  'ANTALYA - MURATPAŞA - ANTALYA BÜYÜKŞEHİR BELEDİYESİ ANAOKULU',
  'ANTALYA - MURATPAŞA - ANTALYA BÜYÜKŞEHİR BELEDİYESİ SELİM KAZAK ANAOKULU',
  'ANTALYA - MURATPAŞA - Hamza Taş İmam Hatip Ortaokulu',
  'ANTALYA - MURATPAŞA - Mevlana Anadolu İmam Hatip Lisesi',
  'ANTALYA - MURATPAŞA - Şehit Muhammet Oğuz Kılınç Anadolu İmam Hatip Lisesi',
  'ANTALYA - MURATPAŞA - 15 TEMMUZ ŞEHİTLER ANAOKULU',
  'ANTALYA - MURATPAŞA - BARBAROS İMAM HATİP ORTAOKULU',
  'ANTALYA - MURATPAŞA - HAMİDİYE İMAM HATİP ORTAOKULU',
  'ANTALYA - MURATPAŞA - ERMENEK İMAM HATİP ORTAOKULU',
  'ANTALYA - MURATPAŞA - RAMAZAN-HATİCE SAVAŞ ÖZEL EĞİTİM UYGULAMA OKULU II. KADEME',
  'ANTALYA - MURATPAŞA - Ramazan-Hatice Savaş Özel Eğitim Uygulama Okulu I. Kademe',
  'ANTALYA - MURATPAŞA - Güzeloba İmam Hatip Ortaokulu',
  'ANTALYA - MURATPAŞA - Muratpaşa Bilim ve Sanat Merkezi',
  'ANTALYA - MURATPAŞA - Şehit Serkan Çölkesen Anadolu Lisesi',
  'ANTALYA - MURATPAŞA - Muratpaşa Bilim ve Sanat Merkezi Anaokulu',
  'ANTALYA - MURATPAŞA - Güvenlik Anaokulu',
  'ANTALYA - MURATPAŞA - Güzeloba Anaokulu',
  'ANTALYA - MURATPAŞA - Konuksever Anaokulu',
  'ANTALYA - MURATPAŞA - Nadire Konuk ve Ali Oğuz Konuk Anaokulu',
  'ANTALYA - MURATPAŞA - Muratpaşa Anaokulu',
  'ANTALYA - MURATPAŞA - Ramazan Savaş Anaokulu',
  'ANTALYA - MURATPAŞA - Hüseyin Avni Bayaz Özel Eğitim Anaokulu',
  'ANTALYA - MURATPAŞA - Piri Reis Anaokulu',
  'ANTALYA - MURATPAŞA - Hacı Hafize Saygan 2 Anaokulu',
  'ANTALYA - MURATPAŞA - Ermenek Anaokulu',
  'ANTALYA - MURATPAŞA - Fatmagül Özpınar Anaokulu',
  'ANTALYA - MURATPAŞA - Salih Fikri Zaman İlkokulu',
  'ANTALYA - SERİK - Şehit Oğuz Kağan Usta İlkokulu',
  'ANTALYA - SERİK - Burmahancı Fatih İlkokulu',
  'ANTALYA - SERİK - Çandır Çok Programlı Anadolu Lisesi',
  'ANTALYA - SERİK - Gebiz Şehit Abdullah Kara Anadolu Lisesi',
  'ANTALYA - SERİK - Serik Halk Eğitimi Merkezi',
  'ANTALYA - SERİK - Serik Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - SERİK - Kadir Demir İlkokulu',
  'ANTALYA - SERİK - Kadir Demir Ortaokulu',
  'ANTALYA - SERİK - Karadayı İlkokulu',
  'ANTALYA - SERİK - Şehit Hasan Güçlü Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - SERİK - Serik Mesleki Eğitim Merkezi',
  'ANTALYA - SERİK - Sarıabalı İlkokulu',
  'ANTALYA - SERİK - Serik Kız Anadolu İmam Hatip Lisesi',
  'ANTALYA - SERİK - Serik Anadolu Lisesi',
  'ANTALYA - SERİK - Serik İbn-i Sina Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - SERİK - Serik Orhangazi Mesleki ve Teknik Anadolu Lisesi',
  'ANTALYA - SERİK - Töngüçlü İlkokulu',
  'ANTALYA - SERİK - Töngüçlü Ortaokulu',
  'ANTALYA - SERİK - Karadayı Ortaokulu',
  'ANTALYA - SERİK - Atatürk Anadolu Lisesi',
  'ANTALYA - SERİK - 9 Mart İlkokulu',
  'ANTALYA - SERİK - 15 Temmuz Şehitleri Ortaokulu',
  'ANTALYA - SERİK - Serik Kazım Karabekir Anaokulu',
  'ANTALYA - SERİK - Dikmen İlkokulu',
  'ANTALYA - SERİK - Bilginler İlkokulu',
  'ANTALYA - SERİK - Aşağıkocayatak Ortaokulu',
  'ANTALYA - SERİK - Yanköy Ortaokulu',
  'ANTALYA - SERİK - Yanköy İlkokulu',
  'ANTALYA - SERİK - Çakallık Ortaokulu',
  'ANTALYA - SERİK - Yukarı Kocayatak Ortaokulu',
  'ANTALYA - SERİK - Çakallık İlkokulu',
  'ANTALYA - SERİK - Aşağıkocayatak İlkokulu',
  'ANTALYA - SERİK - Deniztepesi İlkokulu',
  'ANTALYA - SERİK - Serik Gazi Ortaokulu',
  'ANTALYA - SERİK - Cumalı İlkokulu',
  'ANTALYA - SERİK - Zırlankaya İlkokulu',
  'ANTALYA - SERİK - Akçaalan İlkokulu',
  'ANTALYA - SERİK - Abdurrahmanlar Ortaokulu',
  'ANTALYA - SERİK - Belkıs İlkokulu',
  'ANTALYA - SERİK - Belkıs Ortaokulu',
  'ANTALYA - SERİK - Gedik İlkokulu',
  'ANTALYA - SERİK - Dikmen Ortaokulu',
  'ANTALYA - SERİK - Burhanettin Kaya Ortaokulu',
  'ANTALYA - SERİK - Pınarcık İlkokulu',
  'ANTALYA - SERİK - Kürüş İlkokulu',
  'ANTALYA - SERİK - Kürüş Ortaokulu',
  'ANTALYA - SERİK - Tekeli İlkokulu',
  'ANTALYA - SERİK - Cumhuriyet Ortaokulu',
  'ANTALYA - SERİK - Cumhuriyet İlkokulu',
  'ANTALYA - SERİK - Boğazkent Nurten-Turan Kilit İlkokulu',
  'ANTALYA - SERİK - Boğazkent Nurten Turan Kilit Ortaokulu',
  'ANTALYA - SERİK - Gedik Ortaokulu',
  'ANTALYA - SERİK - Tekeli Ortaokulu',
  'ANTALYA - SERİK - Gebiz Ortaokulu',
  'ANTALYA - SERİK - Şehit Barış Akkabak İlkokulu',
  'ANTALYA - SERİK - Belek Limak İlkokulu',
  'ANTALYA - SERİK - Hacı Mustafa Bankoğlu Ortaokulu',
  'ANTALYA - SERİK - Belek Limak Ortaokulu',
  'ANTALYA - SERİK - Kayaburnu İlkokulu',
  'ANTALYA - SERİK - Kozağacı İlkokulu',
  'ANTALYA - SERİK - Kozağacı Ortaokulu',
  'ANTALYA - SERİK - Çandır Şehit Öğretmen Mustafa Saadettin Küçük Ortaokulu',
  'ANTALYA - SERİK - Çandır Şehit Öğretmen Mustafa Saadettin Küçük İlkokulu',
  'ANTALYA - SERİK - Serik Öğretmenevi ve Akşam Sanat Okulu',
  'ANTALYA - SERİK - Mehmet Akif Ersoy İlkokulu',
  'ANTALYA - SERİK - Mehmet Akif Ersoy Ortaokulu',
  'ANTALYA - SERİK - Cumalı Ortaokulu',
  'ANTALYA - SERİK - Serik Yunus Emre Anadolu Lisesi',
  'ANTALYA - SERİK - SERİK İMAM HATİP ORTAOKULU',
  'ANTALYA - SERİK - SERİK ANADOLU İMAM HATİP LİSESİ',
  'ANTALYA - SERİK - DENİZTEPESİ ORTAOKULU',
  'ANTALYA - SERİK - Serik Mustafa Nazmi Güven Anaokulu',
  'ANTALYA - SERİK - YUKARI KOCAYATAK İLKOKULU',
  'ANTALYA - SERİK - YUKARIKOCAYATAK SAKARYA İLKOKULU',
  'ANTALYA - SERİK - DR.GÜLŞEN-DR.BAKİ ÖZPINAR İLKOKULU',
  'ANTALYA - SERİK - KADRİYE İLKOKULU',
  'ANTALYA - SERİK - SERİK REHBERLİK VE ARAŞTIRMA MERKEZİ',
  'ANTALYA - SERİK - Gebiz İmam Hatip Ortaokulu',
  'ANTALYA - SERİK - ABDURRAHMANLAR İMAM HATİP ORTAOKULU',
  'ANTALYA - SERİK - TEKELİ İMAM HATİP ORTAOKULU',
  'ANTALYA - SERİK - BURHANETTİN KAYA İMAM HATİP ORTAOKULU',
  'ANTALYA - SERİK - ÇANDIR ŞEHİT ÖĞRETMEN MUSTAFA SAADETTİN KÜÇÜK İMAM HATİP ORTAOKULU',
  'ANTALYA - SERİK - ERTUĞRUL GAZİ ANADOLU LİSESİ',
  'ANTALYA - SERİK - SERİK ÖZEL EĞİTİM UYGULAMA OKULU I. KADEME',
  'ANTALYA - SERİK - SERİK ÖZEL EĞİTİM UYGULAMA OKULU II. KADEME',
  'ANTALYA - SERİK - SERİK ÖZEL EĞİTİM UYGULAMA OKULU III. KADEME',
  'ANTALYA - SERİK - Eskiyörük İlkokulu',
  'ANTALYA - SERİK - Yukarı Kocayatak İmam Hatip Ortaokulu',
  'ANTALYA - SERİK - Kozağacı İmam Hatip Ortaokulu',
  'ANTALYA - SERİK - Serik Merkez Anadolu Lisesi',
  'ANTALYA - SERİK - Serik Özel Eğitim Meslek Okulu',
  'ANTALYA - SERİK - Serik Bilim ve Sanat Merkezi',
  'ANTALYA - SERİK - Çandır Anadolu Lisesi',
  'ANTALYA - SERİK - Serik Anaokulu',
  'ANTALYA - SERİK - Selçuklu Anaokulu',
  'ANTALYA - SERİK - Dr.Gülşen-Dr.Baki Özpınar Anaokulu',
  'ANTALYA - SERİK - 23 Nisan Anaokulu',
  'ANTALYA - SERİK - Tekeli Anaokulu',
  'ANTALYA - SERİK - Serik Özel Eğitim Anaokulu',
  'ANTALYA - SERİK - Serik Fen Lisesi',
  'ANTALYA - SERİK - Belek Limak Anaokulu',
  'ANTALYA - SERİK - Hacı Ayfer - Mehmet Ali Yılmaz Anaokulu',
  'ANTALYA - SERİK - Yukarı Kocayatak Anaokulu',
  ];
}