class ArtvinSchools{
  final List<String> _list=[
    'ARTVİN - ARDANUÇ - İskender Paşa Çok Programlı Anadolu Lisesi',
    'ARTVİN - ARDANUÇ - Ardanuç Halk Eğitimi Merkezi',
    'ARTVİN - ARDANUÇ - Ardanuç Anaokulu',
    'ARTVİN - ARDANUÇ - Ardanuç Anadolu İmam Hatip Lisesi',
    'ARTVİN - ARDANUÇ - Cumhuriyet Ortaokulu',
    'ARTVİN - ARDANUÇ - Atatürk İlkokulu',
    'ARTVİN - ARDANUÇ - ARDANUÇ ANADOLU LİSESİ',
    'ARTVİN - ARDANUÇ - Ardanuç Öğretmenevi ve Akşam Sanat Okulu Müdürlüğü',
    'ARTVİN - ARDANUÇ - Ardanuç Tarım Mesleki ve Teknik Anadolu Lisesi',
    'ARTVİN - ARDANUÇ - Güleş İlkokulu',
    'ARTVİN - ARHAVİ - Nurettin Çarmıklı Anadolu İmam Hatip Lisesi',
    'ARTVİN - ARHAVİ - Arhavi Mesleki ve Teknik Anadolu Lisesi',
    'ARTVİN - ARHAVİ - ARHAVİ GAYE ÇARMIKLI ANAOKULU',
    'ARTVİN - ARHAVİ - Fatih Sultan Mehmet Ortaokulu',
    'ARTVİN - ARHAVİ - Atatürk Ortaokulu',
    'ARTVİN - ARHAVİ - Cumhuriyet Ortaokulu',
    'ARTVİN - ARHAVİ - Ertuğrul Kurdoğlu Fen Lisesi',
    'ARTVİN - ARHAVİ - Fatih Sultan Mehmet İlkokulu',
    'ARTVİN - ARHAVİ - Hacılar İlkokulu',
    'ARTVİN - ARHAVİ - Arhavi Halk Eğitimi Merkezi',
    'ARTVİN - ARHAVİ - Arhavi Hüseyin Gürkan Anadolu Lisesi',
    'ARTVİN - ARHAVİ - Nuri Özaltın 75. Yıl İlkokulu',
    'ARTVİN - ARHAVİ - Orhan Yücel Mesleki ve Teknik Anadolu Lisesi',
    'ARTVİN - ARHAVİ - Mehmet Nazif Günal İlkokulu',
    'ARTVİN - ARHAVİ - Cumhuriyet İlkokulu',
    'ARTVİN - ARHAVİ - Hacılar Ortaokulu',
    'ARTVİN - ARHAVİ - Nurettin Çarmıklı Anaokulu',
    'ARTVİN - ARHAVİ - Arhavi Nuri Özaltın Özel Eğitim Anaokulu',
    'ARTVİN - BORÇKA - Borçka Anadolu Lisesi',
    'ARTVİN - BORÇKA - Camili Yatılı Bölge Ortaokulu',
    'ARTVİN - BORÇKA - Cumhuriyet İlkokulu',
    'ARTVİN - BORÇKA - Düzköy Ortaokulu',
    'ARTVİN - BORÇKA - Borçka Halk Eğitimi Merkezi',
    'ARTVİN - BORÇKA - Osman Bakır Anadolu İmam Hatip Lisesi',
    'ARTVİN - BORÇKA - Karşıköy İlkokulu',
    'ARTVİN - BORÇKA - Mehmet Akif Ersoy Ortaokulu',
    'ARTVİN - BORÇKA - Güreşen Şehit Resul Kakşi Ortaokulu',
    'ARTVİN - BORÇKA - Meryem Acar İlkokulu',
    'ARTVİN - BORÇKA - Atatürk Ortaokulu',
    'ARTVİN - BORÇKA - Cumhuriyet Ortaokulu',
    'ARTVİN - BORÇKA - Şehit Savaş Gedik Mesleki ve Teknik Anadolu Lisesi',
    'ARTVİN - BORÇKA - Mehmet Akif Ersoy İlkokulu',
    'ARTVİN - BORÇKA - Atatürk İlkokulu',
    'ARTVİN - BORÇKA - Muratlı İlkokulu',
    'ARTVİN - BORÇKA - 15 Temmuz Şehitler Ortaokulu',
    'ARTVİN - BORÇKA - Karşıköy Ortaokulu',
    'ARTVİN - BORÇKA - Güreşen Şehit Resul Kakşi İlkokulu',
    'ARTVİN - BORÇKA - 7 Mart Anaokulu',
    'ARTVİN - BORÇKA - Yeniyol Ortaokulu',
    'ARTVİN - BORÇKA - Yeniyol İlkokulu',
    'ARTVİN - BORÇKA - Düzköy İlkokulu',
    'ARTVİN - BORÇKA - 15 Temmuz Şehitler İlkokulu',
    'ARTVİN - BORÇKA - Öğretmen Evi ve Akşam Sanat Okulu',
    'ARTVİN - BORÇKA - CAMİLİ İLKOKULU',
    'ARTVİN - BORÇKA - Borçka İmam Hatip Ortaokulu',
    'ARTVİN - HOPA - Atatürk Ortaokulu',
    'ARTVİN - HOPA - Hopa Halk Eğitimi Merkezi',
    'ARTVİN - HOPA - Hopa Atatürk Anadolu Lisesi',
    'ARTVİN - HOPA - Hopa 15 Temmuz Şehitleri Mesleki ve Teknik Anadolu Lisesi',
    'ARTVİN - HOPA - Hopa Nuri Vatan Anadolu Lisesi',
    'ARTVİN - HOPA - Hopa Mesleki ve Teknik Anadolu Lisesi',
    'ARTVİN - HOPA - Hopa Vatan Anaokulu',
    'ARTVİN - HOPA - Mehmet Akif Ersoy İlkokulu',
    'ARTVİN - HOPA - Yavuz Selim Ortaokulu',
    'ARTVİN - HOPA - Hopa Anadolu İmam Hatip Lisesi',
    'ARTVİN - HOPA - Sugören İlkokulu',
    'ARTVİN - HOPA - Cumhuriyet Ortaokulu',
    'ARTVİN - HOPA - Yoldere İlkokulu',
    'ARTVİN - HOPA - Hüsnü Ciner İlkokulu',
    'ARTVİN - HOPA - Sugören Ortaokulu',
    'ARTVİN - HOPA - Karadeniz Ortaokulu',
    'ARTVİN - HOPA - 14 Mart İlkokulu',
    'ARTVİN - HOPA - Öğretmen Evi ve Akşam Sanat Okulu',
    'ARTVİN - HOPA - Hopa Özel Eğitim Meslek Okulu',
    'ARTVİN - HOPA - Yunus Emre Anaokulu',
    'ARTVİN - HOPA - Ahi Evran Mesleki Eğitim Merkezi',
    'ARTVİN - HOPA - YAĞMUR YAZICIOĞLU ANAOKULU',
    'ARTVİN - HOPA - Hopa Bilim ve Sanat Merkezi',
    'ARTVİN - HOPA - Hüsnü Ciner Anaokulu',
    'ARTVİN - KEMALPAŞA - Kemalpaşa Çok Programlı Anadolu Lisesi',
    'ARTVİN - KEMALPAŞA - KEMALPAŞA ORTAOKULU',
    'ARTVİN - KEMALPAŞA - KEMALPAŞA İLKOKULU',
    'ARTVİN - KEMALPAŞA - KAYA ÇAMURLU İLKOKULU',
    'ARTVİN - KEMALPAŞA - KAYA ÇAMURLU ORTAOKULU',
    'ARTVİN - KEMALPAŞA - KEMALPAŞA SERHAT İLKOKULU',
    'ARTVİN - KEMALPAŞA - KÖPRÜCÜ İLKOKULU',
    'ARTVİN - KEMALPAŞA - KEMALPAŞA SERHAT ORTAOKULU',
    'ARTVİN - KEMALPAŞA - KÖPRÜCÜ ORTAOKULU',
    'ARTVİN - KEMALPAŞA - 15 TEMMUZ ANAOKULU',
    'ARTVİN - KEMALPAŞA - Artvin Kemalpaşa Halk Eğitimi Merkezi',
    'ARTVİN - KEMALPAŞA - Kemalpaşa İmam Hatip Ortaokulu',
    'ARTVİN - MERKEZ - Artvin Anadolu İmam Hatip Lisesi',
    'ARTVİN - MERKEZ - 15 Temmuz Şehitleri Anadolu Lisesi',
    'ARTVİN - MERKEZ - Artvin Sosyal Bilimler Lisesi',
    'ARTVİN - MERKEZ - ARTVİN MESLEKİ EĞİTİM MERKEZİ',
    'ARTVİN - MERKEZ - Artvin Özel Eğitim Uygulama Merkezi I. Kademe',
    'ARTVİN - MERKEZ - Artvin Özel Eğitim Uygulama Merkezi II. Kademe',
    'ARTVİN - MERKEZ - Çoruh İlkokulu',
    'ARTVİN - MERKEZ - Çoruh Özel Eğitim Meslek Okulu',
    'ARTVİN - MERKEZ - Gazi Ortaokulu',
    'ARTVİN - MERKEZ - Artvin Halk Eğitimi Merkezi',
    'ARTVİN - MERKEZ - Karadeniz Bakır İlkokulu',
    'ARTVİN - MERKEZ - Milli Egemenlik Anaokulu',
    'ARTVİN - MERKEZ - Ortaköy İlkokulu',
    'ARTVİN - MERKEZ - Artvin Rehberlik ve Araştırma Merkezi',
    'ARTVİN - MERKEZ - Şehit Ömer Zeki Varan Anaokulu',
    'ARTVİN - MERKEZ - Vilayetler Hizmet Birliği Anaokulu',
    'ARTVİN - MERKEZ - Yenimahalle İlkokulu',
    'ARTVİN - MERKEZ - Seyitler TOKİ Şehit Onur İlhan Ortaokulu',
    'ARTVİN - MERKEZ - Artvin Kazım Karabekir Anadolu Lisesi',
    'ARTVİN - MERKEZ - Artvin Türkiye Odalar ve Borsalar Birliği Mesleki ve Teknik Anadolu Lisesi',
    'ARTVİN - MERKEZ - Vakıfbank İlkokulu',
    'ARTVİN - MERKEZ - 7 Mart Ortaokulu',
    'ARTVİN - MERKEZ - 7 Mart İlkokulu',
    'ARTVİN - MERKEZ - Artvin Fen Lisesi',
    'ARTVİN - MERKEZ - Zübeyde Hanım Anaokulu',
    'ARTVİN - MERKEZ - Atatürk Ortaokulu',
    'ARTVİN - MERKEZ - Yenimahalle Ortaokulu',
    'ARTVİN - MERKEZ - Öğretmenevi ve Akşam Sanat Okulu',
    'ARTVİN - MERKEZ - Artvin Özel Eğitim Uygulama Okulu III. Kademe',
    'ARTVİN - MERKEZ - Şehit Erol İnce İmam Hatip Ortaokulu',
    'ARTVİN - MERKEZ - AYHAN ŞAHENK MESLEKİ VE TEKNİK ANADOLU LİSESİ',
    'ARTVİN - MERKEZ - ARTVİN BİLİM VE SANAT MERKEZİ',
    'ARTVİN - MERKEZ - ORTAKÖY İMAM HATİP ORTAOKULU',
    'ARTVİN - MERKEZ - Seyitler TOKİ Şehit Onur İlhan İlkokulu',
    'ARTVİN - MERKEZ - Artvin Özel Eğitim Anaokulu',
    'ARTVİN - MERKEZ - Artvin Spor Lisesi',
    'ARTVİN - MERKEZ - Artvin Güzel Sanatlar Lisesi',
    'ARTVİN - MERKEZ - Artvin Bilim ve Sanat Merkezi Anaokulu',
    'ARTVİN - MERKEZ - İl Milli Eğitim Müdürlüğü',
    'ARTVİN - MURGUL - Damar Ortaokulu',
    'ARTVİN - MURGUL - Murgul Halk Eğitimi Merkezi',
    'ARTVİN - MURGUL - Murgul Atatürk Anadolu Lisesi',
    'ARTVİN - MURGUL - Murgul Öğretmenevi ve Akşam Sanat Okulu',
    'ARTVİN - MURGUL - Murgul Mesleki ve Teknik Anadolu Lisesi',
    'ARTVİN - MURGUL - Yunus Emre İlkokulu',
    'ARTVİN - MURGUL - Damar İlkokulu',
    'ARTVİN - MURGUL - Murgul Ortaokulu',
    'ARTVİN - MURGUL - MURGUL ANAOKULU',
    'ARTVİN - MURGUL - MURGUL ANADOLU İMAM HATİP LİSESİ',
    'ARTVİN - ŞAVŞAT - Atatürk İlkokulu',
    'ARTVİN - ŞAVŞAT - Şavşat Halk Eğitimi Merkezi',
    'ARTVİN - ŞAVŞAT - Nedim Urhan Anadolu İmam Hatip Lisesi',
    'ARTVİN - ŞAVŞAT - Meydancık Çok Programlı Anadolu Lisesi',
    'ARTVİN - ŞAVŞAT - Çiçek Nene Anaokulu',
    'ARTVİN - ŞAVŞAT - Şavşat Çok Programlı Anadolu Lisesi',
    'ARTVİN - ŞAVŞAT - Ahmet Fevzi İlkokulu',
    'ARTVİN - ŞAVŞAT - Atatürk Ortaokulu',
    'ARTVİN - ŞAVŞAT - Ahmet Fevzi Ortaokulu',
    'ARTVİN - ŞAVŞAT - Meydancık İlkokulu',
    'ARTVİN - ŞAVŞAT - Meydancık Ortaokulu',
    'ARTVİN - ŞAVŞAT - ŞAVŞAT ANADOLU LİSESİ',
    'ARTVİN - ŞAVŞAT - Şavşat Öğretmenevi ve Akşam Sanat Okulu',
    'ARTVİN - YUSUFELİ - Alanbaşı Bağlar İlkokulu',
    'ARTVİN - YUSUFELİ - Halitpaşa Ortaokulu',
    'ARTVİN - YUSUFELİ - Yusufeli Halk Eğitimi Merkezi',
    'ARTVİN - YUSUFELİ - İnönü İlkokulu',
    'ARTVİN - YUSUFELİ - Kazım Karabekir İlkokulu',
    'ARTVİN - YUSUFELİ - Kınalıçam İlkokulu',
    'ARTVİN - YUSUFELİ - Kınalıçam Ortaokulu',
    'ARTVİN - YUSUFELİ - Mehmet Akif Ersoy Yatılı Bölge Ortaokulu',
    'ARTVİN - YUSUFELİ - Öğretmenevi ve Akşam Sanat Okulu',
    'ARTVİN - YUSUFELİ - Pamukçular 70. Yıl İlkokulu',
    'ARTVİN - YUSUFELİ - Şehit Salih Hüseyin Parça Anadolu Lisesi',
    'ARTVİN - YUSUFELİ - Yusufeli Çok Programlı Anadolu Lisesi',
    'ARTVİN - YUSUFELİ - Yusufeli Zübeyde Hanım Anaokulu',
    'ARTVİN - YUSUFELİ - Dereiçi Ortaokulu',
    'ARTVİN - YUSUFELİ - Kılıçkaya Şehit Albay Cevat Erten Ortaokulu',
    'ARTVİN - YUSUFELİ - Darıca Ortaokulu',
    'ARTVİN - YUSUFELİ - Sarıgöl Şehit Onbaşı Soner Ateşsaçan Ortaokulu',
    'ARTVİN - YUSUFELİ - İnönü Ortaokulu',
    'ARTVİN - YUSUFELİ - Şehit Dursun Acar Anadolu İmam Hatip Lisesi',
    'ARTVİN - YUSUFELİ - Alanbaşı Bağlar Ortaokulu',
    'ARTVİN - YUSUFELİ - Halitpaşa İlkokulu',
    'ARTVİN - YUSUFELİ - Sarıgöl Şehit Onbaşı Soner Ateşsaçan İlkokulu',
    'ARTVİN - YUSUFELİ - KÜPLÜCE MEHMET AKİF ERSOY İLKOKULU',
    'ARTVİN - YUSUFELİ - KILIÇKAYA İLKOKULU',
    'ARTVİN - YUSUFELİ - KAZIM KARABEKİR ORTAOKULU',
    'ARTVİN - YUSUFELİ - Yusufeli 15 Temmuz Şehitleri İmam Hatip Ortaokulu',
    'ARTVİN - YUSUFELİ - Dereiçi İlkokulu',
    'ARTVİN - YUSUFELİ - Hayme Ana Anaokulu',
    'ARTVİN - YUSUFELİ - Yusufeli Tarım Mesleki ve Teknik Anadolu Lisesi',
  ];

  List<String> get list=>_list;
}