class AydinSchools{
  final List<String> list=[
  'AYDIN - BOZDOĞAN - Altıntaş Şehit Tayfun Kılınç İlkokulu',
  'AYDIN - BOZDOĞAN - Altıntaş Şehit Ercan Menderes İlkokulu',
  'AYDIN - BOZDOĞAN - Bozdoğan Anadolu Lisesi',
  'AYDIN - BOZDOĞAN - Bozdoğan Anaokulu',
  'AYDIN - BOZDOĞAN - Çamlıdere Şehit Musa Sarısaç İlkokulu',
  'AYDIN - BOZDOĞAN - Fatih Ortaokulu',
  'AYDIN - BOZDOĞAN - Bozdoğan Halk Eğitimi Merkezi',
  'AYDIN - BOZDOĞAN - Haydere İlkokulu',
  'AYDIN - BOZDOĞAN - Bozdoğan İmam Hatip Ortaokulu',
  'AYDIN - BOZDOĞAN - Koyuncular Şehit Nihat İzbudak İlkokulu',
  'AYDIN - BOZDOĞAN - Olukbaşı İlkokulu',
  'AYDIN - BOZDOĞAN - Örencik İlkokulu',
  'AYDIN - BOZDOĞAN - Örentaht İlkokulu',
  'AYDIN - BOZDOĞAN - Sırma İlkokulu',
  'AYDIN - BOZDOĞAN - Yaka İlkokulu',
  'AYDIN - BOZDOĞAN - Örentaht Ortaokulu',
  'AYDIN - BOZDOĞAN - Bozdoğan İsmet Sezgin Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - BOZDOĞAN - Öğretmenevi ve Akşam Sanat Okulu',
  'AYDIN - BOZDOĞAN - Yazıkent Mürşide Akçay Ortaokulu',
  'AYDIN - BOZDOĞAN - Yazıkent Mürşide Akçay İlkokulu',
  'AYDIN - BOZDOĞAN - Merkez İlkokulu',
  'AYDIN - BOZDOĞAN - Haydere Ortaokulu',
  'AYDIN - BOZDOĞAN - Amasya Üzeyir Emre Ortaokulu',
  'AYDIN - BOZDOĞAN - Amasya Üzeyir Emre İlkokulu',
  'AYDIN - BOZDOĞAN - Yazıkent Kızılçakır İlkokulu',
  'AYDIN - BOZDOĞAN - Örtülü Ortaokulu',
  'AYDIN - BOZDOĞAN - Örtülü İlkokulu',
  'AYDIN - BOZDOĞAN - Başalan İlkokulu',
  'AYDIN - BOZDOĞAN - Olukbaşı Ortaokulu',
  'AYDIN - BOZDOĞAN - Kemer Hes Ortaokulu',
  'AYDIN - BOZDOĞAN - Kemer Hes İlkokulu',
  'AYDIN - BOZDOĞAN - Kılavuzlar İlkokulu',
  'AYDIN - BOZDOĞAN - Kızılca İlkokulu',
  'AYDIN - BOZDOĞAN - Eymir İlkokulu',
  'AYDIN - BOZDOĞAN - Alamut Ortaokulu',
  'AYDIN - BOZDOĞAN - Alamut İlkokulu',
  'AYDIN - BOZDOĞAN - Fatih İlkokulu',
  'AYDIN - BOZDOĞAN - Ümit-Güldane Erdal Ortaokulu',
  'AYDIN - BOZDOĞAN - Madran İlkokulu',
  'AYDIN - BOZDOĞAN - Karabağlar İlkokulu',
  'AYDIN - BOZDOĞAN - Körteke İlkokulu',
  'AYDIN - BOZDOĞAN - Seki İlkokulu',
  'AYDIN - BOZDOĞAN - Bahattin - Gülten Çırpanlı Anadolu İmam Hatip Lisesi',
  'AYDIN - BOZDOĞAN - Bozdoğan Özel Eğitim Uygulama Okulu I. Kademe',
  'AYDIN - BOZDOĞAN - Bozdoğan Özel Eğitim Uygulama Okulu III. Kademe',
  'AYDIN - BOZDOĞAN - Bozdoğan Özel Eğitim Uygulama Okulu II. Kademe',
  'AYDIN - BUHARKENT - Buharkent Anaokulu',
  'AYDIN - BUHARKENT - Buharkent Halk Eğitimi Merkezi',
  'AYDIN - BUHARKENT - İstiklal İlkokulu',
  'AYDIN - BUHARKENT - Kamilpaşa İlkokulu',
  'AYDIN - BUHARKENT - Kızıldere İlkokulu',
  'AYDIN - BUHARKENT - Ortakçı Cumhuriyet İlkokulu',
  'AYDIN - BUHARKENT - Savcıllı İlkokulu',
  'AYDIN - BUHARKENT - Zafer Ortaokulu',
  'AYDIN - BUHARKENT - Gelenbe Ali Çevik Ortaokulu',
  'AYDIN - BUHARKENT - Şehit Jandarma Üsteğmen Mehmet Esin Anadolu İmam Hatip Lisesi',
  'AYDIN - BUHARKENT - Savcıllı Ortaokulu',
  'AYDIN - BUHARKENT - Gelenbe Ali Çevik İlkokulu',
  'AYDIN - BUHARKENT - Buharkent Belediyesi Anadolu Lisesi',
  'AYDIN - BUHARKENT - Buharkent Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - ÇİNE - Akçaova Anadolu Lisesi',
  'AYDIN - ÇİNE - Bahçearası İlkokulu',
  'AYDIN - ÇİNE - Cumhuriyet İlkokulu',
  'AYDIN - ÇİNE - Çine 70. Yıl Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - ÇİNE - Çine Anadolu İmam Hatip Lisesi',
  'AYDIN - ÇİNE - Çine Madran Anadolu Lisesi',
  'AYDIN - ÇİNE - Çine Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - ÇİNE - Çine Anadolu Lisesi',
  'AYDIN - ÇİNE - Çine Halk Eğitimi Merkezi',
  'AYDIN - ÇİNE - Kuruköy İlkokulu',
  'AYDIN - ÇİNE - Mehmet Emin Ünal Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - ÇİNE - Mehmet Tuncer Anadolu Lisesi',
  'AYDIN - ÇİNE - Çine Mesleki Eğitim Merkezi',
  'AYDIN - ÇİNE - Çine Muhsin Kalkan Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - ÇİNE - Mustafa Türkoğlu Ortaokulu',
  'AYDIN - ÇİNE - Öğretmen Fatma Öz Anaokulu',
  'AYDIN - ÇİNE - Şehit Polis Necati Aygün İlkokulu',
  'AYDIN - ÇİNE - Namık Kemal Ortaokulu',
  'AYDIN - ÇİNE - Feride Raşit Kalkan Ortaokulu',
  'AYDIN - ÇİNE - Cumalı İlkokulu',
  'AYDIN - ÇİNE - Topçam İlkokulu',
  'AYDIN - ÇİNE - İbrahim Kavagı İlkokulu',
  'AYDIN - ÇİNE - Kavşit İlkokulu',
  'AYDIN - ÇİNE - Kahraman İlkokulu',
  'AYDIN - ÇİNE - Evciler İlkokulu',
  'AYDIN - ÇİNE - Hüseyin Özkan İlkokulu',
  'AYDIN - ÇİNE - Yolboyu İlkokulu',
  'AYDIN - ÇİNE - Çaltı İlkokulu',
  'AYDIN - ÇİNE - Eskiçine İlkokulu',
  'AYDIN - ÇİNE - Akçaova Ortaokulu',
  'AYDIN - ÇİNE - Akçaova İlkokulu',
  'AYDIN - ÇİNE - Ovacık İlkokulu',
  'AYDIN - ÇİNE - Atatürk İlkokulu',
  'AYDIN - ÇİNE - Gökyaka İlkokulu',
  'AYDIN - ÇİNE - Altınova İlkokulu',
  'AYDIN - ÇİNE - Fevzipaşa Sevim Kalkan İlkokulu',
  'AYDIN - ÇİNE - Şehit Süleyman Güneri İlkokulu',
  'AYDIN - ÇİNE - ÇİNE İMAM HATİP ORTAOKULU',
  'AYDIN - ÇİNE - Ayhan Yıldız Anaokulu',
  'AYDIN - ÇİNE - Naciye Ünal Özel Eğitim Uygulama Okulu I. Kademe',
  'AYDIN - ÇİNE - Çine Bilim ve Sanat Merkezi',
  'AYDIN - ÇİNE - Atatürk Anaokulu',
  'AYDIN - ÇİNE - Naciye Ünal Özel Eğitim Uygulama Okulu II.Kademe',
  'AYDIN - ÇİNE - Altınabat İlkokulu',
  'AYDIN - ÇİNE - Umurköy İlkokulu',
  'AYDIN - ÇİNE - Elderesi İlkokulu',
  'AYDIN - ÇİNE - Çatak İlkokulu',
  'AYDIN - DİDİM - Didim Anadolu Lisesi',
  'AYDIN - DİDİM - Didim Anaokulu',
  'AYDIN - DİDİM - Esra Karakaya Anadolu Lisesi',
  'AYDIN - DİDİM - Didim Halk Eğitimi Merkezi',
  'AYDIN - DİDİM - Didim Mesleki Eğitim Merkezi',
  'AYDIN - DİDİM - Vilayetler Hizmet Birliği Anaokulu',
  'AYDIN - DİDİM - Atatürk İlkokulu',
  'AYDIN - DİDİM - Didim Selçuk Özsoy Ortaokulu',
  'AYDIN - DİDİM - Ak-Yeniköy Şehit Soner Turan İlkokulu',
  'AYDIN - DİDİM - Ak-Yeniköy Şehit Soner Turan Ortaokulu',
  'AYDIN - DİDİM - Gazi Ortaokulu',
  'AYDIN - DİDİM - Gazi İlkokulu',
  'AYDIN - DİDİM - Cemal Ergenekon Ortaokulu',
  'AYDIN - DİDİM - Zeynep - Mehmet Dönmez Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - DİDİM - Cumhuriyet Ortaokulu',
  'AYDIN - DİDİM - Cumhuriyet İlkokulu',
  'AYDIN - DİDİM - Denizköy İlkokulu',
  'AYDIN - DİDİM - Didim Efeler Ortaokulu',
  'AYDIN - DİDİM - Didim Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - DİDİM - Akköy Ortaokulu',
  'AYDIN - DİDİM - Akköy İlkokulu',
  'AYDIN - DİDİM - Denizköy Ortaokulu',
  'AYDIN - DİDİM - Valiler Ortaokulu',
  'AYDIN - DİDİM - Valiler İlkokulu',
  'AYDIN - DİDİM - Yalıköy Ortaokulu',
  'AYDIN - DİDİM - Arif Nihat Asya Ortaokulu',
  'AYDIN - DİDİM - Balat İlkokulu',
  'AYDIN - DİDİM - Arif Nihat Asya İlkokulu',
  'AYDIN - DİDİM - Mahir Özgür Damar İlkokulu',
  'AYDIN - DİDİM - Akbük Nurullah Kocabıyık İlkokulu',
  'AYDIN - DİDİM - Yalıköy İlkokulu',
  'AYDIN - DİDİM - Fevzipaşa Akbudak İlkokulu',
  'AYDIN - DİDİM - DİDİM ANADOLU İMAM HATİP LİSESİ',
  'AYDIN - DİDİM - BARBAROS HAYRETTİN PAŞA ANADOLU LİSESİ',
  'AYDIN - DİDİM - Didim Yenihisar Anadolu Lisesi',
  'AYDIN - DİDİM - Didim Bilim ve Sanat Merkezi',
  'AYDIN - DİDİM - Atatürk Anaokulu',
  'AYDIN - DİDİM - Mahir Özgür Damar Anaokulu',
  'AYDIN - EFELER - Adnan Menderes Anadolu Lisesi',
  'AYDIN - EFELER - Armutlu İlkokulu',
  'AYDIN - EFELER - Avukat Cevat Aldemir Ortaokulu',
  'AYDIN - EFELER - Şehit Polis Nedip Cengiz Eker Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - EFELER - Aydın Atatürk Anadolu Lisesi',
  'AYDIN - EFELER - Aydın Fen Lisesi',
  'AYDIN - EFELER - Murat-Hale Küçükoğlu Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - EFELER - Aydın Lisesi',
  'AYDIN - EFELER - Aydın Sosyal Bilimler Lisesi',
  'AYDIN - EFELER - Aydın Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - EFELER - Baltaköy Hacı İbrahim Akdemir Ortaokulu',
  'AYDIN - EFELER - Cumhuriyet Anadolu Lisesi',
  'AYDIN - EFELER - Dalama Çok Programlı Anadolu Lisesi',
  'AYDIN - EFELER - Efe Emir Ayşe Çetin Anaokulu',
  'AYDIN - EFELER - Efeler Anadolu Lisesi',
  'AYDIN - EFELER - Emel - Mustafa Uşaklı Anadolu Lisesi',
  'AYDIN - EFELER - Fitnat Nihat Azizler İlkokulu',
  'AYDIN - EFELER - Gazipaşa İlkokulu',
  'AYDIN - EFELER - Gazipaşa Ortaokulu',
  'AYDIN - EFELER - Hacı Celal Oto İlkokulu',
  'AYDIN - EFELER - Adnan Menderes Ortaokulu',
  'AYDIN - EFELER - Hacı Kadriye Arslan Rehberlik ve Araştırma Merkezi',
  'AYDIN - EFELER - Hacı Lütfiye Atay Ortaokulu',
  'AYDIN - EFELER - Halide Hatun İlkokulu',
  'AYDIN - EFELER - Efeler Halk Eğitimi Merkezi',
  'AYDIN - EFELER - Aydın Anadolu İmam Hatip Lisesi',
  'AYDIN - EFELER - Kadıköy Ortaokulu',
  'AYDIN - EFELER - Kardeşköy İlkokulu',
  'AYDIN - EFELER - Kardeşköy Ortaokulu',
  'AYDIN - EFELER - Mehmet Akif Ersoy İlkokulu',
  'AYDIN - EFELER - Mehmet Akif Ersoy Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - EFELER - Şehit Savcı Mehmet Selim Kiraz İmam Hatip Ortaokulu',
  'AYDIN - EFELER - Efeler Mesleki Eğitim Merkezi',
  'AYDIN - EFELER - Mimar Sinan Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - EFELER - Mimar Sinan Anaokulu',
  'AYDIN - EFELER - Süleyman Demirel Anadolu Lisesi',
  'AYDIN - EFELER - Ticaret Odası İlkokulu',
  'AYDIN - EFELER - Umurlu Cavit Başlık Ortaokulu',
  'AYDIN - EFELER - Umurlu Çok Programlı Anadolu Lisesi',
  'AYDIN - EFELER - Umurlu Ortaköy İlkokulu',
  'AYDIN - EFELER - Yahya Kemal Beyatlı İlkokulu',
  'AYDIN - EFELER - Yunus Emre İlkokulu',
  'AYDIN - EFELER - Aydın Yüksel Yalova Güzel Sanatlar Lisesi',
  'AYDIN - EFELER - Zübeyde Hanım Anaokulu',
  'AYDIN - EFELER - Zübeyde Hanım Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - EFELER - Umurlu Eğrikavak Ortaokulu',
  'AYDIN - EFELER - Şehit Rıfat Tunçbilek Ortaokulu',
  'AYDIN - EFELER - Çeştepe Atatürk Ortaokulu',
  'AYDIN - EFELER - Mustafa Kiriş Ortaokulu',
  'AYDIN - EFELER - 75.Yıl Vali Muharrem Göktayoğlu Ortaokulu',
  'AYDIN - EFELER - Ovaeymiri İlkokulu',
  'AYDIN - EFELER - Yedieylül İlkokulu',
  'AYDIN - EFELER - Dalama İlkokulu',
  'AYDIN - EFELER - Dalama Ortaokulu',
  'AYDIN - EFELER - Zübeyde Hanım İlkokulu',
  'AYDIN - EFELER - Ekrem Çifçi İlkokulu',
  'AYDIN - EFELER - Nahit Menteşe Ortaokulu',
  'AYDIN - EFELER - Umurlu Eğrikavak İlkokulu',
  'AYDIN - EFELER - Örsdemir Balkan Ortaokulu',
  'AYDIN - EFELER - Örsdemir Balkan İlkokulu',
  'AYDIN - EFELER - Efeler Ortaokulu',
  'AYDIN - EFELER - Işıklı Ortaokulu',
  'AYDIN - EFELER - Işıklı İlkokulu',
  'AYDIN - EFELER - Doktor Fevzi - Mürüvet Uğuroğlu Ortaokulu',
  'AYDIN - EFELER - Ahmet Şerife Sanlı Ortaokulu',
  'AYDIN - EFELER - Yörük Ali Efe İlkokulu',
  'AYDIN - EFELER - Cumhuriyet İlkokulu',
  'AYDIN - EFELER - Tepecik İlkokulu',
  'AYDIN - EFELER - Tepecik Ortaokulu',
  'AYDIN - EFELER - Dalama Yeniköy Ortaokulu',
  'AYDIN - EFELER - Osmangazi Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - EFELER - Şehit Jandarma Uzman Çavuş Tolga Sağlam İlkokulu',
  'AYDIN - EFELER - Zafer Ortaokulu',
  'AYDIN - EFELER - Umurlu Atatürk İlkokulu',
  'AYDIN - EFELER - İmamköy İlkokulu',
  'AYDIN - EFELER - Kızılcaköy Şehit İdris Atalan Ortaokulu',
  'AYDIN - EFELER - Mehmet Akif Ersoy Ortaokulu',
  'AYDIN - EFELER - Ilıcabaşı Ortaokulu',
  'AYDIN - EFELER - Savrandere Hacı Ahmet Atay İlkokulu',
  'AYDIN - EFELER - Çeştepe İlkokulu',
  'AYDIN - EFELER - Güzelhisar İlkokulu',
  'AYDIN - EFELER - İstiklal Anaokulu',
  'AYDIN - EFELER - Konuklu İlkokulu',
  'AYDIN - EFELER - Umurlu Yukarı Kayacık İlkokulu',
  'AYDIN - EFELER - Gölhisar İlkokulu',
  'AYDIN - EFELER - Yeniköy Ortaokulu',
  'AYDIN - EFELER - Atatürk Özel Eğitim Meslek Okulu',
  'AYDIN - EFELER - Öğretmenevi ve Akşam Sanat Okulu',
  'AYDIN - EFELER - Yılmazköy Ortaokulu',
  'AYDIN - EFELER - Yunus Emre Anaokulu',
  'AYDIN - EFELER - Hacı Hüseyin Aslan Özel Eğitim Uygulama Okulu III. Kademe',
  'AYDIN - EFELER - Osman Yozgatlı Ortaokulu',
  'AYDIN - EFELER - Umurlu Umurbey İlkokulu',
  'AYDIN - EFELER - Unicef Türkiye Milli Komitesi - Seyda KAYHAN Anaokulu',
  'AYDIN - EFELER - Aydın Özel Eğitim Uygulama Merkezi I. Kademe',
  'AYDIN - EFELER - Yeniköy İlkokulu',
  'AYDIN - EFELER - Umurlu Terziler İlkokulu',
  'AYDIN - EFELER - Umurlu Emirdoğan İlkokulu',
  'AYDIN - EFELER - Dalama Yeniköy İlkokulu',
  'AYDIN - EFELER - Dalama Anaokulu',
  'AYDIN - EFELER - Baltaköy Hacı İbrahim Akdemir İlkokulu',
  'AYDIN - EFELER - Ilıcabaşı İlkokulu',
  'AYDIN - EFELER - Kızılcaköy Şehit İdris Atalan İlkokulu',
  'AYDIN - EFELER - Dağeymiri İlkokulu',
  'AYDIN - EFELER - Kadıköy İlkokulu',
  'AYDIN - EFELER - Umurlu İmam Hatip Ortaokulu',
  'AYDIN - EFELER - Efeler İmam Hatip Ortaokulu',
  'AYDIN - EFELER - UMURLU FATİH İLKOKULU',
  'AYDIN - EFELER - AYDIN TİCARET BORSASI BİLİM VE SANAT MERKEZİ',
  'AYDIN - EFELER - Yılmazköy İlkokulu',
  'AYDIN - EFELER - UMURLU KOCAGÜR ORTAOKULU',
  'AYDIN - EFELER - UMURLU KOCAGÜR İLKOKULU',
  'AYDIN - EFELER - RECEP TAYYİP ERDOĞAN İLKOKULU',
  'AYDIN - EFELER - RECEP TAYYİP ERDOĞAN ORTAOKULU',
  'AYDIN - EFELER - UMURLU KUYUCULAR İLKOKULU',
  'AYDIN - EFELER - ŞEHİT ORKUN ALP ARSLAN KIZ ANADOLU İMAM HATİP LİSESİ',
  'AYDIN - EFELER - ŞEHİT POLİS DEMET SEZEN ANAOKULU',
  'AYDIN - EFELER - Efeler Özel Eğitim Uygulama Okulu III. Kademe',
  'AYDIN - EFELER - ADNAN MENDERES ANADOLU İMAM HATİP LİSESİ',
  'AYDIN - EFELER - Aliya İzzetbegoviç İlkokulu',
  'AYDIN - EFELER - ORGANİZE SANAYİ BÖLGESİ ANAOKULU',
  'AYDIN - EFELER - Kadıköy Abdülhamid Han Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - EFELER - TEPEKÖY İLKOKULU',
  'AYDIN - EFELER - Hacı Hüseyin Aslan Özel Eğitim Uygulama Okulu I. Kademe',
  'AYDIN - EFELER - Aydın Özel Eğitim Uygulama Okulu II. Kademe',
  'AYDIN - EFELER - Hacı Hüseyin Aslan Özel Eğitim Uygulama Okulu II. Kademe',
  'AYDIN - EFELER - Şahnalı İlkokulu',
  'AYDIN - EFELER - Şehit Nusret Şen Özel Eğitim Uygulama Okulu I. Kademe',
  'AYDIN - EFELER - Şehit Nusret Şen Özel Eğitim Uygulama Okulu II. Kademe',
  'AYDIN - EFELER - Güzelhisar Özel Eğitim Anaokulu',
  'AYDIN - EFELER - Mehmet Akif Ersoy Anadolu Lisesi',
  'AYDIN - EFELER - Umurlu Özel Eğitim Meslek Okulu',
  'AYDIN - EFELER - AYDIN TİCARET BORSASI BİLİM VE SANAT MERKEZİ ANAOKULU',
  'AYDIN - EFELER - Kübra Efe Anaokulu',
  'AYDIN - EFELER - Ekrem Çifçi Anaokulu',
  'AYDIN - EFELER - Halide Hatun Anaokulu',
  'AYDIN - EFELER - Güzelhisar Anaokulu',
  'AYDIN - EFELER - Yedieylül Anaokulu',
  'AYDIN - EFELER - Avukat Cevat Aldemir Anaokulu',
  'AYDIN - EFELER - Hacı Celal Oto Anaokulu',
  'AYDIN - EFELER - Cumhuriyet Anaokulu',
  'AYDIN - EFELER - Ticaret Odası Anaokulu',
  'AYDIN - EFELER - Musluca İlkokulu',
  'AYDIN - GERMENCİK - Bozköy İlkokulu',
  'AYDIN - GERMENCİK - Çamköy İlkokulu',
  'AYDIN - GERMENCİK - Çocuklar Gülsün Diye Anaokulu',
  'AYDIN - GERMENCİK - Dağyeni İlkokulu',
  'AYDIN - GERMENCİK - Gazi Mustafa Kemal Ortaokulu',
  'AYDIN - GERMENCİK - Germencik Anadolu Lisesi',
  'AYDIN - GERMENCİK - Germencik Halk Eğitimi Merkezi',
  'AYDIN - GERMENCİK - Hıdırbeyli İlkokulu',
  'AYDIN - GERMENCİK - Himmet Çondur Cumhuriyet Ortaokulu',
  'AYDIN - GERMENCİK - Hürriyet İlkokulu',
  'AYDIN - GERMENCİK - Germencik Sabancı Öğretmenevi ve Akşam Sanat Okulu',
  'AYDIN - GERMENCİK - Germencik Mesleki Eğitim Merkezi',
  'AYDIN - GERMENCİK - Bozköy Ortaokulu',
  'AYDIN - GERMENCİK - Çamköy Ortaokulu',
  'AYDIN - GERMENCİK - Ortaklar Adabelen Ortaokulu',
  'AYDIN - GERMENCİK - Ortaklar Atatürk İlkokulu',
  'AYDIN - GERMENCİK - Ortaklar Kurtuluş İlkokulu',
  'AYDIN - GERMENCİK - Ortaklar Anadolu Lisesi',
  'AYDIN - GERMENCİK - Ortaklar Mehmet Hüseyin Öncel İlkokulu',
  'AYDIN - GERMENCİK - Ortaklar Orhan Delgen İmam Hatip Ortaokulu',
  'AYDIN - GERMENCİK - Ömerbeyli İlkokulu',
  'AYDIN - GERMENCİK - Reisköy İlkokulu',
  'AYDIN - GERMENCİK - Turanlar Ortaokulu',
  'AYDIN - GERMENCİK - Şehit Cafer İlkokulu',
  'AYDIN - GERMENCİK - Şehit Cafer Ortaokulu',
  'AYDIN - GERMENCİK - Turanlar İlkokulu',
  'AYDIN - GERMENCİK - Yedieylül İlkokulu',
  'AYDIN - GERMENCİK - Ortaklar Fatih Anaokulu',
  'AYDIN - GERMENCİK - Selatin İlkokulu',
  'AYDIN - GERMENCİK - Neşetiye İlkokulu',
  'AYDIN - GERMENCİK - Neşetiye Ortaokulu',
  'AYDIN - GERMENCİK - Mursallı Sabahat Oğuz Ortaokulu',
  'AYDIN - GERMENCİK - Şehit Mehmet İlkokulu',
  'AYDIN - GERMENCİK - Yılmaz Çakaloğlu İmam Hatip Ortaokulu',
  'AYDIN - GERMENCİK - Ortaklar Fen Lisesi',
  'AYDIN - GERMENCİK - Murat İrem Delgen Ortaokulu',
  'AYDIN - GERMENCİK - MEŞELİ İLKOKULU',
  'AYDIN - GERMENCİK - Germencik Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - İNCİRLİOVA - Acarlar Anaokulu',
  'AYDIN - İNCİRLİOVA - Acarlar Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - İNCİRLİOVA - Acarlar Fatih Sultan Mehmet İlkokulu',
  'AYDIN - İNCİRLİOVA - Acarlar İstiklal İlkokulu',
  'AYDIN - İNCİRLİOVA - Beyköy İlkokulu',
  'AYDIN - İNCİRLİOVA - Cemal Gürbüz Atik Ortaokulu',
  'AYDIN - İNCİRLİOVA - Dereağzı İlkokulu',
  'AYDIN - İNCİRLİOVA - Doktor Reşit Galip Ortaokulu',
  'AYDIN - İNCİRLİOVA - Gerenkova İlkokulu',
  'AYDIN - İNCİRLİOVA - Hacıaliobası İlkokulu',
  'AYDIN - İNCİRLİOVA - İncirliova Halk Eğitimi Merkezi',
  'AYDIN - İNCİRLİOVA - Hürriyet İlkokulu',
  'AYDIN - İNCİRLİOVA - İncirliova Ahmet Çallıoğlu Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - İNCİRLİOVA - İncirliova Anadolu Lisesi',
  'AYDIN - İNCİRLİOVA - Aydın İncirliova Spor Lisesi',
  'AYDIN - İNCİRLİOVA - İsafakılar Şehit Ali İrfan Öztürk İlkokulu',
  'AYDIN - İNCİRLİOVA - Osmanbükü Ekrem Çiftçi İlkokulu',
  'AYDIN - İNCİRLİOVA - Sandıklı Nazmi Topçuoğlu İlkokulu',
  'AYDIN - İNCİRLİOVA - Sınırteke İlkokulu',
  'AYDIN - İNCİRLİOVA - Sınırteke Ortaokulu',
  'AYDIN - İNCİRLİOVA - Zübeyde Hanım Anaokulu',
  'AYDIN - İNCİRLİOVA - 50.Yıl Ortaokulu',
  'AYDIN - İNCİRLİOVA - İzzet Ayaydın Ali Sarıyörük İlkokulu',
  'AYDIN - İNCİRLİOVA - Hürmüs Ayaydın İlkokulu',
  'AYDIN - İNCİRLİOVA - Nazmi Topçuoğlu İlkokulu',
  'AYDIN - İNCİRLİOVA - Erbeyli Ortaokulu',
  'AYDIN - İNCİRLİOVA - Erbeyli İlkokulu',
  'AYDIN - İNCİRLİOVA - Gerenkova Ortaokulu',
  'AYDIN - İNCİRLİOVA - İNCİRLİOVA İMAM HATİP ORTAOKULU',
  'AYDIN - İNCİRLİOVA - Acarlar İmam Hatip Ortaokulu',
  'AYDIN - İNCİRLİOVA - SANDIKLI NAZMİ TOPÇUOĞLU ORTAOKULU',
  'AYDIN - İNCİRLİOVA - İNCİRLİOVA ANADOLU İMAM HATİP LİSESİ',
  'AYDIN - İNCİRLİOVA - İncirliova Anaokulu',
  'AYDIN - INCİRLİOVA - Acarlar 60.Yıl Ortaokulu',
  'AYDIN - INCİRLİOVA - Yazıdere Şehit Adem Akdeniz İlkokulu',
  'AYDIN - İNCİRLİOVA - İncirliova Bilim ve Sanat Merkezi',
  'AYDIN - İNCİRLİOVA - Arpadere İlkokulu',
  'AYDIN - INCİRLİOVA - Karagözler İlkokulu',
  'AYDIN - INCİRLİOVA - İzzet Ayaydın Ali Sarıyörük Anaokulu',
  'AYDIN - KARACASU - Alemler İlkokulu',
  'AYDIN - KARACASU - Alemler Ortaokulu',
  'AYDIN - KARACASU - Ataeymir İlkokulu',
  'AYDIN - KARACASU - Karacasu Halk Eğitimi Merkezi',
  'AYDIN - KARACASU - Karacasu Anaokulu',
  'AYDIN - KARACASU - Karacasu Çok Programlı Anadolu Lisesi',
  'AYDIN - KARACASU - Karacasu Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - KARACASU - Kırçiçeği Anadolu Lisesi',
  'AYDIN - KARACASU - Yaykın İlkokulu',
  'AYDIN - KARACASU - Yenice İlkokulu',
  'AYDIN - KARACASU - Karacasu Şehitleri Ortaokulu',
  'AYDIN - KARACASU - Atatürk İlkokulu',
  'AYDIN - KARACASU - Karacasu İmam Hatip Ortaokulu',
  'AYDIN - KARACASU - Yenice Ortaokulu',
  'AYDIN - KARACASU - Ataeymir Ortaokulu',
  'AYDIN - KARACASU - Ataköy İlkokulu',
  'AYDIN - KARACASU - Ataköy Ortaokulu',
  'AYDIN - KARACASU - Yaykın Ortaokulu',
  'AYDIN - KARACASU - Karacasuyu Sevenler İlkokulu',
  'AYDIN - KARACASU - Geyre Ortaokulu',
  'AYDIN - KARACASU - Geyre İlkokulu',
  'AYDIN - KARACASU - Karacaören Şehit Mehmet Aykan İlkokulu',
  'AYDIN - KARACASU - KARACASU ANADOLU İMAM HATİP LİSESİ',
  'AYDIN - KARPUZLU - Karpuzlu Halk Eğitimi Merkezi',
  'AYDIN - KARPUZLU - Karpuzlu Anadolu Lisesi',
  'AYDIN - KARPUZLU - Şehit Şenol Akar Ortaokulu',
  'AYDIN - KARPUZLU - Tekeler İlkokulu',
  'AYDIN - KARPUZLU - Tekeler Ortaokulu',
  'AYDIN - KARPUZLU - Ulukonak İlkokulu',
  'AYDIN - KARPUZLU - Vakıfbank İlkokulu',
  'AYDIN - KARPUZLU - Çobanisa Hakim Ahmet Akgün İlkokulu',
  'AYDIN - KARPUZLU - Karpuzlu Anadolu İmam Hatip Lisesi',
  'AYDIN - KARPUZLU - Karpuzlu Anaokulu',
  'AYDIN - KARPUZLU - Karpuzlu Meslekî Eğitim Merkezi',
  'AYDIN - KOÇARLI - Aydın Koçarlı Sabancı Öğretmenevi ve Akşam Sanat Okulu',
  'AYDIN - KOÇARLI - Çakırbeyli İlkokulu',
  'AYDIN - KOÇARLI - Çakırbeyli Ortaokulu',
  'AYDIN - KOÇARLI - Esentepe Ortaokulu',
  'AYDIN - KOÇARLI - Koçarlı Halk Eğitimi Merkezi',
  'AYDIN - KOÇARLI - Koçarlı Anadolu Lisesi',
  'AYDIN - KOÇARLI - Mustafa Keziban Küçükoğlu Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - KOÇARLI - Koçarlı Mesleki Eğitim Merkezi',
  'AYDIN - KOÇARLI - Mersinbeleni Ortaokulu',
  'AYDIN - KOÇARLI - Mersinbeleni İlkokulu',
  'AYDIN - KOÇARLI - Cumhuriyet Ortaokulu',
  'AYDIN - KOÇARLI - Atatürk İlkokulu',
  'AYDIN - KOÇARLI - Koçarlı İmam Hatip Ortaokulu',
  'AYDIN - KOÇARLI - Yeniköy Ortaokulu',
  'AYDIN - KOÇARLI - Yeniköy İlkokulu',
  'AYDIN - KOÇARLI - Kasaplar İlkokulu',
  'AYDIN - KOÇARLI - Kızılcabölük İlkokulu',
  'AYDIN - KOÇARLI - Çallı İlkokulu',
  'AYDIN - KOÇARLI - 80.Yıl Cumhuriyet Anaokulu',
  'AYDIN - KOÇARLI - Akmescit İlkokulu',
  'AYDIN - KOÇARLI - Bıyıklı Şehit Abdurrahim Çakır Ortaokulu',
  'AYDIN - KOÇARLI - Bıyıklı İlkokulu',
  'AYDIN - KOÇARLI - Dedeköy İlkokulu',
  'AYDIN - KOÇARLI - Esentepe İlkokulu',
  'AYDIN - KOÇARLI - Koçarlı Adnan Menderes Anadolu İmam Hatip Lisesi',
  'AYDIN - KÖŞK - Başçayır Ortaokulu',
  'AYDIN - KÖŞK - Köşk Halk Eğitimi Merkezi',
  'AYDIN - KÖŞK - Ayla Vural Anadolu Lisesi',
  'AYDIN - KÖŞK - Köşk Anaokulu',
  'AYDIN - KÖŞK - Altı Eylül Ortaokulu',
  'AYDIN - KÖŞK - 100.Yıl Atatürk Ortaokulu',
  'AYDIN - KÖŞK - Akçaköy İlkokulu',
  'AYDIN - KÖŞK - Adnan Menderes İlkokulu',
  'AYDIN - KÖŞK - Akçaköy Ortaokulu',
  'AYDIN - KÖŞK - Çiftlik Ortaokulu',
  'AYDIN - KÖŞK - Cumayanı Ortaokulu',
  'AYDIN - KÖŞK - Cumayanı İlkokulu',
  'AYDIN - KÖŞK - Ilıdağ İlkokulu',
  'AYDIN - KÖŞK - Beyköy Polis Abla Ortaokulu',
  'AYDIN - KÖŞK - Beyköy Polis Abla İlkokulu',
  'AYDIN - KÖŞK - Başçayır İlkokulu',
  'AYDIN - KÖŞK - Ilıdağ Ortaokulu',
  'AYDIN - KÖŞK - Kızılcaköy İlkokulu',
  'AYDIN - KÖŞK - Güzelköy İlkokulu',
  'AYDIN - KÖŞK - Kızılcayer İlkokulu',
  'AYDIN - KÖŞK - Yavuzköy İlkokulu',
  'AYDIN - KÖŞK - Uzundere İlkokulu',
  'AYDIN - KÖŞK - Sarıçam İlkokulu',
  'AYDIN - KÖŞK - Ketenyeri İlkokulu',
  'AYDIN - KÖŞK - Kıran İlkokulu',
  'AYDIN - KÖŞK - Gökkiriş İlkokulu',
  'AYDIN - KÖŞK - Koçak İlkokulu',
  'AYDIN - KÖŞK - Ahatlar İlkokulu',
  'AYDIN - KÖŞK - 100. Yıl Atatürk İlkokulu',
  'AYDIN - KÖŞK - Köşk Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - KÖŞK - ÇİFTLİK İLKOKULU',
  'AYDIN - KÖŞK - Köşk Anadolu İmam Hatip Lisesi',
  'AYDIN - KÖŞK - Şehit İlhan Apaydın İlkokulu',
  'AYDIN - KUŞADASI - Arife Bayram Bayaözlü Ortaokulu',
  'AYDIN - KUŞADASI - Bel-Kent Ortaokulu',
  'AYDIN - KUŞADASI - Derici Mustafa Gürbüz Anadolu Lisesi',
  'AYDIN - KUŞADASI - Feriha Ruhi Karakaş İlkokulu',
  'AYDIN - KUŞADASI - Güzelçamlı Mustafa Kemal İlkokulu',
  'AYDIN - KUŞADASI - Kuşadası Halk Eğitimi Merkezi',
  'AYDIN - KUŞADASI - Ada Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - KUŞADASI - Kirazlı Selim Eren Ortaokulu',
  'AYDIN - KUŞADASI - Güvercinada Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - KUŞADASI - Kuşadası Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - KUŞADASI - Kuşadası Hasan-Fatma Önal Anadolu Lisesi',
  'AYDIN - KUŞADASI - Kuşadası Öğretmenevi ve Akşam Sanat Okulu',
  'AYDIN - KUŞADASI - Mahmut Esat Bozkurt İlkokulu',
  'AYDIN - KUŞADASI - Kuşadası Makbule Hasan Uçar Anadolu Lisesi',
  'AYDIN - KUŞADASI - Melahat Kıvanç Anaokulu',
  'AYDIN - KUŞADASI - Kuşadası Mesleki Eğitim Merkezi',
  'AYDIN - KUŞADASI - Mücella Emgin Anaokulu',
  'AYDIN - KUŞADASI - Rahime Bilici İlkokulu',
  'AYDIN - KUŞADASI - Soğucak Ortaokulu',
  'AYDIN - KUŞADASI - Şehit Kaya Aldoğan Anadolu Lisesi',
  'AYDIN - KUŞADASI - Cumhuriyet İlkokulu',
  'AYDIN - KUŞADASI - Yedieylül İlkokulu',
  'AYDIN - KUŞADASI - Kuşadası İlkokulu',
  'AYDIN - KUŞADASI - Atatürk Ortaokulu',
  'AYDIN - KUŞADASI - Kuşadası İkiçeşmelik Ortaokulu',
  'AYDIN - KUŞADASI - Kuşadası İkiçeşmelik İlkokulu',
  'AYDIN - KUŞADASI - Kazım Dirik İlkokulu',
  'AYDIN - KUŞADASI - İbrahim Zeki Emgin İlkokulu',
  'AYDIN - KUŞADASI - Adviye-Ertuğrul Acun Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - KUŞADASI - Kirazlı Selim Eren İlkokulu',
  'AYDIN - KUŞADASI - Yeniköy İlkokulu',
  'AYDIN - KUŞADASI - Yayla İlkokulu',
  'AYDIN - KUŞADASI - Çakabey Ortaokulu',
  'AYDIN - KUŞADASI - Evliya Çelebi Anaokulu',
  'AYDIN - KUŞADASI - Vali Kadir Uysal Ortaokulu',
  'AYDIN - KUŞADASI - Pakize Kamil Çağlayan Ortaokulu',
  'AYDIN - KUŞADASI - Nermin Metin Akar Ortaokulu',
  'AYDIN - KUŞADASI - Cihan Çeliksoy Anaokulu',
  'AYDIN - KUŞADASI - Davutlar Anaokulu',
  'AYDIN - KUŞADASI - Reşat Nuri Güntekin İlkokulu',
  'AYDIN - KUŞADASI - Kuşadası Anadolu İmam Hatip Lisesi',
  'AYDIN - KUŞADASI - Kuşadası Anadolu Lisesi',
  'AYDIN - KUŞADASI - Şukufe Cemal Özbaş Anadolu Lisesi',
  'AYDIN - KUŞADASI - Aydın Adnan Menderes Üniversitesi Devlet Konservatuvarı Müzik ve Bale Ortaokulu',
  'AYDIN - KUŞADASI - Aydın Adnan Menderes Üniversitesi Devlet Konservatuvarı Müzik ve Sahne Sanatları Lisesi',
  'AYDIN - KUŞADASI - Kuşadası Bilim ve Sanat Merkezi',
  'AYDIN - KUŞADASI - Ayşıl-Oğuz Başöz Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - KUŞADASI - Kuşadası İkiçeşmelik Anaokulu',
  'AYDIN - KUYUCAK - Atatürk Ortaokulu',
  'AYDIN - KUYUCAK - Azizabat İlkokulu',
  'AYDIN - KUYUCAK - Cengiz Topel İlkokulu',
  'AYDIN - KUYUCAK - Ertuğrul Gazi İlkokulu',
  'AYDIN - KUYUCAK - Kuyucak Halk Eğitimi Merkezi',
  'AYDIN - KUYUCAK - Kuyucak Anadolu Lisesi',
  'AYDIN - KUYUCAK - Şehit Bahri Uçuş Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - KUYUCAK - Pamukören Anadolu Lisesi',
  'AYDIN - KUYUCAK - Pamukören Anaokulu',
  'AYDIN - KUYUCAK - Pamukören İlkokulu',
  'AYDIN - KUYUCAK - Pamukören Ortaokulu',
  'AYDIN - KUYUCAK - Başaran İlkokulu',
  'AYDIN - KUYUCAK - Gencelli Ortaokulu',
  'AYDIN - KUYUCAK - Başaran Ortaokulu',
  'AYDIN - KUYUCAK - Taşoluk İlkokulu',
  'AYDIN - KUYUCAK - Horsunlu İlkokulu',
  'AYDIN - KUYUCAK - Çanakkale Şehidi Kocayusufoğlu Hasan Ortaokulu',
  'AYDIN - KUYUCAK - Horsunlu Anaokulu',
  'AYDIN - KUYUCAK - Çobanisa İlkokulu',
  'AYDIN - KUYUCAK - Taşoluk Ortaokulu',
  'AYDIN - KUYUCAK - Şehit Polis Ali İnceoğlu İlkokulu',
  'AYDIN - KUYUCAK - Kayran İlkokulu',
  'AYDIN - KUYUCAK - Kayran Ortaokulu',
  'AYDIN - KUYUCAK - Kuyucak Anaokulu',
  'AYDIN - KUYUCAK - Kurtuluş Ortaokulu',
  'AYDIN - KUYUCAK - Şehit Tekin Durmaz İlkokulu',
  'AYDIN - KUYUCAK - Kuyucak Mesleki Eğitim Merkezi',
  'AYDIN - KUYUCAK - Yamalak Ortaokulu',
  'AYDIN - KUYUCAK - Yamalak İlkokulu',
  'AYDIN - KUYUCAK - Kuyucak İmam Hatip Ortaokulu',
  'AYDIN - KUYUCAK - Yeşildere İlkokulu',
  'AYDIN - KUYUCAK - Yukarı Yakacık İlkokulu',
  'AYDIN - KUYUCAK - Kuyucak Bilim ve Sanat Merkezi',
  'AYDIN - KUYUCAK - Sarıcaova İlkokulu',
  'AYDIN - NAZİLLİ - Aksu İlkokulu',
  'AYDIN - NAZİLLİ - Bayındır İlkokulu',
  'AYDIN - NAZİLLİ - Bayındır Ortaokulu',
  'AYDIN - NAZİLLİ - Demirciler Ortaokulu',
  'AYDIN - NAZİLLİ - Şehit Celal Güngör Ortaokulu',
  'AYDIN - NAZİLLİ - Nazilli Halk Eğitimi Merkezi',
  'AYDIN - NAZİLLİ - Şehit Sümer Deniz Anadolu İmam Hatip Lisesi',
  'AYDIN - NAZİLLİ - Kızıldere İlkokulu',
  'AYDIN - NAZİLLİ - Kızıldere Ortaokulu',
  'AYDIN - NAZİLLİ - Koçlar İlkokulu',
  'AYDIN - NAZİLLİ - Nazilli Latife Hanım Anaokulu',
  'AYDIN - NAZİLLİ - Nazilli Mehmet Akif Ersoy Anadolu Lisesi',
  'AYDIN - NAZİLLİ - Nazilli Mesleki Eğitim Merkezi',
  'AYDIN - NAZİLLİ - Müşerref Gündoğdu Ortaokulu',
  'AYDIN - NAZİLLİ - Nahit Menteşe Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - NAZİLLİ - Nazilli Anadolu Lisesi',
  'AYDIN - NAZİLLİ - Nazilli Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - NAZİLLİ - Nazilli Fen Lisesi',
  'AYDIN - NAZİLLİ - Nazilli Lisesi',
  'AYDIN - NAZİLLİ - Nazilli Menderes Anadolu Lisesi',
  'AYDIN - NAZİLLİ - Nazilli Özel Eğitim Meslek Okulu',
  'AYDIN - NAZİLLİ - Nazlı Kız Anaokulu',
  'AYDIN - NAZİLLİ - Sümer Anaokulu',
  'AYDIN - NAZİLLİ - Zübeyde Hanım Anaokulu',
  'AYDIN - NAZİLLİ - İbn-i Sina Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - NAZİLLİ - Pirlibey Ortaokulu',
  'AYDIN - NAZİLLİ - Nazilli Atatürk Anadolu Lisesi',
  'AYDIN - NAZİLLİ - Demirciler İlkokulu',
  'AYDIN - NAZİLLİ - Vakıfbank İlkokulu',
  'AYDIN - NAZİLLİ - Pirlibey İlkokulu',
  'AYDIN - NAZİLLİ - Bekirler İlkokulu',
  'AYDIN - NAZİLLİ - Nazilli Rehberlik ve Araştırma Merkezi',
  'AYDIN - NAZİLLİ - İstiklal İlkokulu',
  'AYDIN - NAZİLLİ - Şehitler Ortaokulu',
  'AYDIN - NAZİLLİ - Turan Ortaokulu',
  'AYDIN - NAZİLLİ - Ahmet Yesevi İlkokulu',
  'AYDIN - NAZİLLİ - Gazi Mustafa Kemal Ortaokulu',
  'AYDIN - NAZİLLİ - Hasköy Ortaokulu',
  'AYDIN - NAZİLLİ - Hasköy İlkokulu',
  'AYDIN - NAZİLLİ - Aşağı Örencik İlkokulu',
  'AYDIN - NAZİLLİ - İbn-i Sina İlkokulu',
  'AYDIN - NAZİLLİ - Çaylı İlkokulu',
  'AYDIN - NAZİLLİ - Çaylı Ortaokulu',
  'AYDIN - NAZİLLİ - Recebbey İlkokulu',
  'AYDIN - NAZİLLİ - Ovacık İlkokulu',
  'AYDIN - NAZİLLİ - Koçlar Ortaokulu',
  'AYDIN - NAZİLLİ - Fatih Ortaokulu',
  'AYDIN - NAZİLLİ - Aksu Ortaokulu',
  'AYDIN - NAZİLLİ - Yaylapınar İhsan İzgi Ortaokulu',
  'AYDIN - NAZİLLİ - Aşağı Yakacık Ortaokulu',
  'AYDIN - NAZİLLİ - Aşağı Yakacık İlkokulu',
  'AYDIN - NAZİLLİ - Aydoğdu Adnan Menderes İlkokulu',
  'AYDIN - NAZİLLİ - İsabeyli İlkokulu',
  'AYDIN - NAZİLLİ - İsabeyli Ortaokulu',
  'AYDIN - NAZİLLİ - Hisarcık İlkokulu',
  'AYDIN - NAZİLLİ - Yavuz Selim İlkokulu',
  'AYDIN - NAZİLLİ - Yukarı Örencik İlkokulu',
  'AYDIN - NAZİLLİ - Ovacık Ortaokulu',
  'AYDIN - NAZİLLİ - Şehit Mehmet Dinek Ortaokulu',
  'AYDIN - NAZİLLİ - Zafer İlkokulu',
  'AYDIN - NAZİLLİ - Atatürk Ortaokulu',
  'AYDIN - NAZİLLİ - Nahit Menteşe Ortaokulu',
  'AYDIN - NAZİLLİ - Nazilli 50. Yıl Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - NAZİLLİ - Dallıca İlkokulu',
  'AYDIN - NAZİLLİ - Beşeylül Ortaokulu',
  'AYDIN - NAZİLLİ - Ketendere İlkokulu',
  'AYDIN - NAZİLLİ - Orhangazi Ortaokulu',
  'AYDIN - NAZİLLİ - Cumhuriyet İlkokulu',
  'AYDIN - NAZİLLİ - Öğretmen Evi ve Akşam Sanat Okulu',
  'AYDIN - NAZİLLİ - Işıklar İlkokulu',
  'AYDIN - NAZİLLİ - Orhangazi İlkokulu',
  'AYDIN - NAZİLLİ - Çapahasan İlkokulu',
  'AYDIN - NAZİLLİ - Şehit Celal Güngör İlkokulu',
  'AYDIN - NAZİLLİ - Nazilli Özel Eğitim Ortaokulu',
  'AYDIN - NAZİLLİ - Fatih İlkokulu',
  'AYDIN - NAZİLLİ - Nazilli Sosyal Bilimler Lisesi',
  'AYDIN - NAZİLLİ - Yaylapınar İhsan İzgi İlkokulu',
  'AYDIN - NAZİLLİ - Mehmet Sofuoğlu İmam Hatip Ortaokulu',
  'AYDIN - NAZİLLİ - Mastavra İlkokulu',
  'AYDIN - NAZİLLİ - İmam Hatip Ortaokulu',
  'AYDIN - NAZİLLİ - ASIMIN NESLİ ANADOLU İMAM HATİP LİSESİ',
  'AYDIN - NAZİLLİ - Nazilli Güzelköy Özel Eğitim Uygulama Okulu III. Kademe',
  'AYDIN - NAZİLLİ - 15 Temmuz İlkokulu',
  'AYDIN - NAZİLLİ - İsabeyli Anaokulu',
  'AYDIN - NAZİLLİ - Nazilli Bilim ve Sanat Merkezi',
  'AYDIN - NAZİLLİ - Süleyman Efendi Özel Eğitim Uygulama Okulu I. Kademe',
  'AYDIN - NAZİLLİ - Nazilli Güzelköy Özel Eğitim Uygulama Okulu I. Kademe',
  'AYDIN - NAZİLLİ - Nazilli Güzelköy Özel Eğitim Uygulama Okulu II. Kademe',
  'AYDIN - NAZİLLİ - Süleyman Efendi Özel Eğitim Uygulama Okulu II. Kademe',
  'AYDIN - NAZİLLİ - Aslı-Mustafa Takmaklı Kızılay Anaokulu',
  'AYDIN - NAZİLLİ - Nazilli Bilim ve Sanat Merkezi Anaokulu',
  'AYDIN - NAZİLLİ - 15 Temmuz Anaokulu',
  'AYDIN - NAZİLLİ - Fatih Anaokulu',
  'AYDIN - NAZİLLİ - Cumhuriyet Anaokulu',
  'AYDIN - NAZİLLİ - Vakıfbank Anaokulu',
  'AYDIN - NAZİLLİ - Sümer Özel Eğitim Anaokulu',
  'AYDIN - SÖKE - Söke Kız Anadolu İmam Hatip Lisesi',
  'AYDIN - SÖKE - 100.Yıl Atatürk İlkokulu',
  'AYDIN - SÖKE - 100.Yıl Atatürk Ortaokulu',
  'AYDIN - SÖKE - Akçakonak İlkokulu',
  'AYDIN - SÖKE - Ali Rıza Efendi Ortaokulu',
  'AYDIN - SÖKE - Atburgazı İlkokulu',
  'AYDIN - SÖKE - Atburgazı Ortaokulu',
  'AYDIN - SÖKE - Bağarası Nesrin DEMİRTAŞ BİLGİN Anaokulu',
  'AYDIN - SÖKE - Bağarası Çok Programlı Anadolu Lisesi',
  'AYDIN - SÖKE - Bağarası Hürriyet İlkokulu',
  'AYDIN - SÖKE - Bağarası Kemalpaşa Ortaokulu',
  'AYDIN - SÖKE - Batı Söke Çimento Ortaokulu',
  'AYDIN - SÖKE - Çavdar Ferit Çavuş Ortaokulu',
  'AYDIN - SÖKE - Fahrettin Uyguntüzel İlkokulu',
  'AYDIN - SÖKE - Fatma Tüzzehra Orhun Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - SÖKE - Fevzipaşa İlkokulu',
  'AYDIN - SÖKE - Güllübahçe Atatürk Ortaokulu',
  'AYDIN - SÖKE - Söke Halk Eğitimi Merkezi',
  'AYDIN - SÖKE - Söke Hilmi Fırat Anadolu Lisesi',
  'AYDIN - SÖKE - Kisir İlkokulu',
  'AYDIN - SÖKE - Kisir Ortaokulu',
  'AYDIN - SÖKE - Kocagözoğlu Ortaokulu',
  'AYDIN - SÖKE - Mehmet Ali Ekener Anaokulu',
  'AYDIN - SÖKE - Söke Mesleki Eğitim Merkezi',
  'AYDIN - SÖKE - Öğretmen Nebahat Alpan Ortaokulu',
  'AYDIN - SÖKE - Sadullah Kuşada İlkokulu',
  'AYDIN - SÖKE - Savuca Fatma Suat Ortaokulu',
  'AYDIN - SÖKE - Savuca İlkokulu',
  'AYDIN - SÖKE - Sazlıköy Anaokulu',
  'AYDIN - SÖKE - Sazlıköy Hilmi Fırat İlkokulu',
  'AYDIN - SÖKE - Seyda Fırat İlkokulu',
  'AYDIN - SÖKE - Sıdıka İlkokulu',
  'AYDIN - SÖKE - Söke Yavuz Selim Anadolu Lisesi',
  'AYDIN - SÖKE - Söke Atatürk Ortaokulu',
  'AYDIN - SÖKE - Şehit Emre Acar Cumhuriyet Anadolu Lisesi',
  'AYDIN - SÖKE - Söke Cafer Efe Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - SÖKE - Söke Anadolu Lisesi',
  'AYDIN - SÖKE - Söke Rehberlik ve Araştırma Merkezi',
  'AYDIN - SÖKE - Söke Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - SÖKE - Adnan Menderes Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - SÖKE - Söktaş 75.Yıl İlkokulu',
  'AYDIN - SÖKE - Sümer Yılmaz Kocagöz Anaokulu',
  'AYDIN - SÖKE - Söke Ticaret Borsası Suat Orhon Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - SÖKE - Tuzburgazı Ortaokulu',
  'AYDIN - SÖKE - Vakıfbank İlkokulu',
  'AYDIN - SÖKE - Fatih İlkokulu',
  'AYDIN - SÖKE - Felekşan Fırat Ortaokulu',
  'AYDIN - SÖKE - Felekşan Fırat İlkokulu',
  'AYDIN - SÖKE - Söktaş 75.Yıl Ortaokulu',
  'AYDIN - SÖKE - Öğretmen Nebahat Alpan İlkokulu',
  'AYDIN - SÖKE - Çeltikçi Ortaokulu',
  'AYDIN - SÖKE - Sazlıköy Hacı Halil Paşa İlkokulu',
  'AYDIN - SÖKE - Sazlıköy Hacı Halil Paşa Ortaokulu',
  'AYDIN - SÖKE - Behiye Hanım Ortaokulu',
  'AYDIN - SÖKE - Fatih Ortaokulu',
  'AYDIN - SÖKE - Çavdar Ferit Çavuş İlkokulu',
  'AYDIN - SÖKE - Hacıkazımoğlu İlkokulu',
  'AYDIN - SÖKE - Kemalpaşa İlkokulu',
  'AYDIN - SÖKE - Ağaçlı İlkokulu',
  'AYDIN - SÖKE - Özbey Ortaokulu',
  'AYDIN - SÖKE - Fevzipaşa Ortaokulu',
  'AYDIN - SÖKE - Kıryarlar Özel Eğitim Uygulama Okulu III. Kademe',
  'AYDIN - SÖKE - Savuca Fatma Suat İlkokulu',
  'AYDIN - SÖKE - Sarıkemer Emine Gezerler İlkokulu',
  'AYDIN - SÖKE - Sarıkemer Emine Gezerler Ortaokulu',
  'AYDIN - SÖKE - Özbey İlkokulu',
  'AYDIN - SÖKE - Güllübahçe Atatürk İlkokulu',
  'AYDIN - SÖKE - Tuzburgazı İlkokulu',
  'AYDIN - SÖKE - Sazlıköy Hilmi Fırat Ortaokulu',
  'AYDIN - SÖKE - Akçakonak Ortaokulu',
  'AYDIN - SÖKE - Ali Rıza Efendi İlkokulu',
  'AYDIN - SÖKE - Bağarası Hürriyet Ortaokulu',
  'AYDIN - SÖKE - Bağarası Kemalpaşa İlkokulu',
  'AYDIN - SÖKE - Savuca Ortaokulu',
  'AYDIN - SÖKE - Serçin İlkokulu',
  'AYDIN - SÖKE - Sarıkemer Ortaokulu',
  'AYDIN - SÖKE - Sarıkemer İlkokulu',
  'AYDIN - SÖKE - Şehit Oğuz Arslan İmam Hatip Ortaokulu',
  'AYDIN - SÖKE - Söke Özel Eğitim Meslek Okulu',
  'AYDIN - SÖKE - ŞEHİT FARUK DEMİR ANADOLU İMAM HATİP LİSESİ',
  'AYDIN - SÖKE - SÖKE BİLİM VE SANAT MERKEZİ',
  'AYDIN - SÖKE - Öğretmen Evi ve Akşam Sanat Okulu',
  'AYDIN - SÖKE - Kıryarlar Özel Eğitim Uygulama Okulu II. Kademe',
  'AYDIN - SÖKE - Kıryarlar Özel Eğitim Uygulama Okulu I. Kademe',
  'AYDIN - SÖKE - Fehime Kocagöz Anaokulu',
  'AYDIN - SÖKE - Söke Anadolu İmam Hatip Lisesi',
  'AYDIN - SÖKE - Öğretmen Nebahat Alpan Anaokulu',
  'AYDIN - SÖKE - Çeltikçi Anaokulu',
  'AYDIN - SULTANHİSAR - Atça Şehit Ufuk Demirkıran Mesleki ve Teknik Anadolu Lisesi',
  'AYDIN - SULTANHİSAR - Atça Atatürk İlkokulu',
  'AYDIN - SULTANHİSAR - Atça Hadıloğlu İbrahim Uzunırmak Ortaokulu',
  'AYDIN - SULTANHİSAR - Beşeylül İlkokulu',
  'AYDIN - SULTANHİSAR - Cumhuriyet Anaokulu',
  'AYDIN - SULTANHİSAR - Demirhan İlkokulu',
  'AYDIN - SULTANHİSAR - Eskihisar İlkokulu',
  'AYDIN - SULTANHİSAR - Sultanhisar Halk Eğitimi Merkezi',
  'AYDIN - SULTANHİSAR - İncealan İlkokulu',
  'AYDIN - SULTANHİSAR - Kabaca İlkokulu',
  'AYDIN - SULTANHİSAR - Yasemin Lütfiye Anadolu Lisesi',
  'AYDIN - SULTANHİSAR - Atça Şehit Mutlu Uçar Anadolu Lisesi',
  'AYDIN - SULTANHİSAR - Uzunlar İlkokulu',
  'AYDIN - SULTANHİSAR - Gazi Mustafa Kemal İlkokulu',
  'AYDIN - SULTANHİSAR - Atça Fahriye Dilerek İlkokulu',
  'AYDIN - SULTANHİSAR - Atça Ali Sönmez İlkokulu',
  'AYDIN - SULTANHİSAR - Zafer Ortaokulu',
  'AYDIN - SULTANHİSAR - Salavatlı İlkokulu',
  'AYDIN - SULTANHİSAR - Salavatlı Ortaokulu',
  'AYDIN - SULTANHİSAR - Sabiha Gökçen Anaokulu',
  'AYDIN - SULTANHİSAR - Eskihisar Ortaokulu',
  'AYDIN - SULTANHİSAR - Malgaçemir İlkokulu',
  'AYDIN - SULTANHİSAR - Atça Şehit Şükrü Öksüz İmam Hatip Ortaokulu',
  'AYDIN - SULTANHİSAR - Şehit Ayhan Yeşilyol Anadolu İmam Hatip Lisesi',
  'AYDIN - SULTANHİSAR - Sultanhisar Bilim ve Sanat Merkezi',
  'AYDIN - YENİPAZAR - Halk Eğitimi Merkezi',
  'AYDIN - YENİPAZAR - Yenipazar Mesleki Eğitim Merkezi',
  'AYDIN - YENİPAZAR - Yenipazar Anaokulu',
  'AYDIN - YENİPAZAR - Yenipazar Çok Programlı Anadolu Lisesi',
  'AYDIN - YENİPAZAR - Koyunlar İlkokulu',
  'AYDIN - YENİPAZAR - Donduran Ortaokulu',
  'AYDIN - YENİPAZAR - Donduran İlkokulu',
  'AYDIN - YENİPAZAR - Hamzabali Ortaokulu',
  'AYDIN - YENİPAZAR - Hamzabali İlkokulu',
  'AYDIN - YENİPAZAR - Cumhuriyet Ortaokulu',
  'AYDIN - YENİPAZAR - Cumhuriyet İlkokulu',
  'AYDIN - YENİPAZAR - Karacaören Ortaokulu',
  'AYDIN - YENİPAZAR - Paşaköy İlkokulu',
  'AYDIN - YENİPAZAR - Merkez İlkokulu',
  'AYDIN - YENİPAZAR - Merkez Ortaokulu',
  'AYDIN - YENİPAZAR - Karacaören İlkokulu',
  'AYDIN - YENİPAZAR - Yenipazar İmam Hatip Ortaokulu',
  'AYDIN - YENİPAZAR - Yenipazar Anadolu Lisesi',
  ];
}