class BalikesirSchools{
  final List<String> _list=[
  'BALIKESİR - ALTIEYLÜL - Kesirven Şehit Mehmet Eren İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Altıeylül Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Atköy İlkokulu',
  'BALIKESİR - ALTIEYLÜL - 15 Temmuz Şehitler Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Mimar Sinan Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Ermişler Cumhuriyet Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Balıklı İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Fevzi Çakmak İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Gaziosmanpaşa İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Hüma Hatun Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Mehmet Akif Ersoy İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Mehmet Vehbi Bolak Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Kurtdereli Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Mithatpaşa Anaokulu',
  'BALIKESİR - ALTIEYLÜL - Yakupköy İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Şehit Ömer Faruk Bol İmam Hatip Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Hasan Basri Çantay İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Kesirven Şehit Mehmet Eren ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Ovaköy Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Ovaköy İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Mehmet Ağa Safarov Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Plevne İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Burhan Erdayı Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Pamukçu Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - 100. Yıl Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Zağnospaşa Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Aslıhantepecik İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Aslıhantepecik Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Ayşebacı Köyü Şehit İsa Yavaş Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Yunus Emre Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Kabaklı İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Cumhuriyet İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Edip Gürcün İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Namık Kemal İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Karamanlar İlkokulu',
  'BALIKESİR - ALTIEYLÜL - General Kemal Balıkesir Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Karamanlar Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Hatice Fahriye Eğinlioğlu İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Burhan Erdayı İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Şehit Jandarma Uzman Çavuş Okan Dinçer Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Konakpınar Köyü Şehit Jandarma Başçavuş Erbu Serpan Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Balıklı Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Konakpınar Köyü Şehit Jandarma Başçavuş Erbu Serpan İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Sevgi Özel Eğitim Uygulama Merkezi II. Kademe',
  'BALIKESİR - ALTIEYLÜL - Yarış Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Karamanköy Mehmetcik Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Karamanköy Mehmetcik İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Çandır Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Köylüköy İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Köylüköy Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Halalca Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Halalca İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Köseler İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Büyük Bostancı İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Pamukçu İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Gülser-Mehmet Bolluk Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Ortamandıra Şehit Gürel Alagöz Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Macarlar İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Ortamandıra Şehit Gürel Alagöz İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Macarlar Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Sabiha Gökçen Anaokulu',
  'BALIKESİR - ALTIEYLÜL - Mehmet Akif Ersoy Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Yakupköy Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Necatibey Eğitim Fakültesi Anaokulu',
  'BALIKESİR - ALTIEYLÜL - Fahri Kiraz Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Organize Sanayi Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - ALTIEYLÜL - Bengi Anaokulu',
  'BALIKESİR - ALTIEYLÜL - Altıeylül Halk Eğitimi Merkezi',
  'BALIKESİR - ALTIEYLÜL - Gökköy İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Çandır İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Cumhuriyet Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Yakup Mihriye Akdeniz Anadolu İmam Hatip Lisesi',
  'BALIKESİR - ALTIEYLÜL - Kadriye Kemal Gürel İlkokulu',
  'BALIKESİR - ALTIEYLÜL - Ayşebacı Köyü Şehit İsa Yavaş İlkokulu',
  'BALIKESİR - ALTIEYLÜL - ALTIEYLÜL REHBERLİK VE ARAŞTIRMA MERKEZİ',
  'BALIKESİR - ALTIEYLÜL - ATKÖY ORTAOKULU',
  'BALIKESİR - ALTIEYLÜL - Pamukçu İmam Hatip Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Sevgi Özel Eğitim Uygulama Okulu I. Kademe',
  'BALIKESİR - ALTIEYLÜL - Nuran Oğuz Özel Eğitim Anaokulu',
  'BALIKESİR - ALTIEYLÜL - Ahmet Karatoprak İmam Hatip Ortaokulu',
  'BALIKESİR - ALTIEYLÜL - Şehit Uzman Çavuş Davut Armağan Keskin Özel Eğitim Anaokulu',
  'BALIKESİR - ALTIEYLÜL - Balıkesir Atatürk Şehir Hastanesi Anaokulu',
  'BALIKESİR - ALTIEYLÜL - Altıeylül Bilim ve Sanat Merkezi',
  'BALIKESİR - ALTIEYLÜL - Altıeylül Fen Lisesi',
  'BALIKESİR - ALTIEYLÜL - BURHAN ERDAYI ANAOKULU',
  'BALIKESİR - ALTIEYLÜL - GENERAL KEMAL BALIKESİR ANAOKULU',
  'BALIKESİR - ALTIEYLÜL - MEHMET AKİF ERSOY ANAOKULU',
  'BALIKESİR - AYVALIK - Çakmak Ortaokulu',
  'BALIKESİR - AYVALIK - Abdülvahit Sağlam İlkokulu',
  'BALIKESİR - AYVALIK - Akçapınar İlkokulu',
  'BALIKESİR - AYVALIK - Ayvalık İmam Hatip Ortaokulu',
  'BALIKESİR - AYVALIK - Altınova Atatürk İlkokulu',
  'BALIKESİR - AYVALIK - Nuri Zarplı Ortaokulu',
  'BALIKESİR - AYVALIK - Öğretmenevi ve Akşam Sanat Okulu',
  'BALIKESİR - AYVALIK - Altınova Ondört Eylül İlkokulu',
  'BALIKESİR - AYVALIK - Atatürk İlkokulu',
  'BALIKESİR - AYVALIK - Ayvalık Rahim Usta Anadolu Lisesi',
  'BALIKESİR - AYVALIK - Ayvalık Anaokulu',
  'BALIKESİR - AYVALIK - Şehit Abdullah Tayyip Olçok Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - AYVALIK - Ayvalık Zübeyde Hanım Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - AYVALIK - Bağyüzü İlkokulu',
  'BALIKESİR - AYVALIK - Çamoba İlkokulu',
  'BALIKESİR - AYVALIK - Çakmak İlkokulu',
  'BALIKESİR - AYVALIK - Kıvanç Sarlıcalı İlkokulu',
  'BALIKESİR - AYVALIK - Ayvalık Mesleki Eğitim Merkezi',
  'BALIKESİR - AYVALIK - Nuri Zarplı İlkokulu',
  'BALIKESİR - AYVALIK - Pakmaya Kenan Kaptan Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - AYVALIK - İstiklal İlkokulu',
  'BALIKESİR - AYVALIK - Ayvalık Atatürk Anadolu Lisesi',
  'BALIKESİR - AYVALIK - 15 Eylül Ortaokulu',
  'BALIKESİR - AYVALIK - Mecit Ataklı İlkokulu',
  'BALIKESİR - AYVALIK - Ayvalık Anadolu Lisesi',
  'BALIKESİR - AYVALIK - Mehmet Akif Ersoy Ortaokulu',
  'BALIKESİR - AYVALIK - Akçapınar Ortaokulu',
  'BALIKESİR - AYVALIK - Sakarya Ortaokulu',
  'BALIKESİR - AYVALIK - Ali Çetinkaya Ortaokulu',
  'BALIKESİR - AYVALIK - Sakarya İlkokulu',
  'BALIKESİR - AYVALIK - Ali Çetinkaya İlkokulu',
  'BALIKESİR - AYVALIK - Altınova Anaokulu',
  'BALIKESİR - AYVALIK - Ayvalık Halk Eğitimi Merkezi',
  'BALIKESİR - AYVALIK - Mecit Ataklı Ortaokulu',
  'BALIKESİR - AYVALIK - Altınova Merkez İlkokulu',
  'BALIKESİR - AYVALIK - Bağyüzü Ortaokulu',
  'BALIKESİR - AYVALIK - Şehit Ömer Halisdemir Çok Programlı Anadolu Lisesi',
  'BALIKESİR - AYVALIK - Cunda Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - AYVALIK - Necmi Komili İlkokulu',
  'BALIKESİR - AYVALIK - Necmi Komili Ortaokulu',
  'BALIKESİR - AYVALIK - Cihan Yorgun Ortaokulu',
  'BALIKESİR - AYVALIK - Ustalı Anadolu İmam Hatip Lisesi',
  'BALIKESİR - AYVALIK - Sebahat-Cihan Şişman Güzel Sanatlar Lisesi',
  'BALIKESİR - AYVALIK - ATATÜRK ANAOKULU',
  'BALIKESİR - AYVALIK - Ayvalık Rehberlik ve Araştırma Merkezi',
  'BALIKESİR - BALYA - Balya Atatürk Çok Programlı Anadolu Lisesi',
  'BALIKESİR - BALYA - Balya Zübeyde Hanım Anaokulu',
  'BALIKESİR - BALYA - Zübeyde Hanım Yatılı Bölge Ortaokulu',
  'BALIKESİR - BALYA - ÇAMAVŞAR İLKOKULU',
  'BALIKESİR - BALYA - ŞAMİLE ALTINTAŞ İLKOKULU',
  'BALIKESİR - BALYA - ILICA ŞEHİT NECMİ GÜRGEN ORTAOKULU',
  'BALIKESİR - BALYA - HACIHÜSEYİN İLKOKULU',
  'BALIKESİR - BALYA - ILICA ŞEHİT NECMİ GÜRGEN İLKOKULU',
  'BALIKESİR - BALYA - YENİKAVAK İLKOKULU',
  'BALIKESİR - BALYA - ALİDEMİRCİ İLKOKULU',
  'BALIKESİR - BALYA - Balya Halk Eğitimi Merkezi',
  'BALIKESİR - BALYA - ÇAMUCU İLKOKULU',
  'BALIKESİR - BALYA - KOYUNERİ ORTAOKULU',
  'BALIKESİR - BALYA - KOYUNERİ İLKOKULU',
  'BALIKESİR - BALYA - ÇAMAVŞAR ORTAOKULU',
  'BALIKESİR - BALYA - DEREKÖY İLKOKULU',
  'BALIKESİR - BALYA - İmam Hatip Ortaokulu',
  'BALIKESİR - BANDIRMA - Bandırma Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Bandırma Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Bandırma Yavuz Sultan Selim Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Akşemsettin Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Haydar Cavuş Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Bandırma İmam Hatip Ortaokulu',
  'BALIKESİR - BANDIRMA - Edincik Recep Gencer Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Enerjisa Bandırma Fen Lisesi',
  'BALIKESİR - BANDIRMA - Bandırma Halk Eğitimi Merkezi',
  'BALIKESİR - BANDIRMA - Hürriyet İlkokulu',
  'BALIKESİR - BANDIRMA - Bandırma Anadolu İmam Hatip Lisesi',
  'BALIKESİR - BANDIRMA - Kemal Pireci Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Hafsa Sultan Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Bandırma Mesleki Eğitim Merkezi',
  'BALIKESİR - BANDIRMA - Öğretmenevi ve Akşam Sanat Okulu',
  'BALIKESİR - BANDIRMA - Bandırma Rehberlik ve Araştırma Merkezi',
  'BALIKESİR - BANDIRMA - Şehit Mehmet Günenç Anadolu Lisesi',
  'BALIKESİR - BANDIRMA - Şehit Süleymanbey Ortaokulu',
  'BALIKESİR - BANDIRMA - Şehit Teğmen Doğuş Uran Anaokulu',
  'BALIKESİR - BANDIRMA - 100. Yıl İlkokulu',
  'BALIKESİR - BANDIRMA - Aksakal Umut Akkaya Ortaokulu',
  'BALIKESİR - BANDIRMA - Aksakal İlkokulu',
  'BALIKESİR - BANDIRMA - Bandırma Atatürk Özel Eğitim Ortaokulu',
  'BALIKESİR - BANDIRMA - Şehit Süleymanbey İlkokulu',
  'BALIKESİR - BANDIRMA - Cumhuriyet İlkokulu',
  'BALIKESİR - BANDIRMA - Bandırma Atatürk Özel Eğitim İlkokulu',
  'BALIKESİR - BANDIRMA - 17 Eylül İlkokulu',
  'BALIKESİR - BANDIRMA - Kemal Pireci Ortaokulu',
  'BALIKESİR - BANDIRMA - Şehit Öğretmen Mustafa Boz İlkokulu',
  'BALIKESİR - BANDIRMA - Yaman Egeli Ortaokulu',
  'BALIKESİR - BANDIRMA - Edincik Ortaokulu',
  'BALIKESİR - BANDIRMA - Edincik İlkokulu',
  'BALIKESİR - BANDIRMA - Hasan Atlı İlkokulu',
  'BALIKESİR - BANDIRMA - Şehit Bedir Karabıyık Ortaokulu',
  'BALIKESİR - BANDIRMA - Ticaret Borsası Ortaokulu',
  'BALIKESİR - BANDIRMA - Hicri Ercili Özel Eğitim Meslek Okulu',
  'BALIKESİR - BANDIRMA - Ticaret Borsası İlkokulu',
  'BALIKESİR - BANDIRMA - Ali Fahri İşeri İlkokulu',
  'BALIKESİR - BANDIRMA - Eti Maden Ortaokulu',
  'BALIKESİR - BANDIRMA - Çalışkanlar İlkokulu',
  'BALIKESİR - BANDIRMA - Korgeneral Enver Akoğlu Ortaokulu',
  'BALIKESİR - BANDIRMA - Esnaf Sanatkarları Ortaokulu',
  'BALIKESİR - BANDIRMA - Edincik Onsekizeylül İlkokulu',
  'BALIKESİR - BANDIRMA - Ticaret Odası Ortaokulu',
  'BALIKESİR - BANDIRMA - Ticaret Odası İlkokulu',
  'BALIKESİR - BANDIRMA - Bandırma Ortaokulu',
  'BALIKESİR - BANDIRMA - Marmara İlkokulu',
  'BALIKESİR - BANDIRMA - Erikli İlkokulu',
  'BALIKESİR - BANDIRMA - Şehit Pilot Üsteğmen Cemil Kaya Ortaokulu',
  'BALIKESİR - BANDIRMA - Fatih Ortaokulu',
  'BALIKESİR - BANDIRMA - Şehit Pilot Üsteğmen Cemil Kaya İlkokulu',
  'BALIKESİR - BANDIRMA - Yeniyenice İlkokulu',
  'BALIKESİR - BANDIRMA - Ahmet Obalı Anaokulu',
  'BALIKESİR - BANDIRMA - Bandırma Bilim ve Sanat Merkezi',
  'BALIKESİR - BANDIRMA - 15 Temmuz Şehit Ramazan Konuş İmam Hatip Ortaokulu',
  'BALIKESİR - BANDIRMA - Ali Öztaylan Anadolu İmam Hatip Lisesi',
  'BALIKESİR - BANDIRMA - Zübeyde Hanım Anaokulu',
  'BALIKESİR - BANDIRMA - Bandırma Adalet Mesleki Eğitim Merkezi',
  'BALIKESİR - BANDIRMA - Ahmet Baş Anaokulu',
  'BALIKESİR - BANDIRMA - BANDIRMA BİLİM VE SANAT MERKEZİ ANAOKULU',
  'BALIKESİR - BANDIRMA - Sahil Yenice İlkokulu',
  'BALIKESİR - BANDIRMA - Hicri Ercili Özel Eğitim Uygulama Okulu I. Kademe',
  'BALIKESİR - BANDIRMA - Hicri Ercili Özel Eğitim Uygulama Okulu II. Kademe',
  'BALIKESİR - BANDIRMA - Hicri Ercili Özel Eğitim Uygulama Okulu III. Kademe',
  'BALIKESİR - BANDIRMA - ŞEHİT ÖĞRETMEN MUSTAFA BOZ ANAOKULU',
  'BALIKESİR - BANDIRMA - CUMHURİYET ANAOKULU',
  'BALIKESİR - BANDIRMA - ŞEHİT PİLOT ÜSTEĞMEN CEMİL KAYA ANAOKULU',
  'BALIKESİR - BANDIRMA - Çınarlı Özel Eğitim Anaokulu',
  'BALIKESİR - BİGADİÇ - 75. Yıl Eti Holding İlkokulu',
  'BALIKESİR - BİGADİÇ - Eti Maden Işıklar Ortaokulu',
  'BALIKESİR - BİGADİÇ - Bigadiç Anadolu İmam Hatip Lisesi',
  'BALIKESİR - BİGADİÇ - Atatürk İlkokulu',
  'BALIKESİR - BİGADİÇ - Başçeşme İlkokulu',
  'BALIKESİR - BİGADİÇ - Cumhuriyet İlkokulu',
  'BALIKESİR - BİGADİÇ - Bigadiç Anadolu Lisesi',
  'BALIKESİR - BİGADİÇ - Kuvayi Milliye Anadolu Lisesi',
  'BALIKESİR - BİGADİÇ - Bigadiç Dörteylül Şehit Mustafa Çiğdem Anaokulu',
  'BALIKESİR - BİGADİÇ - Bigadiç Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BİGADİÇ - Çayüstü İlkokulu',
  'BALIKESİR - BİGADİÇ - Elyapan İlkokulu',
  'BALIKESİR - BİGADİÇ - Fatih İlkokulu',
  'BALIKESİR - BİGADİÇ - Emirler İlkokulu',
  'BALIKESİR - BİGADİÇ - Bigadiç Muzaffer Emiroğlu Halk Eğitimi Merkezi',
  'BALIKESİR - BİGADİÇ - Hamidiye İlkokulu',
  'BALIKESİR - BİGADİÇ - İlyaslar Şehit Niyazi Elçin İlkokulu',
  'BALIKESİR - BİGADİÇ - İskele İlkokulu',
  'BALIKESİR - BİGADİÇ - Işıklar İlkokulu',
  'BALIKESİR - BİGADİÇ - Kargın İlkokulu',
  'BALIKESİR - BİGADİÇ - Kayırlar Şehit Mustafa Ergin İlkokulu',
  'BALIKESİR - BİGADİÇ - Mecidiye Şehitler İlkokulu',
  'BALIKESİR - BİGADİÇ - Turfullar Şehit Ahmet Kurt İlkokulu',
  'BALIKESİR - BİGADİÇ - Yagcilar Yatılı Bölge Ortaokulu',
  'BALIKESİR - BİGADİÇ - Yeşildere İlkokulu',
  'BALIKESİR - BİGADİÇ - Çağış Ortaokulu',
  'BALIKESİR - BİGADİÇ - Çağış İlkokulu',
  'BALIKESİR - BİGADİÇ - Güvemçetmi Ortaokulu',
  'BALIKESİR - BİGADİÇ - Akyar Ortaokulu',
  'BALIKESİR - BİGADİÇ - Akyar İlkokulu',
  'BALIKESİR - BİGADİÇ - Mecidiye Şehitler Ortaokulu',
  'BALIKESİR - BİGADİÇ - Atatürk Ortaokulu',
  'BALIKESİR - BİGADİÇ - Kozpınar Ortaokulu',
  'BALIKESİR - BİGADİÇ - Kozpınar İlkokulu',
  'BALIKESİR - BİGADİÇ - İlyaslar Şehit Niyazi Elçin Ortaokulu',
  'BALIKESİR - BİGADİÇ - Cumhuriyet Ortaokulu',
  'BALIKESİR - BİGADİÇ - İskele Ortaokulu',
  'BALIKESİR - BİGADİÇ - Dörteylül Ortaokulu',
  'BALIKESİR - BİGADİÇ - Dörteylül Sıtkı Sinan İlkokulu',
  'BALIKESİR - BİGADİÇ - Güvemçetmi İlkokulu',
  'BALIKESİR - BİGADİÇ - Yağcılar Köyü İlkokulu',
  'BALIKESİR - BİGADİÇ - Eti Maden İmam Hatip Ortaokulu',
  'BALIKESİR - BİGADİÇ - Bigadiç Eti Maden Özel Eğitim Uygulama Okulu II. Kademe',
  'BALIKESİR - BİGADİÇ - Bigadiç Eti Maden Özel Eğitim Uygulama Okulu I. Kademe',
  'BALIKESİR - BİGADİÇ - HATİCE KOÇ KIZILAY ANAOKULU',
  'BALIKESİR - BİGADİÇ - ATATÜRK ANAOKULU',
  'BALIKESİR - BİGADİÇ - 75. YIL ETİ HOLDİNG ANAOKULU',
  'BALIKESİR - BİGADİÇ - CUMHURİYET ANAOKULU',
  'BALIKESİR - BİGADİÇ - SITKI SİNAN ANAOKULU',
  'BALIKESİR - BURHANİYE - Emine Akel Anaokulu',
  'BALIKESİR - BURHANİYE - Ayşe Akpınar Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BURHANİYE - Bahçelievler İlkokulu',
  'BALIKESİR - BURHANİYE - ŞEHİT PİLOT ÜSTEĞMEN ERDEM MUT ORTAOKULU',
  'BALIKESİR - BURHANİYE - Burhaniye Atatürk Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BURHANİYE - Burhaniye Hacı Mehmet Fevzi Köylü Anadolu İmam Hatip Lisesi',
  'BALIKESİR - BURHANİYE - Hasan Akın Anadolu Lisesi',
  'BALIKESİR - BURHANİYE - Burhaniye Mesleki Eğitim Merkezi',
  'BALIKESİR - BURHANİYE - Burhaniye Şehit Hasan Çoban Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - BURHANİYE - Celal Toraman Anadolu Lisesi',
  'BALIKESİR - BURHANİYE - Cumhuriyet İlkokulu',
  'BALIKESİR - BURHANİYE - Faruk Kızıklı İlkokulu',
  'BALIKESİR - BURHANİYE - Hacı Mustafa Müdüroğlu Ortaokulu',
  'BALIKESİR - BURHANİYE - Burhaniye Şehit İlyas Arslan Halk Eğitimi Merkezi',
  'BALIKESİR - BURHANİYE - Müjde Babuşcuoğlu Anaokulu',
  'BALIKESİR - BURHANİYE - Öğretmen Evi ve Akşam Sanat Okulu',
  'BALIKESİR - BURHANİYE - Şehit Yılmaz Kobak İlkokulu',
  'BALIKESİR - BURHANİYE - Şarköy Ortaokulu',
  'BALIKESİR - BURHANİYE - Mustafa Keskin İlkokulu',
  'BALIKESİR - BURHANİYE - Kuyumcu İlkokulu',
  'BALIKESİR - BURHANİYE - Şehit Mustafa Serin Ortaokulu',
  'BALIKESİR - BURHANİYE - Dutluca İlkokulu',
  'BALIKESİR - BURHANİYE - Bahadınlı Ortaokulu',
  'BALIKESİR - BURHANİYE - Bahadınlı İlkokulu',
  'BALIKESİR - BURHANİYE - Börezli İlkokulu',
  'BALIKESİR - BURHANİYE - Nadir Tolun Ortaokulu',
  'BALIKESİR - BURHANİYE - Burhaniye Mehmet Akif Ersoy İlkokulu',
  'BALIKESİR - BURHANİYE - Gazi İlkokulu',
  'BALIKESİR - BURHANİYE - Şarköy İlkokulu',
  'BALIKESİR - BURHANİYE - Şehit Ahmet Çelik Ortaokulu',
  'BALIKESİR - BURHANİYE - Pelitköy Halit Selçuk Ortaokulu',
  'BALIKESİR - BURHANİYE - Pelitköy Halit Selçuk İlkokulu',
  'BALIKESİR - BURHANİYE - Sekizeylül İlkokulu',
  'BALIKESİR - BURHANİYE - Karadere İlkokulu',
  'BALIKESİR - BURHANİYE - Kızıklı İlkokulu',
  'BALIKESİR - BURHANİYE - Kızıklı Ortaokulu',
  'BALIKESİR - BURHANİYE - Burhaniye İmam Hatip Ortaokulu',
  'BALIKESİR - BURHANİYE - BURHANİYE TİCARET ODASI ÖZEL EĞİTİM UYGULAMA MERKEZİ I. KADEME',
  'BALIKESİR - BURHANİYE - Burhaniye Bilim ve Sanat Merkezi',
  'BALIKESİR - BURHANİYE - Yıldız Özsaraç Anaokulu',
  'BALIKESİR - BURHANİYE - Burhaniye Kuvâ-yı Milliye Fen Lisesi',
  'BALIKESİR - BURHANİYE - Burhaniye Ticaret Odası Özel Eğitim Uygulama Okulu II. Kademe',
  'BALIKESİR - BURHANİYE - Burhaniye Ticaret Odası Özel Eğitim Uygulama Okulu III. Kademe',
  'BALIKESİR - BURHANİYE - Berna Kundakçı Anaokulu',
  'BALIKESİR - BÜYÜKŞEHİR - Öğretmenevi ve Akşam Sanat Okulu',
  'BALIKESİR - BÜYÜKŞEHİR - Karesibey Öğretmenevi ve Akşam Sanat Okulu Müdürlüğü',
  'BALIKESİR - DURSUNBEY - Durabeyler Şehit Faruk Gezen İlkokulu',
  'BALIKESİR - DURSUNBEY - Farabi Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - DURSUNBEY - Dursunbey Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - DURSUNBEY - Dursunbey Çok Programlı Anadolu Lisesi',
  'BALIKESİR - DURSUNBEY - Dursunbey Mustafa Korkmaz Anadolu Lisesi',
  'BALIKESİR - DURSUNBEY - Dursunbey Halk Eğitimi Merkezi',
  'BALIKESİR - DURSUNBEY - Dursunbey Sarı Hoca Anadolu İmam Hatip Lisesi',
  'BALIKESİR - DURSUNBEY - Nene Hatun Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - DURSUNBEY - Dursunbey Mesleki Eğitim Merkezi',
  'BALIKESİR - DURSUNBEY - Neziha Bal İlkokulu',
  'BALIKESİR - DURSUNBEY - Gökçedağ İlkokulu',
  'BALIKESİR - DURSUNBEY - Dursunbey Borsa İstanbul Yatılı Bölge Ortaokulu',
  'BALIKESİR - DURSUNBEY - Sadullah Özer İlkokulu',
  'BALIKESİR - DURSUNBEY - Sabahattin Göndür İlkokulu',
  'BALIKESİR - DURSUNBEY - Durabeyler Şehit Faruk Gezen Ortaokulu',
  'BALIKESİR - DURSUNBEY - Atatürk Ortaokulu',
  'BALIKESİR - DURSUNBEY - Akbaşlar İlkokulu',
  'BALIKESİR - DURSUNBEY - Selimağa Kayaoğlu İlkokulu',
  'BALIKESİR - DURSUNBEY - Akbaşlar Ortaokulu',
  'BALIKESİR - DURSUNBEY - Selimağa Kayaoğlu Ortaokulu',
  'BALIKESİR - DURSUNBEY - Göbül İlkokulu',
  'BALIKESİR - DURSUNBEY - Göbül Ortaokulu',
  'BALIKESİR - DURSUNBEY - Öğretmenevi ve Akşam Sanat Okulu',
  'BALIKESİR - DURSUNBEY - Kavacık İlkokulu',
  'BALIKESİR - DURSUNBEY - Kavacık Ortaokulu',
  'BALIKESİR - DURSUNBEY - Dursunbey Raif Eriş Anaokulu',
  'BALIKESİR - DURSUNBEY - Hacıömerler İlkokulu',
  'BALIKESİR - DURSUNBEY - Delice İlkokulu',
  'BALIKESİR - DURSUNBEY - Üçeylül İlkokulu',
  'BALIKESİR - DURSUNBEY - Sağırlar İlkokulu',
  'BALIKESİR - DURSUNBEY - Şabanlar Şehit Aydın Eryılmaz İlkokulu',
  'BALIKESİR - DURSUNBEY - Çanakçı İlkokulu',
  'BALIKESİR - DURSUNBEY - Mıcırlar İlkokulu',
  'BALIKESİR - DURSUNBEY - Dursunbey Şehit Ömer Halisdemir İmam Hatip Ortaokulu',
  'BALIKESİR - DURSUNBEY - Süleler İlkokulu',
  'BALIKESİR - DURSUNBEY - Hamzacık Hatun Yılmaz İlkokulu',
  'BALIKESİR - DURSUNBEY - SADULLAH ÖZER ANAOKULU',
  'BALIKESİR - EDREMİT - Abidin Pak-Pakmaya Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Altınoluk Öğretmenevi ve Akşam Sanat Okulu',
  'BALIKESİR - EDREMİT - Edremit Anadolu İmam Hatip Lisesi',
  'BALIKESİR - EDREMİT - Edremit Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Edremit Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Edremit Rehberlik ve Araştırma Merkezi',
  'BALIKESİR - EDREMİT - Balıkesir Edremit Halk Eğitimi Merkezi',
  'BALIKESİR - EDREMİT - Kızılkeçili İlkokulu',
  'BALIKESİR - EDREMİT - Kızılkeçili Ortaokulu',
  'BALIKESİR - EDREMİT - Edremit Mesleki Eğitim Merkezi',
  'BALIKESİR - EDREMİT - Mimar Sinan İlkokulu',
  'BALIKESİR - EDREMİT - Yılmaz Akpınar Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Sarıkız Anaokulu',
  'BALIKESİR - EDREMİT - Akçay Yunus Emre İlkokulu',
  'BALIKESİR - EDREMİT - Şehit Öğretmenler İlkokulu',
  'BALIKESİR - EDREMİT - Akçay Zehra Baysal Anaokulu',
  'BALIKESİR - EDREMİT - Altınoluk Zahit Eroğlu İlkokulu',
  'BALIKESİR - EDREMİT - Mevlana Ortaokulu',
  'BALIKESİR - EDREMİT - Turhan Dökmecioğlu İmam Hatip Ortaokulu',
  'BALIKESİR - EDREMİT - Saniye-Hüseyin Balya Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Karagözoğlu İlkokulu',
  'BALIKESİR - EDREMİT - Kadıköy Mehmet Refii Terzioğlu İlkokulu',
  'BALIKESİR - EDREMİT - Remzi Molvalıoğlu Ortaokulu',
  'BALIKESİR - EDREMİT - İstiklal İlkokulu',
  'BALIKESİR - EDREMİT - Hacıaslanlar İlkokulu',
  'BALIKESİR - EDREMİT - Şehit Öğretmen Şenay Aybüke Yalçın Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Zeytinli Naim Süleymanoğlu İlkokulu',
  'BALIKESİR - EDREMİT - Güre Atatürk Ortaokulu',
  'BALIKESİR - EDREMİT - Altınoluk Mustafa Erçetin Ortaokulu',
  'BALIKESİR - EDREMİT - HAMİYYET - FERUDUN SÖZEN İLKOKULU',
  'BALIKESİR - EDREMİT - Zeytinli İlkokulu',
  'BALIKESİR - EDREMİT - Zeytinli Ortaokulu',
  'BALIKESİR - EDREMİT - Avcılar İlkokulu',
  'BALIKESİR - EDREMİT - Avcılar Ortaokulu',
  'BALIKESİR - EDREMİT - Yaylaönü İlkokulu',
  'BALIKESİR - EDREMİT - Ali Çelik İlkokulu',
  'BALIKESİR - EDREMİT - Göbelezoğlu Ortaokulu',
  'BALIKESİR - EDREMİT - 75.Yıl Ortaokulu',
  'BALIKESİR - EDREMİT - Şehit Mustafa Serin Fen Lisesi',
  'BALIKESİR - EDREMİT - Cumhuriyet İlkokulu',
  'BALIKESİR - EDREMİT - Mehmet Akif Ersoy İlkokulu',
  'BALIKESİR - EDREMİT - Şehit Kadir Altınöz İlkokulu',
  'BALIKESİR - EDREMİT - Şehit Kadir Altınöz Ortaokulu',
  'BALIKESİR - EDREMİT - Güre Atatürk İlkokulu',
  'BALIKESİR - EDREMİT - Ülkü-Muharrem Ertaş Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Kadıköy Leman Akpınar Ortaokulu',
  'BALIKESİR - EDREMİT - Altınoluk Fernur Sözen Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Yılmaz Akpınar İlkokulu',
  'BALIKESİR - EDREMİT - Reşit Çifçi Dokuz Eylül Ortaokulu',
  'BALIKESİR - EDREMİT - Ortaoba Eşref Kaya İlkokulu',
  'BALIKESİR - EDREMİT - Ortaoba Eşref Kaya Ortaokulu',
  'BALIKESİR - EDREMİT - Yolören Esin Akpınar İlkokulu',
  'BALIKESİR - EDREMİT - Yolören Esin Akpınar Ortaokulu',
  'BALIKESİR - EDREMİT - Yaşyer İlkokulu',
  'BALIKESİR - EDREMİT - Bostancı İlkokulu',
  'BALIKESİR - EDREMİT - Narlı İlkokulu',
  'BALIKESİR - EDREMİT - Şehit Öğretmen Necmettin Yılmaz Anaokulu',
  'BALIKESİR - EDREMİT - FATMA-SEVİM KIYAKOĞLU ANAOKULU',
  'BALIKESİR - EDREMİT - Edremit Fernur Sözen Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Fikriye-Mehmet Elberk Anadolu Lisesi',
  'BALIKESİR - EDREMİT - Altınoluk Kardeş Çavuşoğlu Ortaokulu',
  'BALIKESİR - EDREMİT - Hamiyyet-Ferudun Sözen Özel Eğitim Uygulama Okulu I. Kademe',
  'BALIKESİR - EDREMİT - Hamiyyet-Ferudun Sözen Özel Eğitim Uygulama Okulu II. Kademe',
  'BALIKESİR - EDREMİT - ALTINOLUK NECMİ ŞAHİN İLKOKULU',
  'BALIKESİR - EDREMİT - Fatih İmam Hatip Ortaokulu',
  'BALIKESİR - EDREMİT - Salih Korkut Budaras İlkokulu',
  'BALIKESİR - EDREMİT - Edremit 15 Temmuz Şehitler İmam Hatip Ortaokulu',
  'BALIKESİR - EDREMİT - Mithat-Fethi Büyükdalgıç İlkokulu',
  'BALIKESİR - EDREMİT - Şehit Tümgeneral Aydoğan Aydın Ortaokulu',
  'BALIKESİR - EDREMİT - Nilüfer Hatun Anaokulu',
  'BALIKESİR - EDREMİT - Saniye Karagözoğlu Özel Eğitim Uygulama Okulu III. Kademe',
  'BALIKESİR - EDREMİT - Akçay Şehit Halil Kantarcı Ortaokulu',
  'BALIKESİR - EDREMİT - NİHAT TANSOY İLKOKULU',
  'BALIKESİR - EDREMİT - Altınoluk Zehra Baysal Anaokulu',
  'BALIKESİR - EDREMİT - Altınoluk Niyazi Erol İmam Hatip Ortaokulu',
  'BALIKESİR - EDREMİT - KADIKÖY ZEHRA BAYSAL ANAOKULU',
  'BALIKESİR - EDREMİT - Şehit Hamdibey Ortaokulu',
  'BALIKESİR - EDREMİT - Edremit Bilim ve Sanat Merkezi',
  'BALIKESİR - EDREMİT - Hasan Basri Çantay Hafız İmam Hatip Ortaokulu',
  'BALIKESİR - EDREMİT - ALTINOLUK ZAHİT EROĞLU ANAOKULU',
  'BALIKESİR - EDREMİT - Edremit Anaokulu',
  'BALIKESİR - ERDEK - Atatürk İlkokulu',
  'BALIKESİR - ERDEK - HALİTPAŞA İLKOKULU',
  'BALIKESİR - ERDEK - Erdek Halk Eğitimi Merkezi',
  'BALIKESİR - ERDEK - Karşıyaka Çok Programlı Anadolu Lisesi',
  'BALIKESİR - ERDEK - Reşit Mazhar Ertüzün Anaokulu',
  'BALIKESİR - ERDEK - Muzaffer Gürer Ortaokulu',
  'BALIKESİR - ERDEK - İstiklal İlkokulu',
  'BALIKESİR - ERDEK - Erdek Anadolu Lisesi',
  'BALIKESİR - ERDEK - OCAKLAR ORTAOKULU',
  'BALIKESİR - ERDEK - Ocaklar İlkokulu',
  'BALIKESİR - ERDEK - Nerime Yüksel Ortaokulu',
  'BALIKESİR - ERDEK - Ahmet Vehbi ÇIKRIKÇIOĞLU Anadolu İmam Hatip Lisesi',
  'BALIKESİR - ERDEK - 18 EYLÜL ORTAOKULU',
  'BALIKESİR - ERDEK - Kapıdağ Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - ERDEK - KARŞIYAKA ORTAOKULU',
  'BALIKESİR - ERDEK - Karşıyaka İlkokulu',
  'BALIKESİR - ERDEK - RECEP AHMET MERCAN ORTAOKULU',
  'BALIKESİR - ERDEK - Çakıl İlkokulu',
  'BALIKESİR - ERDEK - Çayağzı İlkokulu',
  'BALIKESİR - ERDEK - Öğretmenevi ve Akşam Sanat Okulu',
  'BALIKESİR - ERDEK - Kestanelik İlkokulu',
  'BALIKESİR - GÖMEÇ - İlkkurşun Anaokulu',
  'BALIKESİR - GÖMEÇ - Karaağaç Ahmet Karakaş Ortaokulu',
  'BALIKESİR - GÖMEÇ - AHMET TULUN HİMAM İLKOKULU',
  'BALIKESİR - GÖMEÇ - Karaağaç Ahmet Karakaş İlkokulu',
  'BALIKESİR - GÖMEÇ - ŞEHİT MUSTAFA GÜVENÇ ALDEMİR ORTAOKULU',
  'BALIKESİR - GÖMEÇ - HACIHÜSEYİNLER İLKOKULU',
  'BALIKESİR - GÖMEÇ - Gömeç İmam Hatip Ortaokulu',
  'BALIKESİR - GÖMEÇ - ULUBEYLER İLKOKULU',
  'BALIKESİR - GÖMEÇ - ULUBEYLER ORTAOKULU',
  'BALIKESİR - GÖMEÇ - HACIHÜSEYİNLER ORTAOKULU',
  'BALIKESİR - GÖMEÇ - Hacıoğlu İlkokulu',
  'BALIKESİR - GÖMEÇ - 6 Eylül Mesleki Eğitim Merkezi',
  'BALIKESİR - GÖMEÇ - Gömeç Halk Eğitimi Merkezi',
  'BALIKESİR - GÖMEÇ - ŞEHİT MUSTAFA GÜVENÇ ALDEMİR İLKOKULU',
  'BALIKESİR - GÖMEÇ - Gömeç Anadolu Lisesi',
  'BALIKESİR - GÖNEN - Gönen Anadolu Lisesi',
  'BALIKESİR - GÖNEN - Gönen Ticaret Odası Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - GÖNEN - Gönen H. Sükriye İpek Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - GÖNEN - Gönen Mustafa Uşdu Anadolu Lisesi',
  'BALIKESİR - GÖNEN - Gönen Ömer Seyfettin Fen Lisesi',
  'BALIKESİR - GÖNEN - Balıkesir Gönen Halk Eğitimi Merkezi',
  'BALIKESİR - GÖNEN - Gönen Anadolu İmam Hatip Lisesi',
  'BALIKESİR - GÖNEN - Gönen Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - GÖNEN - Gönen Mesleki Eğitim Merkezi',
  'BALIKESİR - GÖNEN - Öğretmenevi ve Akşam Sanat Okulu',
  'BALIKESİR - GÖNEN - Öğretmen Işıl İpek Ortaokulu',
  'BALIKESİR - GÖNEN - Sarıköy Atatürk İlkokulu',
  'BALIKESİR - GÖNEN - Sarıköy Çok Programlı Anadolu Lisesi',
  'BALIKESİR - GÖNEN - Sarıköy Ortaokulu',
  'BALIKESİR - GÖNEN - Şehit Cengiz Topel Anaokulu',
  'BALIKESİR - GÖNEN - Ulukır İlkokulu',
  'BALIKESİR - GÖNEN - Eczacı İzzet Akçiçek İlkokulu',
  'BALIKESİR - GÖNEN - Özcan Kılınçay İlkokulu',
  'BALIKESİR - GÖNEN - Altıeylül Ortaokulu',
  'BALIKESİR - GÖNEN - Karşıyaka 100. Yıl İlkokulu',
  'BALIKESİR - GÖNEN - Kadir Köker Ortaokulu',
  'BALIKESİR - GÖNEN - Mehmet Akif Ersoy İlkokulu',
  'BALIKESİR - GÖNEN - Mehmet Ahmet Genç Ortaokulu',
  'BALIKESİR - GÖNEN - Öğretmenim Ortaokulu',
  'BALIKESİR - GÖNEN - Mehmet Ahmet Genç İlkokulu',
  'BALIKESİR - GÖNEN - Hasanbey Ortaokulu',
  'BALIKESİR - GÖNEN - Hasanbey İlkokulu',
  'BALIKESİR - GÖNEN - Gündoğan İlkokulu',
  'BALIKESİR - GÖNEN - Gündoğan Ortaokulu',
  'BALIKESİR - GÖNEN - Mehmet Çanakçı İlkokulu',
  'BALIKESİR - GÖNEN - Atatürk Ortaokulu',
  'BALIKESİR - GÖNEN - Erdal Tanrıöver Anaokulu',
  'BALIKESİR - GÖNEN - Şehit Kaymakam Rahmi Bey İlkokulu',
  'BALIKESİR - GÖNEN - Atatürk İlkokulu',
  'BALIKESİR - GÖNEN - Gönenli Mehmet Efendi İmam Hatip Ortaokulu',
  'BALIKESİR - GÖNEN - Buğdaylı İlkokulu',
  'BALIKESİR - GÖNEN - Mirciler Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - GÖNEN - Gönen Özel Eğitim Uygulama Okulu I. Kademe',
  'BALIKESİR - GÖNEN - Şehit Abdullah Tayyip Olçok İmam Hatip Ortaokulu',
  'BALIKESİR - GÖNEN - Gönen Özel Eğitim Uygulama Okulu II. Kademe',
  'BALIKESİR - HAVRAN - Eseler İlkokulu',
  'BALIKESİR - HAVRAN - Havran Halk Eğitimi Merkezi',
  'BALIKESİR - HAVRAN - KOBAKLAR ORTAOKULU',
  'BALIKESİR - HAVRAN - Hak-İş Hizmet-İş Sendikası Kocaseyit İlkokulu',
  'BALIKESİR - HAVRAN - Muzaffer Leman Akpınar Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - HAVRAN - KALABAK İLKOKULU',
  'BALIKESİR - HAVRAN - KALABAK ORTAOKULU',
  'BALIKESİR - HAVRAN - HALİL İBRAHİM YILDIRIM FAZLICA İLKOKULU',
  'BALIKESİR - HAVRAN - Tepeoba İlkokulu',
  'BALIKESİR - HAVRAN - Kocadağ Damlar İlkokulu',
  'BALIKESİR - HAVRAN - KOCASEYİT ORTAOKULU',
  'BALIKESİR - HAVRAN - Şehit Eyüp Karataş Ortaokulu',
  'BALIKESİR - HAVRAN - Havran Anadolu Lisesi',
  'BALIKESİR - HAVRAN - Sekizeylül Ortaokulu',
  'BALIKESİR - HAVRAN - ALİÇETİNKAYA İLKOKULU',
  'BALIKESİR - HAVRAN - GÜLSÜM MEHMET UYSAL BÜYÜKDERE İLKOKULU',
  'BALIKESİR - HAVRAN - GÜLSÜM MEHMET UYSAL BÜYÜKDERE ORTAOKULU',
  'BALIKESİR - HAVRAN - Havran İmam Hatip Ortaokulu',
  'BALIKESİR - HAVRAN - Küçükdere İlkokulu',
  'BALIKESİR - HAVRAN - ÇAMDİBİ İLKOKULU',
  'BALIKESİR - HAVRAN - ÇAMDİBİ ORTAOKULU',
  'BALIKESİR - HAVRAN - Seyitonbaşı İlkokulu',
  'BALIKESİR - HAVRAN - ERMİŞ SOYLU İLKOKULU',
  'BALIKESİR - HAVRAN - Mehmet Sever Dereören İlkokulu',
  'BALIKESİR - HAVRAN - KÜÇÜKŞAPÇI ORTAOKULU',
  'BALIKESİR - HAVRAN - ÖMER ÇAVUŞ ANAOKULU',
  'BALIKESİR - HAVRAN - Temaşalık İlkokulu',
  'BALIKESİR - HAVRAN - Sıdıka Ürütürk Eğmir İlkokulu',
  'BALIKESİR - HAVRAN - KOBAKLAR İLKOKULU',
  'BALIKESİR - HAVRAN - Havran Mesleki Eğitim Merkezi',
  'BALIKESİR - HAVRAN - HALLAÇLAR İLKOKULU',
  'BALIKESİR - HAVRAN - Mehmet Çalışır Anadolu İmam Hatip Lisesi',
  'BALIKESİR - HAVRAN - KÜÇÜKŞAPÇI İLKOKULU',
  'BALIKESİR - HAVRAN - Zeynep Banu Çakırdere İlkokulu',
  'BALIKESİR - İVRİNDİ - 7 EYLÜL İLKOKULU',
  'BALIKESİR - İVRİNDİ - Evciler İlkokulu',
  'BALIKESİR - İVRİNDİ - İvrindi Anadolu İmam Hatip Lisesi',
  'BALIKESİR - İVRİNDİ - Gökçeyazı Çok Programlı Anadolu Lisesi',
  'BALIKESİR - İVRİNDİ - İ.Sefa Giray Bozören İlkokulu',
  'BALIKESİR - İVRİNDİ - Soğanbükü Müdafa-i Hukuk Ortaokulu',
  'BALIKESİR - İVRİNDİ - İvrindi Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - İVRİNDİ - Şehit Kenan Dalkılıç İlkokulu',
  'BALIKESİR - İVRİNDİ - Gümeli İlkokulu',
  'BALIKESİR - İVRİNDİ - İ.Sefa Giray Bozören Ortaokulu',
  'BALIKESİR - İVRİNDİ - Yağlılar İlkokulu',
  'BALIKESİR - İVRİNDİ - Büyükyenice İlkokulu',
  'BALIKESİR - İVRİNDİ - Büyükyenice Ortaokulu',
  'BALIKESİR - İVRİNDİ - Küçükyenice Ortaokulu',
  'BALIKESİR - İVRİNDİ - Küçükyenice İlkokulu',
  'BALIKESİR - İVRİNDİ - Yürekli İlkokulu',
  'BALIKESİR - İVRİNDİ - Şehit Fatih Tomuşoğlu Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - İVRİNDİ - İvrindi Halk Eğitimi Merkezi',
  'BALIKESİR - İVRİNDİ - Korucu Yatılı Bölge Ortaokulu',
  'BALIKESİR - İVRİNDİ - KAYAPA ORTAOKULU',
  'BALIKESİR - İVRİNDİ - Kayapa İlkokulu',
  'BALIKESİR - İVRİNDİ - Gazievrenos İlkokulu',
  'BALIKESİR - İVRİNDİ - Değirmenbaşı İlkokulu',
  'BALIKESİR - İVRİNDİ - Demirciler İlkokulu',
  'BALIKESİR - İVRİNDİ - Gökçeyazı Şehit Rıdvan Çetinkaya Ortaokulu',
  'BALIKESİR - İVRİNDİ - Gökçeyazı Şehit Rıdvan Çetinkaya İlkokulu',
  'BALIKESİR - İVRİNDİ - Okçular Şehit Hasan Kuzu İlkokulu',
  'BALIKESİR - İVRİNDİ - Büyükfındık Ortaokulu',
  'BALIKESİR - İVRİNDİ - Büyükfındık İlkokulu',
  'BALIKESİR - İVRİNDİ - VİLAYETLER BİRLİĞİ ŞEHİT GEDİZ ÇİVİ ANAOKULU',
  'BALIKESİR - İVRİNDİ - Susuzyayla İlkokulu',
  'BALIKESİR - İVRİNDİ - Şehit Turan Kurt Ortaokulu',
  'BALIKESİR - İVRİNDİ - Korucu Şehit Bülent Emen Çok Programlı Anadolu Lisesi',
  'BALIKESİR - İVRİNDİ - Korucu Mehmet Kulak İlkokulu',
  'BALIKESİR - İVRİNDİ - İvrindi Anadolu Lisesi',
  'BALIKESİR - İVRİNDİ - Şehit Tuncay Özdemir İmam Hatip Ortaokulu',
  'BALIKESİR - İVRİNDİ - Gazi Mehmet Azman Çavuş Özel Eğitim Meslek Okulu',
  'BALIKESİR - İVRİNDİ - Nurettin Çarmıklı Madencilik Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - İVRİNDİ - İvrindi Gazi Mehmet Azman Çavuş Özel Eğitim Uygulama Okulu I. Kademe',
  'BALIKESİR - İVRİNDİ - İvrindi Gazi Mehmet Azman Çavuş Özel Eğitim Uygulama Okulu II. Kademe',
  'BALIKESİR - KARESİ - Merkez Ece Amca İlkokulu',
  'BALIKESİR - KARESİ - Albay C. Tayyar-Nuran Oğuz Anadolu Lisesi',
  'BALIKESİR - KARESİ - Ali Rıza Güçkan Anaokulu',
  'BALIKESİR - KARESİ - Balıkesir Lisesi',
  'BALIKESİR - KARESİ - Şehit Prof. Dr. İlhan Varank Bilim ve Sanat Merkezi',
  'BALIKESİR - KARESİ - Balıkesir Karesi Ortaokulu',
  'BALIKESİR - KARESİ - Balıkesir Muharrem Hasbi Anadolu Lisesi',
  'BALIKESİR - KARESİ - Balıkesir Rehberlik ve Araştırma Merkezi',
  'BALIKESİR - KARESİ - Çiğdem Batubey Ortaokulu',
  'BALIKESİR - KARESİ - Deliktaş İlkokulu',
  'BALIKESİR - KARESİ - Fatma-Emin Kutvar Anadolu Lisesi',
  'BALIKESİR - KARESİ - Karesi Halk Eğitimi Merkezi',
  'BALIKESİR - KARESİ - İbrahim Bodur Mesleki Eğitim Merkezi',
  'BALIKESİR - KARESİ - İl Özel İdare Özel Eğitim Uygulama Okulu III. Kademe',
  'BALIKESİR - KARESİ - Balıkesir Anadolu İmam Hatip Lisesi',
  'BALIKESİR - KARESİ - İnebey Anadolu Lisesi',
  'BALIKESİR - KARESİ - İstanbulluoğlu Sosyal Bilimler Lisesi',
  'BALIKESİR - KARESİ - Kabakdere Ortaokulu',
  'BALIKESİR - KARESİ - T.C. Ziraat Bankası Güzel Sanatlar Lisesi',
  'BALIKESİR - KARESİ - Karahallılar Ortaokulu',
  'BALIKESİR - KARESİ - Beyköy İlkokulu',
  'BALIKESİR - KARESİ - Naciye Kabakçı Anaokulu',
  'BALIKESİR - KARESİ - Nazende Kurşun Anaokulu',
  'BALIKESİR - KARESİ - Nuran Oğuz Anaokulu',
  'BALIKESİR - KARESİ - Rahmi Kula Anadolu Lisesi',
  'BALIKESİR - KARESİ - Sevinç Kurşun İlkokulu',
  'BALIKESİR - KARESİ - Sıdıka Sami Kula Anaokulu',
  'BALIKESİR - KARESİ - Sırrı Yırcalı Anadolu Lisesi',
  'BALIKESİR - KARESİ - Şamlı Şehit Mustafa Adışen İlkokulu',
  'BALIKESİR - KARESİ - Şamlı Şehit Mustafa Adışen Ortaokulu',
  'BALIKESİR - KARESİ - Şehit Turgut Solak Fen Lisesi',
  'BALIKESİR - KARESİ - Tatlıpınar İlkokulu',
  'BALIKESİR - KARESİ - Yeniköy İlkokulu',
  'BALIKESİR - KARESİ - Zübeyde Hanım Anaokulu',
  'BALIKESİR - KARESİ - Zühtü Özkardaşlar Anadolu Lisesi',
  'BALIKESİR - KARESİ - Kabakdere İlkokulu',
  'BALIKESİR - KARESİ - Albay Tayyar-Nuran Oğuz İlkokulu',
  'BALIKESİR - KARESİ - Balıkesir Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - KARESİ - Sakarya İlkokulu',
  'BALIKESİR - KARESİ - Alişuuri İlkokulu',
  'BALIKESİR - KARESİ - Hacıilbey Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - KARESİ - Şehit Yüzbaşı İlker Acar Ortaokulu',
  'BALIKESİR - KARESİ - Ali Hikmet Paşa İlkokulu',
  'BALIKESİR - KARESİ - Ali Hikmet Paşa Ortaokulu',
  'BALIKESİR - KARESİ - Adnan Menderes Anadolu Lisesi',
  'BALIKESİR - KARESİ - Merkez Zafer İlkokulu',
  'BALIKESİR - KARESİ - Fatih Ortaokulu',
  'BALIKESİR - KARESİ - Ovacık İlkokulu',
  'BALIKESİR - KARESİ - Ovacık Ortaokulu',
  'BALIKESİR - KARESİ - Kocaavşar İlkokulu',
  'BALIKESİR - KARESİ - Kocaavşar Ortaokulu',
  'BALIKESİR - KARESİ - Kalaycılar İlkokulu',
  'BALIKESİR - KARESİ - ÜÇPINARLI ŞEHİT ALİ İLKOKULU',
  'BALIKESİR - KARESİ - 23 Nisan Şehit Deniz Göçkün İlkokulu',
  'BALIKESİR - KARESİ - Mehmet Şeref Eğinlioğlu Ortaokulu',
  'BALIKESİR - KARESİ - Kayabey Şehit Ferruh Kulaoğlu Ortaokulu',
  'BALIKESİR - KARESİ - Fatih İlkokulu',
  'BALIKESİR - KARESİ - Kamçıllı İlkokulu',
  'BALIKESİR - KARESİ - Firdevs Hattatoğlu Özel Eğitim Meslek Okulu',
  'BALIKESİR - KARESİ - Şehit Jandarma Teğmen Cengiz Evranos İlkokulu',
  'BALIKESİR - KARESİ - Şehit Jandarma Teğmen Cengiz Evranos Ortaokulu',
  'BALIKESİR - KARESİ - Ercan Kıvrak İlkokulu',
  'BALIKESİR - KARESİ - Yağcılar İlkokulu',
  'BALIKESİR - KARESİ - Bakacak Şehit Yüksel Bayhan Ortaokulu',
  'BALIKESİR - KARESİ - Tatlıpınar Ortaokulu',
  'BALIKESİR - KARESİ - Merkez Turplu ilkokulu',
  'BALIKESİR - KARESİ - Yeniköy Ortaokulu',
  'BALIKESİR - KARESİ - Aktarma Naile Erol Gülcan İlkokulu',
  'BALIKESİR - KARESİ - Atatürk İlkokulu',
  'BALIKESİR - KARESİ - Atatürk Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - KARESİ - Gazi İmam Hatip Ortaokulu',
  'BALIKESİR - KARESİ - Gazi Mustafa Kemal Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - KARESİ - Bakacak Şehit Yüksel Bayhan İlkokulu',
  'BALIKESİR - KARESİ - Yaylabayır İlkokulu',
  'BALIKESİR - KARESİ - Umut Özel Eğitim Ortaokulu',
  'BALIKESİR - KARESİ - ŞULE YÜKSEL ŞENLER KIZ ANADOLU İMAM HATİP LİSESİ',
  'BALIKESİR - KARESİ - Balıkesir İmam Hatip Ortaokulu',
  'BALIKESİR - KARESİ - Şamlı İmam Hatip Ortaokulu',
  'BALIKESİR - KARESİ - Mehmet Azman Çavuş Ortaokulu',
  'BALIKESİR - KARESİ - Süeybe Karakuş Anaokulu',
  'BALIKESİR - KARESİ - Albay Cafer Tayyar-Nuran Oğuz Ortaokulu',
  'BALIKESİR - KARESİ - Şehit Mesut Yağan Anaokulu',
  'BALIKESİR - KARESİ - Deliktaş Ortaokulu',
  'BALIKESİR - KARESİ - Necip Fazıl Kısakürek Ortaokulu',
  'BALIKESİR - KARESİ - ŞEHİT ASTSUBAY CEMİL ERKEK ORTAOKULU',
  'BALIKESİR - KARESİ - Umut Özel Eğitim İlkokulu',
  'BALIKESİR - KARESİ - Ömer Kurşun Anaokulu',
  'BALIKESİR - KARESİ - Kurtdereli Mehmet Pehlivan Spor Lisesi',
  'BALIKESİR - KARESİ - Dr. Ayşe Hümeyra Ökten Kız Anadolu İmam Hatip Lisesi',
  'BALIKESİR - KARESİ - Balıkesir Olgunlaşma Enstitüsü',
  'BALIKESİR - KARESİ - ALİ HİKMET PAŞA ANAOKULU',
  'BALIKESİR - KARESİ - SEVİNÇ KURŞUN ANAOKULU',
  'BALIKESİR - KARESİ - 23 NİSAN ŞEHİT DENİZ GÖÇKÜN ANAOKULU',
  'BALIKESİR - KEPSUT - Cumhuriyet İlkokulu',
  'BALIKESİR - KEPSUT - Hacer Özer İlkokulu',
  'BALIKESİR - KEPSUT - Oktay Koçman Ortaokulu',
  'BALIKESİR - KEPSUT - Mahmudiye İlkokulu',
  'BALIKESİR - KEPSUT - Mahmudiye Ortaokulu',
  'BALIKESİR - KEPSUT - Keçidere Ortaokulu',
  'BALIKESİR - KEPSUT - Sarac İlkokulu',
  'BALIKESİR - KEPSUT - Keçidere İlkokulu',
  'BALIKESİR - KEPSUT - Eşeler İlkokulu',
  'BALIKESİR - KEPSUT - 125.Yıl Yatılı Bölge Ortaokulu',
  'BALIKESİR - KEPSUT - Kepsut Çok Programlı Anadolu Lisesi',
  'BALIKESİR - KEPSUT - Kepsut Halk Eğitimi Merkezi',
  'BALIKESİR - KEPSUT - Hotaşlar İlkokulu',
  'BALIKESİR - KEPSUT - Hotaşlar Ortaokulu',
  'BALIKESİR - KEPSUT - İsaalan İlkokulu',
  'BALIKESİR - KEPSUT - Kepsut Hasan Basri Çantay İmam Hatip Ortaokulu',
  'BALIKESİR - KEPSUT - Kepsut Anaokulu',
  'BALIKESİR - KEPSUT - Yaylabaşı İlkokulu',
  'BALIKESİR - KEPSUT - Kepsut Anadolu Lisesi',
  'BALIKESİR - MANYAS - Manyas Anadolu İmam Hatip Lisesi',
  'BALIKESİR - MANYAS - İstiklal İlkokulu',
  'BALIKESİR - MANYAS - Salur Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - MANYAS - Şevketiye İlkokulu',
  'BALIKESİR - MANYAS - Kızıksa Ortaokulu',
  'BALIKESİR - MANYAS - Atatürk Ortaokulu',
  'BALIKESİR - MANYAS - Manyas Anadolu Lisesi',
  'BALIKESİR - MANYAS - Nene Hatun Anaokulu',
  'BALIKESİR - MANYAS - Akçaova Ortaokulu',
  'BALIKESİR - MANYAS - Kızıksa İlkokulu',
  'BALIKESİR - MANYAS - Manyas Öğretmenevi ve Akşam Sanat Okulu',
  'BALIKESİR - MANYAS - Manyas Halk Eğitimi Merkezi',
  'BALIKESİR - MANYAS - İmam Hatip Ortaokulu',
  'BALIKESİR - MARMARA - Marmara Halk Eğitimi Merkezi',
  'BALIKESİR - MARMARA - Marmara Çok Programlı Anadolu Lisesi',
  'BALIKESİR - MARMARA - Topağaç İlkokulu',
  'BALIKESİR - MARMARA - Recep Ahmet Mercan Ortaokulu',
  'BALIKESİR - MARMARA - Recep Ahmet Mercan İlkokulu',
  'BALIKESİR - MARMARA - Saraylar İlkokulu',
  'BALIKESİR - MARMARA - Saraylar Ortaokulu',
  'BALIKESİR - MARMARA - Avşa İlkokulu',
  'BALIKESİR - MARMARA - Avşa Ortaokulu',
  'BALIKESİR - MARMARA - Güner Yavuz Anaokulu',
  'BALIKESİR - MARMARA - Saraylar Anadolu İmam Hatip Lisesi',
  'BALIKESİR - MARMARA - Marmara Anaokulu',
  'BALIKESİR - SAVAŞTEPE - Fatih Ortaokulu',
  'BALIKESİR - SAVAŞTEPE - Sarıbeyler Ortaokulu',
  'BALIKESİR - SAVAŞTEPE - Sarıbeyler İlkokulu',
  'BALIKESİR - SAVAŞTEPE - Savaştepe Anadolu İmam Hatip Lisesi',
  'BALIKESİR - SAVAŞTEPE - Karacalar Mustafa Kangal Ortaokulu',
  'BALIKESİR - SAVAŞTEPE - Şehit Onbaşı Bayram Kaya Ortaokulu',
  'BALIKESİR - SAVAŞTEPE - Tıbbiyeli Hikmet Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - SAVAŞTEPE - Mehmet Akif Ersoy İlkokulu',
  'BALIKESİR - SAVAŞTEPE - Karacalar Mustafa Kangal İlkokulu',
  'BALIKESİR - SAVAŞTEPE - Savaştepe Halk Eğitimi Merkezi',
  'BALIKESİR - SAVAŞTEPE - Alişuuri Ortaokulu',
  'BALIKESİR - SAVAŞTEPE - Savaştepe Meslekî ve Teknik Anadolu Lisesi',
  'BALIKESİR - SAVAŞTEPE - Necip Fazıl Kısakürek Anadolu Lisesi',
  'BALIKESİR - SAVAŞTEPE - Yeşilhisar İlkokulu',
  'BALIKESİR - SAVAŞTEPE - Zafer İlkokulu',
  'BALIKESİR - SAVAŞTEPE - Şehit Onbaşı Bayram Kaya İlkokulu',
  'BALIKESİR - SAVAŞTEPE - SOĞUCAK İLKOKULU',
  'BALIKESİR - SAVAŞTEPE - Savaştepe Anaokulu',
  'BALIKESİR - SAVAŞTEPE - Cumhuriyet İlkokulu',
  'BALIKESİR - SAVAŞTEPE - SÖĞÜTÇÜK İLKOKULU',
  'BALIKESİR - SINDIRGI - Sındırgı Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - SINDIRGI - Cumhuriyet Ortaokulu',
  'BALIKESİR - SINDIRGI - Gölcük Ortaokulu',
  'BALIKESİR - SINDIRGI - Gölcük İlkokulu',
  'BALIKESİR - SINDIRGI - Sındırgı Halk Eğitimi Merkezi',
  'BALIKESİR - SINDIRGI - Kurtuluş İlkokulu',
  'BALIKESİR - SINDIRGI - İbrahim Ethem Akıncı İlkokulu',
  'BALIKESİR - SINDIRGI - İbrahim Ethem Akıncı Ortaokulu',
  'BALIKESİR - SINDIRGI - Düvertepe Yatılı Bölge Ortaokulu',
  'BALIKESİR - SINDIRGI - Öğretmenevi ve Akşam Sanat Okulu',
  'BALIKESİR - SINDIRGI - Sındırgı Anadolu İmam Hatip Lisesi',
  'BALIKESİR - SINDIRGI - Kocakonak İlkokulu',
  'BALIKESİR - SINDIRGI - Atatürk İlkokulu',
  'BALIKESİR - SINDIRGI - 3 Eylül Anaokulu',
  'BALIKESİR - SINDIRGI - Yaylabayır Muazzez Keskin İlkokulu',
  'BALIKESİR - SINDIRGI - Sındırgı Makbule Efe Anadolu Lisesi',
  'BALIKESİR - SINDIRGI - Yağcıbedir Ortaokulu',
  'BALIKESİR - SINDIRGI - Yüreğil Ortaokulu',
  'BALIKESİR - SINDIRGI - Yüreğil İlkokulu',
  'BALIKESİR - SINDIRGI - Sındırgı İmam Hatip Ortaokulu',
  'BALIKESİR - SINDIRGI - Düvertepe İlkokulu',
  'BALIKESİR - SUSURLUK - ATATÜRK İLKOKULU',
  'BALIKESİR - SUSURLUK - Şehit Erbil Arslan Ortaokulu',
  'BALIKESİR - SUSURLUK - Susurluk Anadolu Lisesi',
  'BALIKESİR - SUSURLUK - FATİH İLKOKULU',
  'BALIKESİR - SUSURLUK - Susurluk Halk Eğitimi Merkezi',
  'BALIKESİR - SUSURLUK - Susurluk Anadolu İmam Hatip Lisesi',
  'BALIKESİR - SUSURLUK - Hayme Ana Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - SUSURLUK - 5 Eylül Anadolu Lisesi',
  'BALIKESİR - SUSURLUK - Susurluk Mesleki ve Teknik Anadolu Lisesi',
  'BALIKESİR - SUSURLUK - Zübeyde Hanım Anaokulu',
  'BALIKESİR - SUSURLUK - NİMET SADIK ÖZYİĞİT ORTAOKULU',
  'BALIKESİR - SUSURLUK - Dereköy İlkokulu',
  'BALIKESİR - SUSURLUK - KARAPÜRÇEK ŞEHİT MESUT NAYMAN ORTAOKULU',
  'BALIKESİR - SUSURLUK - ŞEKER İLKOKULU',
  'BALIKESİR - SUSURLUK - KARAPÜRÇEK ŞEHİT MESUT NAYMAN İLKOKULU',
  'BALIKESİR - SUSURLUK - Demirkapı Şeref Eğinlioğlu İlkokulu',
  'BALIKESİR - SUSURLUK - Beşeylül İlkokulu',
  'BALIKESİR - SUSURLUK - ÖMERKÖY ORTAOKULU',
  'BALIKESİR - SUSURLUK - ŞERAFETTİN TUNALI İLKOKULU',
  'BALIKESİR - SUSURLUK - ŞERAFETTİN TUNALI ORTAOKULU',
  'BALIKESİR - SUSURLUK - GÖBEL ŞEHİT NUSRET KULA İLKOKULU',
  'BALIKESİR - SUSURLUK - GÖBEL ŞEHİT NUSRET KULA ORTAOKULU',
  'BALIKESİR - SUSURLUK - Susurluk İmam Hatip Ortaokulu',
  'BALIKESİR - SUSURLUK - ŞEHİT ERBİL ARSLAN ANAOKULU',
  ];

  List<String> get list=>_list;
}