class BilecikSchools{
  final List<String> _list=[
  'BİLECİK - BOZÜYÜK - Albay İbrahim Çolak İlkokulu',
  'BİLECİK - BOZÜYÜK - Zehra Ulusay Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - BOZÜYÜK - Kumral Abdal Anadolu Lisesi',
  'BİLECİK - BOZÜYÜK - Bozüyük Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - BOZÜYÜK - Bozüyük Anaokulu',
  'BİLECİK - BOZÜYÜK - Bozüyük Fen Lisesi',
  'BİLECİK - BOZÜYÜK - Bozüyük Halk Eğitimi Merkezi',
  'BİLECİK - BOZÜYÜK - Cumhuriyet İlkokulu',
  'BİLECİK - BOZÜYÜK - Bozüyük Anadolu İmam Hatip Lisesi',
  'BİLECİK - BOZÜYÜK - Bozüyük Mimar Sinan Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - BOZÜYÜK - Bozüyük Mesleki Eğitim Merkezi',
  'BİLECİK - BOZÜYÜK - Mustafa Şeker Anadolu Lisesi',
  'BİLECİK - BOZÜYÜK - Bozüyük Borsa İstanbul Anadolu Lisesi',
  'BİLECİK - BOZÜYÜK - Bozüyük Rehberlik ve Araştırma Merkezi',
  'BİLECİK - BOZÜYÜK - Bozüyük Selahattin Şeker Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - BOZÜYÜK - Vilayetler Hizmet Birliği Anaokulu',
  'BİLECİK - BOZÜYÜK - Yavuz Sultan Selim Ortaokulu',
  'BİLECİK - BOZÜYÜK - Zafer İlkokulu',
  'BİLECİK - BOZÜYÜK - Necatibey Ortaokulu',
  'BİLECİK - BOZÜYÜK - Öğretmen Bekir Aral İlkokulu',
  'BİLECİK - BOZÜYÜK - 100.Yıl Ortaokulu',
  'BİLECİK - BOZÜYÜK - Atatürk İlkokulu',
  'BİLECİK - BOZÜYÜK - Saffet Şeker Ortaokulu',
  'BİLECİK - BOZÜYÜK - Hamza Bey İlkokulu',
  'BİLECİK - BOZÜYÜK - Şehit Zafer İpek Özel Eğitim İlkokulu',
  'BİLECİK - BOZÜYÜK - Hoca Ahmet Yesevi İlkokulu',
  'BİLECİK - BOZÜYÜK - Metristepe İlkokulu',
  'BİLECİK - BOZÜYÜK - Arif Nihat Asya Ortaokulu',
  'BİLECİK - BOZÜYÜK - Şehit Zafer İpek Özel Eğitim Ortaokulu',
  'BİLECİK - BOZÜYÜK - Şehit Zafer İpek Özel Eğitim Mesleki Eğitim Merkezi (Okulu)',
  'BİLECİK - BOZÜYÜK - Necip Fazıl Kısakürek İlkokulu',
  'BİLECİK - BOZÜYÜK - Mehmet Akif Ersoy Ortaokulu',
  'BİLECİK - BOZÜYÜK - Dodurga İlkokulu',
  'BİLECİK - BOZÜYÜK - İçköy İlkokulu',
  'BİLECİK - BOZÜYÜK - Ertuğrulgazi İlkokulu',
  'BİLECİK - BOZÜYÜK - Ertuğrulgazi Ortaokulu',
  'BİLECİK - BOZÜYÜK - Dodurga Ortaokulu',
  'BİLECİK - BOZÜYÜK - Saffet Şeker İlkokulu',
  'BİLECİK - BOZÜYÜK - İçköy Ortaokulu',
  'BİLECİK - BOZÜYÜK - Albay İbrahim Çolak Ortaokulu',
  'BİLECİK - BOZÜYÜK - Akpınar Şehit Vahit Elmas İlkokulu',
  'BİLECİK - BOZÜYÜK - FATİH SULTAN MEHMET İMAM HATİP ORTAOKULU',
  'BİLECİK - BOZÜYÜK - HALİME HATUN ANAOKULU',
  'BİLECİK - BOZÜYÜK - TOKİ İLKOKULU',
  'BİLECİK - BOZÜYÜK - Bozüyük Kız Anadolu İmam Hatip Lisesi',
  'BİLECİK - BOZÜYÜK - Öğretmen Evi ve Akşam Sanat Okulu',
  'BİLECİK - BOZÜYÜK - Bozüyük Özel Eğitim Uygulama Okulu II. Kademe',
  'BİLECİK - BOZÜYÜK - Bozüyük Özel Eğitim Uygulama Okulu I. Kademe',
  'BİLECİK - BOZÜYÜK - Bozüyük Özel Eğitim Uygulama Okulu III. Kademe',
  'BİLECİK - BOZÜYÜK - Meliha Ercan Ortaokulu',
  'BİLECİK - BOZÜYÜK - Bozüyük Hayme Ana Özel Eğitim Anaokulu',
  'BİLECİK - BOZÜYÜK - Bozüyük Bilim ve Sanat Merkezi',
  'BİLECİK - BOZÜYÜK - Bilecik Güzel Sanatlar Lisesi',
  'BİLECİK - BOZÜYÜK - Kapanalan İlkokulu',
  'BİLECİK - BOZÜYÜK - Bozüyük Bilim ve Sanat Merkezi Anaokulu',
  'BİLECİK - BOZÜYÜK - Necip Fazıl Kısakürek Anaokulu',
  'BİLECİK - BOZÜYÜK - Nejat Ferit Eczacıbaşı İlkokulu',
  'BİLECİK - BOZÜYÜK - Bozüyük Devlet Hastanesi Anaokulu',
  'BİLECİK - GÖLPAZARI - Gölpazarı İsmail Kara Anaokulu',
  'BİLECİK - GÖLPAZARI - Güner Orbay Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - GÖLPAZARI - Gölpazarı Halk Eğitimi Merkezi',
  'BİLECİK - GÖLPAZARI - Gölpazarı Anadolu İmam Hatip Lisesi',
  'BİLECİK - GÖLPAZARI - Gazimihal Ortaokulu',
  'BİLECİK - GÖLPAZARI - Gazimihal İlkokulu',
  'BİLECİK - GÖLPAZARI - Cengiz Topel İlkokulu',
  'BİLECİK - GÖLPAZARI - Cengiz Topel Ortaokulu',
  'BİLECİK - GÖLPAZARI - Şehit Kemal Ay Anadolu Lisesi',
  'BİLECİK - GÖLPAZARI - Öğretmenevi ve Akşam Sanat Okulu',
  'BİLECİK - İNHİSAR - İnhisar Halk Eğitimi Merkezi',
  'BİLECİK - İNHİSAR - İnhisar Çok Programlı Anadolu Lisesi',
  'BİLECİK - İNHİSAR - Atatürk Ortaokulu',
  'BİLECİK - İNHİSAR - Atatürk İlkokulu',
  'BİLECİK - İNHİSAR - ABDULLAH MİHALGAZİ İMAM HATİP ORTAOKULU',
  'BİLECİK - İNHİSAR - İnhisar Öğretmenevi ve Akşam Sanat okulu Müdürlüğü',
  'BİLECİK - MERKEZ - Bilecik Kız Anadolu İmam Hatip Lisesi',
  'BİLECİK - MERKEZ - 15 Temmuz Şehitler Anadolu Lisesi',
  'BİLECİK - MERKEZ - Bilecik Şeyh Edebali Anadolu İmam Hatip Lisesi',
  'BİLECİK - MERKEZ - Bilecik Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - MERKEZ - Bilecik Anaokulu',
  'BİLECİK - MERKEZ - Bilecik Bahçelievler Anaokulu',
  'BİLECİK - MERKEZ - Bilecik Borsa İstanbul Bilim ve Sanat Merkezi',
  'BİLECİK - MERKEZ - İbn - i Sina Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - MERKEZ - Ertuğrulgazi Lisesi',
  'BİLECİK - MERKEZ - Bilecik Halk Eğitimi Merkezi',
  'BİLECİK - MERKEZ - Hayme Ana Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - MERKEZ - Malhun Hatun İlkokulu',
  'BİLECİK - MERKEZ - Şehit Kaymakam Muhammed Fatih Safitürk Ortaokulu',
  'BİLECİK - MERKEZ - Yavuz Selim Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - MERKEZ - Bilecik Mesleki Eğitim Merkezi',
  'BİLECİK - MERKEZ - Öğretmenevi ve Akşam Sanat Okulu',
  'BİLECİK - MERKEZ - Refik Arslan Öztürk Fen Lisesi',
  'BİLECİK - MERKEZ - Bilecik Rehberlik ve Araştırma Merkezi',
  'BİLECİK - MERKEZ - Pelitözü Şehit Münir Kopuk İlkokulu',
  'BİLECİK - MERKEZ - Atatürk İlkokulu',
  'BİLECİK - MERKEZ - Yeniköy Elif Alpdemir İlkokulu',
  'BİLECİK - MERKEZ - Cumhuriyet İlkokulu',
  'BİLECİK - MERKEZ - Kozabirlik İlkokulu',
  'BİLECİK - MERKEZ - Osmangazi Ortaokulu',
  'BİLECİK - MERKEZ - Ertuğrulgazi İlkokulu',
  'BİLECİK - MERKEZ - Murat Hüdavendigar Ortaokulu',
  'BİLECİK - MERKEZ - Mehmet Akif Ersoy İlkokulu',
  'BİLECİK - MERKEZ - Mehmet Akif Ersoy Ortaokulu',
  'BİLECİK - MERKEZ - Edebali Ortaokulu',
  'BİLECİK - MERKEZ - Bilecik Özel Eğitim İlkokulu',
  'BİLECİK - MERKEZ - Bilecik Özel Eğitim Ortaokulu',
  'BİLECİK - MERKEZ - Bilecik Özel Eğitim Meslek Okulu',
  'BİLECİK - MERKEZ - Bilecik Özel Eğitim Uygulama Okulu I. Kademe',
  'BİLECİK - MERKEZ - Bilecik Özel Eğitim Uygulama Okulu II. Kademe',
  'BİLECİK - MERKEZ - Bilecik Özel Eğitim Uygulama Okulu III. Kademe',
  'BİLECİK - MERKEZ - Balahatun Anaokulu',
  'BİLECİK - MERKEZ - TOKİ İlkokulu',
  'BİLECİK - MERKEZ - Bayırköy İlkokulu',
  'BİLECİK - MERKEZ - Bayırköy Ortaokulu',
  'BİLECİK - MERKEZ - Vezirhan İlkokulu',
  'BİLECİK - MERKEZ - 700.Yıl İlkokulu',
  'BİLECİK - MERKEZ - 700.Yıl Ortaokulu',
  'BİLECİK - MERKEZ - AŞAĞIKÖY İLKOKULU',
  'BİLECİK - MERKEZ - Pelitözü Şehit Münir Kopuk Ortaokulu',
  'BİLECİK - MERKEZ - DURSUN FAKIH İMAM HATİP ORTAOKULU',
  'BİLECİK - MERKEZ - ŞEYH EDEBALİ ÜNİVERSİTESİ ANAOKULU',
  'BİLECİK - MERKEZ - VEZİRHAN ORTAOKULU',
  'BİLECİK - MERKEZ - TOKİ Ortaokulu',
  'BİLECİK - MERKEZ - Mehmet Nuri Efendi Anaokulu',
  'BİLECİK - MERKEZ - Bilecik Borsa İstanbul Bilim ve Sanat Merkezi Anaokulu',
  'BİLECİK - MERKEZ - Küplü İlkokulu',
  'BİLECİK - MERKEZ - Bilecik Eğitim ve Araştırma Hastanesi Anaokulu',
  'BİLECİK - OSMANELİ - Cumhuriyet Ortaokulu',
  'BİLECİK - OSMANELİ - Çerkeşli İlkokulu',
  'BİLECİK - OSMANELİ - Osmaneli Halk Eğitimi Merkezi',
  'BİLECİK - OSMANELİ - Oğulpaşa Yeşilçimen İlkokulu',
  'BİLECİK - OSMANELİ - Osmaneli 75. Yıl Anadolu Lisesi',
  'BİLECİK - OSMANELİ - Osmaneli Anaokulu',
  'BİLECİK - OSMANELİ - Osmaneli Nilüfer Hatun Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - OSMANELİ - Atatürk Ortaokulu',
  'BİLECİK - OSMANELİ - Hisarcık Beşevler İlkokulu',
  'BİLECİK - OSMANELİ - Hisarcık Beşevler Ortaokulu',
  'BİLECİK - OSMANELİ - Balaban İlkokulu',
  'BİLECİK - OSMANELİ - Osmaneli İlkokulu',
  'BİLECİK - OSMANELİ - Osmaneli Şehit Osman Er Anadolu İmam Hatip Lisesi',
  'BİLECİK - PAZARYERİ - Pazaryeri Halk Eğitimi Merkezi',
  'BİLECİK - PAZARYERİ - Hilmi Duralioğlu Anadolu Lisesi',
  'BİLECİK - PAZARYERİ - Pazaryeri Anaokulu',
  'BİLECİK - PAZARYERİ - Nabi Avcı Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - PAZARYERİ - Kınık İlkokulu',
  'BİLECİK - PAZARYERİ - Kınık Ortaokulu',
  'BİLECİK - PAZARYERİ - Pazaryeri İlkokulu',
  'BİLECİK - PAZARYERİ - Atatürk Ortaokulu',
  'BİLECİK - PAZARYERİ - Beşeylül İlkokulu',
  'BİLECİK - PAZARYERİ - Öğretmen Evi ve Akşam Sanat Okulu',
  'BİLECİK - PAZARYERİ - Şehit Zafer Koyuncu İmam Hatip Ortaokulu',
  'BİLECİK - PAZARYERİ - Karaköy İlkokulu',
  'BİLECİK - PAZARYERİ - Pazaryeri Özel Eğitim Anaokulu',
  'BİLECİK - SÖĞÜT - 700. Yıl Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - SÖĞÜT - 75.Yıl Cumhuriyet Anaokulu',
  'BİLECİK - SÖĞÜT - Ayşe Küflü İlkokulu',
  'BİLECİK - SÖĞÜT - Söğüt Ertuğrulgazi Mesleki ve Teknik Anadolu Lisesi',
  'BİLECİK - SÖĞÜT - Söğüt Halk Eğitimi Merkezi',
  'BİLECİK - SÖĞÜT - Söğüt Anadolu İmam Hatip Lisesi',
  'BİLECİK - SÖĞÜT - Salih ve Ömer Musaoğlu İlkokulu',
  'BİLECİK - SÖĞÜT - Söğüt Anadolu Lisesi',
  'BİLECİK - SÖĞÜT - 100.Yıl Atatürk Ortaokulu',
  'BİLECİK - SÖĞÜT - Ertuğrulgazi Ortaokulu',
  'BİLECİK - SÖĞÜT - 100.Yıl Atatürk İlkokulu',
  'BİLECİK - SÖĞÜT - Çaltı İlkokulu',
  'BİLECİK - SÖĞÜT - Çaltı Ortaokulu',
  'BİLECİK - SÖĞÜT - Küre Dursun Fakıh İlkokulu',
  'BİLECİK - SÖĞÜT - Küre Dursun Fakıh Ortaokulu',
  'BİLECİK - SÖĞÜT - Yaşar Musaoğlu İlkokulu',
  'BİLECİK - SÖĞÜT - Yaşar Musaoğlu Ortaokulu',
  'BİLECİK - SÖĞÜT - ORHANGAZİ İMAM HATİP ORTAOKULU',
  'BİLECİK - YENİPAZAR - Atatürk Ortaokulu',
  'BİLECİK - YENİPAZAR - Halk Eğitimi Merkezi',
  'BİLECİK - YENİPAZAR - Yenipazar Çok Programlı Anadolu Lisesi',
  'BİLECİK - YENİPAZAR - 75.Yıl Cumhuriyet İlkokulu',
  'BİLECİK - YENİPAZAR - Yenipazar Öğretmenevi ve Akşam Sanat Okulu Müdürlüğü',

  ];

  List<String> get list=>_list;
}