class BingolSchools{
  final List<String> _list=[
  'BİNGÖL - ADAKLI - Adaklı Çok Programlı Anadolu Lisesi',
  'BİNGÖL - ADAKLI - Adaklı Yatılı Bölge Ortaokulu',
  'BİNGÖL - ADAKLI - Hasbağlar İlkokulu',
  'BİNGÖL - ADAKLI - Hasbağlar Ortaokulu',
  'BİNGÖL - ADAKLI - Mercan Çomak İlkokulu',
  'BİNGÖL - ADAKLI - Aktaş İlkokulu',
  'BİNGÖL - ADAKLI - Yeşiltepe İlkokulu',
  'BİNGÖL - ADAKLI - Doğankaya İlkokulu',
  'BİNGÖL - ADAKLI - Kırkpınar İlkokulu',
  'BİNGÖL - ADAKLI - Elmadüzü İlkokulu',
  'BİNGÖL - ADAKLI - Erbaşlar İlkokulu',
  'BİNGÖL - ADAKLI - Çatmaoluk Çiçekli İlkokulu',
  'BİNGÖL - ADAKLI - Adaklı Halk Eğitimi Merkezi',
  'BİNGÖL - ADAKLI - Çatma İlkokulu',
  'BİNGÖL - ADAKLI - Adaklı Anaokulu',
  'BİNGÖL - ADAKLI - Adaklı İmam Hatip Ortaokulu',
  'BİNGÖL - ADAKLI - Karaçubuk İlkokulu',
  'BİNGÖL - ADAKLI - Karaçubuk Ortaokulu',
  'BİNGÖL - ADAKLI - Selahaddin Eyyübi İlkokulu',
  'BİNGÖL - ADAKLI - Adaklı Şehit Hikmet Saydan İlkokulu',
  'BİNGÖL - ADAKLI - Adaklı Öğretmenevi ve ASO',
  'BİNGÖL - ADAKLI - Bağlarpınar İlkokulu',
  'BİNGÖL - ADAKLI - Kaynakdüzü Karakoç İlkokulu',
  'BİNGÖL - ADAKLI - Kozlu İlkokulu',
  'BİNGÖL - GENÇ - Çaytepe Ortaokulu',
  'BİNGÖL - GENÇ - Şehit Mehmet Koçdağı Anadolu Lisesi',
  'BİNGÖL - GENÇ - Genç İmam Hatip Ortaokulu',
  'BİNGÖL - GENÇ - Genç Halk Eğitimi Merkezi',
  'BİNGÖL - GENÇ - Genç Anadolu İmam Hatip Lisesi',
  'BİNGÖL - GENÇ - Çamlık İlkokulu',
  'BİNGÖL - GENÇ - Şehit Murat Yıldırım Mesleki ve Teknik Anadolu Lisesi',
  'BİNGÖL - GENÇ - Milli Eğitim Vakfı İlkokulu',
  'BİNGÖL - GENÇ - Nuri Özaltın İlkokulu',
  'BİNGÖL - GENÇ - Servi Şehit Ali Kalan Yatılı Bölge Ortaokulu',
  'BİNGÖL - GENÇ - Yenişehir Anaokulu',
  'BİNGÖL - GENÇ - Yunus Emre İlkokulu',
  'BİNGÖL - GENÇ - Mevlana Ortaokulu',
  'BİNGÖL - GENÇ - Borsa İstanbul Atatürk Ortaokulu',
  'BİNGÖL - GENÇ - Şehit Serkan Gençer İlkokulu',
  'BİNGÖL - GENÇ - Genç Yatılı Bölge Ortaokulu',
  'BİNGÖL - GENÇ - Borsa İstanbul Yayla Ortaokulu',
  'BİNGÖL - GENÇ - Alaaddin İlkokulu',
  'BİNGÖL - GENÇ - Direkli İlkokulu',
  'BİNGÖL - GENÇ - Direkli Yedievler İlkokulu',
  'BİNGÖL - GENÇ - Eskibağ Çöğürlü İlkokulu',
  'BİNGÖL - GENÇ - Günkondu Yeniçağ İlkokulu',
  'BİNGÖL - GENÇ - Servi Merkez İlkokulu',
  'BİNGÖL - GENÇ - Yatansöğüt İlkokulu',
  'BİNGÖL - GENÇ - Yaydere İlkokulu',
  'BİNGÖL - GENÇ - İnönü Ortaokulu',
  'BİNGÖL - GENÇ - Öğretmenevi ve Akşam Sanat Okulu',
  'BİNGÖL - GENÇ - İbn - i Sina Mesleki ve Teknik Anadolu Lisesi',
  'BİNGÖL - GENÇ - Sevgi Anaokulu',
  'BİNGÖL - GENÇ - Çaytepe İlkokulu',
  'BİNGÖL - GENÇ - Şehit Recep Tümen İmam Hatip Ortaokulu',
  'BİNGÖL - GENÇ - Gönülaçan İlkokulu',
  'BİNGÖL - GENÇ - Genç İlkokulu',
  'BİNGÖL - GENÇ - Genç Murat İmam Hatip Ortaokulu',
  'BİNGÖL - GENÇ - Gökkuşağı Anaokulu',
  'BİNGÖL - GENÇ - Yayla İlkokulu',
  'BİNGÖL - GENÇ - Sırmalıova İlkokulu',
  'BİNGÖL - GENÇ - Kuruca İlkokulu',
  'BİNGÖL - GENÇ - Genç Bilim ve Sanat Merkezi',
  'BİNGÖL - GENÇ - Genç Fen Lisesi',
  'BİNGÖL - GENÇ - Doludere İlkokulu',
  'BİNGÖL - GENÇ - Çaybaşı İlkokulu',
  'BİNGÖL - GENÇ - Yeniyazı Kaldırım İlkokulu',
  'BİNGÖL - GENÇ - Saadet Özge Anaokulu',
  'BİNGÖL - GENÇ - Doğanca İlkokulu',
  'BİNGÖL - GENÇ - Genç Özel Eğitim Uygulama Okulu I. Kademe',
  'BİNGÖL - GENÇ - Genç Özel Eğitim Uygulama Okulu II. Kademe',
  'BİNGÖL - GENÇ - Genç Özel Eğitim Uygulama Okulu III. Kademe',
  'BİNGÖL - KARLIOVA - 11 Mart İlkokulu',
  'BİNGÖL - KARLIOVA - 125.Yıl Anaokulu',
  'BİNGÖL - KARLIOVA - Cilligöl İlkokulu',
  'BİNGÖL - KARLIOVA - Devecik İlkokulu',
  'BİNGÖL - KARLIOVA - Göynük Yeni Yerleşim İlkokulu',
  'BİNGÖL - KARLIOVA - Karlıova Halk Eğitimi Merkezi',
  'BİNGÖL - KARLIOVA - Kargapazarı İlkokulu',
  'BİNGÖL - KARLIOVA - Kargapazarı Ortaokulu',
  'BİNGÖL - KARLIOVA - Karlıova Mesleki ve Teknik Anadolu Lisesi',
  'BİNGÖL - KARLIOVA - Öğretmen Hüseyin Hüsnü Tekışık Ortaokulu',
  'BİNGÖL - KARLIOVA - Şehit İdris Demir İlkokulu',
  'BİNGÖL - KARLIOVA - Şehit İdris Demir Ortaokulu',
  'BİNGÖL - KARLIOVA - Şehit Tarık Aydemir Yatılı Bölge Ortaokulu',
  'BİNGÖL - KARLIOVA - Kızılçubuk İlkokulu',
  'BİNGÖL - KARLIOVA - Dörtyol Ortaokulu',
  'BİNGÖL - KARLIOVA - Derinçay İlkokulu',
  'BİNGÖL - KARLIOVA - Kantarkaya İlkokulu',
  'BİNGÖL - KARLIOVA - Kantarkaya Ortaokulu',
  'BİNGÖL - KARLIOVA - Boncukgöze İlkokulu',
  'BİNGÖL - KARLIOVA - Sudurağı İlkokulu',
  'BİNGÖL - KARLIOVA - Hacılar Ortaokulu',
  'BİNGÖL - KARLIOVA - Hacılar İlkokulu',
  'BİNGÖL - KARLIOVA - Dörtyol İlkokulu',
  'BİNGÖL - KARLIOVA - Karlıca İlkokulu',
  'BİNGÖL - KARLIOVA - Yiğitler İlkokulu',
  'BİNGÖL - KARLIOVA - Yiğitler Ortaokulu',
  'BİNGÖL - KARLIOVA - Karlıova Anadolu Lisesi',
  'BİNGÖL - KARLIOVA - Kalencik Ortaokulu',
  'BİNGÖL - KARLIOVA - Bağlıisa İlkokulu',
  'BİNGÖL - KARLIOVA - Mollaşakir Tarlacık İlkokulu',
  'BİNGÖL - KARLIOVA - Yorgançayır İlkokulu',
  'BİNGÖL - KARLIOVA - Geçitli İlkokulu',
  'BİNGÖL - KARLIOVA - Çukurtepe İlkokulu',
  'BİNGÖL - KARLIOVA - Toklular İlkokulu',
  'BİNGÖL - KARLIOVA - Toklular Ortaokulu',
  'BİNGÖL - KARLIOVA - Çukurtepe Ortaokulu',
  'BİNGÖL - KARLIOVA - Mollaşakir İlkokulu',
  'BİNGÖL - KARLIOVA - Kalencik İmam Hatip Ortaokulu',
  'BİNGÖL - KARLIOVA - Aşağı Yağmurlu İlkokulu',
  'BİNGÖL - KARLIOVA - Bağlıisa Selekan İlkokulu',
  'BİNGÖL - KARLIOVA - Çatak İlkokulu',
  'BİNGÖL - KARLIOVA - Sakaören Ortaokulu',
  'BİNGÖL - KARLIOVA - Yoncalık İlkokulu',
  'BİNGÖL - KARLIOVA - Yeniköy İlkokulu',
  'BİNGÖL - KARLIOVA - Viranşehir İlkokulu',
  'BİNGÖL - KARLIOVA - Yukarı Yağmurlu İlkokulu',
  'BİNGÖL - KARLIOVA - Ortaköy İlkokulu',
  'BİNGÖL - KARLIOVA - Sarıkuşak Yeni Yerleşim İlkokulu',
  'BİNGÖL - KARLIOVA - Serpmekaya Bedran İlkokulu',
  'BİNGÖL - KARLIOVA - Serpmekaya İlkokulu',
  'BİNGÖL - KARLIOVA - Karabalçık İlkokulu',
  'BİNGÖL - KARLIOVA - Suçatı İlkokulu',
  'BİNGÖL - KARLIOVA - Kaşıkçı İlkokulu',
  'BİNGÖL - KARLIOVA - Karlıova Kız Anadolu İmam Hatip Lisesi',
  'BİNGÖL - KARLIOVA - Serpmekaya Yalnızan İlkokulu',
  'BİNGÖL - KARLIOVA - Kale İlkokulu',
  'BİNGÖL - KARLIOVA - Sakaören İlkokulu',
  'BİNGÖL - KARLIOVA - Ayten Tekışık İlkokulu',
  'BİNGÖL - KARLIOVA - Ayten Tekışık Ortaokulu',
  'BİNGÖL - KARLIOVA - Kızılağaç Meşeli İlkokulu',
  'BİNGÖL - KARLIOVA - Bağlıisa Çiçekli İlkokulu',
  'BİNGÖL - KARLIOVA - Kaynak İlkokulu',
  'BİNGÖL - KARLIOVA - HARMANTEPE İLKOKULU',
  'BİNGÖL - KARLIOVA - HASANOVA İLKOKULU',
  'BİNGÖL - KARLIOVA - ILIPINAR İLKOKULU',
  'BİNGÖL - KARLIOVA - Kalencik İlkokulu',
  'BİNGÖL - KARLIOVA - KÜMBET İLKOKULU',
  'BİNGÖL - KARLIOVA - ŞEHİT HACI ALAN ANADOLU İMAM HATİP LİSESİ',
  'BİNGÖL - KARLIOVA - 15 TEMMUZ İLKOKULU',
  'BİNGÖL - KARLIOVA - KARLIOVA ÖĞRETMENEVİ AKŞAM SANAT OKULU MÜDÜRLÜĞÜ',
  'BİNGÖL - KIĞI - Kiği Halk Eğitimi Merkezi',
  'BİNGÖL - KIĞI - Kiğı Fuat Dağıstan Çok Programlı Anadolu Lisesi',
  'BİNGÖL - KIĞI - Öğretmenevi ve Akşam Sanat Okulu',
  'BİNGÖL - KIĞI - Yusuf Ziya Değnekçi Ortaokulu',
  'BİNGÖL - KIĞI - Kiğı Yatılı Bölge Ortaokulu',
  'BİNGÖL - KIĞI - 20 Kasım Kurtulus İlkokulu',
  'BİNGÖL - KIĞI - Çanakçı İlkokulu',
  'BİNGÖL - KIĞI - Nacaklı İlkokulu',
  'BİNGÖL - KIĞI - Sırmaçek İlkokulu',
  'BİNGÖL - KIĞI - Şehit Kaymakam Muhammet Fatih Safitürk İlkokulu',
  'BİNGÖL - KIĞI - Menekşe Durmuşoğlu Anaokulu',
  'BİNGÖL - KIĞI - Nacaklı İncesu İlkokulu',
  'BİNGÖL - KIĞI - Dallıca İlkokulu',
  'BİNGÖL - KIĞI - Alagöz İlkokulu',
  'BİNGÖL - KIĞI - Nacaklı Alican İlkokulu',
  'BİNGÖL - MERKEZ - 100.Yıl Ortaokulu',
  'BİNGÖL - MERKEZ - 60. Yıl Mesleki ve Teknik Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Bal Peteği Anaokulu',
  'BİNGÖL - MERKEZ - Bingöl Güzel Sanatlar Lisesi',
  'BİNGÖL - MERKEZ - Karşıyaka Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Bingöl Mesleki ve Teknik Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Mevlana Kız Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Çavuşlar İlkokulu',
  'BİNGÖL - MERKEZ - Bingöl Merkez İmam Hatip Ortaokulu',
  'BİNGÖL - MERKEZ - Güveçli İlkokulu',
  'BİNGÖL - MERKEZ - Güveçli Ortaokulu',
  'BİNGÖL - MERKEZ - Bingöl Halk Eğitimi Merkezi',
  'BİNGÖL - MERKEZ - Borsa İstanbul Bingöl Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Kardelen Anaokulu',
  'BİNGÖL - MERKEZ - Karşıyaka Anaokulu',
  'BİNGÖL - MERKEZ - Kazım Karabekir Ortaokulu',
  'BİNGÖL - MERKEZ - Karşıyaka Mesleki ve Teknik Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Mehmet Akif Ersoy Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Bingöl Mesleki Eğitim Merkezi',
  'BİNGÖL - MERKEZ - Murat İlkokulu',
  'BİNGÖL - MERKEZ - Bingöl Rehberlik ve Araştırma Merkezi',
  'BİNGÖL - MERKEZ - Rekabet Kurumu Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Sancak Ahmet Yesevi Ortaokulu',
  'BİNGÖL - MERKEZ - Şehit Mustafa Gündoğdu İlkokulu',
  'BİNGÖL - MERKEZ - Saray Mesleki ve Teknik Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Türkiye Büyük Millet Meclisi Vakfı Bingöl Fen Lisesi',
  'BİNGÖL - MERKEZ - Yeşilyurt Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Uydukent Anaokulu',
  'BİNGÖL - MERKEZ - Yavuz Selim İlkokulu',
  'BİNGÖL - MERKEZ - Yunus Emre Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Zübeyde Hanım Anaokulu',
  'BİNGÖL - MERKEZ - Gazi Ortaokulu',
  'BİNGÖL - MERKEZ - Cumhuriyet İlkokulu',
  'BİNGÖL - MERKEZ - Ilıcalar İlkokulu',
  'BİNGÖL - MERKEZ - Ilıcalar Ortaokulu',
  'BİNGÖL - MERKEZ - Milli Egemenlik Ortaokulu',
  'BİNGÖL - MERKEZ - Milli Egemenlik İlkokulu',
  'BİNGÖL - MERKEZ - 75.Yıl İlkokulu',
  'BİNGÖL - MERKEZ - Ankara Büyükşehir Belediyesi İlkokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Fatih İlkokulu',
  'BİNGÖL - MERKEZ - Yeşilyurt Ortaokulu',
  'BİNGÖL - MERKEZ - Sultan Abdulhamid Han Ortaokulu',
  'BİNGÖL - MERKEZ - Garip İlkokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Kaleönü Ortaokulu',
  'BİNGÖL - MERKEZ - TOBB Cevdet Yılmaz Ortaokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Gözeler Haraba Ortaokulu',
  'BİNGÖL - MERKEZ - Büyüktekören İlkokulu',
  'BİNGÖL - MERKEZ - Kumgeçit İlkokulu',
  'BİNGÖL - MERKEZ - İçmeler Mehmet Akif İnan Ortaokulu',
  'BİNGÖL - MERKEZ - Sudüğünü Ortaokulu',
  'BİNGÖL - MERKEZ - Elmalı İlkokulu',
  'BİNGÖL - MERKEZ - Kazım Karabekir İlkokulu',
  'BİNGÖL - MERKEZ - Gazi İlkokulu',
  'BİNGÖL - MERKEZ - Çavuşlar Yeni Yerleşim İlkokulu',
  'BİNGÖL - MERKEZ - Çavuşlar Yeni Yerleşim Ortaokulu',
  'BİNGÖL - MERKEZ - Şehit Astsubay Muhammed Koşan Ortaokulu',
  'BİNGÖL - MERKEZ - İbni Sina Ortaokulu',
  'BİNGÖL - MERKEZ - İbni Sina İlkokulu',
  'BİNGÖL - MERKEZ - Dikme İlkokulu',
  'BİNGÖL - MERKEZ - Karapınar İlkokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Mustafa Kemal Paşa İlkokulu',
  'BİNGÖL - MERKEZ - Mimar Sinan İlkokulu',
  'BİNGÖL - MERKEZ - Arıcılar İlkokulu',
  'BİNGÖL - MERKEZ - Bingöl Bilim ve Sanat Merkezi',
  'BİNGÖL - MERKEZ - Çevrimpınar İlkokulu',
  'BİNGÖL - MERKEZ - Ağaçeli 100.Yıl İlkokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Sarayiçi İlkokulu',
  'BİNGÖL - MERKEZ - Atatürk Anadolu Lisesi',
  'BİNGÖL - MERKEZ - Gökdere Hacılar İlkokulu',
  'BİNGÖL - MERKEZ - Turgut Özal Ortaokulu',
  'BİNGÖL - MERKEZ - Sudüğünü İlkokulu',
  'BİNGÖL - MERKEZ - Yukarı Ağaçeli İlkokulu',
  'BİNGÖL - MERKEZ - Selahaddin Eyyubi Anadolu İmam Hatip Lisesi',
  'BİNGÖL - MERKEZ - İncesu İlkokulu',
  'BİNGÖL - MERKEZ - Aşağı Yenibaşlar İlkokulu',
  'BİNGÖL - MERKEZ - Vali Kurtuluş Şişmantürk İlkokulu',
  'BİNGÖL - MERKEZ - Vali Kurtuluş Şişmantürk Ortaokulu',
  'BİNGÖL - MERKEZ - Turgut Özal Anaokulu',
  'BİNGÖL - MERKEZ - Göltepesi Yeni Yerleşim İlkokulu',
  'BİNGÖL - MERKEZ - Göltepesi Yeni Yerleşim Ortaokulu',
  'BİNGÖL - MERKEZ - Saray Anaokulu',
  'BİNGÖL - MERKEZ - Gökçekanat İlkokulu',
  'BİNGÖL - MERKEZ - Ilıcalar Şehit Mansur Salcan Yatılı Bölge Ortaokulu',
  'BİNGÖL - MERKEZ - Ilıcalar Kamışlı İlkokulu',
  'BİNGÖL - MERKEZ - Direkli İlkokulu',
  'BİNGÖL - MERKEZ - Vali Güner Orbay Ortaokulu',
  'BİNGÖL - MERKEZ - Çobantaşı İlkokulu',
  'BİNGÖL - MERKEZ - Yamaç Ortaokulu',
  'BİNGÖL - MERKEZ - Yamaç İlkokulu',
  'BİNGÖL - MERKEZ - Çeltiksuyu Sabah Gazetesi İlkokulu',
  'BİNGÖL - MERKEZ - Çeltiksuyu Sabah Gazetesi Ortaokulu',
  'BİNGÖL - MERKEZ - Ekinyolu Köprübaşı İlkokulu',
  'BİNGÖL - MERKEZ - Sancak Ortaokulu',
  'BİNGÖL - MERKEZ - Şehit Mustafa Gündoğdu Ortaokulu',
  'BİNGÖL - MERKEZ - Emtağ İlkokulu',
  'BİNGÖL - MERKEZ - Emtağ Ortaokulu',
  'BİNGÖL - MERKEZ - Sancak İlkokulu',
  'BİNGÖL - MERKEZ - Sütgölü İlkokulu',
  'BİNGÖL - MERKEZ - Kurudere Tugay İlkokulu',
  'BİNGÖL - MERKEZ - Yolçatı İlkokulu',
  'BİNGÖL - MERKEZ - Ilıcalar İmam Hatip Ortaokulu',
  'BİNGÖL - MERKEZ - Alatepe İlkokulu',
  'BİNGÖL - MERKEZ - İçmeler Mehmet Akif İnan İlkokulu',
  'BİNGÖL - MERKEZ - Ormanardı İlkokulu',
  'BİNGÖL - MERKEZ - Yelesen İlkokulu',
  'BİNGÖL - MERKEZ - Yazgülü İlkokulu',
  'BİNGÖL - MERKEZ - Şaban İlkokulu',
  'BİNGÖL - MERKEZ - Kardeşler İlkokulu',
  'BİNGÖL - MERKEZ - Yeniköy İlkokulu',
  'BİNGÖL - MERKEZ - Bingöl Anadolu İmam Hatip Lisesi',
  'BİNGÖL - MERKEZ - Milli Eğitim Vakfı Öğretmen Serkan Akyaz İlkokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Ekinyolu Ortaokulu',
  'BİNGÖL - MERKEZ - Öğretmenevi ve Akşam Sanat Okulu',
  'BİNGÖL - MERKEZ - Papatyalar Anaokulu',
  'BİNGÖL - MERKEZ - KÜÇÜKBAŞKÖY İLKOKULU',
  'BİNGÖL - MERKEZ - Gözer Ortaokulu',
  'BİNGÖL - MERKEZ - Atatürk İlkokulu',
  'BİNGÖL - MERKEZ - AŞAĞI YUMAKLI İLKOKULU',
  'BİNGÖL - MERKEZ - Erdemli İlkokulu',
  'BİNGÖL - MERKEZ - KUŞKONDU İLKOKULU',
  'BİNGÖL - MERKEZ - Bingöl Özel Eğitim Uygulama Okulu I. Kademe',
  'BİNGÖL - MERKEZ - SANCAK ÇOK PROGRAMLI ANADOLU LİSESİ',
  'BİNGÖL - MERKEZ - ILICALAR UZUNDERE İLKOKULU',
  'BİNGÖL - MERKEZ - Şekerpancarı İlkokulu',
  'BİNGÖL - MERKEZ - Bingöl Özel Eğitim Uygulama Okulu II. Kademe',
  'BİNGÖL - MERKEZ - ÇUKURCA YENİ YERLEŞİM İLKOKULU',
  'BİNGÖL - MERKEZ - CUMHURİYET KIZ ANADOLU İMAM HATİP LİSESİ',
  'BİNGÖL - MERKEZ - BİLALOĞLU HARİCİYECİLER İLKOKULU',
  'BİNGÖL - MERKEZ - RABİA HATUN KIZ ANADOLU İMAM HATİP LİSESİ',
  'BİNGÖL - MERKEZ - KURUCA İLKOKULU',
  'BİNGÖL - MERKEZ - 15 TEMMUZ ŞEHİTLERİ İMAM HATİP ORTAOKULU',
  'BİNGÖL - MERKEZ - SANCAK İMAM HATİP ORTAOKULU',
  'BİNGÖL - MERKEZ - 15 TEMMUZ MİLLİ İRADE ANADOLU İMAM HATİP LİSESİ',
  'BİNGÖL - MERKEZ - İÇMELER MEHMET AKİF İNAN İMAM HATİP ORTAOKULU',
  'BİNGÖL - MERKEZ - Borsa İstanbul Gözeler Haraba İlkokulu',
  'BİNGÖL - MERKEZ - ŞEHİT ZAFER KURT MESLEKİ VE TEKNİK ANADOLU LİSESİ',
  'BİNGÖL - MERKEZ - VALİ GÜNER ORBAY İMAM HATİP ORTAOKULU',
  'BİNGÖL - MERKEZ - Borsa İstanbul Kaleönü İlkokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Kaleönü İmam Hatip Ortaokulu',
  'BİNGÖL - MERKEZ - Gözer İlkokulu',
  'BİNGÖL - MERKEZ - Büyükbaşköy İlkokulu',
  'BİNGÖL - MERKEZ - İçpınar İlkokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Sarıçiçek İlkokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Sarıçiçek Ortaokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Ekinyolu İlkokulu',
  'BİNGÖL - MERKEZ - Bingöl Özel Eğitim Uygulama Okulu III. Kademe',
  'BİNGÖL - MERKEZ - Yeşilyurt İlkokulu',
  'BİNGÖL - MERKEZ - Yeşilova İlkokulu',
  'BİNGÖL - MERKEZ - Alibirköyü İlkokulu',
  'BİNGÖL - MERKEZ - Turgut Özal İmam Hatip Ortaokulu',
  'BİNGÖL - MERKEZ - Bingöl Özel Eğitim Meslek Okulu',
  'BİNGÖL - MERKEZ - Bingöl Spor Lisesi',
  'BİNGÖL - MERKEZ - Bingöl Özel Eğitim Anaokulu',
  'BİNGÖL - MERKEZ - Ilıcalar Kılıçlı İlkokulu',
  'BİNGÖL - MERKEZ - Kiran Aşağı Paymerk İlkokulu',
  'BİNGÖL - MERKEZ - Gökdere İlkokulu',
  'BİNGÖL - MERKEZ - Yaygınçayır İlkokulu',
  'BİNGÖL - MERKEZ - Aşağı Suvaran İlkokulu',
  'BİNGÖL - MERKEZ - Yukarı Yumaklı İlkokulu',
  'BİNGÖL - MERKEZ - Yaygınçayır Üsküdar İlkokulu',
  'BİNGÖL - MERKEZ - Yukarı Yenibaşlar İlkokulu',
  'BİNGÖL - MERKEZ - Sudüğünü Hanoçayırı İlkokulu',
  'BİNGÖL - MERKEZ - Köklü İlkokulu',
  'BİNGÖL - MERKEZ - Kartal İlkokulu',
  'BİNGÖL - MERKEZ - Güngören İlkokulu',
  'BİNGÖL - MERKEZ - Çiriş İlkokulu',
  'BİNGÖL - MERKEZ - Bahçeli İlkokulu',
  'BİNGÖL - MERKEZ - Sütana Kızılay Anaokulu',
  'BİNGÖL - MERKEZ - Alatepe Ortaokulu',
  'BİNGÖL - MERKEZ - İl Milli Eğitim Müdürlüğü',
  'BİNGÖL - MERKEZ - Atatürk Anaokulu',
  'BİNGÖL - MERKEZ - Şehit Mustafa Gündoğdu Anaokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Sarayiçi Anaokulu',
  'BİNGÖL - MERKEZ - Cumhuriyet Anaokulu',
  'BİNGÖL - MERKEZ - Borsa İstanbul Kaleönü Anaokulu',
  'BİNGÖL - MERKEZ - Gazi Anaokulu',
  'BİNGÖL - SOLHAN - Atatürk İlkokulu',
  'BİNGÖL - SOLHAN - Sabiha Bahçıvan Anadolu Lisesi',
  'BİNGÖL - SOLHAN - Solhan Kız Anadolu İmam Hatip Lisesi',
  'BİNGÖL - SOLHAN - Solhan Anadolu Lisesi',
  'BİNGÖL - SOLHAN - 28 Ağustos İlkokulu',
  'BİNGÖL - SOLHAN - 28 Ağustos Ortaokulu',
  'BİNGÖL - SOLHAN - Solhan Yatılı Bölge Ortaokulu',
  'BİNGÖL - SOLHAN - Yenibaşak Yatılı Bölge Ortaokulu',
  'BİNGÖL - SOLHAN - Yeşilova İmam Hatip Ortaokulu',
  'BİNGÖL - SOLHAN - Mehmet Akif Ersoy İlkokulu',
  'BİNGÖL - SOLHAN - Öğretmen Veli Tuğa İlkokulu',
  'BİNGÖL - SOLHAN - Borsa İstanbul Arakonak İlkokulu',
  'BİNGÖL - SOLHAN - Mehmet Akif Ersoy Ortaokulu',
  'BİNGÖL - SOLHAN - Atatürk Ortaokulu',
  'BİNGÖL - SOLHAN - Yüzen Ada Anaokulu',
  'BİNGÖL - SOLHAN - Borsa İstanbul Arakonak Ortaokulu',
  'BİNGÖL - SOLHAN - Şehit Kaymakam Ersin Ateş İlkokulu',
  'BİNGÖL - SOLHAN - Şehit Kaymakam Ersin Ateş Ortaokulu',
  'BİNGÖL - SOLHAN - Murat İlkokulu',
  'BİNGÖL - SOLHAN - Dilektepe İlkokulu',
  'BİNGÖL - SOLHAN - Solhan Halk Eğitimi Merkezi',
  'BİNGÖL - SOLHAN - Gelintepe İlkokulu',
  'BİNGÖL - SOLHAN - Öğretmenevi ve Akşam Sanat Okulu',
  'BİNGÖL - SOLHAN - Hazarşah Şehitleri İlkokulu',
  'BİNGÖL - SOLHAN - Hazarşah Yeni Yerleşim Ortaokulu',
  'BİNGÖL - SOLHAN - Öğretmen Hüseyin Artunç Mesleki ve Teknik Anadolu Lisesi',
  'BİNGÖL - SOLHAN - Hazarşah Yeni Yerleşim İlkokulu',
  'BİNGÖL - SOLHAN - Eşmetaş İlkokulu',
  'BİNGÖL - SOLHAN - Tarhan İlkokulu',
  'BİNGÖL - SOLHAN - Yiğitharmanı İlkokulu',
  'BİNGÖL - SOLHAN - YEŞİLOVA ANAOKULU',
  'BİNGÖL - SOLHAN - DİLEKTEPE ORTAOKULU',
  'BİNGÖL - SOLHAN - Şehit Ersin Özyurt Anadolu İmam Hatip Lisesi',
  'BİNGÖL - SOLHAN - SOLHAN FARABİ MESLEKİ VE TEKNİK ANADOLU LİSESİ',
  'BİNGÖL - SOLHAN - Asmakaya İlkokulu',
  'BİNGÖL - SOLHAN - SOLHAN İMAM HATİP ORTAOKULU',
  'BİNGÖL - SOLHAN - SOLHAN İLKOKULU',
  'BİNGÖL - SOLHAN - Öğretmen Veli Tuğa Ortaokulu',
  'BİNGÖL - SOLHAN - Yenibaşak İlkokulu',
  'BİNGÖL - SOLHAN - Yenibaşak İmam Hatip Ortaokulu',
  'BİNGÖL - SOLHAN - Solhan Merkez İmam Hatip Ortaokulu',
  'BİNGÖL - SOLHAN - Atatürk İmam Hatip Ortaokulu',
  'BİNGÖL - SOLHAN - Dilektepe İmam Hatip Ortaokulu',
  'BİNGÖL - SOLHAN - Solhan Özel Eğitim Uygulama Okulu I. Kademe',
  'BİNGÖL - SOLHAN - Solhan Özel Eğitim Uygulama Okulu II. Kademe',
  'BİNGÖL - SOLHAN - Solhan Özel Eğitim Uygulama Okulu III. Kademe',
  'BİNGÖL - SOLHAN - Kırık Yürekli İlkokulu',
  'BİNGÖL - SOLHAN - Asmakaya Bozkar İlkokulu',
  'BİNGÖL - SOLHAN - Atatürk Anaokulu',
  'BİNGÖL - YAYLADERE - Yayladere Ortaokulu',
  'BİNGÖL - YAYLADERE - Yayladere Çok Programlı Anadolu Lisesi',
  'BİNGÖL - YAYLADERE - Yayladere İlkokulu',
  'BİNGÖL - YAYLADERE - Yayladere Halk Eğitimi Merkezi',
  'BİNGÖL - YEDİSU - Yedisu Çok Programlı Anadolu Lisesi',
  'BİNGÖL - YEDİSU - Yedisu Yatılı Bölge Ortaokulu',
  'BİNGÖL - YEDİSU - Yedisu İlkokulu',
  'BİNGÖL - YEDİSU - Yedisu Halk Eğitimi Merkezi',
  'BİNGÖL - YEDİSU - Kürdan İlkokulu',
  'BİNGÖL - YEDİSU - Döşengi İlkokulu',

  ];

  List<String> get list=>_list;
}