class BitlisSchools{
  final List<String> _list=[
  'BİTLİS - ADİLCEVAZ - Adilcevaz Anadolu Lisesi',
  'BİTLİS - ADİLCEVAZ - Adilcevaz Anaokulu',
  'BİTLİS - ADİLCEVAZ - Akçıra Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Akçıra Köyü Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Atatürk İlkokulu',
  'BİTLİS - ADİLCEVAZ - Aydınlar İlkokulu',
  'BİTLİS - ADİLCEVAZ - Aydınlar Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Adilcevaz Halk Eğitimi Merkezi',
  'BİTLİS - ADİLCEVAZ - Hıdırşah İlkokulu',
  'BİTLİS - ADİLCEVAZ - İbrahim Karaoğlanoğlu İlkokulu',
  'BİTLİS - ADİLCEVAZ - Şehit Muhammed BOZARSLAN Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Adilcevaz Tuğrul Bey Anadolu Lisesi',
  'BİTLİS - ADİLCEVAZ - Şehit Mehmet Ali Erçetin İlkokulu',
  'BİTLİS - ADİLCEVAZ - Harmantepe Köyü Nedim Korkut İlkokulu',
  'BİTLİS - ADİLCEVAZ - Bahçedere Köyü Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Atatürk Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Çanakyayla Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Kömürlü Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Kömürlü Köyü Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Kavuştuk Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Kavuştuk Köyü Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Harmantepe Köyü Nedim Korkut Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Mehmet Kamile Karahan İlkokulu',
  'BİTLİS - ADİLCEVAZ - Selçuklu İlkokulu',
  'BİTLİS - ADİLCEVAZ - Selçuklu Ortaokulu',
  'BİTLİS - ADİLCEVAZ - İnönü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Yukarı Süphan İlkokulu',
  'BİTLİS - ADİLCEVAZ - Yukarı Süphan Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Karşıyaka Köyü Ortaokulu',
  'BİTLİS - ADİLCEVAZ - İbrahim Karaoğlanoğlu Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Cumhuriyet Yatılı Bölge Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Şehit Mehmet Ali Erçetin Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Karşıyaka Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Hıdırşah Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Aşağı Süphan Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Aşağı Süphan İlkokulu',
  'BİTLİS - ADİLCEVAZ - Adilcevaz Süphan Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - ADİLCEVAZ - TOKİ Şehit Yusuf Sayan Ortaokulu',
  'BİTLİS - ADİLCEVAZ - TOKİ Şehit Yusuf Sayan İlkokulu',
  'BİTLİS - ADİLCEVAZ - Göldüzü Köyü Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Göldüzü Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Rabia Hatun Kız Anadolu İmam Hatip Lisesi',
  'BİTLİS - ADİLCEVAZ - Öğretmenevi ve Akşam Sanat Okulu',
  'BİTLİS - ADİLCEVAZ - Hasan Atlı İlkokulu',
  'BİTLİS - ADİLCEVAZ - Hasan Atlı Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Akçıra Köyü Gölbaşı Mezrası İlkokulu',
  'BİTLİS - ADİLCEVAZ - Şehit Kemal Dursun Anadolu İmam Hatip Lisesi',
  'BİTLİS - ADİLCEVAZ - Mehmet Kamile Karahan Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Akyazı Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Bahçedere Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Gümüşdöven Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Mollafadıl Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - ESENKIYI KÖYÜ İLKOKULU',
  'BİTLİS - ADİLCEVAZ - Aydınlar İmam Hatip Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Örentaş Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Erikbağı Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Yarımada Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Karaşeyh Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Aydınlar Budaklı Mahallesi İlkokulu',
  'BİTLİS - ADİLCEVAZ - Adilcevaz İlkokulu',
  'BİTLİS - ADİLCEVAZ - Adilcevaz Ortaokulu',
  'BİTLİS - ADİLCEVAZ - İlk Umut Anaokulu',
  'BİTLİS - ADİLCEVAZ - Karaşeyh Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Aydınlar Kışkılı Mahallesi İlkokulu',
  'BİTLİS - ADİLCEVAZ - Çanakyayla Köyü Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Şehit Alattin Bozarslan İlkokulu',
  'BİTLİS - ADİLCEVAZ - Bahçedere Köyü İmam Hatip Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Akçıra Köyü Gölbaşı Mezrası Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Cumhuriyet İmam Hatip Ortaokulu',
  'BİTLİS - ADİLCEVAZ - Şehit Polis Mahmut İkibeş Özel Eğitim Uygulama Okulu I. Kademe',
  'BİTLİS - ADİLCEVAZ - Şehit Polis Mahmut İkibeş Özel Eğitim Uygulama Okulu II. Kademe',
  'BİTLİS - ADİLCEVAZ - İbrahim Karaoğlanoğlu İmam Hatip Ortaokulu',
  'BİTLİS - ADİLCEVAZ - İpekçayır Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - Aydınlar Gültepe Mahallesi İlkokulu',
  'BİTLİS - ADİLCEVAZ - Gölüstü Köyü İlkokulu',
  'BİTLİS - ADİLCEVAZ - İnönü Anaokulu',
  'BİTLİS - ADİLCEVAZ - Şehit Mehmet Ali Erçetin Anaokulu',
  'BİTLİS - ADİLCEVAZ - Adilcevaz Özel Eğitim Anaokulu',
  'BİTLİS - AHLAT - Ahlat Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - AHLAT - Ergezen İlkokulu',
  'BİTLİS - AHLAT - Şehit Erdoğan Gökbulak Ortaokulu',
  'BİTLİS - AHLAT - Sadullah Gencer Anadolu Lisesi',
  'BİTLİS - AHLAT - Şehit Mesut Ardıç Anadolu İmam Hatip Lisesi',
  'BİTLİS - AHLAT - Şehit Erdoğan Gökbulak İlkokulu',
  'BİTLİS - AHLAT - Şehit Sümmani Görgen Yatılı Bölge Ortaokulu',
  'BİTLİS - AHLAT - Selçuklu Ortaokulu',
  'BİTLİS - AHLAT - Selçuklu İlkokulu',
  'BİTLİS - AHLAT - Güzelsu Ortaokulu',
  'BİTLİS - AHLAT - Yatılı Bölge Ortaokulu',
  'BİTLİS - AHLAT - Atatürk İlkokulu',
  'BİTLİS - AHLAT - Muzaffer İncesu Ortaokulu',
  'BİTLİS - AHLAT - Atatürk Ortaokulu',
  'BİTLİS - AHLAT - Yeni Köprü Ortaokulu',
  'BİTLİS - AHLAT - Taşharman Ortaokulu',
  'BİTLİS - AHLAT - Alakır İlkokulu',
  'BİTLİS - AHLAT - Ovakışla İMKB Yatılı Bölge Ortaokulu',
  'BİTLİS - AHLAT - Nazik İlkokulu',
  'BİTLİS - AHLAT - Ergezen Ortaokulu',
  'BİTLİS - AHLAT - Alakır Ortaokulu',
  'BİTLİS - AHLAT - Abdurrahmangazi İlkokulu',
  'BİTLİS - AHLAT - Ovakışla Cumhuriyet Ortaokulu',
  'BİTLİS - AHLAT - Ovakışla Cumhuriyet İlkokulu',
  'BİTLİS - AHLAT - Ovakışla Ortaokulu',
  'BİTLİS - AHLAT - Yunus Ensari Ortaokulu',
  'BİTLİS - AHLAT - Ahlat Halk Eğitimi Merkezi',
  'BİTLİS - AHLAT - Ertuğrul Gazi Ortaokulu',
  'BİTLİS - AHLAT - Fatih İlkokulu',
  'BİTLİS - AHLAT - Alpaslan Ortaokulu',
  'BİTLİS - AHLAT - Güzelsu İlkokulu',
  'BİTLİS - AHLAT - Seyrantepe İlkokulu',
  'BİTLİS - AHLAT - Ovakışla İlkokulu',
  'BİTLİS - AHLAT - Taşharman İlkokulu',
  'BİTLİS - AHLAT - Yeniköprü İlkokulu',
  'BİTLİS - AHLAT - OVAKIŞLA IMKB İLKOKULU',
  'BİTLİS - AHLAT - Ovakışla İmam Hatip Ortaokulu',
  'BİTLİS - AHLAT - Otluyazı Ortaokulu',
  'BİTLİS - AHLAT - Şehit Erdoğan Gökbulak Anaokulu',
  'BİTLİS - AHLAT - Kınalıkoç İlkokulu',
  'BİTLİS - AHLAT - Burcukaya İlkokulu',
  'BİTLİS - AHLAT - Erzen Hatun Kız Anadolu İmam Hatip Lisesi',
  'BİTLİS - AHLAT - Cemalettin İlkokulu',
  'BİTLİS - AHLAT - Saka İlkokulu',
  'BİTLİS - AHLAT - Dilburnu İlkokulu',
  'BİTLİS - AHLAT - Soğanlı İlkokulu',
  'BİTLİS - AHLAT - Şehit Murat SARIGÜL İmam Hatip Ortaokulu',
  'BİTLİS - AHLAT - Bayındır İlkokulu',
  'BİTLİS - AHLAT - Bayındır Ortaokulu',
  'BİTLİS - AHLAT - Kanuni İlkokulu',
  'BİTLİS - AHLAT - Ahlat Ergezen Anaokulu',
  'BİTLİS - AHLAT - Otluyazı İlkokulu',
  'BİTLİS - AHLAT - Vakıfbank İlkokulu',
  'BİTLİS - AHLAT - Gölgören İlkokulu',
  'BİTLİS - AHLAT - Yuvadamı İlkokulu',
  'BİTLİS - AHLAT - Ahlat Mesleki Eğitim Merkezi',
  'BİTLİS - AHLAT - Yoğurtyemez İlkokulu',
  'BİTLİS - AHLAT - Develik İlkokulu',
  'BİTLİS - AHLAT - Ahlat Selçuklu Öğretmenevi ve Akşam Sanat Okulu',
  'BİTLİS - AHLAT - Yunus Ensari İlkokulu',
  'BİTLİS - AHLAT - Kuşhane İlkokulu',
  'BİTLİS - AHLAT - Şehit Halit Topuz İlkokulu',
  'BİTLİS - AHLAT - Serinbayır İlkokulu',
  'BİTLİS - AHLAT - Akçaören İlkokulu',
  'BİTLİS - AHLAT - Ahlat Selçuklu Anadolu Lisesi',
  'BİTLİS - AHLAT - Bahçe İlkokulu',
  'BİTLİS - AHLAT - Tuğrul Bey İlkokulu',
  'BİTLİS - AHLAT - Ahlat Ovakışla Anaokulu',
  'BİTLİS - AHLAT - Çağrı Bey İlkokulu',
  'BİTLİS - AHLAT - Çağrı Bey Ortaokulu',
  'BİTLİS - AHLAT - Ahlat Saadet Ayber Özel Eğitim Uygulama Okulu I. Kademe',
  'BİTLİS - AHLAT - Ahlat Saadet Ayber Özel Eğitim Uygulama Okulu II. Kademe',
  'BİTLİS - AHLAT - Hayme Hatun Anaokulu',
  'BİTLİS - AHLAT - Şehit Eren Öztürk İlkokulu',
  'BİTLİS - AHLAT - Şehit Eren Öztürk Ortaokulu',
  'BİTLİS - AHLAT - Ahlat Bilim ve Sanat Merkezi',
  'BİTLİS - AHLAT - Çatalağzı Köyü İlkokulu',
  'BİTLİS - AHLAT - Çukurtarla Köyü İlkokulu',
  'BİTLİS - AHLAT - Ali Ayber Anadolu Lisesi',
  'BİTLİS - AHLAT - Yunus Ensari Anaokulu',
  'BİTLİS - AHLAT - Ovakışla Anadolu Lisesi',
  'BİTLİS - GÜROYMAK - Değirmenköy İlkokulu',
  'BİTLİS - GÜROYMAK - Gölbaşı Cumhuriyet Yatılı Bölge Ortaokulu',
  'BİTLİS - GÜROYMAK - Güroymak Anadolu Lisesi',
  'BİTLİS - GÜROYMAK - Güroymak Yatılı Bölge Ortaokulu',
  'BİTLİS - GÜROYMAK - İpekyolu Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - GÜROYMAK - Günkırı Ortaokulu',
  'BİTLİS - GÜROYMAK - Günkırı İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Borsa İstanbul Anadolu Lisesi',
  'BİTLİS - GÜROYMAK - Çallı Köyü İlkokulu',
  'BİTLİS - GÜROYMAK - Yunus Emre Ortaokulu',
  'BİTLİS - GÜROYMAK - Turgut Özal Ortaokulu',
  'BİTLİS - GÜROYMAK - Şehit Er Fevzi Güngür İlkokulu',
  'BİTLİS - GÜROYMAK - Şehit Er Fevzi Güngür Ortaokulu',
  'BİTLİS - GÜROYMAK - Fatih İlkokulu',
  'BİTLİS - GÜROYMAK - Yunus Emre İlkokulu',
  'BİTLİS - GÜROYMAK - Mehmet Akif Ortaokulu',
  'BİTLİS - GÜROYMAK - Mehmet Akif İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Selahaddin Eyyubi Anadolu İmam Hatip Lisesi',
  'BİTLİS - GÜROYMAK - Değirmenköyü Köşk Merzası İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Ortaokulu',
  'BİTLİS - GÜROYMAK - Atatürk Ortaokulu',
  'BİTLİS - GÜROYMAK - Güroymak İlkokulu',
  'BİTLİS - GÜROYMAK - Atatürk İlkokulu',
  'BİTLİS - GÜROYMAK - Gölbaşı Ortaokulu',
  'BİTLİS - GÜROYMAK - Yazıkonak İlkokulu',
  'BİTLİS - GÜROYMAK - Kazım Karabekir İlkokulu',
  'BİTLİS - GÜROYMAK - Kazım Karabekir Ortaokulu',
  'BİTLİS - GÜROYMAK - Saklı İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Mutlu Anaokulu',
  'BİTLİS - GÜROYMAK - Kavunlu İlkokulu',
  'BİTLİS - GÜROYMAK - Arpacık İlkokulu',
  'BİTLİS - GÜROYMAK - Yukarı Kolbaşı İlkokulu',
  'BİTLİS - GÜROYMAK - Yamaç Köyü Şehit Er Ethem Öztürk İlkokulu',
  'BİTLİS - GÜROYMAK - YAMAÇ KÖYÜ ŞEHIT ER ETHEM ÖZTÜRK ORTAOKULU',
  'BİTLİS - GÜROYMAK - Kaleli İlkokulu',
  'BİTLİS - GÜROYMAK - Taşüstü İlkokulu',
  'BİTLİS - GÜROYMAK - Gölbaşı İlkokulu',
  'BİTLİS - GÜROYMAK - Yayladere Mahallesi 23 Nisan İlkokulu',
  'BİTLİS - GÜROYMAK - Taşüstü Ortaokulu',
  'BİTLİS - GÜROYMAK - Fatih Ortaokulu',
  'BİTLİS - GÜROYMAK - Gölbaşı Anaokulu',
  'BİTLİS - GÜROYMAK - 100. Yıl İlkokulu',
  'BİTLİS - GÜROYMAK - 100. Yıl Ortaokulu',
  'BİTLİS - GÜROYMAK - Özkavak İlkokulu',
  'BİTLİS - GÜROYMAK - Tahtalı İlkokulu',
  'BİTLİS - GÜROYMAK - Güzelli Ortaokulu',
  'BİTLİS - GÜROYMAK - Güzelli İlkokulu',
  'BİTLİS - GÜROYMAK - Kekliktepe İlkokulu',
  'BİTLİS - GÜROYMAK - Gölbaşı Sıcaksu İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Halk Eğitimi Merkezi',
  'BİTLİS - GÜROYMAK - Oduncular İlkokulu',
  'BİTLİS - GÜROYMAK - Çıtak İlkokulu',
  'BİTLİS - GÜROYMAK - 19 Mayıs İlkokulu',
  'BİTLİS - GÜROYMAK - Şehit Piyade Uzman Çavuş Şahin ASLAN Ortaokulu',
  'BİTLİS - GÜROYMAK - Kuştaşı İlkokulu',
  'BİTLİS - GÜROYMAK - Turgut Özal İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Anaokulu',
  'BİTLİS - GÜROYMAK - Arpacık Köyü Konak Mezrası İlkokulu',
  'BİTLİS - GÜROYMAK - Çayarası Köyü Akbulut Mezrası İlkokulu',
  'BİTLİS - GÜROYMAK - Gedikpınar İlkokulu',
  'BİTLİS - GÜROYMAK - Yemişveren İlkokulu',
  'BİTLİS - GÜROYMAK - Öğretmenevi ve Akşam Sanat Okulu',
  'BİTLİS - GÜROYMAK - Şehit Er Mahfuz Urut İlkokulu',
  'BİTLİS - GÜROYMAK - Şehit Er Mahfuz Urut Ortaokulu',
  'BİTLİS - GÜROYMAK - Değirmenköy Ortaokulu',
  'BİTLİS - GÜROYMAK - Gedikpınar Köyü Keklik Tepe Mezrası İlkokulu',
  'BİTLİS - GÜROYMAK - Sütderesi İlkokulu',
  'BİTLİS - GÜROYMAK - Ahmet Mücteba Albayrak İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - GÜROYMAK - Günkırı Anaokulu',
  'BİTLİS - GÜROYMAK - Gölbaşı İmam Hatip Ortaokulu',
  'BİTLİS - GÜROYMAK - Gölbaşı Sevgili Öğretmenim Anaokulu',
  'BİTLİS - GÜROYMAK - Adnan Menderes İlkokulu',
  'BİTLİS - GÜROYMAK - Özkavak Köyü Ortaokulu',
  'BİTLİS - GÜROYMAK - Adnan Menderes Ortaokulu',
  'BİTLİS - GÜROYMAK - Yemişveren Köyü Ortaokulu',
  'BİTLİS - GÜROYMAK - Mevlana İlkokulu',
  'BİTLİS - GÜROYMAK - Akşemseddin İlkokulu',
  'BİTLİS - GÜROYMAK - DEĞİRMEN KÖYÜ ANAOKULU',
  'BİTLİS - GÜROYMAK - Günkırı İmam Hatip Ortaokulu',
  'BİTLİS - GÜROYMAK - Umut Anaokulu',
  'BİTLİS - GÜROYMAK - Oduncular Köyü Ortaokulu',
  'BİTLİS - GÜROYMAK - Çayarası İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Selahattin Rahime Dur Kiz Anadolu İmam Hatip Lisesi',
  'BİTLİS - GÜROYMAK - Şehit Piyade Uzman Çavuş Şahin ASLAN İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Mesleki Eğitim Merkezi',
  'BİTLİS - GÜROYMAK - Saklı Köyü Işıklı Mezrası İlkokulu',
  'BİTLİS - GÜROYMAK - Saklı Köyü Ortaokulu',
  'BİTLİS - GÜROYMAK - Güroymak İmam Hatip Ortaokulu',
  'BİTLİS - GÜROYMAK - Güroymak Salih Özmen Özel Eğitim Uygulama I. Kademe',
  'BİTLİS - GÜROYMAK - Güroymak Salih Özmen Özel Eğitim Uygulama II. Kademe',
  'BİTLİS - GÜROYMAK - Üzümveren Köyü İlkokulu',
  'BİTLİS - GÜROYMAK - Güroymak Salih Özmen Özel Eğitim Uygulama Okulu III. Kademe',
  'BİTLİS - GÜROYMAK - 19 Mayıs Ortaokulu',
  'BİTLİS - GÜROYMAK - Güroymak Özel Eğitim Anaokulu',
  'BİTLİS - GÜROYMAK - Güroymak Sevgi Anaokulu',
  'BİTLİS - HİZAN - Hizan Kadir Has Anadolu Lisesi',
  'BİTLİS - HİZAN - Yatılı Bölge Ortaokulu',
  'BİTLİS - HİZAN - Yunus Emre Anaokulu',
  'BİTLİS - HİZAN - Başkent Üniversitesi İlkokulu',
  'BİTLİS - HİZAN - Başkent Üniversitesi Ortaokulu',
  'BİTLİS - HİZAN - İstiklal Ortaokulu',
  'BİTLİS - HİZAN - Şht.Öğrt. A. Nafiz Özbağrıaçık Ortaokulu',
  'BİTLİS - HİZAN - Şht.Öğrt. A. Nafiz Özbağrıaçık İlkokulu',
  'BİTLİS - HİZAN - Sağınlı Kamran İnan Yatılı Bölge Ortaokulu',
  'BİTLİS - HİZAN - Hizan Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - HİZAN - Süttaşı Ortaokulu',
  'BİTLİS - HİZAN - Karasu Yatılı Bölge Ortaokulu',
  'BİTLİS - HİZAN - Nurs İlkokulu',
  'BİTLİS - HİZAN - Nurs Ortaokulu',
  'BİTLİS - HİZAN - Hizan 80. Yıl Anaokulu',
  'BİTLİS - HİZAN - Fatma Aliye Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - HİZAN - Süttaşı İlkokulu',
  'BİTLİS - HİZAN - Hizan Said Nursi Anadolu İmam Hatip Lisesi',
  'BİTLİS - HİZAN - Kolludere Ortaokulu',
  'BİTLİS - HİZAN - Cumhuriyet İlkokulu',
  'BİTLİS - HİZAN - Ballı Ortaokulu',
  'BİTLİS - HİZAN - 75.Yıl İMKB Abidin İnan Gaydalı Kız Yatılı Bölge Ortaokulu',
  'BİTLİS - HİZAN - Hizan Halk Eğitimi Merkezi',
  'BİTLİS - HİZAN - Döküktaş Köyü İlkokulu',
  'BİTLİS - HİZAN - Öğretmenevi ve Akşam Sanat Okulu',
  'BİTLİS - HİZAN - Kalkanlı Köyü İlkokulu',
  'BİTLİS - HİZAN - Aşağı Kazanlı İlkokulu',
  'BİTLİS - HİZAN - Koçyiğit Köyü İlkokulu',
  'BİTLİS - HİZAN - Yoğurtlu Köyü İlkokulu',
  'BİTLİS - HİZAN - Gayda Köyü Yolbaşı Mezrası İlkokulu',
  'BİTLİS - HİZAN - Yukarıçallı Köyü İlkokulu',
  'BİTLİS - HİZAN - Ürünveren Köyü Yapağı Mezrası İlkokulu',
  'BİTLİS - HİZAN - Kapısuyu Köyü Dibekli Mezrası İlkokulu',
  'BİTLİS - HİZAN - Kolludere İlkokulu',
  'BİTLİS - HİZAN - Tutumlu Köyü İlkokulu',
  'BİTLİS - HİZAN - Harmandöven Köyü İlkokulu',
  'BİTLİS - HİZAN - Akdik Köyü İlkokulu',
  'BİTLİS - HİZAN - Uzuntaş Köyü İlkokulu',
  'BİTLİS - HİZAN - Ağılözü İlkokulu',
  'BİTLİS - HİZAN - Sarıtaş Köyü İlkokulu',
  'BİTLİS - HİZAN - İçlikaval Köyü İlkokulu',
  'BİTLİS - HİZAN - Karbastı Köyü Avlak Mezrası İlkokulu',
  'BİTLİS - HİZAN - Akbıyık İlkokulu',
  'BİTLİS - HİZAN - Akçevre İlkokulu',
  'BİTLİS - HİZAN - Aladana İlkokulu',
  'BİTLİS - HİZAN - Ayrancı Mezrası İlkokulu',
  'BİTLİS - HİZAN - Bağbaşı Mezrası İlkokulu',
  'BİTLİS - HİZAN - Nuh Köyü İlkokulu',
  'BİTLİS - HİZAN - Ballıca Köyü İlkokulu',
  'BİTLİS - HİZAN - Bozpınar Köyü Ölçülü Mezrası İlkokulu',
  'BİTLİS - HİZAN - Çalışkanlar Köyü İlkokulu',
  'BİTLİS - HİZAN - Çatakdeğirmen Köyü Çavuşlu Mezrası İlkokulu',
  'BİTLİS - HİZAN - Çayır Köyü İlkokulu',
  'BİTLİS - HİZAN - Çevrecik Mezrası İlkokulu',
  'BİTLİS - HİZAN - Çökekyazı İlkokulu',
  'BİTLİS - HİZAN - Dayılar Köyü İlkokulu',
  'BİTLİS - HİZAN - Derince Köyü İlkokulu',
  'BİTLİS - HİZAN - Döküktaş Köyü Kayaş Mezrası İlkokulu',
  'BİTLİS - HİZAN - Döküktaş Köyü Topluca Mezrası İlkokulu',
  'BİTLİS - HİZAN - Durak Mezrası İlkokulu',
  'BİTLİS - HİZAN - Düztepe İlkokulu',
  'BİTLİS - HİZAN - Ekinli Köyü Deliklitaş Mezrası İlkokulu',
  'BİTLİS - HİZAN - Ekinli Köyü İlkokulu',
  'BİTLİS - HİZAN - Ekintepe Köyü İlkokulu',
  'BİTLİS - HİZAN - Elmacık Köyü Elmalı Mezrası İlkokulu',
  'BİTLİS - HİZAN - Gayda Köyü Bağışlı Mezrası İlkokulu',
  'BİTLİS - HİZAN - Gökay Köyü İlkokulu',
  'BİTLİS - HİZAN - Göktepe Köyü İlkokulu',
  'BİTLİS - HİZAN - Gönüllü Köyü İlkokulu',
  'BİTLİS - HİZAN - Görece Köyü İlkokulu',
  'BİTLİS - HİZAN - Göze Mezrası İlkokulu',
  'BİTLİS - HİZAN - Harmandöven Köyü Otlu Mezrası İlkokulu',
  'BİTLİS - HİZAN - Karaağaç Köyü İlkokulu',
  'BİTLİS - HİZAN - Karakoyun Mezrası İlkokulu',
  'BİTLİS - HİZAN - Karbastı Köyü İlkokulu',
  'BİTLİS - HİZAN - Keklik Köyü İlkokulu',
  'BİTLİS - HİZAN - Nurs Köyü Aşağı Ayvacık Mezrası İlkokulu',
  'BİTLİS - HİZAN - Kilimli Mezrası İlkokulu',
  'BİTLİS - HİZAN - Koçlu Köyü İlkokulu',
  'BİTLİS - HİZAN - Meydan Köyü İlkokulu',
  'BİTLİS - HİZAN - Ortaca Köyü İlkokulu',
  'BİTLİS - HİZAN - Oymapınar Köyü İlkokulu',
  'BİTLİS - HİZAN - Sağırkaya Köyü İlkokulu',
  'BİTLİS - HİZAN - Sarpkaya Köyü İlkokulu',
  'BİTLİS - HİZAN - Ürünveren Köyü Tuğlu Mezrası İlkokulu',
  'BİTLİS - HİZAN - Yamaç Mezrası İlkokulu',
  'BİTLİS - HİZAN - Yedikardeş İlkokulu',
  'BİTLİS - HİZAN - Yemişli İlkokulu',
  'BİTLİS - HİZAN - Yenicik Köyü İlkokulu',
  'BİTLİS - HİZAN - Yığınkaya Köyü İlkokulu',
  'BİTLİS - HİZAN - Yukarı Ayvacık Köyü İlkokulu',
  'BİTLİS - HİZAN - Gökçimen İlkokulu',
  'BİTLİS - HİZAN - Altınoluk İlkokulu',
  'BİTLİS - HİZAN - Gayda Köyü Receban Mezrası İlkokulu',
  'BİTLİS - HİZAN - Gökay Köyü Varkan Mezrası İlkokulu',
  'BİTLİS - HİZAN - YUKARIAYVACIK KÖYÜ YAYLALI MEZRASI İLKOKULU',
  'BİTLİS - HİZAN - Esenler Köyü Bayır Mezrası İlkokulu',
  'BİTLİS - HİZAN - Horozdere Ortaokulu',
  'BİTLİS - HİZAN - Horozdere İlkokulu',
  'BİTLİS - HİZAN - Kapısuyu Köyü İlkokulu',
  'BİTLİS - HİZAN - Hizan Merkez Ortaokulu',
  'BİTLİS - HİZAN - Altınoluk-Gökçimen Ortaokulu',
  'BİTLİS - HİZAN - Çatakdeğirmen Köyü İlkokulu',
  'BİTLİS - HİZAN - Ürünveren Köyü Mehmetçik İlkokulu',
  'BİTLİS - HİZAN - Erencik Köyü İlkokulu',
  'BİTLİS - HİZAN - SAĞINLI KÖYÜ İLKOKULU',
  'BİTLİS - HİZAN - Gavsı Hizan İlkokulu',
  'BİTLİS - HİZAN - Hacı Mehmet Köyü İlkokulu',
  'BİTLİS - HİZAN - Abidin İnan Gaydalı İmam Hatip Ortaokulu',
  'BİTLİS - HİZAN - Mehmet Akif Ersoy Ortaokulu',
  'BİTLİS - HİZAN - Mehmet Akif Ersoy İlkokulu',
  'BİTLİS - HİZAN - Sağınlı Kamran İnan İmam Hatip Ortaokulu',
  'BİTLİS - HİZAN - Yeşilova İmam Hatip Ortaokulu',
  'BİTLİS - HİZAN - Hizan Kız Anadolu İmam Hatip Lisesi',
  'BİTLİS - HİZAN - Bahçelievler İmam Hatip Ortaokulu',
  'BİTLİS - HİZAN - Koyunlu Mezrası İlkokulu',
  'BİTLİS - HİZAN - Ballı İlkokulu',
  'BİTLİS - HİZAN - Budaklı Köyü İlkokulu',
  'BİTLİS - HİZAN - Sarpkaya Köyü Mut Mezrası İlkokulu',
  'BİTLİS - HİZAN - 75. YIL ABİDİN İNAN GAYDALI İLKOKULU',
  'BİTLİS - HİZAN - HİZAN İLKOKULU',
  'BİTLİS - HİZAN - Çökekyazı Ortaokulu',
  'BİTLİS - HİZAN - Kalkanlı Köyü Ortaokulu',
  'BİTLİS - HİZAN - Hizan İmam Hatip Ortaokulu',
  'BİTLİS - HİZAN - Hizan Kız Anadolu Lisesi',
  'BİTLİS - HİZAN - Bölüklü Köyü İlkokulu',
  'BİTLİS - HİZAN - Sağırkaya Köyü Akçakonak Mezrası İlkokulu',
  'BİTLİS - HİZAN - Güvendik Mezrası İlkokulu',
  'BİTLİS - HİZAN - Bozpınar Köyü İlkokulu',
  'BİTLİS - HİZAN - Samanyolu Mezrası İlkokulu',
  'BİTLİS - HİZAN - Çayırlı Mezrası İlkokulu',
  'BİTLİS - HİZAN - Dağören Köyü İlkokulu',
  'BİTLİS - HİZAN - Elmacık Köyü İlkokulu',
  'BİTLİS - HİZAN - Ağaçlı Köyü İlkokulu',
  'BİTLİS - HİZAN - Yazmalı Mezrası İlkokulu',
  'BİTLİS - HİZAN - Karlıtepe Köyü İlkokulu',
  'BİTLİS - HİZAN - Alancık Mezrası İlkokulu',
  'BİTLİS - HİZAN - Nurs Köyü Yukarı Şenlik Mezrası İlkokulu',
  'BİTLİS - HİZAN - Sarıtaş Köyü Özenli Mezrası İlkokulu',
  'BİTLİS - HİZAN - Yığınkaya Köyü Kardeşlik İlkokulu',
  'BİTLİS - HİZAN - Klavuz Mezrası İlkokulu',
  'BİTLİS - HİZAN - Soğuksu Köyü İlkokulu',
  'BİTLİS - HİZAN - Sürücüler Köyü İlkokulu',
  'BİTLİS - HİZAN - Karbastı Köyü Taş Mezrası İlkokulu',
  'BİTLİS - HİZAN - Esenler Köyü İlkokulu',
  'BİTLİS - HİZAN - Karbastı Köyü Koç Mezrası İlkokulu',
  'BİTLİS - HİZAN - Esenler Köyü Otluca Mezrası İlkokulu',
  'BİTLİS - HİZAN - Ballıca Köyü Yukarıaksüt Mezrası İlkokulu',
  'BİTLİS - HİZAN - Horoz Dere Köyü Akbaş Mezrası İlkokulu',
  'BİTLİS - HİZAN - Hizan Özel Eğitim Anaokulu',
  'BİTLİS - MERKEZ - 100. Yıl Atatürk Ortaokulu',
  'BİTLİS - MERKEZ - 13 Kasım Atatürk Anaokulu',
  'BİTLİS - MERKEZ - Bitlis Anadolu Lisesi',
  'BİTLİS - MERKEZ - Bitlis Güzeldere Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - MERKEZ - Bitlis Cemil Özgür Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - MERKEZ - Ziya Eren Spor Lisesi',
  'BİTLİS - MERKEZ - Bitlis Lisesi',
  'BİTLİS - MERKEZ - Bitlis Mesleki Eğitim Merkezi',
  'BİTLİS - MERKEZ - Bitlis Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - MERKEZ - Hikmet Kiler Fen Lisesi',
  'BİTLİS - MERKEZ - Kazımpaşa İlkokulu',
  'BİTLİS - MERKEZ - Mustafa Kemal Atatürk İlkokulu',
  'BİTLİS - MERKEZ - Narlıdere Yatılı Bölge Ortaokulu',
  'BİTLİS - MERKEZ - Bitlis Necibe Gencer Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - MERKEZ - Servan Ölekli Anaokulu',
  'BİTLİS - MERKEZ - Şems-i Bitlis İlkokulu',
  'BİTLİS - MERKEZ - Merkez Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - MERKEZ - Yolalan Şeh.Jan.Üst Çavuş Kaan Şen Yatılı Bölge Ortaokulu',
  'BİTLİS - MERKEZ - Zübeyde Hanım Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - MERKEZ - Dideban Ortaokulu',
  'BİTLİS - MERKEZ - 75.Yıl Anaokulu',
  'BİTLİS - MERKEZ - Muştakbaba Ortaokulu',
  'BİTLİS - MERKEZ - Zübeyde Hanım İlkokulu',
  'BİTLİS - MERKEZ - Merkez Yatılı Bölge Ortaokulu',
  'BİTLİS - MERKEZ - Selahaddin Eyyubi Ortaokulu',
  'BİTLİS - MERKEZ - Kireçtaşı Köyü Ortaokulu',
  'BİTLİS - MERKEZ - Kireçtaşı Köyü İlkokulu',
  'BİTLİS - MERKEZ - Türkiye Odalar ve Borsalar Birliği İlkokulu',
  'BİTLİS - MERKEZ - Karbastı Köyü Doğanlı Mezrası İlkokulu',
  'BİTLİS - MERKEZ - İdris-i Bitlis İlkokulu',
  'BİTLİS - MERKEZ - Kurtuluş Özgür Kaya Taşdelen Ortaokulu',
  'BİTLİS - MERKEZ - Şehit Alpaslan KURT İlkokulu',
  'BİTLİS - MERKEZ - Bitlis Ahmet Eren Bilim ve Sanat Merkezi',
  'BİTLİS - MERKEZ - Muştakbaba İlkokulu',
  'BİTLİS - MERKEZ - Konaç Köyü İlkokulu',
  'BİTLİS - MERKEZ - Şehit Öğretmen Ergin Komut İlkokulu',
  'BİTLİS - MERKEZ - Hüsrevpaşa Ortaokulu',
  'BİTLİS - MERKEZ - Şehit Hüsamettin Kandemir Ortaokulu',
  'BİTLİS - MERKEZ - Ahmet Eren Özel Eğitim Uygulama Okulu III. Kademe',
  'BİTLİS - MERKEZ - Ahmet Eren Özel Eğitim Uygulama Okulu I. Kademe',
  'BİTLİS - MERKEZ - MNG Kargo İlkokulu',
  'BİTLİS - MERKEZ - Şükri Bitlisi Ortaokulu',
  'BİTLİS - MERKEZ - TOKİ Ahmet Eren İlkokulu',
  'BİTLİS - MERKEZ - Polis Amca İlkokulu',
  'BİTLİS - MERKEZ - Polis Amca Ortaokulu',
  'BİTLİS - MERKEZ - Yükseliş İlkokulu',
  'BİTLİS - MERKEZ - Yükseliş Ortaokulu',
  'BİTLİS - MERKEZ - 8 Ağustos Ortaokulu',
  'BİTLİS - MERKEZ - Bölükyazı Tekel Edip Safder Gaydalı Yatılı Bölge Ortaokulu',
  'BİTLİS - MERKEZ - 75. Yıl Cumhuriyet İlkokulu',
  'BİTLİS - MERKEZ - 75. Yıl Cumhuriyet Ortaokulu',
  'BİTLİS - MERKEZ - Bitlis Beş Minare Anadolu Lisesi',
  'BİTLİS - MERKEZ - Bitlis Said Nursi Anadolu İmam Hatip Lisesi',
  'BİTLİS - MERKEZ - Düzköy İlkokulu',
  'BİTLİS - MERKEZ - Yolalan Yeni Mahalle İlkokulu',
  'BİTLİS - MERKEZ - Yolalan Beldesi Kale Mahallesi İlkokulu',
  'BİTLİS - MERKEZ - Bitlis Vilayetler Birliği Anaokulu',
  'BİTLİS - MERKEZ - Hatuniye Kız Anadolu İmam Hatip Lisesi',
  'BİTLİS - MERKEZ - Bitlis Halk Eğitimi Merkezi',
  'BİTLİS - MERKEZ - Oya Havare İlkokulu',
  'BİTLİS - MERKEZ - Saray Ortaokulu',
  'BİTLİS - MERKEZ - Saray İlkokulu',
  'BİTLİS - MERKEZ - Şehit Tahsin Barutçu Anadolu Lisesi',
  'BİTLİS - MERKEZ - İÇGEÇİT KÖYÜ İLKOKULU',
  'BİTLİS - MERKEZ - BİTLİS REHBERLİK VE ARAŞTIRMA MERKEZİ',
  'BİTLİS - MERKEZ - DEĞİRMENALTI KÖYÜ ORTAOKULU',
  'BİTLİS - MERKEZ - TABANÖZÜ KÖYÜ İLKOKULU',
  'BİTLİS - MERKEZ - Gökmeydan İlkokulu',
  'BİTLİS - MERKEZ - Koruk Köyü İlkokulu',
  'BİTLİS - MERKEZ - Fatih İlkokulu',
  'BİTLİS - MERKEZ - Fatih Ortaokulu',
  'BİTLİS - MERKEZ - YEŞİLSIRT KÖYÜ İLKOKULU',
  'BİTLİS - MERKEZ - Mustafa Kemal Atatürk Ortaokulu',
  'BİTLİS - MERKEZ - TOKİ Ortaokulu',
  'BİTLİS - MERKEZ - Nurullah Eren Anadolu Lisesi',
  'BİTLİS - MERKEZ - Bölükyazı Köyü İlkokulu',
  'BİTLİS - MERKEZ - ÖĞRETMENEVİ VE AKŞAM SANAT OKULU',
  'BİTLİS - MERKEZ - Aşağıkaraboy Köyü İlkokulu',
  'BİTLİS - MERKEZ - Konuksayar Köyü İlkokulu',
  'BİTLİS - MERKEZ - Necip Fazıl Kısakürek Ortaokulu',
  'BİTLİS - MERKEZ - Ziya Eren Güzel Sanatlar Lisesi',
  'BİTLİS - MERKEZ - İHLASİYE ANADOLU İMAM HATİP LİSESİ',
  'BİTLİS - MERKEZ - Necip Fazıl Kısakürek İlkokulu',
  'BİTLİS - MERKEZ - Seyyid İbrahim İmam Hatip Ortaokulu',
  'BİTLİS - MERKEZ - Şehit Mahir AYABAK İlkokulu',
  'BİTLİS - MERKEZ - Şehit Mahir AYABAK Ortaokulu',
  'BİTLİS - MERKEZ - Narlıdere Köyü İlkokulu',
  'BİTLİS - MERKEZ - 8 Ağustos Şehit Metin Özdemir İlkokulu',
  'BİTLİS - MERKEZ - Adnan Menderes Ortaokulu',
  'BİTLİS - MERKEZ - Değirmenaltı Köyü İlkokulu',
  'BİTLİS - MERKEZ - Arıdağ Köyü Ortaokulu',
  'BİTLİS - MERKEZ - Arıdağı Köyü Şehit Sedat Aktaş İlkokulu',
  'BİTLİS - MERKEZ - YOLYAZI KÖYÜ İLKOKULU',
  'BİTLİS - MERKEZ - Yolalan Köyü Çınarbaşı Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Feyzullah Ensari İmam Hatip Ortaokulu',
  'BİTLİS - MERKEZ - Başhan Köyü İlkokulu',
  'BİTLİS - MERKEZ - Tanrıyar Köyü İlkokulu',
  'BİTLİS - MERKEZ - Bitlis İmam Hatip Ortaokulu',
  'BİTLİS - MERKEZ - Toki Rahva Anaokulu',
  'BİTLİS - MERKEZ - Şehit Mahir AYABAK İmam Hatip Ortaokulu',
  'BİTLİS - MERKEZ - Doğruyol Köyü İlkokulu',
  'BİTLİS - MERKEZ - Çeltikli Şehit Nadir İpek İlkokulu',
  'BİTLİS - MERKEZ - Keklikdüzü Köyü İlkokulu',
  'BİTLİS - MERKEZ - Üçkardeş Köyü Nadir Ertan Uygun İlkokulu',
  'BİTLİS - MERKEZ - TINAR KÖYÜ İLKOKULU',
  'BİTLİS - MERKEZ - Alaniçi Köyü Yenice Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Alaniçi Köyü İlkokulu',
  'BİTLİS - MERKEZ - Dörtağaç Köyü İlkokulu',
  'BİTLİS - MERKEZ - Yolalan Köyü İlkokulu',
  'BİTLİS - MERKEZ - İçmeli Köyü İlkokulu',
  'BİTLİS - MERKEZ - Başmaklı Köyü İlkokulu',
  'BİTLİS - MERKEZ - Küllüce Köyü İlkokulu',
  'BİTLİS - MERKEZ - Tabanözü Köyü Akçalı Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Dereağzı Köyü İlkokulu',
  'BİTLİS - MERKEZ - Yolcular Köyü Samanlı Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Cumhuriyet Köyü İlkokulu',
  'BİTLİS - MERKEZ - Yalnızçamlar Köyü İlkokulu',
  'BİTLİS - MERKEZ - Ahmet Eren Özel Eğitim Uygulama Okulu II. Kademe',
  'BİTLİS - MERKEZ - Yukarı Başhan Köyü İlkokulu',
  'BİTLİS - MERKEZ - Boztepe Köyü İlkokulu',
  'BİTLİS - MERKEZ - Kokarsu Köyü İlkokulu',
  'BİTLİS - MERKEZ - Kömüryakan Köyü Aşağı Mahalle İlkokulu',
  'BİTLİS - MERKEZ - Yumurtatepe Köyü İlkokulu',
  'BİTLİS - MERKEZ - Yukarıkaraboy Köyü İlkokulu',
  'BİTLİS - MERKEZ - Çalıdüzü Köyü Yavuzlar Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Yolcular Köyü İlkokulu',
  'BİTLİS - MERKEZ - Dereağzı Köyü Kavakdibi Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Karınca Köyü İlkokulu',
  'BİTLİS - MERKEZ - Sarıkonak Köyü İlkokulu',
  'BİTLİS - MERKEZ - Geçitbaşı Köyü Kapalı Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Yaygın Köyü İlkokulu',
  'BİTLİS - MERKEZ - Doğruyol Köyü Çadırlı Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Ahmet Eren Özel Eğitim Meslek Okulu',
  'BİTLİS - MERKEZ - Merkez İmam Hatip Ortaokulu',
  'BİTLİS - MERKEZ - Bitlis Özel Eğitim Anaokulu',
  'BİTLİS - MERKEZ - Beş Minare Anaokulu',
  'BİTLİS - MERKEZ - Kömüryakan Köyü Yukarı Mahalle İlkokulu',
  'BİTLİS - MERKEZ - Şehit Mahir Ayabak Anaokulu',
  'BİTLİS - MERKEZ - Bayramalan Köyü İlkokulu',
  'BİTLİS - MERKEZ - Kayabaşı Köyü İlkokulu',
  'BİTLİS - MERKEZ - Yolcular Köyü Ören Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Deliktaş Köyü İlkokulu',
  'BİTLİS - MERKEZ - Keklikdüzü Köyü Kuşlu Mezrası İlkokulu',
  'BİTLİS - MERKEZ - Yolalan İmam Hatip Ortaokulu',
  'BİTLİS - MERKEZ - Ahmet Eren Bilim ve Sanat Merkezi Anaokulu',
  'BİTLİS - MERKEZ - Hasan Banuki İmam Hatip Ortaokulu',
  'BİTLİS - MERKEZ - Abdülhamid Han İmam Hatip Ortaokulu',
  'BİTLİS - MERKEZ - Kurubulak Anaokulu',
  'BİTLİS - MERKEZ - Hüsrevpaşa Anaokulu',
  'BİTLİS - MUTKİ - Mutki Halk Eğitimi Merkezi',
  'BİTLİS - MUTKİ - İkizler Cumhuriyet Yatılı Bölge Ortaokulu',
  'BİTLİS - MUTKİ - Yatılı Bölge Ortaokulu',
  'BİTLİS - MUTKİ - Çitliyol Köyü İlkokulu',
  'BİTLİS - MUTKİ - Uran Şehit Piyade Er Bayram KARDAŞ İlkokulu',
  'BİTLİS - MUTKİ - Yazıcık İlkokulu',
  'BİTLİS - MUTKİ - Üçadım Köyü İlkokulu',
  'BİTLİS - MUTKİ - Çığır İlkokulu',
  'BİTLİS - MUTKİ - Açıkalan İlkokulu',
  'BİTLİS - MUTKİ - Kavakbaşı Yatılı Bölge Ortaokulu',
  'BİTLİS - MUTKİ - Dereyolu İlkokulu',
  'BİTLİS - MUTKİ - Kavakbaşı Anaokulu',
  'BİTLİS - MUTKİ - Erler Yatılı Bölge Ortaokulu',
  'BİTLİS - MUTKİ - Atatürk Ortaokulu',
  'BİTLİS - MUTKİ - Yalıntaş Köyü İlkokulu',
  'BİTLİS - MUTKİ - Yenidoğan Köyü İlkokulu',
  'BİTLİS - MUTKİ - Mutki Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - MUTKİ - Kayabaşı Köyü İlkokulu',
  'BİTLİS - MUTKİ - Yuvalıdam İlkokulu',
  'BİTLİS - MUTKİ - Yanıkçakır İlkokulu',
  'BİTLİS - MUTKİ - Çiğdemalan İlkokulu',
  'BİTLİS - MUTKİ - Çatalsöğüt Köyü İlkokulu',
  'BİTLİS - MUTKİ - Mutki Anadolu Lisesi',
  'BİTLİS - MUTKİ - Beşevler Köyü İlkokulu',
  'BİTLİS - MUTKİ - Akçaağaç Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Atatürk İlkokulu',
  'BİTLİS - MUTKİ - Kuşdili Köyü İlkokulu',
  'BİTLİS - MUTKİ - Küllüce Köyü İlkokulu',
  'BİTLİS - MUTKİ - Uğur Köyü İlkokulu',
  'BİTLİS - MUTKİ - İkizler Köyü İlkokulu',
  'BİTLİS - MUTKİ - Kovanlı Köyü İlkokulu',
  'BİTLİS - MUTKİ - Dağarcık Köyü İlkokulu',
  'BİTLİS - MUTKİ - Mutki Anaokulu',
  'BİTLİS - MUTKİ - Mutki Anadolu İmam Hatip Lisesi',
  'BİTLİS - MUTKİ - Taşboğaz Köyü İlkokulu',
  'BİTLİS - MUTKİ - Ekizler Köyü Ortaokulu',
  'BİTLİS - MUTKİ - Şehit Mehmet Emin Sözügüzel Ortaokulu',
  'BİTLİS - MUTKİ - Boğazönü İlkokulu',
  'BİTLİS - MUTKİ - Boğazönü Ortaokulu',
  'BİTLİS - MUTKİ - ESENYURT MEZRASI İLKOKULU',
  'BİTLİS - MUTKİ - Kocainiş Köyü İlkokulu',
  'BİTLİS - MUTKİ - Mutki Öğretmenevi ve Akşam Sanat Okulu',
  'BİTLİS - MUTKİ - Koyunlu Şehit Piyade Er Yener Barış İlkokulu',
  'BİTLİS - MUTKİ - Kavakbaşı İlkokulu',
  'BİTLİS - MUTKİ - Kayran İlkokulu',
  'BİTLİS - MUTKİ - Arpalıseki Köyü İlkokulu',
  'BİTLİS - MUTKİ - Ulaş Köyü İlkokulu',
  'BİTLİS - MUTKİ - Salman Köyü İlkokulu',
  'BİTLİS - MUTKİ - Salman Köyü Ortaokulu',
  'BİTLİS - MUTKİ - Sekiliyazı İlkokulu',
  'BİTLİS - MUTKİ - ÇATALERİK KÖYÜ İLKOKULU',
  'BİTLİS - MUTKİ - Ölçülü Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Yalıntaş Köyü Zorova Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Kayran Köyü Köprübaşı Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Dağlık Köyü İlkokulu',
  'BİTLİS - MUTKİ - BOZBURUN KÖYÜ SERİNCE MEZRASI İLKOKULU',
  'BİTLİS - MUTKİ - Akpınar Köyü İlkokulu',
  'BİTLİS - MUTKİ - Alkoyun Köyü İlkokulu',
  'BİTLİS - MUTKİ - Göztepe Köyü İlkokulu',
  'BİTLİS - MUTKİ - Çığır Köyü Şehit Ahmet Tuncel İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Uran Köyü Şehit Piyade Er Bayram Kardaş İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Mutki İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Açıkalan Köyü İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Dereyolu Köyü Şehit Şentürk Uslu İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Çitliyol Köyü İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Dağlık Köyü İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Koyunlu Köyü İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Yalıntaş Köyü İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Bağarası Köyü Cevizli Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Kayabaşı Köyü İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Yuvalıdam Köyü İmam hatip Ortaokulu',
  'BİTLİS - MUTKİ - Yanıkçakır Köyü İmam Hatip Ortaokulu',
  'BİTLİS - MUTKİ - Zeydan İlkokulu',
  'BİTLİS - MUTKİ - Bağarası İlkokulu',
  'BİTLİS - MUTKİ - Geyikpınar Köyü Ortaokulu',
  'BİTLİS - MUTKİ - Ekizler Köyü İlkokulu',
  'BİTLİS - MUTKİ - Karabudak Köyü İlkokulu',
  'BİTLİS - MUTKİ - Alıcık Köyü İlkokulu',
  'BİTLİS - MUTKİ - Arpalıseki Köyü Çimenli Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Çukurca Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Çayırlı Köyü İlkokulu',
  'BİTLİS - MUTKİ - Çığır Köyü Ocaklı Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Güvenli Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Özen Köyü İlkokulu',
  'BİTLİS - MUTKİ - Geyikpınar Köyü İlkokulu',
  'BİTLİS - MUTKİ - Oluklu Köyü İlkokulu',
  'BİTLİS - MUTKİ - Taşyol İlkokulu',
  'BİTLİS - MUTKİ - Tolgalı İlkokulu',
  'BİTLİS - MUTKİ - Arpalıseki Köyü Yüksekova Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Ballı Köyü İlkokulu',
  'BİTLİS - MUTKİ - Akıncı Köyü İlkokulu',
  'BİTLİS - MUTKİ - Küllüce Köyü Ortaokulu',
  'BİTLİS - MUTKİ - ikizler Köyü Balkaya Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Göztepe Köyü Abakay Mezrası İlkokulu',
  'BİTLİS - MUTKİ - ERLER İLKOKULU',
  'BİTLİS - MUTKİ - Bağarası Köyü Yalçınkaya Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Meydan Köyü İlkokulu',
  'BİTLİS - MUTKİ - Gümüşkanat Köyü İlkokulu',
  'BİTLİS - MUTKİ - Kapaklı İlkokulu',
  'BİTLİS - MUTKİ - Havarik Köyü İlkokulu',
  'BİTLİS - MUTKİ - Kavakbaşı Ozanlı İlkokulu',
  'BİTLİS - MUTKİ - OLUKLU KÖYÜ YEŞİLCE MEZRASI İLKOKULU',
  'BİTLİS - MUTKİ - Kaşak İlkokulu',
  'BİTLİS - MUTKİ - Alkoyun Köyü Hopir Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Yenidoğan Köyü Ortaokulu',
  'BİTLİS - MUTKİ - Mutki Meydan Ortaokulu',
  'BİTLİS - MUTKİ - Kavakbaşı Anadolu Lisesi',
  'BİTLİS - MUTKİ - Kocainiş Köyü Onbaşı Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Göztepe Köyü Cevizli Mezrası İlkokulu',
  'BİTLİS - MUTKİ - Kaşıklı Köyü İlkokulu',
  'BİTLİS - MUTKİ - Bozburun Köyü Şehit Cahit Çelik Ortaokulu',
  'BİTLİS - MUTKİ - Sarıçiçek Köyü İlkokulu',
  'BİTLİS - MUTKİ - Bozburun Köyü İlkokulu',
  'BİTLİS - TATVAN - Sadullah Gencer Sosyal Bilimler Lisesi',
  'BİTLİS - TATVAN - Tatvan Atatürk Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - TATVAN - Cumhuriyet İlkokulu',
  'BİTLİS - TATVAN - Cumhuriyet Ortaokulu',
  'BİTLİS - TATVAN - Fatih İlkokulu',
  'BİTLİS - TATVAN - Fatih Ortaokulu',
  'BİTLİS - TATVAN - Tatvan Halk Eğitimi Merkezi',
  'BİTLİS - TATVAN - Hüseyin Çelik Anadolu Lisesi',
  'BİTLİS - TATVAN - Saadettin AKA Ortaokulu',
  'BİTLİS - TATVAN - Karşıyaka İlkokulu',
  'BİTLİS - TATVAN - Karşıyaka Ortaokulu',
  'BİTLİS - TATVAN - Kıyıdüzü Köyü İlkokulu',
  'BİTLİS - TATVAN - Tatvan Rehberlik ve Araştırma Merkezi',
  'BİTLİS - TATVAN - Tatvan Anadolu Lisesi',
  'BİTLİS - TATVAN - Tatvan Fen Lisesi',
  'BİTLİS - TATVAN - Tatvan İMKB Ortaokulu',
  'BİTLİS - TATVAN - Tatvan İMKB Yatılı Bölge Ortaokulu',
  'BİTLİS - TATVAN - Benekli Köyü İlkokulu',
  'BİTLİS - TATVAN - Benekli Köyü Ortaokulu',
  'BİTLİS - TATVAN - Tatvan Van Gölü Ortaokulu',
  'BİTLİS - TATVAN - Tatvan Van Gölü İlkokulu',
  'BİTLİS - TATVAN - Yelkenli İlkokulu',
  'BİTLİS - TATVAN - Selahaddin Eyyubi Ortaokulu',
  'BİTLİS - TATVAN - Tuğ Ortaokulu',
  'BİTLİS - TATVAN - Mehmetçik İlkokulu',
  'BİTLİS - TATVAN - 75.Yıl İMKB Jnd.Çav.Sedat Köroğlu Yatılı Bölge Ortaokulu',
  'BİTLİS - TATVAN - Tatvan Seydi Ali Reis Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - TATVAN - Şehit Öğr.Bayram Yasemin Tekin İlkokulu',
  'BİTLİS - TATVAN - Çekmece Ortaokulu',
  'BİTLİS - TATVAN - Bahçelievler İlkokulu',
  'BİTLİS - TATVAN - Bahçelievler Ortaokulu',
  'BİTLİS - TATVAN - İstasyon İlkokulu',
  'BİTLİS - TATVAN - Kıyıdüzü Köyü Ortaokulu',
  'BİTLİS - TATVAN - Öğretmenevi ve Akşam Sanat Okulu',
  'BİTLİS - TATVAN - Vakıfbank İlkokulu',
  'BİTLİS - TATVAN - Mehmet Akif Ersoy Ortaokulu',
  'BİTLİS - TATVAN - Tatvan Şehit Mehmet Ali Kılıç Anadolu İmam Hatip Lisesi',
  'BİTLİS - TATVAN - Tatvan İMKB İlkokulu',
  'BİTLİS - TATVAN - Tatvan Sarıkum Köyü İlkokulu',
  'BİTLİS - TATVAN - Tatvan Sarıkum Köyü Ortaokulu',
  'BİTLİS - TATVAN - Tatvan Valide Sultan Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - TATVAN - Tatvan Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - TATVAN - Milli Hakimiyet İlkokulu',
  'BİTLİS - TATVAN - Kırkbulak Şehitler Ortaokulu',
  'BİTLİS - TATVAN - Göllü Köyü Ortaokulu',
  'BİTLİS - TATVAN - Göllü Köyü İlkokulu',
  'BİTLİS - TATVAN - Tatvan Özel Eğitim Uygulama Okulu II. Kademe',
  'BİTLİS - TATVAN - Mehmet Zeki Peker İlkokulu',
  'BİTLİS - TATVAN - TOKİ Prof. Dr. Fuat Sezgin Anadolu Lisesi',
  'BİTLİS - TATVAN - Tatvan Cumhuriyet Anaokulu',
  'BİTLİS - TATVAN - Çağlayan İlkokulu',
  'BİTLİS - TATVAN - Çağlayan Ortaokulu',
  'BİTLİS - TATVAN - Hüsnü M. Özyeğin Vakfı-Deniz Süren Ortaokulu',
  'BİTLİS - TATVAN - İlk Adım Anaokulu',
  'BİTLİS - TATVAN - Ahmet Mücteba Albayrak Ortaokulu',
  'BİTLİS - TATVAN - Yumurtatepe İlkokulu',
  'BİTLİS - TATVAN - Tatvan Küçüksu Köyü Vali Uğur BORAN Ortaokulu',
  'BİTLİS - TATVAN - Tatvan Anaokulu',
  'BİTLİS - TATVAN - Uluer İlkokulu',
  'BİTLİS - TATVAN - Yoncabaşı Ortaokulu',
  'BİTLİS - TATVAN - Yoncabaşı İlkokulu',
  'BİTLİS - TATVAN - Örenlik İlkokulu',
  'BİTLİS - TATVAN - Alacabük Ortaokulu',
  'BİTLİS - TATVAN - Alacabük İlkokulu',
  'BİTLİS - TATVAN - Beştaş Mezrası İlkokulu',
  'BİTLİS - TATVAN - Dumlupınar Ortaokulu',
  'BİTLİS - TATVAN - Suffe İlkokulu',
  'BİTLİS - TATVAN - Dumlupınar İlkokulu',
  'BİTLİS - TATVAN - Said-i Nursi İlkokulu',
  'BİTLİS - TATVAN - Tatvan Şehit Ömer Halisdemir İmam Hatip Ortaokulu',
  'BİTLİS - TATVAN - Kırkbulak Şehitler İlkokulu',
  'BİTLİS - TATVAN - Fatih Anaokulu',
  'BİTLİS - TATVAN - Tatvan Sarıkum Köyü Hayrettin Sancar Ortaokulu',
  'BİTLİS - TATVAN - Tatvan Sarıkum Köyü Hayrettin Sancar İlkokulu',
  'BİTLİS - TATVAN - Faki Teyran Anaokulu',
  'BİTLİS - TATVAN - Güntepe Köyü Ahmed-i Hani İlkokulu',
  'BİTLİS - TATVAN - Sahil Anaokulu',
  'BİTLİS - TATVAN - Mehmet Akif Ersoy İlkokulu',
  'BİTLİS - TATVAN - Zeki Ergezen İlkokulu',
  'BİTLİS - TATVAN - Çanakdüzü Köyü Ortaokulu',
  'BİTLİS - TATVAN - Tatvan Prof. Dr. Necmettin Erbakan İmam Hatip Ortaokulu',
  'BİTLİS - TATVAN - Yunus Emre Anaokulu',
  'BİTLİS - TATVAN - Sultan Alparslan İmam Hatip Ortaokulu',
  'BİTLİS - TATVAN - Selahaddin Eyyubi İlkokulu',
  'BİTLİS - TATVAN - Tatvan Mesleki Eğitim Merkezi',
  'BİTLİS - TATVAN - Tatvan Kız Anadolu İmam Hatip Lisesi',
  'BİTLİS - TATVAN - Bahçelievler Anaokulu',
  'BİTLİS - TATVAN - Dalda Köyü İlkokulu',
  'BİTLİS - TATVAN - Tatvan Küçüksu Köyü Vali Uğur BORAN İlkokulu',
  'BİTLİS - TATVAN - Çanakdüzü Köyü İlkokulu',
  'BİTLİS - TATVAN - Eğritaş Köyü Mesut Peker İlkokulu',
  'BİTLİS - TATVAN - Ahmet Mücteba Albayrak İlkokulu',
  'BİTLİS - TATVAN - Tatvan Özel Eğitim Uygulama Okulu I. Kademe',
  'BİTLİS - TATVAN - Çekmece İlkokulu',
  'BİTLİS - TATVAN - Koyunpınar İlkokulu',
  'BİTLİS - TATVAN - Çalıdüzü İlkokulu',
  'BİTLİS - TATVAN - Said-i Nursi Ortaokulu',
  'BİTLİS - TATVAN - Yavuz Sultan Selim Ortaokulu',
  'BİTLİS - TATVAN - Mevlana İlkokulu',
  'BİTLİS - TATVAN - Tatvan Özel Eğitim Uygulama Okulu III. Kademe',
  'BİTLİS - TATVAN - Atatürk Anadolu Lisesi',
  'BİTLİS - TATVAN - Tatvan Bilim ve Sanat Merkezi',
  'BİTLİS - TATVAN - Nene Hatun Mesleki ve Teknik Anadolu Lisesi',
  'BİTLİS - TATVAN - 15 Temmuz Şehitler Ortaokulu',
  'BİTLİS - TATVAN - Hidayet İlkokulu',
  'BİTLİS - TATVAN - İbn-i Sina Anaokulu',
  'BİTLİS - TATVAN - Kuruyaka Köyü İlkokulu',
  'BİTLİS - TATVAN - Harmanlı Köyü İlkokulu',
  'BİTLİS - TATVAN - Köprücük Köyü İlkokulu',
  'BİTLİS - TATVAN - Tatvan Özel Eğitim Anaokulu',
  'BİTLİS - TATVAN - 100. Yıl Cumhuriyet Anaokulu',
  'BİTLİS - TATVAN - Said-i Nursi Anaokulu',
  'BİTLİS - TATVAN - 15 Temmuz Şehitler Anaokulu',

  ];

  List<String> get list=>_list;
}