class BoluSchools{
  final List<String> _list=[
  'BOLU - DÖRTDİVAN - Cumhuriyet İlkokulu',
  'BOLU - DÖRTDİVAN - Çavuşlar İlkokulu',
  'BOLU - DÖRTDİVAN - Dörtdivan Çok Programlı Anadolu Lisesi',
  'BOLU - DÖRTDİVAN - Şehit Orhan Yalçın Ortaokulu',
  'BOLU - DÖRTDİVAN - Dörtdivan Halk Eğitimi Merkezi',
  'BOLU - DÖRTDİVAN - Öğretmen Evi ve Akşam Sanat Okulu',
  'BOLU - DÖRTDİVAN - Yunus Emre İmam Hatip Ortaokulu',
  'BOLU - DÖRTDİVAN - Dörtdivan Anaokulu',
  'BOLU - GEREDE - 100. Yıl İlkokulu',
  'BOLU - GEREDE - Gerede Anadolu İmam Hatip Lisesi',
  'BOLU - GEREDE - Gerede Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - GEREDE - Gerede Hacı Sadık Öztosun Anadolu Lisesi',
  'BOLU - GEREDE - Gerede Anadolu Lisesi',
  'BOLU - GEREDE - Esentepe Aşçılık Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - GEREDE - Göynükören İlkokulu',
  'BOLU - GEREDE - Gerede Halk Eğitimi Merkezi',
  'BOLU - GEREDE - İbrahim Hilmi Koçbeyoğlu Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - GEREDE - Nimet Meto Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - GEREDE - Gerede Mesleki Eğitim Merkezi',
  'BOLU - GEREDE - Esentepe Ortaokulu',
  'BOLU - GEREDE - Yenimahalle İlkokulu',
  'BOLU - GEREDE - Yenimahalle Ortaokulu',
  'BOLU - GEREDE - Zübeyde Hanım Anaokulu',
  'BOLU - GEREDE - Seyit Mithat Dayıoğlu İlkokulu',
  'BOLU - GEREDE - Seyit Mithat Dayıoğlu Ortaokulu',
  'BOLU - GEREDE - Mehmet Zeliha Güzelce İlkokulu',
  'BOLU - GEREDE - Halil Nom İlkokulu',
  'BOLU - GEREDE - Mustafa Çevikoğlu ve Halil Çevikoğlu İlkokulu',
  'BOLU - GEREDE - Ibrıcak Coşkun Arda İlkokulu',
  'BOLU - GEREDE - Seviller Ortaokulu',
  'BOLU - GEREDE - Gerede Ortaokulu',
  'BOLU - GEREDE - Fatma SeyitMehmet Eren Anaokulu',
  'BOLU - GEREDE - BAHÇELİEVLER İLKOKULU',
  'BOLU - GEREDE - GEREDE FEN LİSESİ',
  'BOLU - GEREDE - Şehit İlhan Sezer İmam Hatip Ortaokulu',
  'BOLU - GEREDE - Gerede 100. Yıl İmam Hatip Ortaokulu',
  'BOLU - GEREDE - GEREDE SEYİT MİTHAT DAYIOĞLU İMAM HATİP ORTAOKULU',
  'BOLU - GEREDE - Gerede Habibullah Üstün Kız Anadolu İmam Hatip Lisesi',
  'BOLU - GEREDE - Gerede Bilim ve Sanat Merkezi',
  'BOLU - GEREDE - Mehmet Zeliha Güzelce Anaokulu',
  'BOLU - GÖYNÜK - Akşemsettin Anadolu İmam Hatip Lisesi',
  'BOLU - GÖYNÜK - Ali Ericek İlkokulu',
  'BOLU - GÖYNÜK - Göynük Ali Ericek İlkokulu',
  'BOLU - GÖYNÜK - Göynük Halk Eğitimi Merkezi',
  'BOLU - GÖYNÜK - Kuyupınar Ovaboyu İlkokulu',
  'BOLU - GÖYNÜK - Nejla Türk İlkokulu',
  'BOLU - GÖYNÜK - Ali Ericek Ortaokulu',
  'BOLU - GÖYNÜK - Göynük Ortaokulu',
  'BOLU - GÖYNÜK - Kuyupınar Ovaboyu Ortaokulu',
  'BOLU - GÖYNÜK - Şehit Ziya Sarpkaya Ortaokulu',
  'BOLU - GÖYNÜK - Orhan Çalış Çok Programlı Anadolu Lisesi',
  'BOLU - GÖYNÜK - Ekinciler Ortaokulu',
  'BOLU - GÖYNÜK - GÖYNÜK İMAM HATİP ORTAOKULU',
  'BOLU - GÖYNÜK - Şehit Ziya Sarpkaya İlkokulu',
  'BOLU - GÖYNÜK - Ekinciler İlkokulu',
  'BOLU - GÖYNÜK - Nejla Türk Ortaokulu',
  'BOLU - GÖYNÜK - Göynük Öğretmenevi ve Akşam Sanat Okulu',
  'BOLU - GÖYNÜK - Zeynep Hatun Anaokulu',
  'BOLU - KIBRISCIK - Şehit Yıldırım Oflaz Çok Programlı Anadolu Lisesi',
  'BOLU - KIBRISCIK - Kıbrıscık Halk Eğitimi Merkezi',
  'BOLU - KIBRISCIK - Kıbrıscık Ortaokulu',
  'BOLU - KIBRISCIK - Şehit Süleyman Tombak İlkokulu',
  'BOLU - KIBRISCIK - KIBRISÇIK İMAM HATİP ORTAOKULU',
  'BOLU - MENGEN - Aşcılar Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - MENGEN - Gökcesu Ortaokulu',
  'BOLU - MENGEN - Gökçesu Şehit Aydın Çetin İlkokulu',
  'BOLU - MENGEN - Mengen Halk Eğitimi Merkezi',
  'BOLU - MENGEN - Mengen Anadolu İmam Hatip Lisesi',
  'BOLU - MENGEN - Gentaş Ahmet Kahraman Çok Programlı Anadolu Lisesi',
  'BOLU - MENGEN - Şehit Hasan Durmuşoğlu İlkokulu',
  'BOLU - MENGEN - Mengen Ortaokulu',
  'BOLU - MENGEN - Cumhuriyet İlkokulu',
  'BOLU - MENGEN - Mengen Atatürk Ortaokulu',
  'BOLU - MENGEN - MENGEN ANAOKULU',
  'BOLU - MENGEN - Gökçesu İmam Hatip Ortaokulu',
  'BOLU - MENGEN - Mengen Mesleki Eğitim Merkezi',
  'BOLU - MENGEN - Opet Mengen Pazarköy Cezmi Bilgin Aşçılık Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - MERKEZ - 50.Yıl İzzet Baysal İlkokulu',
  'BOLU - MERKEZ - 60. Yıl Ortaokulu',
  'BOLU - MERKEZ - 60.Yıl İlkokulu',
  'BOLU - MERKEZ - Abant İlkokulu',
  'BOLU - MERKEZ - Aktaş Anaokulu',
  'BOLU - MERKEZ - Alıçören Ortaokulu',
  'BOLU - MERKEZ - Bolu Anadolu İmam Hatip Lisesi',
  'BOLU - MERKEZ - Atatürk İlkokulu',
  'BOLU - MERKEZ - Atatürk Ortaokulu',
  'BOLU - MERKEZ - Behiye Baysal İlkokulu',
  'BOLU - MERKEZ - Bolu Anadolu Lisesi',
  'BOLU - MERKEZ - Bolu Sosyal Bilimler Lisesi',
  'BOLU - MERKEZ - Bolu Atatürk Anadolu Lisesi',
  'BOLU - MERKEZ - Bolu Bağışçılar Vakfı Anaokulu',
  'BOLU - MERKEZ - Bolu Fen Lisesi',
  'BOLU - MERKEZ - Bolu Güzel Sanatlar Lisesi',
  'BOLU - MERKEZ - Bolu Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - MERKEZ - Çobankaya Şehit Murat Paçal İlkokulu',
  'BOLU - MERKEZ - Dağkent Kıroğlu Eğitim ve Sağlık Vakfı İlkokulu',
  'BOLU - MERKEZ - Emine Mehmet Baysal Özel Eğitim Uygulama Merkezi I. Kademe',
  'BOLU - MERKEZ - Emine Mehmet Baysal Anadolu Lisesi',
  'BOLU - MERKEZ - Gazipaşa İlkokulu',
  'BOLU - MERKEZ - Gazipaşa Ortaokulu',
  'BOLU - MERKEZ - İnkılap İlkokulu',
  'BOLU - MERKEZ - İzzet Baysal Anadolu Lisesi',
  'BOLU - MERKEZ - İzzet Baysal Abant Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - MERKEZ - İzzet Baysal Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - MERKEZ - İzzet Baysal Anaokulu',
  'BOLU - MERKEZ - Bolu İzzet Baysal Halk Eğitimi Merkezi',
  'BOLU - MERKEZ - İzzet Baysal Mesleki Eğitim Merkezi',
  'BOLU - MERKEZ - Gölyüzü İzzet Baysal Anadolu Lisesi',
  'BOLU - MERKEZ - Karakoy TOKİ Ortaokulu',
  'BOLU - MERKEZ - Karaköy TOKİ İlkokulu',
  'BOLU - MERKEZ - Koç İlkokulu',
  'BOLU - MERKEZ - Latife Hanım Anaokulu',
  'BOLU - MERKEZ - Mebrure - İlhan Bağışgil Anaokulu',
  'BOLU - MERKEZ - Mevlâna İlkokulu',
  'BOLU - MERKEZ - Mevlâna Ortaokulu',
  'BOLU - MERKEZ - Milli Egemenlik İlkokulu',
  'BOLU - MERKEZ - Milli Egemenlik Ortaokulu',
  'BOLU - MERKEZ - Mimar İzzet Baysal Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - MERKEZ - Mustafa Çizmecioğlu Anadolu Lisesi',
  'BOLU - MERKEZ - Bolu Rehberlik ve Araştırma Merkezi',
  'BOLU - MERKEZ - Ankara Altındağ Belediyesi Kız Anadolu İmam Hatipi Lisesi',
  'BOLU - MERKEZ - Vali Mehmet Ali Türker Anaokulu',
  'BOLU - MERKEZ - Bolu Türkiye Odalar ve Borsalar Birliği Zübeyde Hanım Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - MERKEZ - Sakarya İlkokulu',
  'BOLU - MERKEZ - Sakarya Ortaokulu',
  'BOLU - MERKEZ - Karacasu İlkokulu',
  'BOLU - MERKEZ - Paşaköy İlkokulu',
  'BOLU - MERKEZ - Karacasu Ortaokulu',
  'BOLU - MERKEZ - 100. Yıl Ortaokulu',
  'BOLU - MERKEZ - Kültür İlkokulu',
  'BOLU - MERKEZ - Şehit Ozan Özen Ortaokulu',
  'BOLU - MERKEZ - Çaygökpınar İlkokulu',
  'BOLU - MERKEZ - Mehmet Akif Ersoy İlkokulu',
  'BOLU - MERKEZ - Canip Baysal Ortaokulu',
  'BOLU - MERKEZ - Çimento Çaydurt İlkokulu',
  'BOLU - MERKEZ - Canip Baysal Anadolu Lisesi',
  'BOLU - MERKEZ - Köroğlu İlkokulu',
  'BOLU - MERKEZ - Köroğlu Ortaokulu',
  'BOLU - MERKEZ - Dodurga Abdi Sın İlkokulu',
  'BOLU - MERKEZ - Yıldırım Bayezıt İlkokulu',
  'BOLU - MERKEZ - 100. Yıl İlkokulu',
  'BOLU - MERKEZ - Emine Mehmet Baysal Özel Eğitim Uygulama Merkezi II. Kademe',
  'BOLU - MERKEZ - Doğancı Ayşe - Yılmaz Becikoğlu Ortaokulu',
  'BOLU - MERKEZ - Yukarısoku İlkokulu',
  'BOLU - MERKEZ - Yukarısoku Ortaokulu',
  'BOLU - MERKEZ - Dodurga Abdi Sin Ortaokulu',
  'BOLU - MERKEZ - Canip Baysal İlkokulu',
  'BOLU - MERKEZ - 50 Yıl İzzet Baysal Ortaokulu',
  'BOLU - MERKEZ - Orhan Gazi Ortaokulu',
  'BOLU - MERKEZ - Sarıcalar Özel Eğitim Uygulama Okulu III. Kademe',
  'BOLU - MERKEZ - Behiye Baysal Ortaokulu',
  'BOLU - MERKEZ - Cumhuriyet İlkokulu',
  'BOLU - MERKEZ - Yunus Emre Ortaokulu',
  'BOLU - MERKEZ - Dağkent Kıroğlu Eğitim ve Sağlık Vakfı Ortaokulu',
  'BOLU - MERKEZ - Yunus Emre İlkokulu',
  'BOLU - MERKEZ - Çobankaya Şehit Murat Paçal Ortaokulu',
  'BOLU - MERKEZ - Büyük Berk Özel Eğitim Meslek Okulu',
  'BOLU - MERKEZ - Vilayetler Hizmet Birliği Anaokulu',
  'BOLU - MERKEZ - HACI BAYRAM VELİ İMAM-HATİP ORTAOKULU',
  'BOLU - MERKEZ - BOLU SPOR LİSESİ',
  'BOLU - MERKEZ - BOLU ANAOKULU',
  'BOLU - MERKEZ - SOLMAZ VE AHMET BAYSAL EMİNEANA ANAOKULU',
  'BOLU - MERKEZ - BOLU SOLMAZ-AHMET BAYSAL ÖĞRETMEN EVİ VE ASO',
  'BOLU - MERKEZ - BOLU BİLİM VE SANAT MERKEZİ',
  'BOLU - MERKEZ - BOLU İMAM HATİP ORTAOKULU',
  'BOLU - MERKEZ - REFİKAANA ANAOKULU',
  'BOLU - MERKEZ - Kadriyeana Anaokulu',
  'BOLU - MERKEZ - AKŞEMSEDDİN İMAM HATİP ORTAOKULU',
  'BOLU - MERKEZ - BOLU 15 TEMMUZ ŞEHİTLER İMAM HATİP ORTAOKULU',
  'BOLU - MERKEZ - BOLU KIZ ANADOLU İMAM HATİP LİSESİ',
  'BOLU - MERKEZ - İZZET BAYSAL ORTAOKULU',
  'BOLU - MERKEZ - Kındıra İlkokulu',
  'BOLU - MERKEZ - Doğancı Ayşe-Yılmaz Becikoğlu İlkokulu',
  'BOLU - MERKEZ - Gülçiçek Hatun Anaokulu',
  'BOLU - MERKEZ - Turgut Özal Anadolu Lisesi',
  'BOLU - MERKEZ - Şerife Bacı Anaokulu',
  'BOLU - MERKEZ - Kanuni Anadolu Lisesi',
  'BOLU - MERKEZ - Halime Hatun Özel Eğitim Anaokulu',
  'BOLU - MERKEZ - Solmazana Anaokulu',
  'BOLU - MERKEZ - Bilsem Anaokulu',
  'BOLU - MERKEZ - Bolu Organize Sanayi Bölgesi Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - MERKEZ - Mevlana Anaokulu',
  'BOLU - MERKEZ - Karacasu Anaokulu',
  'BOLU - MERKEZ - 100. Yıl Anaokulu',
  'BOLU - MERKEZ - Behiye Baysal Anaokulu',
  'BOLU - MERKEZ - Milli Egemenlik Anaokulu',
  'BOLU - MERKEZ - Cumhuriyet Anaokulu',
  'BOLU - MERKEZ - Yukarısoku Anaokulu',
  'BOLU - MERKEZ - 60. Yıl Anaokulu',
  'BOLU - MERKEZ - Atatürk Anaokulu',
  'BOLU - MERKEZ - Kültür Anaokulu',
  'BOLU - MERKEZ - Emine Mehmet Baysal Özel Eğitim Anaokulu',
  'BOLU - MERKEZ - Köroğlu Anaokulu',
  'BOLU - MERKEZ - Yunus Emre Anaokulu',
  'BOLU - MUDURNU - Çamyurdu İlkokulu',
  'BOLU - MUDURNU - Mudurnu Halk Eğitimi Merkezi',
  'BOLU - MUDURNU - Mudurnu Çok Programlı Anadolu Lisesi',
  'BOLU - MUDURNU - Nilüfer Hatun Anaokulu',
  'BOLU - MUDURNU - Taşkesti Çok Programlı Anadolu Lisesi',
  'BOLU - MUDURNU - Taşkesti İlkokulu',
  'BOLU - MUDURNU - Taşkesti Ortaokulu',
  'BOLU - MUDURNU - Yazılar İlkokulu',
  'BOLU - MUDURNU - Yazılar Ortaokulu',
  'BOLU - MUDURNU - Hacımusalar Ortaokulu',
  'BOLU - MUDURNU - Mudurnu Ortaokulu',
  'BOLU - MUDURNU - Abdurrahim Tırsi İmam Hatip Ortaokulu',
  'BOLU - MUDURNU - Dumlupınar İlkokulu',
  'BOLU - MUDURNU - MUDURNU ANADOLU İMAM HATİP LİSESİ',
  'BOLU - MUDURNU - TAŞKESTİ İMAM HATİP ORTAOKULU',
  'BOLU - MUDURNU - Hacımusalar İlkokulu',
  'BOLU - SEBEN - Seben Halk Eğitimi Merkezi',
  'BOLU - SEBEN - Seben Atatürk İlkokulu',
  'BOLU - SEBEN - Şehit Kaymakam Muhammet Fatih Safitürk Çok Programlı Anadolu Lisesi',
  'BOLU - SEBEN - Seben Ortaokulu',
  'BOLU - SEBEN - Seben Anaokulu',
  'BOLU - SEBEN - MEHMET AKİF ERSOY İMAM HATİP ORTAOKULU',
  'BOLU - YENİÇAĞA - Yaşar Çelik Çok Programlı Anadolu Lisesi',
  'BOLU - YENİÇAĞA - Yeniçağa Halk Eğitimi Merkezi',
  'BOLU - YENİÇAĞA - Mehmet Çelik İlkokulu',
  'BOLU - YENİÇAĞA - Yeniçağa Mesleki Eğitim Merkezi',
  'BOLU - YENİÇAĞA - Öğretmen Evi ve Akşam Sanat Okulu',
  'BOLU - YENİÇAĞA - Şair Dertli İlkokulu',
  'BOLU - YENİÇAĞA - Yeniçağa Aşçılar Mesleki ve Teknik Anadolu Lisesi',
  'BOLU - YENİÇAĞA - Yeniçağa Borsa İstanbul İmam Hatip Ortaokulu',
  'BOLU - YENİÇAĞA - Mehmet Çelik Ortaokulu',
  'BOLU - YENİÇAĞA - Yaşar Çelik İlkokulu',
  'BOLU - YENİÇAĞA - Yeniçağa Nene Hatun Anaokulu',

  ];

  List<String> get list=>_list;
}