class BursaSchools{
  final List<String> _list=[
  'BURSA - BÜYÜKORHAN - Şehit Halis Keskin Çok Programlı Anadolu Lisesi',
  'BURSA - BÜYÜKORHAN - Büyükorhan Halk Eğitimi Merkezi',
  'BURSA - BÜYÜKORHAN - Aktaş İlkokulu',
  'BURSA - BÜYÜKORHAN - Şehit Ramazan Aktay İlkokulu',
  'BURSA - BÜYÜKORHAN - Kınık İlkokulu',
  'BURSA - BÜYÜKORHAN - Kınık Ortaokulu',
  'BURSA - BÜYÜKORHAN - Şehit Zeki Uğur Ortaokulu',
  'BURSA - BÜYÜKORHAN - Atatürk İlkokulu',
  'BURSA - BÜYÜKORHAN - Şehit İsa Özkan Anadolu İmam Hatip Lisesi',
  'BURSA - GEMLİK - 11 Eylül İlkokulu',
  'BURSA - GEMLİK - Celal Bayar Anadolu Lisesi',
  'BURSA - GEMLİK - Cumhuriyet İlkokulu',
  'BURSA - GEMLİK - Ali Kütük Ortaokulu',
  'BURSA - GEMLİK - Gemlik Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - GEMLİK - Gemport Gemlik Anadolu Lisesi',
  'BURSA - GEMLİK - Gemlik Rehberlik ve Araştırma Merkezi',
  'BURSA - GEMLİK - Atatepe Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - GEMLİK - Gemlik Halk Eğitimi Merkezi',
  'BURSA - GEMLİK - Koza Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - GEMLİK - Kurşunlu Nursel Çağlar İlkokulu',
  'BURSA - GEMLİK - Lale Kemal Kılıç Ortaokulu',
  'BURSA - GEMLİK - Umurbey Celal Bayar Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - GEMLİK - Zübeyde Hanım Anaokulu',
  'BURSA - GEMLİK - Mehmet Akif Ersoy İlkokulu',
  'BURSA - GEMLİK - Şehit Mehmet Koray Pınar Ortaokulu',
  'BURSA - GEMLİK - Ayşe Ziver Karataş İlkokulu',
  'BURSA - GEMLİK - Şehit Cem Üner Ortaokulu',
  'BURSA - GEMLİK - Şehit Cem Üner İlkokulu',
  'BURSA - GEMLİK - Atatürk İlkokulu',
  'BURSA - GEMLİK - Umurbey Abdullah Fehmi İlkokulu',
  'BURSA - GEMLİK - Şükrü Şenol Ortaokulu',
  'BURSA - GEMLİK - Gemlik Hisar Anadolu Lisesi',
  'BURSA - GEMLİK - Şehit Mehmet Güngör İlkokulu',
  'BURSA - GEMLİK - Şehit Mehmet Güngör Ortaokulu',
  'BURSA - GEMLİK - Ali Kütahya Ortaokulu',
  'BURSA - GEMLİK - Umurbey Abdullah Fehmi Ortaokulu',
  'BURSA - GEMLİK - Şehit Gökhan Aydınlı Ortaokulu',
  'BURSA - GEMLİK - Şehit Esat Akbaba Ortaokulu',
  'BURSA - GEMLİK - Şehit Öğretmen Etem Yaşar İlkokulu',
  'BURSA - GEMLİK - Borusan İlkokulu',
  'BURSA - GEMLİK - Ali Kütahya İlkokulu',
  'BURSA - GEMLİK - Gemlik Anadolu İmam Hatip Lisesi',
  'BURSA - GEMLİK - 100.Yıl İlkokulu',
  'BURSA - GEMLİK - Gemlik Mesleki Eğitim Merkezi',
  'BURSA - GEMLİK - Şehit Cemal İlkokulu',
  'BURSA - GEMLİK - Kurşunlu Nursel Çağlar Ortaokulu',
  'BURSA - GEMLİK - Engürücük İlkokulu',
  'BURSA - GEMLİK - Engürücük Ortaokulu',
  'BURSA - GEMLİK - Gemlik Daniş Ekim Öğretmenevi ve Akşam Sanat Okulu Müdürlüğü',
  'BURSA - GEMLİK - Roda Anadolu İmam Hatip Lisesi',
  'BURSA - GEMLİK - Özdilek Cevdet Aynur Mayruk Kız Anadolu İmam Hatip Lisesi',
  'BURSA - GEMLİK - HALİTPAŞA İMAM HATİP ORTAOKULU',
  'BURSA - GEMLİK - ALİ KÜTAHYA İMAM HATİP ORTAOKULU',
  'BURSA - GEMLİK - Cihatlı Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - GEMLİK - Cihatlı Özel Eğitim Uygulama Okulu I. Kademe',
  'BURSA - GEMLİK - Cihatlı Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - GEMLİK - TSO Gazi İmam Hatip Ortaokulu',
  'BURSA - GEMLİK - Gemlik Bilim ve Sanat Merkezi',
  'BURSA - GEMLİK - Gemlik Cumhuriyet Anaokulu',
  'BURSA - GEMLİK - Lale Kemal Kılıç Anaokulu',
  'BURSA - GEMLİK - Ayşe Ziver Karataş Anaokulu',
  'BURSA - GEMLİK - 11 Eylül Anaokulu',
  'BURSA - GEMLİK - Şehit Mehmet Güngör Anaokulu',
  'BURSA - GEMLİK - Koza Özel Eğitim Anaokulu',
  'BURSA - GEMLİK - Zübeyde Hanım Özel Eğitim Anaokulu',
  'BURSA - GEMLİK - Gemlik Fen Lisesi',
  'BURSA - GÜRSU - Gürsu Borsa İstanbul Anadolu Lisesi',
  'BURSA - GÜRSU - Gürsu Anaokulu',
  'BURSA - GÜRSU - Lokman Hekim Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - GÜRSU - Yıldız Anadolu Lisesi',
  'BURSA - GÜRSU - Hacı Huriye Tinç Ortaokulu',
  'BURSA - GÜRSU - Hacı Huriye Tinç İlkokulu',
  'BURSA - GÜRSU - Latif Dörtçelik Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - GÜRSU - Zuhal Dörtçelik Şenipek Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - GÜRSU - Gürsu Halk Eğitimi Merkezi',
  'BURSA - GÜRSU - Zafer Ortaokulu',
  'BURSA - GÜRSU - Hamdi Çalış Ortaokulu',
  'BURSA - GÜRSU - Adaköy Ateş Sarıbal İlkokulu',
  'BURSA - GÜRSU - Adaköy Ateş Sarıbal Ortaokulu',
  'BURSA - GÜRSU - Kazıklı İlkokulu',
  'BURSA - GÜRSU - İğdir İlkokulu',
  'BURSA - GÜRSU - Karahıdır İlkokulu',
  'BURSA - GÜRSU - Yüksel Bodur İmam Hatip Ortaokulu',
  'BURSA - GÜRSU - Yüksel Bodur İlkokulu',
  'BURSA - GÜRSU - Ticaret ve Sanayi Odası Gürsu Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - GÜRSU - Selcen Hatun Anaokulu',
  'BURSA - GÜRSU - Ali Firdevs Lizor İlkokulu',
  'BURSA - GÜRSU - Mehmet Akif Ersoy İlkokulu',
  'BURSA - GÜRSU - Atatürk İlkokulu',
  'BURSA - GÜRSU - Hacı Huriye Tinç İmam Hatip Ortaokulu',
  'BURSA - GÜRSU - Gürsu Anadolu İmam Hatip Lisesi',
  'BURSA - GÜRSU - GÜRSU TOKİ ORTAOKULU',
  'BURSA - GÜRSU - GÜRSU TOKİ İLKOKULU',
  'BURSA - GÜRSU - 80.YIL CUMHURİYET İMAM HATİP ORTAOKULU',
  'BURSA - GÜRSU - GÜRSU FAZIL HÜSNÜ DAĞLARCA ANADOLU LİSESİ',
  'BURSA - GÜRSU - Gürsu Halime Hatun Anaokulu',
  'BURSA - GÜRSU - Şehit Sefa Uzun İlkokulu',
  'BURSA - GÜRSU - Gürsu Recep Tayyip Erdoğan Ortaokulu',
  'BURSA - GÜRSU - Gürsu Bilim ve Sanat Merkezi',
  'BURSA - GÜRSU - Gürsu Rehberlik ve Araştırma Merkezi',
  'BURSA - GÜRSU - Hacı Huriye Tinç Anaokulu',
  'BURSA - GÜRSU - Gürsu Atatürk Anaokulu',
  'BURSA - GÜRSU - Yenidoğan Anaokulu',
  'BURSA - HARMANCIK - Harmancık Halk Eğitimi Merkezi',
  'BURSA - HARMANCIK - Şehit Emre Sevinç Çok Programlı Anadolu Lisesi',
  'BURSA - HARMANCIK - Harmancık Ortaokulu',
  'BURSA - HARMANCIK - Şehit Adil Kınık İlkokulu',
  'BURSA - HARMANCIK - HARMANCIK İMAM HATİP ORTAOKULU',
  'BURSA - HARMANCIK - GÜLÖZÜ İLKOKULU',
  'BURSA - İNEGÖL - Alanyurt İlkokulu',
  'BURSA - İNEGÖL - Alanyurt Ortaokulu',
  'BURSA - İNEGÖL - Cumhuriyet İlkokulu',
  'BURSA - İNEGÖL - Çitli Nihat Korkmaz İlkokulu',
  'BURSA - İNEGÖL - Çitli Nihat Korkmaz Ortaokulu',
  'BURSA - İNEGÖL - Deydinler Dr.Emin Acar İlkokulu',
  'BURSA - İNEGÖL - Edebey Ortaokulu',
  'BURSA - İNEGÖL - Gündüzlü İlkokulu',
  'BURSA - İNEGÖL - Gündüzlü Ortaokulu',
  'BURSA - İNEGÖL - Gaziosmanpaşa İmam Hatip Ortaokulu',
  'BURSA - İNEGÖL - İnegöl Salih İbrahim Kırcalı Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - İNEGÖL - İnegöl Anadolu İmam Hatip Lisesi',
  'BURSA - İNEGÖL - Naire Çikayeva Anadolu Lisesi',
  'BURSA - İNEGÖL - Dörtçelik Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - İNEGÖL - İnegöl Mediha-Hayri Çelik Fen Lisesi',
  'BURSA - İNEGÖL - İnegöl Öğretmenevi ve Akşam Sanat Okulu',
  'BURSA - İNEGÖL - Yenice 19 Mayıs Anadolu Lisesi',
  'BURSA - İNEGÖL - İnegöl Mesleki Eğitim Merkezi',
  'BURSA - İNEGÖL - Mesudiye İlkokulu',
  'BURSA - İNEGÖL - Nuh Mehmet Küçükçalık Anadolu Lisesi',
  'BURSA - İNEGÖL - Tahtaköprü İlkokulu',
  'BURSA - İNEGÖL - Ticaret ve Sanayi Odası İlkokulu',
  'BURSA - İNEGÖL - Yenice Perihan Coşkun İlkokulu',
  'BURSA - İNEGÖL - Zeki Konukoğlu Anadolu Lisesi',
  'BURSA - İNEGÖL - Altıeylül Ortaokulu',
  'BURSA - İNEGÖL - Akhisar İlkokulu',
  'BURSA - İNEGÖL - Turgut Alp Anadolu Lisesi',
  'BURSA - İNEGÖL - Akşemsettin İlkokulu',
  'BURSA - İNEGÖL - 75.Yıl İlkokulu',
  'BURSA - İNEGÖL - İnegöl Halk Eğitimi Merkezi',
  'BURSA - İNEGÖL - Müşerref-Muzaffer Samda Ortaokulu',
  'BURSA - İNEGÖL - 100.Yıl İlkokulu',
  'BURSA - İNEGÖL - Şipali İlkokulu',
  'BURSA - İNEGÖL - Şükrünailipaşa İlkokulu',
  'BURSA - İNEGÖL - İnegöl Fenerbahçeliler Derneği Hamamlı İlkokulu',
  'BURSA - İNEGÖL - Hamzabey Ortaokulu',
  'BURSA - İNEGÖL - Dipsizgöl İlkokulu',
  'BURSA - İNEGÖL - Dipsizgöl Ortaokulu',
  'BURSA - İNEGÖL - Tahtaköprü Ortaokulu',
  'BURSA - İNEGÖL - Atatürk Ortaokulu',
  'BURSA - İNEGÖL - Edebey İlkokulu',
  'BURSA - İNEGÖL - Fatih İlkokulu',
  'BURSA - İNEGÖL - Yenice Ali Şefika Göztepe İlkokulu',
  'BURSA - İNEGÖL - Şakir Lakşe İlkokulu',
  'BURSA - İNEGÖL - Vehbi Koç İlkokulu',
  'BURSA - İNEGÖL - Alibey İlkokulu',
  'BURSA - İNEGÖL - Hacer Salih Yıldız İlkokulu',
  'BURSA - İNEGÖL - Kurşunlu İstiklal İlkokulu',
  'BURSA - İNEGÖL - İsaören İlkokulu',
  'BURSA - İNEGÖL - İsaören Ortaokulu',
  'BURSA - İNEGÖL - TOKİ Mehmet Akif Ersoy İlkokulu',
  'BURSA - İNEGÖL - TOKİ Necip Fazıl Kısakürek Ortaokulu',
  'BURSA - İNEGÖL - Prof.Dr.Selçuk Yahşi Ortaokulu',
  'BURSA - İNEGÖL - Çeltikçi İlkokulu',
  'BURSA - İNEGÖL - Çeltikçi Ortaokulu',
  'BURSA - İNEGÖL - 80.Yıl İlkokulu',
  'BURSA - İNEGÖL - İstaş Kentaş Ortaokulu',
  'BURSA - İNEGÖL - Şipali Ortaokulu',
  'BURSA - İNEGÖL - Maden İlkokulu',
  'BURSA - İNEGÖL - Hamzabey İlkokulu',
  'BURSA - İNEGÖL - Kulaca İlkokulu',
  'BURSA - İNEGÖL - Cemil Sönmez İlkokulu',
  'BURSA - İNEGÖL - Boğazköy İlkokulu',
  'BURSA - İNEGÖL - Fatma Mehmet Göztepe Anaokulu',
  'BURSA - İNEGÖL - İshakpaşa Anaokulu',
  'BURSA - İNEGÖL - Eskikaracakaya İlkokulu',
  'BURSA - İNEGÖL - Sinanbey İlkokulu',
  'BURSA - İNEGÖL - Fikriye Koşarer Anaokulu',
  'BURSA - İNEGÖL - İnegöl Hanife - Selçuk Teşik Rehberlik ve Araştırma Merkezi',
  'BURSA - İNEGÖL - Ömer Osman Çağlayan Ortaokulu',
  'BURSA - İNEGÖL - Kulaca Ortaokulu',
  'BURSA - İNEGÖL - Kocatepe İlkokulu',
  'BURSA - İNEGÖL - Kocatepe Ortaokulu',
  'BURSA - İNEGÖL - Ortaköy Süleyman Ezim Ortaokulu',
  'BURSA - İNEGÖL - Talha Ömer Faruk Teşik Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - İNEGÖL - Küçükyenice İlkokulu',
  'BURSA - İNEGÖL - Yenice 19 Mayıs Ortaokulu',
  'BURSA - İNEGÖL - Küçükyenice Ortaokulu',
  'BURSA - İNEGÖL - Bilal İlkokulu',
  'BURSA - İNEGÖL - İnegöl Zübeyde Hanım Anaokulu',
  'BURSA - İNEGÖL - Kurşunlu Cumhuriyet Ortaokulu',
  'BURSA - İNEGÖL - İnegöl İlkokulu',
  'BURSA - İNEGÖL - Nene Hatun Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - İNEGÖL - Müşerref-Muzaffer Samda İlkokulu',
  'BURSA - İNEGÖL - Cerrah Ortaokulu',
  'BURSA - İNEGÖL - Cerrah İlkokulu',
  'BURSA - İNEGÖL - Ömer Osman Çağlayan Özel Eğitim Meslek Okulu',
  'BURSA - İNEGÖL - Huzur İlkokulu',
  'BURSA - İNEGÖL - İshakpaşa İlkokulu',
  'BURSA - İNEGÖL - İnegöl Belediyesi Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - İNEGÖL - Nene Hatun Özel Eğitim Uygulama Merkezi I. Kademe',
  'BURSA - İNEGÖL - Alibey Ortaokulu',
  'BURSA - İNEGÖL - Dr. Emin Acar İmam Hatip Ortaokulu',
  'BURSA - İNEGÖL - Hacı Sevim Yıldız - 1 Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - İNEGÖL - GAZİPAŞA ORTAOKULU',
  'BURSA - İNEGÖL - ESKİKARACAKAYA ORTAOKULU',
  'BURSA - İNEGÖL - İnegöl Kız Anadolu İmam Hatip Lisesi',
  'BURSA - İNEGÖL - HAMİTABAT İLKOKULU',
  'BURSA - İNEGÖL - ÇAYYAKA İLKOKULU',
  'BURSA - İNEGÖL - HACI SEVİM YILDIZ-3 MESLEKİ VE TEKNİK ANADOLU LİSESİ',
  'BURSA - İNEGÖL - İNEGÖL SPOR LİSESİ',
  'BURSA - İNEGÖL - HACI SEVİM YILDIZ-2 MESLEKİ VE TEKNİK ANADOLU LİSESİ',
  'BURSA - İNEGÖL - Halil İnalcık Sosyal Bilimler Lisesi',
  'BURSA - İNEGÖL - Hacı Sevim Yıldız-4 Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - İNEGÖL - ERTUĞRULGAZİ ORTAOKULU',
  'BURSA - İNEGÖL - DEYDİNLER ORTAOKULU',
  'BURSA - İNEGÖL - MAHMUDİYE İMAM HATİP ORTAOKULU',
  'BURSA - İNEGÖL - DUMLUPINAR ORTAOKULU',
  'BURSA - İNEGÖL - İnegöl Borsa İstanbul Anadolu İmam Hatip Lisesi',
  'BURSA - İNEGÖL - Yenice Abdurrahman Öztarhan İmam Hatip Ortaokulu',
  'BURSA - İNEGÖL - İNEGÖL FENERBAHÇELİLER DERNEĞİ HAMAMLI ORTAOKULU',
  'BURSA - İNEGÖL - HACI SEVİM YILDIZ ANAOKULU',
  'BURSA - İNEGÖL - ERDEM BEYAZIT İMAM HATİP ORTAOKULU',
  'BURSA - İNEGÖL - HOCAKÖY İLKOKULU',
  'BURSA - İNEGÖL - AKINCILAR İLKOKULU',
  'BURSA - İNEGÖL - SEZAİ KARAKOÇ ORTAOKULU',
  'BURSA - İNEGÖL - Nuri Pakdil İmam Hatip Ortaokulu',
  'BURSA - İNEGÖL - Halime Hatun Anaokulu',
  'BURSA - İNEGÖL - Kurşunlu İlkokulu',
  'BURSA - İNEGÖL - ABDULHAMİT HAN ORTAOKULU',
  'BURSA - İNEGÖL - Yunus Emre Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - İNEGÖL - İNEGÖL ORGANİZE SANAYİ BÖLGESİ ORTAOKULU',
  'BURSA - İNEGÖL - ŞEHİT FEVZİ BAŞARAN ANADOLU İMAM HATİP LİSESİ',
  'BURSA - İNEGÖL - YILDIRIM BAYEZİD İMAM HATİP ORTAOKULU',
  'BURSA - İNEGÖL - Hocaköy Ortaokulu',
  'BURSA - İNEGÖL - HACI SEVİM YILDIZ MOBİLYA VE İÇ MEKAN TASARIMI TEKNOLOJİSİ MESLEKİ VE TEKNİK ANADOLU LİSESİ',
  'BURSA - İNEGÖL - KAŞIKÇIOĞLU ORTAOKULU',
  'BURSA - İNEGÖL - YÜKSEL BODUR ANAOKULU',
  'BURSA - İNEGÖL - Cerrah İmam Hatip Ortaokulu',
  'BURSA - İNEGÖL - EDEBEY İMAM HATİP ORTAOKULU',
  'BURSA - İNEGÖL - ERTUĞRULGAZİ İMAM HATİP ORTAOKULU',
  'BURSA - İNEGÖL - KURŞUNLU İMAM HATİP ORTAOKULU',
  'BURSA - İNEGÖL - BAKYAPI HACI ALİ BAKGÖR ORTAOKULU',
  'BURSA - İNEGÖL - DOĞAN YELKEN İLKOKULU',
  'BURSA - İNEGÖL - Ortaköy Süleyman Ezim İlkokulu',
  'BURSA - İNEGÖL - İnegöl Hüma Hatun Anaokulu',
  'BURSA - İNEGÖL - Toki Necip Fazıl Kısakürek İmam Hatip Ortaokulu',
  'BURSA - İNEGÖL - Bursa Borsa İstanbul Anadolu Lisesi',
  'BURSA - İNEGÖL - MÜSİAD Saime Sultan Bilim ve Sanat Merkezi',
  'BURSA - İNEGÖL - Ertuğrulgazi İlkokulu',
  'BURSA - İNEGÖL - İnegöl Anaokulu',
  'BURSA - İNEGÖL - Toki Necip Fazıl Kısakürek Anaokulu',
  'BURSA - İNEGÖL - Yenice Ali Şefika Göztepe Anaokulu',
  'BURSA - İNEGÖL - İnegöl Organize Sanayi Bölgesi Anaokulu',
  'BURSA - İNEGÖL - Ertuğrulgazi Anaokulu',
  'BURSA - İZNİK - Candarlı İlkokulu',
  'BURSA - İZNİK - Candarlı Ortaokulu',
  'BURSA - İZNİK - Göllüce İlkokulu',
  'BURSA - İZNİK - Göllüce Ortaokulu',
  'BURSA - İZNİK - İznik Halk Eğitimi Merkezi',
  'BURSA - İZNİK - İznik Anadolu İmam Hatip Lisesi',
  'BURSA - İZNİK - Eşrefzade Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - İZNİK - İznik Anadolu Lisesi',
  'BURSA - İZNİK - Kadir Koyutürk İlkokulu',
  'BURSA - İZNİK - Kaynarca İlkokulu',
  'BURSA - İZNİK - Selçuk İlkokulu',
  'BURSA - İZNİK - Çakırca Ortaokulu',
  'BURSA - İZNİK - Cumhuriyet İlkokulu',
  'BURSA - İZNİK - Orhaniye Ortaokulu',
  'BURSA - İZNİK - Şehit Sedat Pelit Anadolu Lisesi',
  'BURSA - İZNİK - Tacir İlkokulu',
  'BURSA - İZNİK - İznik Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - İZNİK - Çiçekli İlkokulu',
  'BURSA - İZNİK - Kılıçaslan İlkokulu',
  'BURSA - İZNİK - Kılıçaslan Ortaokulu',
  'BURSA - İZNİK - Alparslan Ortaokulu',
  'BURSA - İZNİK - Boyalıca İlkokulu',
  'BURSA - İZNİK - Boyalıca Ortaokulu',
  'BURSA - İZNİK - Selçuk Ortaokulu',
  'BURSA - İZNİK - Cumhuriyet Ortaokulu',
  'BURSA - İZNİK - Çiçekli Ortaokulu',
  'BURSA - İZNİK - Orhaniye İlkokulu',
  'BURSA - İZNİK - Mahmudiye İlkokulu',
  'BURSA - İZNİK - Sansarak İlkokulu',
  'BURSA - İZNİK - Ögretmen Evi ve Akşam Sanat Okulu',
  'BURSA - İZNİK - Elbeyli Ortaokulu',
  'BURSA - İZNİK - ELBEYLİ İLKOKULU',
  'BURSA - İZNİK - Çakırca İlkokulu',
  'BURSA - İZNİK - TACİR İMAM HATİP ORTAOKULU',
  'BURSA - İZNİK - KAYNARCA İMAM HATİP ORTAOKULU',
  'BURSA - İZNİK - İznik Rehberlik ve Araştırma Merkezi',
  'BURSA - İZNİK - Kılıçaslan Anaokulu',
  'BURSA - İZNİK - Bursa İznik Türkiye Odalar ve Borsalar Birliği Anaokulu',
  'BURSA - KARACABEY - Beylik İlkokulu',
  'BURSA - KARACABEY - Dağkadı İlkokulu',
  'BURSA - KARACABEY - Dağkadı Ortaokulu',
  'BURSA - KARACABEY - Karacabey Halk Eğitimi Merkezi',
  'BURSA - KARACABEY - Karacabey Anadolu İmam Hatip Lisesi',
  'BURSA - KARACABEY - İstiklal Ortaokulu',
  'BURSA - KARACABEY - Karacabey Anadolu Lisesi',
  'BURSA - KARACABEY - Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - KARACABEY - Dayı Karacabey Anadolu Lisesi',
  'BURSA - KARACABEY - Karacabey Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - KARACABEY - Murat Hüdavendigar İlkokulu',
  'BURSA - KARACABEY - Ögretmen Evi ve Akşam Sanat Okulu',
  'BURSA - KARACABEY - Ömer Matlı İlkokulu',
  'BURSA - KARACABEY - Karacabey Ortaokulu',
  'BURSA - KARACABEY - Cumhuriyet İlkokulu',
  'BURSA - KARACABEY - Sadık Yılmaz Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - KARACABEY - Atatürk İlkokulu',
  'BURSA - KARACABEY - Beylik Ortaokulu',
  'BURSA - KARACABEY - Sultaniye Ortaokulu',
  'BURSA - KARACABEY - Karakoca İlkokulu',
  'BURSA - KARACABEY - Sultaniye İlkokulu',
  'BURSA - KARACABEY - Karakoca Ortaokulu',
  'BURSA - KARACABEY - 14 Eylül Ortaokulu',
  'BURSA - KARACABEY - Ulubatlıhasan İlkokulu',
  'BURSA - KARACABEY - Şehit Yüzbaşı Atilla Savaş Acarca Ortaokulu',
  'BURSA - KARACABEY - Seyran Ortaokulu',
  'BURSA - KARACABEY - Seyran İlkokulu',
  'BURSA - KARACABEY - Karacabey Ticaret ve Sanayi Odası Mesleki Eğitim Merkezi',
  'BURSA - KARACABEY - Cahide Kırlağaç Anaokulu',
  'BURSA - KARACABEY - TOKİ Şehit Yzb. Erhan Kındır İlkokulu',
  'BURSA - KARACABEY - Sarıbey Serkan Argın İlkokulu',
  'BURSA - KARACABEY - Sarıbey Serkan Argın Ortaokulu',
  'BURSA - KARACABEY - Keşlik İlkokulu',
  'BURSA - KARACABEY - Keşlik Ortaokulu',
  'BURSA - KARACABEY - Şehit Bahadır Tayfur İlkokulu',
  'BURSA - KARACABEY - Şehit Bilal Kanat İlkokulu',
  'BURSA - KARACABEY - Şehit Bilal Kanat Ortaokulu',
  'BURSA - KARACABEY - Öztusan İlkokulu',
  'BURSA - KARACABEY - Şehit Serkan Şahin Ortaokulu',
  'BURSA - KARACABEY - Hacı Ahmediye Onur İlkokulu',
  'BURSA - KARACABEY - Muhsin Özdamar Ortaokulu',
  'BURSA - KARACABEY - Şehit Jandarma Uzman Çavuş Cemil Turan İlkokulu',
  'BURSA - KARACABEY - Karacabey Ulviye Matlı Fen Lisesi',
  'BURSA - KARACABEY - Farabi Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - KARACABEY - Şehit Jandarma Uzman Çavuş Cemil Turan Ortaokulu',
  'BURSA - KARACABEY - Karacabey Ertuğrul Gazi İmam Hatip Ortaokulu',
  'BURSA - KARACABEY - Kurşunlu İlkokulu',
  'BURSA - KARACABEY - Karacabey Rehberlik ve Araştırma Merkezi',
  'BURSA - KARACABEY - Karacabey İmam Hatip Ortaokulu',
  'BURSA - KARACABEY - Şehit Özcan Özsoy Kız Anadolu İmam Hatip Lisesi',
  'BURSA - KARACABEY - Adnan Menderes Ortaokulu',
  'BURSA - KARACABEY - Karacabey Ticaret Borsası Harmanlı Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - KARACABEY - Subaşı İlkokulu',
  'BURSA - KARACABEY - Karacabey Belediyesi Anaokulu',
  'BURSA - KARACABEY - Muhsin Yazıcıoğlu Ortaokulu',
  'BURSA - KARACABEY - Karacabey Özel Eğitim Meslek Okulu',
  'BURSA - KARACABEY - Karacabey Bilim ve Sanat Merkezi',
  'BURSA - KARACABEY - Ömer Matlı Anaokulu',
  'BURSA - KARACABEY - Karacabey Cumhuriyet Anaokulu',
  'BURSA - KELES - Keles Halk Eğitimi Merkezi',
  'BURSA - KELES - I.Murat İlkokulu',
  'BURSA - KELES - Keles Anadolu İmam Hatip Lisesi',
  'BURSA - KELES - Keles Anaokulu',
  'BURSA - KELES - Keles Çok Programlı Anadolu Lisesi',
  'BURSA - KELES - Davut Zeki Akpınar Yatılı Bölge Ortaokulu',
  'BURSA - KELES - Gelemiç İlkokulu',
  'BURSA - KELES - Barakli İlkokulu',
  'BURSA - KELES - Abdullah Akça Ortaokulu',
  'BURSA - KELES - Abdullah Akça İlkokulu',
  'BURSA - KELES - Sorgun İlkokulu',
  'BURSA - KELES - BARAKLİ ORTAOKULU',
  'BURSA - KELES - KIRANIŞIKLAR İLKOKULU',
  'BURSA - KELES - Kıranışıklar Ortaokulu',
  'BURSA - KELES - KELES İMAM HATİP ORTAOKULU',
  'BURSA - KESTEL - Atatürk İlkokulu',
  'BURSA - KESTEL - Bursa Çimento Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - KESTEL - Erdoğan İlkokulu',
  'BURSA - KESTEL - Kestel Halk Eğitimi Merkezi',
  'BURSA - KESTEL - Kestel Anaokulu',
  'BURSA - KESTEL - Hasan Coşkun Anadolu Lisesi',
  'BURSA - KESTEL - Yenimahalle İlkokulu',
  'BURSA - KESTEL - Şehit Polis İsmail Özbek Ortaokulu',
  'BURSA - KESTEL - Toplu Konutlar Ortaokulu',
  'BURSA - KESTEL - Barakfakih Ortaokulu',
  'BURSA - KESTEL - Barakfakih İlkokulu',
  'BURSA - KESTEL - Cumhuriyet İlkokulu',
  'BURSA - KESTEL - Babasultan Musa Coşkun ilkokulu',
  'BURSA - KESTEL - Babasultan Musa Coşkun Ortaokulu',
  'BURSA - KESTEL - Şehit Emre Karaaslan Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - KESTEL - Kestel Hasan Aslanoba Anadolu Lisesi',
  'BURSA - KESTEL - Çataltepe Ortaokulu',
  'BURSA - KESTEL - Kestel Belediyesi Esentepe İlkokulu',
  'BURSA - KESTEL - Şehit Mustafa Kurt Ortaokulu',
  'BURSA - KESTEL - Musa Amca İlkokulu',
  'BURSA - KESTEL - Derekızık İlkokulu',
  'BURSA - KESTEL - Erdoğan Ortaokulu',
  'BURSA - KESTEL - Çataltepe İlkokulu',
  'BURSA - KESTEL - VANİ MEHMET ANADOLU İMAM HATİP LİSESİ',
  'BURSA - KESTEL - KESTEL KIZ ANADOLU İMAM HATİP LİSESİ',
  'BURSA - KESTEL - Bursa Kestel Musa Amca Öğretmen Evi ASO',
  'BURSA - KESTEL - Narlıdere Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - KESTEL - MUSTAFA TUNALI İMAM HATİP ORTAOKULU',
  'BURSA - KESTEL - KESTEL MEHMET AKİF ERSOY İLKOKULU',
  'BURSA - KESTEL - KESTEL BEŞEVLER ORTAOKULU',
  'BURSA - KESTEL - Narlıdere Özel Eğitim Uygulama Okulu I. Kademe',
  'BURSA - KESTEL - Ümitalan İlkokulu',
  'BURSA - KESTEL - Gölcük İlkokulu',
  'BURSA - KESTEL - Kestel Rehberlik ve Araştırma Merkezi',
  'BURSA - KESTEL - Kestel Yunus Emre İlkokulu',
  'BURSA - KESTEL - Uludağ Anadolu İmam Hatip Lisesi',
  'BURSA - KESTEL - Kestel Bilim ve Sanat Merkezi',
  'BURSA - KESTEL - Kestel Atatürk Anaokulu',
  'BURSA - KESTEL - Barakfakih Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - KESTEL - Kestel Belediyesi Esentepe Anaokulu',
  'BURSA - KESTEL - Kestel Nuri Erbak Anaokulu',
  'BURSA - MUDANYA - Ahmet Rüştü Anadolu Lisesi',
  'BURSA - MUDANYA - Cafer Yener İlkokulu',
  'BURSA - MUDANYA - Dereköy İlkokulu',
  'BURSA - MUDANYA - Esence Süleyman Avcı Ortaokulu',
  'BURSA - MUDANYA - Esence Süleyman Avcı İlkokulu',
  'BURSA - MUDANYA - Hasköy İlkokulu',
  'BURSA - MUDANYA - İkbal-Betül Ali İhsan Çilingiroğlu Ortaokulu',
  'BURSA - MUDANYA - Mudanya Anadolu İmam Hatip Lisesi',
  'BURSA - MUDANYA - M.Zeki Yazıcı İlkokulu',
  'BURSA - MUDANYA - Mudanya Dörtçelik Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - MUDANYA - Mudanya Sami Evkuran Anadolu Lisesi',
  'BURSA - MUDANYA - Necla Orhan İlkokulu',
  'BURSA - MUDANYA - Turhan Tayan Anadolu Lisesi',
  'BURSA - MUDANYA - Ülkü Köyü Ortaokulu',
  'BURSA - MUDANYA - Ülkü Köyü İlkokulu',
  'BURSA - MUDANYA - Mürsel Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - MUDANYA - Güzelyalı Anaokulu',
  'BURSA - MUDANYA - Çayönü İlkokulu',
  'BURSA - MUDANYA - Çayönü Ortaokulu',
  'BURSA - MUDANYA - Atatürk Ortaokulu',
  'BURSA - MUDANYA - Hatice-İsmail Hakkı Kayan Ortaokulu',
  'BURSA - MUDANYA - Mütareke İlkokulu',
  'BURSA - MUDANYA - Dereköy Ortaokulu',
  'BURSA - MUDANYA - Akköy İlkokulu',
  'BURSA - MUDANYA - Necla Orhan Ortaokulu',
  'BURSA - MUDANYA - Zeytinbağı İlkokulu',
  'BURSA - MUDANYA - Zeytinbağı Ortaokulu',
  'BURSA - MUDANYA - Şükrü Çavuş Sait Eroğlu İlkokulu',
  'BURSA - MUDANYA - 12 Eylül İlkokulu',
  'BURSA - MUDANYA - M.Zeki Yazıcı Ortaokulu',
  'BURSA - MUDANYA - Mudanya Halk Eğitimi Merkezi',
  'BURSA - MUDANYA - Mudanya Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - MUDANYA - MUDANYA ÖĞRETMENEVİ VE AKŞAM SANAT OKULU MÜDÜRLÜĞÜ',
  'BURSA - MUDANYA - Cepni İlkokulu',
  'BURSA - MUDANYA - HASKÖY ORTAOKULU',
  'BURSA - MUDANYA - Mudanya İmam Hatip Ortaokulu',
  'BURSA - MUDANYA - Şehit Cüneyt Bursa Kız Anadolu İmam Hatip Lisesi',
  'BURSA - MUDANYA - GÜZELYALI İLKOKULU',
  'BURSA - MUDANYA - Mudanya Güzelyalı İmam Hatip Ortaokulu',
  'BURSA - MUDANYA - Mudanya Güzelyalı Anadolu Lisesi',
  'BURSA - MUDANYA - Mudanya Halitpaşa Ortaokulu',
  'BURSA - MUDANYA - Mudanya Rehberlik ve Araştırma Merkezi',
  'BURSA - MUSTAFAKEMALPAŞA - Alpağut İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Mustafa Kemal Paşa Anadolu İmam Hatip Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - Hamzabey Bilim ve Sanat Merkezi',
  'BURSA - MUSTAFAKEMALPAŞA - Çeltikçi Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Şehit Tuncay Çanak İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Mustafakemalpaşa İsmail Hakkı Şenpamukçu Halk Eğitimi Merkezi',
  'BURSA - MUSTAFAKEMALPAŞA - İbrahim Önal Fen Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - Nilüfer Hatun Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - Mehmet Akif Ersoy İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Mustafakemalpaşa Mesleki Eğitim Merkezi',
  'BURSA - MUSTAFAKEMALPAŞA - Mevlana İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Mustafa Kemal Paşa Öğretmenevi ve Akşam Sanat Okulu',
  'BURSA - MUSTAFAKEMALPAŞA - Hasan Celal Güzel Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - Akşemsettin Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - Mustafakemalpaşa Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - Mustafakemalpaşa Anaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Mustafa Kemal Paşa Anadolu Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - Sedat Karan Anadolu Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - Taşpınar Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Demireli İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Demireli Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Yunus Emre İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Taşpınar İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Balibey İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Öğretmendavut İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Karaoğlan İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Çeltikçi İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Ovaazatlı İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Ovaazatlı Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Tatkavaklı Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Tatkavaklı İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Sincansarnıç İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Sincansarnıç Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Lalaşahinpaşa Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Mustafakemalpaşa Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Devecikonağı İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Devecikonağı Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Mehmet Akif Ersoy Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Adaköy İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Atatürk Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Yalıntaş İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Yalıntaş Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Koşuboğazi Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Ormankadı İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Ormankadı Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Tepecik Şehit Ali Üzel Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Güner Şenpamukçu Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - İbn-i Sina Özel Eğitim Meslek Okulu',
  'BURSA - MUSTAFAKEMALPAŞA - Koşuboğazi İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Karaorman İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Karaorman Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Yeşilova İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - 14 Eylül İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Güllüce İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - Güllüce Ortaokulu',
  'BURSA - MUSTAFAKEMALPAŞA - TOKİ Fatih İlkokulu',
  'BURSA - MUSTAFAKEMALPAŞA - TOKİ FATİH ORTAOKULU',
  'BURSA - MUSTAFAKEMALPAŞA - TOKİ Ayas Bey Anadolu Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - Mustafakemalpaşa Kız Anadolu İmam Hatip Lisesi',
  'BURSA - MUSTAFAKEMALPAŞA - YALINTAŞ İMAM HATİP ORTAOKULU',
  'BURSA - MUSTAFAKEMALPAŞA - ŞEHİT HİKMET AKTAŞ ORTAOKULU',
  'BURSA - MUSTAFAKEMALPAŞA - ZÜFERBEY İMAM HATİP ORTAOKULU',
  'BURSA - MUSTAFAKEMALPASA - İbn-i Sina Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - MUSTAFAKEMALPASA - İbn-i Sina Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - MUSTAFAKEMALPASA - İbn-i Sina Özel Eğitim Uygulama Okulu I. Kademe',
  'BURSA - MUSTAFAKEMALPASA - Cahit Zarifoğlu İlkokulu',
  'BURSA - MUSTAFAKEMALPASA - Mustafakemalpaşa Rehberlik ve Araştırma Merkezi',
  'BURSA - MUSTAFAKEMALPASA - Karyağmaz İlkokulu',
  'BURSA - MUSTAFAKEMALPASA - Hamzabey Bilim ve Sanat Merkezi Anaokulu',
  'BURSA - MUSTAFAKEMALPASA - 14 Eylül Anaokulu',
  'BURSA - MUSTAFAKEMALPASA - Mustafakemalpaşa Yunus Emre Anaokulu',
  'BURSA - MUSTAFAKEMALPASA - Lalaşahinpaşa Özel Eğitim Anaokulu',
  'BURSA - NİLÜFER - Ali Karasu İlkokulu',
  'BURSA - NİLÜFER - Ali Karasu Anadolu Lisesi',
  'BURSA - NİLÜFER - Ahmet Erdem Anadolu Lisesi',
  'BURSA - NİLÜFER - Fatih Anadolu İmam Hatip Lisesi',
  'BURSA - NİLÜFER - Görükle Akşemsettin İlkokulu',
  'BURSA - NİLÜFER - Nilüfer Halk Eğitimi Merkezi',
  'BURSA - NİLÜFER - Işıktepe Rüveyde Dörtçelik İlkokulu',
  'BURSA - NİLÜFER - İrfaniye İlkokulu',
  'BURSA - NİLÜFER - Nilüfer Özel Eğitim Meslek Lisesi',
  'BURSA - NİLÜFER - M. Kemal Coşkunöz Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Nilüfer Mesleki Eğitim Merkezi',
  'BURSA - NİLÜFER - Nilüfer Anadolu İmam Hatip Lisesi',
  'BURSA - NİLÜFER - Nilüfer Borsa İstanbul Fen Lisesi',
  'BURSA - NİLÜFER - Nur - Hayati Kurtcan Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Öğretmen Mehmet Aras İlkokulu',
  'BURSA - NİLÜFER - Nilüfer Rehberlik ve Araştırma Merkezi',
  'BURSA - NİLÜFER - Tahtalı İlkokulu',
  'BURSA - NİLÜFER - Ürünlü İlkokulu',
  'BURSA - NİLÜFER - Vardar Anaokulu',
  'BURSA - NİLÜFER - Tofaş Fen Lisesi',
  'BURSA - NİLÜFER - Nilüfer Belediyesi Özlüce İlkokulu',
  'BURSA - NİLÜFER - Fethiye Ortaokulu',
  'BURSA - NİLÜFER - Demirci İlkokulu',
  'BURSA - NİLÜFER - Hasanağa Ortaokulu',
  'BURSA - NİLÜFER - Zekai Gümüşdiş Ortaokulu',
  'BURSA - NİLÜFER - Gölyazı Ünallar İlkokulu',
  'BURSA - NİLÜFER - Görükle Hazinedaroğlu Özkan İlkokulu',
  'BURSA - NİLÜFER - Konaklı Ortaokulu',
  'BURSA - NİLÜFER - Şahinler Anadolu Lisesi',
  'BURSA - NİLÜFER - Konaklı İlkokulu',
  'BURSA - NİLÜFER - Koç Ortaokulu',
  'BURSA - NİLÜFER - Süleyman Cura Ortaokulu',
  'BURSA - NİLÜFER - İbrahim Uyar İlkokulu',
  'BURSA - NİLÜFER - Fethiye Şehit Öğretmen Şekip Akın İlkokulu',
  'BURSA - NİLÜFER - Hüsnü Züber İlkokulu',
  'BURSA - NİLÜFER - Vahide Aktuğ Ortaokulu',
  'BURSA - NİLÜFER - Dilek Özer Ortaokulu',
  'BURSA - NİLÜFER - Gölyazı Ünallar Ortaokulu',
  'BURSA - NİLÜFER - Otomotiv Endüstrisi İhracatçıları Birliği Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Emir-Koop İlkokulu',
  'BURSA - NİLÜFER - Cavit Çaglar Ortaokulu',
  'BURSA - NİLÜFER - Güngören İlkokulu',
  'BURSA - NİLÜFER - Nilüfer Özel Eğitim Meslek Okulu',
  'BURSA - NİLÜFER - Mitat Enç Özel Eğitim İlkokulu',
  'BURSA - NİLÜFER - Üçevler Şehit Faik Gökçen İlkokulu',
  'BURSA - NİLÜFER - Ahmet Uyar İlkokulu',
  'BURSA - NİLÜFER - Kayapa Şehit Jandarma Er Eyüp Gürsoy İlkokulu',
  'BURSA - NİLÜFER - Bursa Zeki Müren Güzel Sanatlar Lisesi',
  'BURSA - NİLÜFER - Özlüce Şehit Aykut Yurtsever Anadolu Lisesi',
  'BURSA - NİLÜFER - İrfaniye Ortaokulu',
  'BURSA - NİLÜFER - Eşref Ergin İlkokulu',
  'BURSA - NİLÜFER - Kayapa Şehit Jandarma Er Eyüp Gürsoy Ortaokulu',
  'BURSA - NİLÜFER - Eşref Ergin Ortaokulu',
  'BURSA - NİLÜFER - İslam Uyar Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Nilüfer Belediyesi Bursa Rotary İlkokulu',
  'BURSA - NİLÜFER - Kayapa İlkokulu',
  'BURSA - NİLÜFER - Kayapa Ortaokulu',
  'BURSA - NİLÜFER - Görükle Dumlupınar İlkokulu',
  'BURSA - NİLÜFER - Demirci Ortaokulu',
  'BURSA - NİLÜFER - Ali Durmaz Ortaokulu',
  'BURSA - NİLÜFER - Şehit Piyade Kurmay Yarbay İlker Çelikcan Ortaokulu',
  'BURSA - NİLÜFER - Çalı İlkokulu',
  'BURSA - NİLÜFER - Çalı İmam Hatip Ortaokulu',
  'BURSA - NİLÜFER - Hüseyin Özdilek Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Sadettin Türkün Ortaokulu',
  'BURSA - NİLÜFER - Canaydın İlkokulu',
  'BURSA - NİLÜFER - Akçalar Fahriye Sayarel İlkokulu',
  'BURSA - NİLÜFER - Yaylacık İlkokulu',
  'BURSA - NİLÜFER - Yaylacık Ortaokulu',
  'BURSA - NİLÜFER - Feriha Uyar Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Zübeyde Hanım Anaokulu',
  'BURSA - NİLÜFER - Akçalar Fahriye Sayarel Ortaokulu',
  'BURSA - NİLÜFER - Kara Mehmet Ortaokulu',
  'BURSA - NİLÜFER - TEV Dr İbrahim Öktem Anaokulu',
  'BURSA - NİLÜFER - Işıktepe Rüveyde Dörtçelik Ortaokulu',
  'BURSA - NİLÜFER - Hasanağa Şehit Piyade Er Kadir Çavuşoğlu Ortaokulu',
  'BURSA - NİLÜFER - Gümüştepe İlkokulu',
  'BURSA - NİLÜFER - Hasanağa İlkokulu',
  'BURSA - NİLÜFER - Havva Aslanoba Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Tahtalı Ortaokulu',
  'BURSA - NİLÜFER - Çamlıca Anadolu Lisesi',
  'BURSA - NİLÜFER - Yolçatı Şehit Coşkun Çalı Ortaokulu',
  'BURSA - NİLÜFER - Nedim Öztan İlkokulu',
  'BURSA - NİLÜFER - Mualla Türkün Anaokulu',
  'BURSA - NİLÜFER - İpek Özel Eğitim Uygulama Merkezi I. Kademe',
  'BURSA - NİLÜFER - Alaattinbey Özel Eğitim Mesleki Eğitim Merkezi Okulu',
  'BURSA - NİLÜFER - Mitat Enç Özel Eğitim Ortaokulu',
  'BURSA - NİLÜFER - NOSAB İlkokulu',
  'BURSA - NİLÜFER - İpek Özel Eğitim Uygulama Merkezi II. Kademe',
  'BURSA - NİLÜFER - İpek Özel Eğitim İş Uygulama Merkezi (Okulu)',
  'BURSA - NİLÜFER - Alara İlkokulu',
  'BURSA - NİLÜFER - Alara Ortaokulu',
  'BURSA - NİLÜFER - Duyum İşitme Engelliler İlkokulu',
  'BURSA - NİLÜFER - Duyum İşitme Engelliler Ortaokulu',
  'BURSA - NİLÜFER - Yolçatı Şehit Coşkun Çalı İlkokulu',
  'BURSA - NİLÜFER - Nilüfer İsmail Kadriye Solakoğulları Ortaokulu',
  'BURSA - NİLÜFER - Abdurrahman Vardar İlkokulu',
  'BURSA - NİLÜFER - Gökçe İlkokulu',
  'BURSA - NİLÜFER - Özlüce Nurettin Topçu Kız Anadolu İmam Hatip Lisesi',
  'BURSA - NİLÜFER - Atatürk Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Ürünlü Ortaokulu',
  'BURSA - NİLÜFER - Doğanköy Şehit Yakup Kurt Ortaokulu',
  'BURSA - NİLÜFER - Ataevler Anaokulu',
  'BURSA - NİLÜFER - Nesrin Fuat Bursalı İlkokulu',
  'BURSA - NİLÜFER - Gevher Hatun Anaokulu',
  'BURSA - NİLÜFER - Görükle Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Nilüfer Anaokulu',
  'BURSA - NİLÜFER - Doğanköy İlkokulu',
  'BURSA - NİLÜFER - Nilüfer Belediyesi Barış Anadolu Lisesi',
  'BURSA - NİLÜFER - ÖZLÜCE ANAOKULU',
  'BURSA - NİLÜFER - Meral-Muammer Ağım Ortaokulu',
  'BURSA - NİLÜFER - ŞEHİT KARA PİLOT YÜZBAŞI HAKAN TAN ORTAOKULU',
  'BURSA - NİLÜFER - BADIRGA İLKOKULU',
  'BURSA - NİLÜFER - ŞEHİT KARA PİLOT YÜZBAŞI HAKAN TAN İLKOKULU',
  'BURSA - NİLÜFER - HATİCE GANİ ERVERDİ ORTAOKULU',
  'BURSA - NİLÜFER - İSMAİL KARASU İMAM HATİP ORTAOKULU',
  'BURSA - NİLÜFER - TUNA İMAM HATİP ORTAOKULU',
  'BURSA - NİLÜFER - ALİ KUŞÇU ANADOLU İMAM HATİP LİSESİ',
  'BURSA - NİLÜFER - HASANAĞA ŞEHİT PİYADE ER KADİR ÇAVUŞOĞLU İLKOKULU',
  'BURSA - NİLÜFER - 15 TEMMUZ İLKOKULU',
  'BURSA - NİLÜFER - NİLÜFER ŞEHİTLER ORTAOKULU',
  'BURSA - NİLÜFER - ÖĞRETMEN HASAN GÜNEY ORTAOKULU',
  'BURSA - NİLÜFER - ÖZLÜCE RASİM ÖZDENÖREN ANADOLU İMAM HATİP LİSESİ',
  'BURSA - NİLÜFER - ŞEHİT ZAFER KOYUNCU İMAM HATİP ORTAOKULU',
  'BURSA - NİLÜFER - AHMET MUHARREM UĞUR ANAOKULU',
  'BURSA - NİLÜFER - MİLLİ İRADE ANAOKULU',
  'BURSA - NİLÜFER - İLKADIM ANAOKULU',
  'BURSA - NİLÜFER - ŞEHİT MURAT ALKAN İMAM HATİP ORTAOKULU',
  'BURSA - NİLÜFER - BEŞEVLER ANAOKULU',
  'BURSA - NİLÜFER - HALİL İNALCIK BİLİM VE SANAT MERKEZİ',
  'BURSA - NİLÜFER - ULUDAĞ ÜNİVERSİTESİ ANAOKULU',
  'BURSA - NİLÜFER - FETHİYE İMAM HATİP ORTAOKULU',
  'BURSA - NİLÜFER - ERTUĞRUL SEYHAN ANADOLU LİSESİ',
  'BURSA - NİLÜFER - ÖZLÜCE AZİZ SANCAR ORTAOKULU',
  'BURSA - NİLÜFER - OSMAN ŞEVKİ ULUDAĞ ANADOLU LİSESİ',
  'BURSA - NİLÜFER - AHMET CEVDET PAŞA ANADOLU İMAM HATİP LİSESİ',
  'BURSA - NİLÜFER - AHMET YESEVİ ANADOLU LİSESİ',
  'BURSA - NİLÜFER - Şehit Hüseyin Akyüz Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - NİLÜFER - Uludağ Üniversitesi Devlet Konservatuvarı Müzik ve Bale Ortaokulu',
  'BURSA - NİLÜFER - Uludağ Üniversitesi Devlet Konservatuvarı Müzik ve Bale İlkokulu',
  'BURSA - NİLÜFER - Uludağ Üniversitesi Devlet Konservatuvarı Müzik ve Sahne Sanatları Lisesi',
  'BURSA - NİLÜFER - Kayapa Özel Eğitim Uygulama Okulu I. Kademe',
  'BURSA - NİLÜFER - Kayapa Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - NİLÜFER - Kayapa Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - NİLÜFER - Hüseyin Özdilek Anadolu Lisesi',
  'BURSA - NİLÜFER - İslam Uyar Anadolu Lisesi',
  'BURSA - NİLÜFER - Şehit Sıtkı Şen İlkokulu',
  'BURSA - NİLÜFER - Nilüfer Belediyesi Bursa Rotary Anaokulu',
  'BURSA - NİLÜFER - Üçevler Şehit Faik Gökçen Anaokulu',
  'BURSA - NİLÜFER - Hasanağa Şehit Piyade Er Kadir Çavuşoğlu Anaokulu',
  'BURSA - NİLÜFER - Canaydın Anaokulu',
  'BURSA - NİLÜFER - Çalı Anaokulu',
  'BURSA - NİLÜFER - Akçalar Fahriye Sayarel Anaokulu',
  'BURSA - NİLÜFER - Fethiye Şehit Öğretmen Şekip Akın Anaokulu',
  'BURSA - NİLÜFER - Nilüfer Duyum Özel Eğitim Anaokulu',
  'BURSA - ORHANELİ - Altıntaş İlkokulu',
  'BURSA - ORHANELİ - Hacı Mustafa Öden Kız Anadolu İmam Hatip Lisesi',
  'BURSA - ORHANELİ - Goynuk Belen İlkokulu',
  'BURSA - ORHANELİ - Orhaneli Halk Eğitimi Merkezi',
  'BURSA - ORHANELİ - Orhaneli Türkan-Sait Yılmaz Anadolu Lisesi',
  'BURSA - ORHANELİ - A. Necati Yılmaz Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - ORHANELİ - Demirci Şehit Himmet Aydın Ortaokulu',
  'BURSA - ORHANELİ - Erenler İlkokulu',
  'BURSA - ORHANELİ - Erenler Ortaokulu',
  'BURSA - ORHANELİ - Termik Santral İlkokulu',
  'BURSA - ORHANELİ - Demirci İlkokulu',
  'BURSA - ORHANELİ - Akalan Köyü Mehmet-Asiye Eğitman İlkokulu',
  'BURSA - ORHANELİ - Şehit Jandarma Er Ayvaz Gür İlkokulu',
  'BURSA - ORHANELİ - Sait Yılmaz İlkokulu',
  'BURSA - ORHANELİ - Karıncalı İlkokulu',
  'BURSA - ORHANELİ - Kadri Uğur Ortaokulu',
  'BURSA - ORHANELİ - İbrahim-Hüsniye Çağlayan Ortaokulu',
  'BURSA - ORHANELİ - Orhaneli Fevzipaşa İlkokulu',
  'BURSA - ORHANELİ - Çöreler İlkokulu',
  'BURSA - ORHANELİ - Sırıl İlkokulu',
  'BURSA - ORHANELİ - TERMİK SANTRAL ORTAOKULU',
  'BURSA - ORHANELİ - Şehit İbrahim Gür Ortaokulu',
  'BURSA - ORHANELİ - FADIL İLKOKULU',
  'BURSA - ORHANELİ - 15 Temmuz Şehitleri Anadolu İmam Hatip Lisesi',
  'BURSA - ORHANELİ - KARINCALI İMAM HATİP ORTAOKULU',
  'BURSA - ORHANELİ - Orhaneli Rehberlik ve Araştırma Merkezi',
  'BURSA - ORHANGAZİ - Şehit Bülent Albayrak İlkokulu',
  'BURSA - ORHANGAZİ - Ahmet Yesevi İlkokulu',
  'BURSA - ORHANGAZİ - Ahmet Yesevi Ortaokulu',
  'BURSA - ORHANGAZİ - Gedelek Orhan Öcalgiray İlkokulu',
  'BURSA - ORHANGAZİ - Erenler Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - ORHANGAZİ - Kurtuluş İlkokulu',
  'BURSA - ORHANGAZİ - Orhangazi 125. Yıl Anaokulu',
  'BURSA - ORHANGAZİ - Orhangazi Anadolu Lisesi',
  'BURSA - ORHANGAZİ - Orhangazi Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - ORHANGAZİ - Orhangazi Çok Programlı Anadolu Lisesi',
  'BURSA - ORHANGAZİ - Orhangazi İmam Hatip Ortaokulu',
  'BURSA - ORHANGAZİ - Orhangazi Öğretmenevi ve Akşam Sanat Okulu Müdürlüğü',
  'BURSA - ORHANGAZİ - 15 Temmuz Şehitler Anadolu Lisesi',
  'BURSA - ORHANGAZİ - Örnekköy Orhan Öcalgiray İlkokulu',
  'BURSA - ORHANGAZİ - Tuna İlkokulu',
  'BURSA - ORHANGAZİ - Gazi Osman Paşa Ortaokulu',
  'BURSA - ORHANGAZİ - Atatürk İlkokulu',
  'BURSA - ORHANGAZİ - Orhangazi Kız Anadolu İmam Hatip Lisesi',
  'BURSA - ORHANGAZİ - Koç İlkokulu',
  'BURSA - ORHANGAZİ - Gedelek Orhan Öcalgiray Ortaokulu',
  'BURSA - ORHANGAZİ - Üreğil İlkokulu',
  'BURSA - ORHANGAZİ - Orhanbey İlkokulu',
  'BURSA - ORHANGAZİ - Çakırlı İlkokulu',
  'BURSA - ORHANGAZİ - Çakırlı Ortaokulu',
  'BURSA - ORHANGAZİ - Ali Tekin İlkokulu',
  'BURSA - ORHANGAZİ - Saadet Öcalgiray Özel Eğitim İlkokulu',
  'BURSA - ORHANGAZİ - Saadet Öcalgiray Özel Eğitim Ortaokulu',
  'BURSA - ORHANGAZİ - Saadet Öcalgiray Özel Eğitim Meslek Okulu',
  'BURSA - ORHANGAZİ - Cargill İlkokulu',
  'BURSA - ORHANGAZİ - Soloz İlkokulu',
  'BURSA - ORHANGAZİ - Yenikoy Ortaokulu',
  'BURSA - ORHANGAZİ - Yenikoy İlkokulu',
  'BURSA - ORHANGAZİ - Narlıca İlkokulu',
  'BURSA - ORHANGAZİ - Orhangazi Halk Eğitimi Merkezi',
  'BURSA - ORHANGAZİ - Ortaköy Orhan Öcalgiray İlkokulu',
  'BURSA - ORHANGAZİ - Gurleler Orhan Öcalgiray İlkokulu',
  'BURSA - ORHANGAZİ - Gurleler Orhan Öcalgiray Ortaokulu',
  'BURSA - ORHANGAZİ - Soloz Ortaokulu',
  'BURSA - ORHANGAZİ - Süleymanşah Anadolu İmam Hatip Lisesi',
  'BURSA - ORHANGAZİ - Mehmet Akif Ersoy Ortaokulu',
  'BURSA - ORHANGAZİ - Orhangazi Ortaokulu',
  'BURSA - ORHANGAZİ - Abdulhamid Han Ortaokulu',
  'BURSA - ORHANGAZİ - Narlıca Ortaokulu',
  'BURSA - ORHANGAZİ - Koç Anaokulu',
  'BURSA - ORHANGAZİ - Orhangazi Atatürk Anaokulu',
  'BURSA - ORHANGAZİ - Orhangazi Anaokulu',
  'BURSA - ORHANGAZİ - Fındıklı İlköğretim Okulu',
  'BURSA - ORHANGAZİ - Fındıklı İlkokulu',
  'BURSA - ORHANGAZİ - Çeltikçi İlkokulu',
  'BURSA - ORHANGAZİ - Orhangazi Fen Lisesi',
  'BURSA - OSMANGAZİ - BTSO Hayri Terzioğlu Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Ahmet Çabuk Ortaokulu',
  'BURSA - OSMANGAZİ - Ali Osman Sönmez Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - ŞEHİT DENİZ PİYADE ER TAHSİN ŞEN ORTAOKULU',
  'BURSA - OSMANGAZİ - BTSO Hasan Alkoçlar Anaokulu',
  'BURSA - OSMANGAZİ - BTSO Ali Osman Sönmez Sosyal Bilimler Lisesi',
  'BURSA - OSMANGAZİ - Bursa BTSO Celal Sönmez Spor Lisesi',
  'BURSA - OSMANGAZİ - BTSO Kamil Tolon Bilim ve Sanat Merkezi',
  'BURSA - OSMANGAZİ - Bursa Kız Lisesi',
  'BURSA - OSMANGAZİ - Bursa Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Hamidiye Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Davut Dörtçelik İlkokulu',
  'BURSA - OSMANGAZİ - Demirtaş Gevher Sönmez İlkokulu',
  'BURSA - OSMANGAZİ - Demirtaşpaşa Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Dr.Necla Yazıcıoğlu İlkokulu',
  'BURSA - OSMANGAZİ - Ergin Ağaç Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Hamitler TOKİ Anaokulu',
  'BURSA - OSMANGAZİ - Hamitler TOKİ Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Hürriyet Ticaret ve Sanayi Odası İlkokulu',
  'BURSA - OSMANGAZİ - Hüseyin Karabacak İlkokulu',
  'BURSA - OSMANGAZİ - Hüseyin Karabacak Ortaokulu',
  'BURSA - OSMANGAZİ - KÜÇÜKBALIKLI ANAOKULU',
  'BURSA - OSMANGAZİ - Malcılar Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Osmangazi Mesleki Eğitim Merkezi',
  'BURSA - OSMANGAZİ - Mollafenari Şehit Sinan Yaylı İlkokulu',
  'BURSA - OSMANGAZİ - Orhanbey İlkokulu',
  'BURSA - OSMANGAZİ - Osmangazi Ali Osman Sönmez Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Muradiye Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Osmangazi Gazi Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Osmangazi Rehberlik ve Araştırma Merkezi',
  'BURSA - OSMANGAZİ - Ovaakça Şarık Tara Özel Eğitim Meslek Okulu',
  'BURSA - OSMANGAZİ - Öztimurlar Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Pilot Sanayi İlkokulu',
  'BURSA - OSMANGAZİ - Seçköy İlkokulu',
  'BURSA - OSMANGAZİ - Şehit Murat Atsen İlkokulu',
  'BURSA - OSMANGAZİ - Şükrü Şankaya Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Şükrü Şankaya İlkokulu',
  'BURSA - OSMANGAZİ - Turgut Yılmazipek Yatılı Bölge Ortaokulu',
  'BURSA - OSMANGAZİ - Veysel Karani Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Yeniceabat Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Yunuseli Anaokulu',
  'BURSA - OSMANGAZİ - Yunuseli Hacı Naciye Kanalıcı Ortaokulu',
  'BURSA - OSMANGAZİ - Yusuf Köstem İlkokulu',
  'BURSA - OSMANGAZİ - Ziya Gökalp İlkokulu',
  'BURSA - OSMANGAZİ - Türk Eğitim Vakfı Hayri Tokaman Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Bursa Hürriyet Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Reşitpaşa İlkokulu',
  'BURSA - OSMANGAZİ - Şht.Jandarma Er Bahadır Aydın Ortaokulu',
  'BURSA - OSMANGAZİ - Abdülhalim Altınoluk Uludağ Ortaokulu',
  'BURSA - OSMANGAZİ - Uludağ İlkokulu',
  'BURSA - OSMANGAZİ - BTSO Hüseyin Sungur Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Sakarya Ortaokulu',
  'BURSA - OSMANGAZİ - Sabiha Köstem Ortaokulu',
  'BURSA - OSMANGAZİ - Osmangazi Halk Eğitimi Merkezi',
  'BURSA - OSMANGAZİ - Çaybaşı İlkokulu',
  'BURSA - OSMANGAZİ - Çaybaşı Ortaokulu',
  'BURSA - OSMANGAZİ - Bilge Malcıoğlu İlkokulu',
  'BURSA - OSMANGAZİ - Sabri Katırcı İlkokulu',
  'BURSA - OSMANGAZİ - Dr.Ayten Bozkaya İlkokulu',
  'BURSA - OSMANGAZİ - Mihraplı Abdulkadir Can Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Osmangazi Hüma Hatun Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - İnönü Ortaokulu',
  'BURSA - OSMANGAZİ - Hocailyas Ortaokulu',
  'BURSA - OSMANGAZİ - Mehmet Aker İlkokulu',
  'BURSA - OSMANGAZİ - Ali Hadi Türkay İlkokulu',
  'BURSA - OSMANGAZİ - Bursa Çimento Fabrikası Ortaokulu',
  'BURSA - OSMANGAZİ - Osmangazi İlkokulu',
  'BURSA - OSMANGAZİ - Hasan Ali Yücel Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Mustafa Münevver Olağaner İlkokulu',
  'BURSA - OSMANGAZİ - Gazi İlkokulu',
  'BURSA - OSMANGAZİ - Osmangazi Belediyesi Hacı Akkadın Tarman İlkokulu',
  'BURSA - OSMANGAZİ - Atatürk Ortaokulu',
  'BURSA - OSMANGAZİ - Şehit Göksu Şafak Şahin İlkokulu',
  'BURSA - OSMANGAZİ - Hamitler Adnan Türkay Ortaokulu',
  'BURSA - OSMANGAZİ - Şehit Ömer Halisdemir Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - BTSO Sait Ete Ortaokulu',
  'BURSA - OSMANGAZİ - Şehit Selcan Akbaş Ortaokulu',
  'BURSA - OSMANGAZİ - Kamil Sarıaydın İlkokulu',
  'BURSA - OSMANGAZİ - Dürdane Ortaokulu',
  'BURSA - OSMANGAZİ - Dr.Ayten Bozkaya Ortaokulu',
  'BURSA - OSMANGAZİ - Şehit Yunus Yılmaz Ortaokulu',
  'BURSA - OSMANGAZİ - Cumhuriyet Anadolu Lisesi',
  'BURSA - OSMANGAZİ - İstiklal İlkokulu',
  'BURSA - OSMANGAZİ - Bursa Erkek Lisesi',
  'BURSA - OSMANGAZİ - Zübeyde Hanım Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Şehit Jandarma Er Selim Koçdemir Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Osmangazi Belediyesi Hacı Akkadın Tarman Ortaokulu',
  'BURSA - OSMANGAZİ - Osmangazi-Ahi Hasan Ortaokulu',
  'BURSA - OSMANGAZİ - İsmetiye Hasan Orhaneddin İlkokulu',
  'BURSA - OSMANGAZİ - Emine -Hasan Özatav Ortaokulu',
  'BURSA - OSMANGAZİ - Erdem Bayazıt Ortaokulu',
  'BURSA - OSMANGAZİ - Yunuseli Şehit Gürcan Ulucan İlkokulu',
  'BURSA - OSMANGAZİ - Nilüfer Mukaddes Yazıcılar İlkokulu',
  'BURSA - OSMANGAZİ - Nilüfer Mukaddes Yazıcılar Ortaokulu',
  'BURSA - OSMANGAZİ - Erhan Nasyalçın İlkokulu',
  'BURSA - OSMANGAZİ - Cavit Çağlar Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Bursa Olgunlaşma Enstitüsü',
  'BURSA - OSMANGAZİ - Gaziakdemir İlkokulu',
  'BURSA - OSMANGAZİ - Başöğretmen Ortaokulu',
  'BURSA - OSMANGAZİ - Şehit Onbaşı Hakan Yutkun Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Şehit Jandarma Uzman Çavuş İlyas Genel İlkokulu',
  'BURSA - OSMANGAZİ - Şehit Erol Olçok Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Muradiye İlkokulu',
  'BURSA - OSMANGAZİ - Osmangazi Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Şahin Yılmaz İlkokulu',
  'BURSA - OSMANGAZİ - Bursa Emek Anaokulu',
  'BURSA - OSMANGAZİ - 11 Eylül İlkokulu',
  'BURSA - OSMANGAZİ - Şehit Doğan Sevinç Ortaokulu',
  'BURSA - OSMANGAZİ - Başaran İlkokulu',
  'BURSA - OSMANGAZİ - Fatih Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Şehit Bkm.Onb.Tolga Taştan İlkokulu',
  'BURSA - OSMANGAZİ - Altıparmak Fethi Açançiçek Ortaokulu',
  'BURSA - OSMANGAZİ - Fatih İlkokulu',
  'BURSA - OSMANGAZİ - İbni Sina İlkokulu',
  'BURSA - OSMANGAZİ - Fatih Ortaokulu',
  'BURSA - OSMANGAZİ - Rahmiye Malcıoğlu İlkokulu',
  'BURSA - OSMANGAZİ - Süleyman Çelebi Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Şehit Komando Er Samet Saraç Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Sönmez İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Barbaros Ortaokulu',
  'BURSA - OSMANGAZİ - Ovaakça İlkokulu',
  'BURSA - OSMANGAZİ - Salih Şeremet Ortaokulu',
  'BURSA - OSMANGAZİ - Remzi Zümrüt İlkokulu',
  'BURSA - OSMANGAZİ - Sadi Etkeser İlkokulu',
  'BURSA - OSMANGAZİ - Şehit Jandarma Komando Er Ramazan Okur Ortaokulu',
  'BURSA - OSMANGAZİ - Hatice Salih Kut İlkokulu',
  'BURSA - OSMANGAZİ - Kükürtlü Ticaret ve Sanayi Odası İlkokulu',
  'BURSA - OSMANGAZİ - Şaypa Ayşe Şaylı İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Merinos İlkokulu',
  'BURSA - OSMANGAZİ - Necdet Coşkunüzer İlkokulu',
  'BURSA - OSMANGAZİ - Dobruca İlkokulu',
  'BURSA - OSMANGAZİ - Bahar Semiha Acar İlkokulu',
  'BURSA - OSMANGAZİ - Dr. Ayten Bozkaya Anaokulu',
  'BURSA - OSMANGAZİ - Mürüvvet Baş Anaokulu',
  'BURSA - OSMANGAZİ - Orhan Kara İlkokulu',
  'BURSA - OSMANGAZİ - Mithatpaşa Ortaokulu',
  'BURSA - OSMANGAZİ - Nilüferhatun İlkokulu',
  'BURSA - OSMANGAZİ - ALIYA İZZETBEGOVIÇ İMAM HATIP ORTAOKULU',
  'BURSA - OSMANGAZİ - Şehit Üsteğmen Mesut Beyazıtlı İlkokulu',
  'BURSA - OSMANGAZİ - Bursa Anaokulu',
  'BURSA - OSMANGAZİ - BTSO Sait Ete İlkokulu',
  'BURSA - OSMANGAZİ - Tophane İlkokulu',
  'BURSA - OSMANGAZİ - Çınar Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Süleyman Çelebi İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Şehit Jandarma Er Samet Akdeniz İlkokulu',
  'BURSA - OSMANGAZİ - Şükrü Naili Paşa Ortaokulu',
  'BURSA - OSMANGAZİ - 23 Nisan Ortaokulu',
  'BURSA - OSMANGAZİ - I.Murat İlkokulu',
  'BURSA - OSMANGAZİ - Necatibey Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Farabi İlkokulu',
  'BURSA - OSMANGAZİ - Osmangazi Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Lütfi Banuşoğlu İlkokulu',
  'BURSA - OSMANGAZİ - Hürriyet Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Hülya Şahnaoğlu Anaokulu',
  'BURSA - OSMANGAZİ - Hanife Murat Ortaokulu',
  'BURSA - OSMANGAZİ - Bursa Atatürk Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Sönmez İlkokulu',
  'BURSA - OSMANGAZİ - Nazife-Hüseyin Meriç Ortaokulu',
  'BURSA - OSMANGAZİ - Nazife-Hüseyin Meriç İlkokulu',
  'BURSA - OSMANGAZİ - Tarık Çevikel İlkokulu',
  'BURSA - OSMANGAZİ - Güner Rubacı İlkokulu',
  'BURSA - OSMANGAZİ - Çukurca Fan Club İlkokulu',
  'BURSA - OSMANGAZİ - Çukurca Fan Club Ortaokulu',
  'BURSA - OSMANGAZİ - Mümin Canbaz Ortaokulu',
  'BURSA - OSMANGAZİ - Gündoğdu İlkokulu',
  'BURSA - OSMANGAZİ - Bilge Malcıoğlu Ortaokulu',
  'BURSA - OSMANGAZİ - Tophane Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Ovaakça Ortaokulu',
  'BURSA - OSMANGAZİ - Osmangazi Özel İdare İlkokulu',
  'BURSA - OSMANGAZİ - Davut Çalışkan İlkokulu',
  'BURSA - OSMANGAZİ - Büyükşehir Belediyesi Zafer-Atıcılar Ortaokulu',
  'BURSA - OSMANGAZİ - Mehmet Torun Özel Eğitim Meslek Okulu',
  'BURSA - OSMANGAZİ - Şehit Taner Çobanoğlu Ortaokulu',
  'BURSA - OSMANGAZİ - İsmetiye Hasan Orhaneddin Ortaokulu',
  'BURSA - OSMANGAZİ - Şehit J. Çvş. Erman Aydın Ortaokulu',
  'BURSA - OSMANGAZİ - Süleyman Şah İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - BTSO Baha Cemal Zağra Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - OSMANGAZİ - Nizam Karasu Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Aziz Torun Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - OSMANGAZİ - Öğretmen Evi ve Akşam Sanat Okulu',
  'BURSA - OSMANGAZİ - I.Murat Ortaokulu',
  'BURSA - OSMANGAZİ - Cem Sultan Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Celal Bayar İlkokulu',
  'BURSA - OSMANGAZİ - Hamzabey Ortaokulu',
  'BURSA - OSMANGAZİ - Kırcılar Anaokulu',
  'BURSA - OSMANGAZİ - Ahmet Hamdi Gökbayrak Fen Lisesi',
  'BURSA - OSMANGAZİ - Meliha - Cemal Bağcı Ortaokulu',
  'BURSA - OSMANGAZİ - TOKİ Cahit Zarifoğlu Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Şehit Hakan Ünver Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Demirtaş İsmail Hakkı Bursevi Kız Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Çağlayan Memduh Gülseçen İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Necdet Coşkunüzer Ortaokulu',
  'BURSA - OSMANGAZİ - Faik Yılmazipek İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Faik Yılmazipek İlkokulu',
  'BURSA - OSMANGAZİ - TOKİ ŞEHİT JANDARMA ER ALİ BAKIŞ İLKOKULU',
  'BURSA - OSMANGAZİ - Şehit Jandarma Er Halim Çimen İlkokulu',
  'BURSA - OSMANGAZİ - Somuncubaba İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Hundi Hatun Anaokulu',
  'BURSA - OSMANGAZİ - Osmangazi Üftade İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Hayme Ana Anaokulu',
  'BURSA - OSMANGAZİ - Fertur İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Eşrefoğlu Rumi İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Uluslararası Murat Hüdavendigar Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Öğretmen Mehmet Ali Deniz İlkokulu',
  'BURSA - OSMANGAZİ - Mehmet Halit Baki Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Çağlayan Memduh Gülseçen İlkokulu',
  'BURSA - OSMANGAZİ - Niyazi Mısri Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Mehmet Akif Ersoy İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Şükrü Şankaya İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Mehmet Zahid Kotku Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Şeyh Şamil İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Öğretmen Neşe Horasan Anaokulu',
  'BURSA - OSMANGAZİ - Şeyh Edebali Kız Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Selçukgazi İlkokulu',
  'BURSA - OSMANGAZİ - M.Nezir Gencer İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Osmangazi Cavit Çağlar İlkokulu',
  'BURSA - OSMANGAZİ - Şehit Köksal Kaşaltı İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Doğanbey Semiha Acar İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Yunuseli Hacı Naciye Kanalıcı İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Nursel Çağlar Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Şükrü Naili Paşa İmam Hatip Ortaokulu',
  'BURSA - OSMANGAZİ - Dürdane İlkokulu',
  'BURSA - OSMANGAZİ - Gündoğdu Ortaokulu',
  'BURSA - OSMANGAZİ - Hacı Hacer Çağlar Ortaokulu',
  'BURSA - OSMANGAZİ - Bursa Türkiye Odalar ve Borsalar Birliği Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Selçukgazi Ortaokulu',
  'BURSA - OSMANGAZİ - Ayşe Hafsa Sultan Anaokulu',
  'BURSA - OSMANGAZİ - Dağakça İlkokulu',
  'BURSA - OSMANGAZİ - Osmangazi Kırcılar Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Şerife Bacı Özel Eğitim Anaokulu',
  'BURSA - OSMANGAZİ - Nermin Şankaya Anaokulu',
  'BURSA - OSMANGAZİ - Karabalçık Celal Sönmez İlkokulu',
  'BURSA - OSMANGAZİ - BTSO Baha Cemal Zağra Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - OSMANGAZİ - BTSO Baha Cemal Zağra Özel Eğitim Uygulama Okulu I. Kademe',
  'BURSA - OSMANGAZİ - Hasan Celal Güzel İlkokulu',
  'BURSA - OSMANGAZİ - Şehit Sinan Acar Ortaokulu',
  'BURSA - OSMANGAZİ - Hasan Gülişan Arseven Kız Anadolu İmam Hatip Lisesi',
  'BURSA - OSMANGAZİ - Ovaakça Şarık Tara Anadolu Lisesi',
  'BURSA - OSMANGAZİ - Mustafa Çağlar Özel Eğitim Uygulama Okulu I. Kademe',
  'BURSA - OSMANGAZİ - Mustafa Çağlar Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - OSMANGAZİ - Mustafa Çağlar Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - OSMANGAZİ - Bisaş İlkokulu',
  'BURSA - OSMANGAZİ - Mümin Canbaz İlkokulu',
  'BURSA - OSMANGAZİ - Macide Gazioğlu Kükürtlü Ortaokulu',
  'BURSA - OSMANGAZİ - Kırcılar Ortaokulu',
  'BURSA - OSMANGAZİ - Kırcılar İlkokulu',
  'BURSA - OSMANGAZİ - Osmangazi Bilim ve Sanat Merkezi',
  'BURSA - OSMANGAZİ - Karabalçık Celal Sönmez Ortaokulu',
  'BURSA - OSMANGAZİ - Şehit Göksu Şafak Şahin Anaokulu',
  'BURSA - OSMANGAZİ - Güner Rubacı Anaokulu',
  'BURSA - OSMANGAZİ - Celal Bayar Anaokulu',
  'BURSA - OSMANGAZİ - Dr.Necla Yazıcıoğlu Anaokulu',
  'BURSA - OSMANGAZİ - Osmangazi Uludağ Anaokulu',
  'BURSA - OSMANGAZİ - Öğretmen Mehmet Ali Deniz Anaokulu',
  'BURSA - OSMANGAZİ - Mümin Canbaz Anaokulu',
  'BURSA - OSMANGAZİ - Yusuf Köstem Anaokulu',
  'BURSA - OSMANGAZİ - Yunuseli Şehit Gürcan Ulucan Anaokulu',
  'BURSA - OSMANGAZİ - Kamil Sarıaydın Anaokulu',
  'BURSA - OSMANGAZİ - Osmangazi Belediyesi Hacı Akkadın Tarman Anaokulu',
  'BURSA - OSMANGAZİ - TOKİ Şehit Jandarma Er Ali Bakış Anaokulu',
  'BURSA - OSMANGAZİ - Sadi Etkeser Anaokulu',
  'BURSA - OSMANGAZİ - Başöğretmen Anaokulu',
  'BURSA - OSMANGAZİ - Fatih Anaokulu',
  'BURSA - OSMANGAZİ - Bilge Malcıoğlu Anaokulu',
  'BURSA - OSMANGAZİ - Tarık Çevikel Anaokulu',
  'BURSA - OSMANGAZİ - Ali Hadi Türkay Anaokulu',
  'BURSA - OSMANGAZİ - Şehit Murat Atsen Anaokulu',
  'BURSA - OSMANGAZİ - Şehit Jandarma Uzman Çavuş İlyas Genel Anaokulu',
  'BURSA - OSMANGAZİ - Salih Şeremet Anaokulu',
  'BURSA - OSMANGAZİ - Nilüfer Hatun Anaokulu',
  'BURSA - OSMANGAZİ - 23 Nisan Anaokulu',
  'BURSA - OSMANGAZİ - Şht.Jandarma Er Bahadır Aydın Anaokulu',
  'BURSA - OSMANGAZİ - İstiklal Anaokulu',
  'BURSA - OSMANGAZİ - Şehit Jandarma Er Halim Çimen Anaokulu',
  'BURSA - OSMANGAZİ - Orhan Kara Anaokulu',
  'BURSA - OSMANGAZİ - Aziz Torun Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - OSMANGAZİ - Aziz Torun Özel Eğitim Uygulama Okulu I. Kademe',
  'BURSA - OSMANGAZİ - Bursa Çimento Fabrikası Anaokulu',
  'BURSA - OSMANGAZİ - Ovaakça Şarık Tara Özel Eğitim Anaokulu',
  'BURSA - OSMANGAZİ - BTSO Baha Cemal Zağra Özel Eğitim Anaokulu',
  'BURSA - OSMANGAZİ - Mehmet Torun Özel Eğitim Anaokulu',
  'BURSA - OSMANGAZİ - Hatice Salih Kut Anaokulu',
  'BURSA - YENİŞEHİR - Ertuğrul Gazi Anadolu Lisesi',
  'BURSA - YENİŞEHİR - Halk Eğitimi Merkezi',
  'BURSA - YENİŞEHİR - Yenişehir Yusuf Ateş Anadolu İmam Hatip Lisesi',
  'BURSA - YENİŞEHİR - Koç Ortaokulu',
  'BURSA - YENİŞEHİR - Koyunhisar İlkokulu',
  'BURSA - YENİŞEHİR - Yenişehir Hüma Hatun Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YENİŞEHİR - Yenişehir Şişecam Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YENİŞEHİR - Terziler İlkokulu',
  'BURSA - YENİŞEHİR - Gevher Nesibe Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YENİŞEHİR - Yenişehir Anaokulu',
  'BURSA - YENİŞEHİR - Süleymanpaşa İlkokulu',
  'BURSA - YENİŞEHİR - Tahirağa İlkokulu',
  'BURSA - YENİŞEHİR - Köprühisar Atatürk Ortaokulu',
  'BURSA - YENİŞEHİR - Aydoğdubey İlkokulu',
  'BURSA - YENİŞEHİR - TOKİ Orhangazi Ortaokulu',
  'BURSA - YENİŞEHİR - Akçeşme İlkokulu',
  'BURSA - YENİŞEHİR - Yolören Ortaokulu',
  'BURSA - YENİŞEHİR - Yolören İlkokulu',
  'BURSA - YENİŞEHİR - 100.Yıl İlkokulu',
  'BURSA - YENİŞEHİR - Orhaniye Gazi Müstecip Onbaşı İlkokulu',
  'BURSA - YENİŞEHİR - Yenişehir Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YENİŞEHİR - Müyesser İbrahim Sünnetçioğlu Ortaokulu',
  'BURSA - YENİŞEHİR - Koyunhisar Ortaokulu',
  'BURSA - YENİŞEHİR - SÖYLEMİŞ ORTAOKULU',
  'BURSA - YENİŞEHİR - ÇELEBİ İLKOKULU',
  'BURSA - YENİŞEHİR - BALİBEY ORTAOKULU',
  'BURSA - YENİŞEHİR - ŞEHİT YUNUS BAL ORTAOKULU',
  'BURSA - YENİSEHİR - Müyesser İbrahim Sünnetçioğlu İmam Hatip Ortaokulu',
  'BURSA - YENİSEHİR - Balibey İmam Hatip Ortaokulu',
  'BURSA - YENİSEHİR - Yenişehir Özel Eğitim Uygulama Okulu I. Kademe',
  'BURSA - YENİSEHİR - Yenişehir Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - YENİSEHİR - İlhan Oğuz Anadolu Lisesi',
  'BURSA - YILDIRIM - Ahmet Hamdi Tanpınar İlkokulu',
  'BURSA - YILDIRIM - Belediye 100.Yıl Anaokulu',
  'BURSA - YILDIRIM - Bursa Ahmet Vefik Paşa Anadolu Lisesi',
  'BURSA - YILDIRIM - Cumhuriyet İlkokulu',
  'BURSA - YILDIRIM - Dörtçelik İlkokulu',
  'BURSA - YILDIRIM - Emine Sait Uyar İlkokulu',
  'BURSA - YILDIRIM - Erdoğan Şahinoğlu Ortaokulu',
  'BURSA - YILDIRIM - Fevzi Çakmak İlkokulu',
  'BURSA - YILDIRIM - Fidyekızık İlkokulu',
  'BURSA - YILDIRIM - Yıldırım Halk Eğitimi Merkezi',
  'BURSA - YILDIRIM - Has Asansör Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YILDIRIM - İhsan Dikmen 4 İlkokulu',
  'BURSA - YILDIRIM - İşgir Ortaokulu',
  'BURSA - YILDIRIM - MALTEPE ANAOKULU',
  'BURSA - YILDIRIM - MEVLANA ANAOKULU',
  'BURSA - YILDIRIM - Mustafa Dörtçelik İlkokulu',
  'BURSA - YILDIRIM - Mümin Gençoğlu 1 İlkokulu',
  'BURSA - YILDIRIM - Mümin Gençoğlu 2 İlkokulu',
  'BURSA - YILDIRIM - Nuri Erbak Ortaokulu',
  'BURSA - YILDIRIM - Rüveyde Dörtçelik Özel Eğitim Meslek Okulu',
  'BURSA - YILDIRIM - Sabiha Gökçen Anaokulu',
  'BURSA - YILDIRIM - Samanlı Latif Dörtçelik Ortaokulu',
  'BURSA - YILDIRIM - Mehmet Akif İnan Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - Şehit Jandarma Er Selahattin Çırak İlkokulu',
  'BURSA - YILDIRIM - Şehit Jandarma Komando Er Bahri Avcı Mesleki Eğitim Merkezi',
  'BURSA - YILDIRIM - Şehit Piyade Er Nezir Akgül Ortaokulu',
  'BURSA - YILDIRIM - Şehit Polis Bülent Aslan İlkokulu',
  'BURSA - YILDIRIM - Şehit Öğretmen Mahmut Çatalkaya Ortaokulu',
  'BURSA - YILDIRIM - Teferrüç Ali Osman Gür İlkokulu',
  'BURSA - YILDIRIM - Ulubatlı Hasan Anadolu Lisesi',
  'BURSA - YILDIRIM - Vakıf İlkokulu',
  'BURSA - YILDIRIM - Kızıklar Ortaokulu',
  'BURSA - YILDIRIM - Vilayetler Hizmet Birliği Anaokulu',
  'BURSA - YILDIRIM - Yeşilyayla Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YILDIRIM - Yıldırım Beyazıt Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YILDIRIM - Yıldırım Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YILDIRIM - Yıldırım Rehberlik ve Araştırma Merkezi',
  'BURSA - YILDIRIM - YİĞİTLER ANAOKULU',
  'BURSA - YILDIRIM - Yiğitler Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YILDIRIM - Selçuk Hatun Ortaokulu',
  'BURSA - YILDIRIM - Naz Özdilek İlkokulu',
  'BURSA - YILDIRIM - Şehit Harun Arvas Ortaokulu',
  'BURSA - YILDIRIM - Bala Hatun Anaokulu',
  'BURSA - YILDIRIM - Yıldırım Belediyesi Hacı Saide Zorlu Özel Eğitim Uygulama Okulu I. Kademe',
  'BURSA - YILDIRIM - Yıldırım Belediyesi Hacı Saide Zorlu Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - YILDIRIM - Hasan Ali Yücel İlkokulu',
  'BURSA - YILDIRIM - Yunus Emre İlkokulu',
  'BURSA - YILDIRIM - Hasan Öztimur İlkokulu',
  'BURSA - YILDIRIM - Haşim İşcan İlkokulu',
  'BURSA - YILDIRIM - Bursa Yıldırım Ticaret ve Sanayi Odası Anadolu Lisesi',
  'BURSA - YILDIRIM - Arif Nihat Asya İlkokulu',
  'BURSA - YILDIRIM - Şehit Polis İbrahim Akın Ortaokulu',
  'BURSA - YILDIRIM - Yavuz Selim Ortaokulu',
  'BURSA - YILDIRIM - Yavuz Selim İlkokulu',
  'BURSA - YILDIRIM - Mümin Gençoğlu 2 Ortaokulu',
  'BURSA - YILDIRIM - Samanlı İlkokulu',
  'BURSA - YILDIRIM - Şeh.Kurmay Binb.Ufuk Bülent Yavuz İlkokulu',
  'BURSA - YILDIRIM - Fethiye Dörtçelik Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - Bursa İpekçilik Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - Değirmenlikızık Dumlupınar İlkokulu',
  'BURSA - YILDIRIM - Emirbuhari Ortaokulu',
  'BURSA - YILDIRIM - Latif Dörtçelik Anaokulu',
  'BURSA - YILDIRIM - Şehit Piyade Onbaşı Orhan Tezcan İlkokulu',
  'BURSA - YILDIRIM - Namazgah Gıyasettin Bingöl İlkokulu',
  'BURSA - YILDIRIM - Makbule-Atadan Anaokulu',
  'BURSA - YILDIRIM - Yıldırım Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YILDIRIM - Emir Sultan Anadolu Lisesi',
  'BURSA - YILDIRIM - Yiğitler Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - Ertugrul Gazi Anadolu Lisesi',
  'BURSA - YILDIRIM - Kazım Karabekir İlkokulu',
  'BURSA - YILDIRIM - Şirinevler İlkokulu',
  'BURSA - YILDIRIM - Karapınar Şehit Samet Çaldır İlkokulu',
  'BURSA - YILDIRIM - Şehit P.Bnb.Ercüment Türkmen Ortaokulu',
  'BURSA - YILDIRIM - Değirmenönü İlkokulu',
  'BURSA - YILDIRIM - Dumlupınar Anaokulu',
  'BURSA - YILDIRIM - Setbaşı Ortaokulu',
  'BURSA - YILDIRIM - Emek Ortaokulu',
  'BURSA - YILDIRIM - Mimar Sinan Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YILDIRIM - Yıldırım Beyazıt Anadolu Lisesi',
  'BURSA - YILDIRIM - Şehit Öğretmen Kubilay Anadolu Lisesi',
  'BURSA - YILDIRIM - Adnan Menderes Ortaokulu',
  'BURSA - YILDIRIM - Celebi Mehmet Anadolu Lisesi',
  'BURSA - YILDIRIM - Yıldırım Belediyesi Hacı Saide Zorlu Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - YILDIRIM - Balabanbey Dörtçelik İlkokulu',
  'BURSA - YILDIRIM - Nuri Erbak Anadolu Lisesi',
  'BURSA - YILDIRIM - Bursa Merkez Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - Şeh.Kurmay Binb.Ufuk Bülent Yavuz Ortaokulu',
  'BURSA - YILDIRIM - Akıncıtürk İhsan Dikmen İlkokulu',
  'BURSA - YILDIRIM - Faik Çelik Mesleki ve Teknik Anadolu Lisesi',
  'BURSA - YILDIRIM - Şerif Artış İlkokulu',
  'BURSA - YILDIRIM - Nuri Nihat Aslanoba Anadolu Lisesi',
  'BURSA - YILDIRIM - Gülhanım Karasu İlkokulu',
  'BURSA - YILDIRIM - Yıldırım Belediyesi Hacı Mehmet Zorlu Özel Eğitim Meslek Okulu',
  'BURSA - YILDIRIM - Yıldırım Belediye Ortaokulu',
  'BURSA - YILDIRIM - Turgay Ciner İlkokulu',
  'BURSA - YILDIRIM - Alirızabey İlkokulu',
  'BURSA - YILDIRIM - Yahya Kemal Beyatlı Ortaokulu',
  'BURSA - YILDIRIM - Necip Fazıl Kısakürek Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - Gülbahar Hatun Anaokulu',
  'BURSA - YILDIRIM - Atatürk Anaokulu',
  'BURSA - YILDIRIM - Yıldırım Anaokulu',
  'BURSA - YILDIRIM - Cumalıkızık Ortaokulu',
  'BURSA - YILDIRIM - Ayşe Müzeyyen Tozluoğlu İlkokulu',
  'BURSA - YILDIRIM - Fevzi Çakmak Ortaokulu',
  'BURSA - YILDIRIM - Peyami Safa Ortaokulu',
  'BURSA - YILDIRIM - Davutkadı Eşref Evcil İlkokulu',
  'BURSA - YILDIRIM - Zübeyde Hanım Ortaokulu',
  'BURSA - YILDIRIM - Yıldırım Belediyesi İmam Hatip Ortaokulu',
  'BURSA - YILDIRIM - Yeşilevler Münevver Özran İlkokulu',
  'BURSA - YILDIRIM - Mustafa Necati İlkokulu',
  'BURSA - YILDIRIM - Yıldırım İlkokulu',
  'BURSA - YILDIRIM - Akçağlayan İhsan Dikmen İlkokulu',
  'BURSA - YILDIRIM - Cumalıkızık İlkokulu',
  'BURSA - YILDIRIM - Nurettin-Gülten Kutlucan İlkokulu',
  'BURSA - YILDIRIM - Şerif-Rabia Kutlucan Ortaokulu',
  'BURSA - YILDIRIM - Üstün Üründül İlkokulu',
  'BURSA - YILDIRIM - Samanlı Özel Eğitim Uygulama Merkezi I. Kademe',
  'BURSA - YILDIRIM - Vakıf Ortaokulu',
  'BURSA - YILDIRIM - Rüveyde Dörtçelik Özel Eğitim Ortaokulu',
  'BURSA - YILDIRIM - Yeşil Devlet Hatun Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - Vatan Anaokulu',
  'BURSA - YILDIRIM - Şehit Piyade Er Rahim Keskin Ortaokulu',
  'BURSA - YILDIRIM - FATİH SULTAN MEHMET ORTAOKULU',
  'BURSA - YILDIRIM - Anadolu İmam Hatip Ortaokulu',
  'BURSA - YILDIRIM - Nene Hatun Anaokulu',
  'BURSA - YILDIRIM - Şehit Hasan Hüseyin Daşdemir Ortaokulu',
  'BURSA - YILDIRIM - Ticaret Borsası İmam Hatip Ortaokulu',
  'BURSA - YILDIRIM - GÜLÇİÇEK HATUN KIZ ANADOLU İMAM HATİP LİSESİ',
  'BURSA - YILDIRIM - SEMİHA MUSTAFA ÖZER ORTAOKULU',
  'BURSA - YILDIRIM - HÜMA HATUN ÖZEL EĞİTİM ANAOKULU',
  'BURSA - YILDIRIM - Namık Kemal İmam Hatip Ortaokulu',
  'BURSA - YILDIRIM - AKÇAĞLAYAN ANADOLU İMAM HATİP LİSESİ',
  'BURSA - YILDIRIM - Alirızabey İmam Hatip Ortaokulu',
  'BURSA - YILDIRIM - ADNAN MENDERES İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - Kanuni Kız Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - MİLLET MAHALLESİ İLKOKULU',
  'BURSA - YILDIRIM - Mahmut Celalettin ÖKTEN İmam Hatip Ortaokulu',
  'BURSA - YILDIRIM - Necmettin Erbakan Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - ŞİRİNEVLER İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - KARAPINAR İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - EMİRBUHARİ İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - 6 NİSAN ANADOLU LİSESİ',
  'BURSA - YILDIRIM - Şerafeddin Atalay Anaokulu',
  'BURSA - YILDIRIM - Güzide Hafız Kız Anadolu İmam Hatip Lisesi',
  'BURSA - YILDIRIM - KAŞGARLI MAHMUD ANADOLU LİSESİ',
  'BURSA - YILDIRIM - FATİH SULTAN MEHMET İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - SAMANLI LATİF DÖRTÇELİK İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - İHSAN DİKMEN İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - SAİT SÜHEYLA BİLDİRENER İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - HASAN ÖZTİMUR 75.YIL İLKOKULU',
  'BURSA - YILDIRIM - Şehit Zeki Burak Okay Ortaokulu',
  'BURSA - YILDIRIM - ŞEHİT PİYADE ER NEZİR AKGÜL İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - VAKIF İMAM HATİP ORTAOKULU',
  'BURSA - YILDIRIM - Samanlı Özel Eğitim Uygulama Okulu II. Kademe',
  'BURSA - YILDIRIM - Samanlı Özel Eğitim Uygulama Okulu III. Kademe',
  'BURSA - YILDIRIM - Semiha Mustafa Özer İmam Hatip Ortaokulu',
  'BURSA - YILDIRIM - Şehit Hasan Hüseyin Daşdemir İmam Hatip Ortaokulu',
  'BURSA - YILDIRIM - Mehmet Akif Ersoy Ortaokulu',
  'BURSA - YILDIRIM - Eyüp Sultan Anaokulu',
  'BURSA - YILDIRIM - Prof. Dr. Fuat Sezgin Ortaokulu',
  'BURSA - YILDIRIM - Yıldırım Bilim ve Sanat Merkezi',
  'BURSA - YILDIRIM - Prof. Dr. Fuat Sezgin Anadolu Lisesi',
  'BURSA - YILDIRIM - Mehmet Akif Ersoy Anadolu Lisesi',
  'BURSA - YILDIRIM - Fevziye Yazıcıoğlu Kızılay Anaokulu',
  'BURSA - YILDIRIM - Şehit Piyade Onbaşı Orhan Tezcan Anaokulu',
  'BURSA - YILDIRIM - Karapınar Şehit Samet Çaldır Anaokulu',
  'BURSA - YILDIRIM - Mahmut Celalettin Ökten Anaokulu',
  'BURSA - YILDIRIM - Yıldırım Yunus Emre Anaokulu',
  'BURSA - YILDIRIM - Akıncıtürk İhsan Dikmen Anaokulu',
  'BURSA - YILDIRIM - Akçağlayan İhsan Dikmen Anaokulu',
  'BURSA - YILDIRIM - Balabanbey Dörtçelik Anaokulu',
  'BURSA - YILDIRIM - Fevzi Çakmak Anaokulu',
  'BURSA - YILDIRIM - Naz Özdilek Anaokulu',
  'BURSA - YILDIRIM - Şehit Jandarma Er Selahattin Çırak Anaokulu',
  'BURSA - YILDIRIM - Hasan Ali Yücel Anaokulu',
  'BURSA - YILDIRIM - Millet Mahallesi Anaokulu',
  'BURSA - YILDIRIM - Hasan Öztimur 75.Yıl Anaokulu',
  'BURSA - YILDIRIM - Haşim İşcan Anaokulu',
  'BURSA - YILDIRIM - Şehit Polis Bülent Aslan Anaokulu',
  'BURSA - YILDIRIM - Gülhanım Karasu Anaokulu',
  'BURSA - YILDIRIM - Dörtçelik Anaokulu',
  'BURSA - YILDIRIM - Yıldırım Beyazıt Anaokulu',
  'BURSA - YILDIRIM - Emirbuhari Anaokulu',
  'BURSA - YILDIRIM - Yiğitler Özel Eğitim Anaokulu',

  ];

  List<String> get list=>_list;
}